/* Connected research workspace. One canonical model, explicit observations,
 * immutable calculation records, and revision-safe execution. No automatic AI calls.
 */
(function(root){'use strict';
const $=id=>document.getElementById(id),P=root.FokoProjectCore,E=root.FokoResearchEngine,Charts=root.FokoResearchCharts,Store=root.FokoResearchStore,{esc,toast,download}=root.FokoResearchUI,clone=x=>JSON.parse(JSON.stringify(x));
const SCHEMA='foko.research/1',params=new URLSearchParams(location.search),keys={last:'foko:research:last',recent:'foko:research:recent'},S={id:'research-'+Date.now().toString(36),model:null,data:null,path:null,records:[],current:{},notes:{hypothesis:'',interpretation:'',nextTest:''},revision:0,sequence:0,job:null,invalid:null,draftDirty:false,dataDraftDirty:false,tab:'model',pin:null,pendingModel:null,scenarios:[],attachments:[]};let saveTimer,liveTimer;
const fmt=Charts.fmt,D=root.FokoExperimentData,H=root.FokoModelAuthoring;let editor=null;
function setStatus(state,message){$('currentState').dataset.state=state;$('currentState').textContent={ready:'Ready',running:'Running',completed:'Current result',outdated:'Inputs changed',failed:'Check inputs',cancelled:'Cancelled'}[state]||state;$('runStatus').dataset.state=state;$('runStatus').textContent=message;}
function showError(error){setStatus('failed',error.message||String(error));}
function abortActive(){S.sequence++;if(S.job){S.job.cancel();S.job=null;}$('cancelRun').hidden=true;$('runProgress').hidden=true;document.querySelectorAll('[data-run],#runRobust,#runCurrent').forEach(b=>b.disabled=false);}
function invalidate(message='Inputs changed. Previous calculations remain in Evidence; run again for the current inputs.'){abortActive();S.revision++;S.current={};setStatus('outdated',message);renderCurrent();queueSave();}
function bundle(){return {schema:SCHEMA,version:E.VERSION,id:S.id,path:S.path?.id||null,model:clone(S.model),data:clone(S.data),notes:clone(S.notes),results:clone(S.records),scenarios:clone(S.scenarios),attachments:clone(S.attachments),updatedAt:new Date().toISOString(),notice:'Historical records preserve their own inputs. Imported records must be recomputed before being treated as locally computed evidence.'};}
function save(){if(S.invalid||!S.model){$('saveState').textContent='Invalid edits · last valid save retained';return;}const b=bundle(),ok=Store.set('foko:research:project:'+S.id,b);Store.set(keys.last,S.id);const recents=Store.get(keys.recent,[]).filter(p=>p.id!==S.id);recents.unshift({id:S.id,name:S.model.name,updatedAt:b.updatedAt,runs:S.records.length});Store.set(keys.recent,recents.slice(0,12));$('saveState').textContent=ok?'Saved locally · export for backup':'Session-only · export before leaving';$('journalSave').textContent=ok?'Notes saved in this browser with the project.':'Persistent storage unavailable; export your notes and project.';}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,250);}
function defaultModel(){return P.normalizeModel({name:'Untitled model',vars:['x'],eqs:['0'],y0:[1],params:{rate:[.2,0,1]},t0:0,t1:10,points:250,rtol:1e-7,atol:1e-9,method:'rk45',units:{x:'unspecified'},timeUnit:'unspecified',question:'',assumptions:[],outputVar:'x',outputMetric:'final',description:'Define the scientific system and its limits.'});}
function validateData(data,model){if(data===null||data===undefined)return null;if(data.schema===D.SCHEMA)return D.validate(data,model);if(!model.vars.includes(data.output))throw new Error('Imported observations refer to a state absent from the model.');if(!Array.isArray(data.T)||!Array.isArray(data.Y)||data.T.length!==data.Y.length||data.T.length<8||data.T.length>1000)throw new Error('Imported observations require 8–1,000 matching times and values.');for(let i=0;i<data.T.length;i++){if(!Number.isFinite(data.T[i])||!Number.isFinite(data.Y[i])||data.T[i]<model.t0||data.T[i]>model.t1||i>0&&data.T[i]<=data.T[i-1])throw new Error('Imported observations must be finite, increasing and inside the model time span.');}return clone(data);}
function load(raw,imported=false){
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Import a model or experiment object.');
 const b=raw.schema===SCHEMA?raw:null,model=P.normalizeModel(b?b.model:raw.model||raw);
 root.FokoStudioCompute.compile(model,root.math);D.compileObservables(model,root.FokoStudioCompute,root.math);
 if(model.t1<=model.t0)throw new Error('The experiment requires an increasing time span.');
 const data=b?validateData(b.data,model):null,records=b&&Array.isArray(b.results)?clone(b.results):[];
 if(records.length>200)throw new Error('Import at most 200 records at once.');
 for(const r of records){
  if(!r||!['simulation','synthetic','fit','sensitivity','ensemble','surrogate'].includes(r.kind)||typeof r.id!=='string'||!r.snapshot?.model||!r.result||typeof r.result!=='object'||!r.snapshot.settings||typeof r.snapshot.settings!=='object')throw new Error('An experiment record has an invalid shape. Import rejected without changing the current model.');
  const historical=P.normalizeModel(r.snapshot.model);root.FokoStudioCompute.compile(historical,root.math);validateData(r.snapshot.data,historical);
  if(r.result.warnings!==undefined&&(!Array.isArray(r.result.warnings)||r.result.warnings.some(w=>typeof w!=='string')))throw new Error('Invalid warning list in an imported result.');
 }
 const scenarios=(b?.scenarios||[]).map(x=>{if(!x?.id||typeof x.name!=='string')throw new Error('Invalid scenario.');const m=P.normalizeModel(x.model);return {...clone(x),model:m,data:validateData(x.data,m)};});
 if(scenarios.length>20)throw new Error('Import at most 20 scenarios.');
 const attachments=(b?.attachments||[]).map(x=>{if(x.schema!=='foko.programme-evidence/1'||!x.run?.snapshot?.model||!['verify','infer','compare','release'].includes(x.gate))throw new Error('Invalid programme attachment.');return {...clone(x),evidenceLevel:imported?'imported; not independently reproduced':x.evidenceLevel};});
 if(attachments.length>60)throw new Error('Import at most 60 evidence attachments.');
 const next={model,scenarios,attachments,path:b?.path?root.FokoResearchPaths[b.path]||null:null,id:imported?'research-'+Date.now().toString(36):b?.id||S.id,data,
 notes:b?{hypothesis:String(b.notes?.hypothesis||''),interpretation:String(b.notes?.interpretation||''),nextTest:String(b.notes?.nextTest||'')}:{hypothesis:'',interpretation:'',nextTest:''},
 records:records.map(r=>({...r,source:imported?'imported; unverified':r.source||'saved local record',sessionCurrent:false})),current:{},invalid:null,draftDirty:false,dataDraftDirty:false,pin:null};
 Object.assign(S,next);S.revision++;editor?.clearHistory();
}
function init(){try{if(params.get('new')==='1'||params.get('import')==='1'){S.model=defaultModel();}else if(params.get('case')==='fluorescence'){S.model=P.normalizeModel(root.FokoMeasurementCase.model);S.data=D.validate(root.FokoMeasurementCase.data,S.model);S.notes.hypothesis='One shared decay rate should explain both known initial conditions through the calibrated fluorescence operator.';}else if(params.has('path')){const p=root.FokoResearchPaths[params.get('path')];if(!p)throw new Error('Unknown research pathway. Choose a model from the library.');S.path=p;S.model=P.normalizeModel(p.model);}else{let id=params.get('resume');if(!id||id==='last')id=Store.get(keys.last);const b=id&&Store.get('foko:research:project:'+id);if(b)load(b);else{S.path=root.FokoResearchPaths.dynamics;S.model=P.normalizeModel(S.path.model);}}
 renderInputs();renderCurrent();setStatus('ready',S.records.length?'Project restored. Past calculations are historical; recompute to establish current evidence.':'Define your model or run the editable starting point.');save();if(Store.get('foko:research:guideDismissed',false))$('onboarding').hidden=true;const tab=location.hash.slice(1);if(['model','fit','robust','ml','evidence'].includes(tab))switchTab(tab,false);if(params.get('import')==='1')setStatus('ready','Use Import to choose a Project JSON, research bundle, or direct model JSON.');
 }catch(e){S.model=defaultModel();renderInputs();renderCurrent();showError(e);}}
function parameterLabel(k){if(S.model.parameterMeta?.[k]?.label)return S.model.parameterMeta[k].label;return S.path?.id==='plant'?({Amax:'Assimilation capacity',light:'Light intensity',co2:'CO₂ concentration',temp:'Temperature',irrigation:'Irrigation',division:'Division rate',death:'Death rate'}[k]||k):k;}
function renderInputs(){const m=S.model;$('projectName').value=m.name;$('question').value=m.question;$('t0').value=m.t0;$('t1').value=m.t1;$('modelJSON').value=JSON.stringify(m,null,2);$('output').innerHTML=m.vars.map(v=>`<option value="${esc(v)}">${esc(v)} · ${esc(m.units[v]||'unspecified')}</option>`).join('');$('output').value=m.outputVar;$('metric').value=m.outputMetric;
 $('initialInputs').innerHTML=m.vars.map((v,i)=>`<div class="param-line"><label for="init-${i}">${esc(v)} <span class="small muted">(${esc(m.units[v]||'unspecified')})</span></label><input id="init-${i}" type="number" step="any" data-initial="${i}" value="${m.y0[i]}"></div>`).join('');
 const preferred=S.path?.id==='plant'?['light','co2','temp','irrigation','Amax']:[...(S.path?.fit||[]),S.path?.surrogate,...Object.keys(m.params)].filter((x,i,a)=>x&&a.indexOf(x)===i).slice(0,4),main=preferred.filter(k=>m.params[k]);
 $('parameterInputs').innerHTML=main.map((k,i)=>{const p=m.params[k];return `<div class="param-line"><label for="quick-${i}">${esc(parameterLabel(k))}${parameterLabel(k)!==k?'<br><span class="small muted">'+esc(k)+'</span>':''}</label><input id="quick-${i}" type="number" step="any" data-param="${esc(k)}" data-param-part="0" value="${p[0]}"></div><input type="range" style="width:100%;min-height:30px;padding:0" aria-label="Adjust ${esc(k)} within its declared range" data-slider="${esc(k)}" min="${p[1]}" max="${p[2]}" step="${(p[2]-p[1])/200||1}" value="${p[0]}" ${p[1]===p[2]?'disabled':''}>`;}).join('');
 $('allParameters').innerHTML=Object.entries(m.params).map(([k,p],i)=>`<fieldset style="border:0;border-bottom:1px solid var(--line);padding:12px 0"><legend class="small" style="font-family:var(--mono)">${esc(k)}</legend><div class="field-row"><label class="field">Nominal<input type="number" step="any" data-param="${esc(k)}" data-param-part="0" value="${p[0]}"></label><label class="field">Minimum<input type="number" step="any" data-param="${esc(k)}" data-param-part="1" value="${p[1]}"></label><label class="field">Maximum<input type="number" step="any" data-param="${esc(k)}" data-param-part="2" value="${p[2]}"></label></div></fieldset>`).join('')||'<p>No parameters declared. Add them in the model editor.</p>';
 const free=Object.entries(m.params).filter(([k,p])=>p[2]>p[1]);$('fitParameters').innerHTML=free.map(([k],i)=>`<label><input type="checkbox" data-fit-param="${esc(k)}" ${(S.path?.fit||free.slice(0,2).map(x=>x[0])).includes(k)?'checked':''}>${esc(k)}</label>`).join('');$('ensembleParameters').innerHTML=free.map(([k],i)=>`<label><input type="checkbox" data-ensemble-param="${esc(k)}" ${i<3?'checked':''}>${esc(k)}</label>`).join('');$('surrogateParameter').innerHTML=free.map(([k])=>`<option value="${esc(k)}">${esc(parameterLabel(k))} (${esc(k)})</option>`).join('');if(S.path?.surrogate&&m.params[S.path.surrogate])$('surrogateParameter').value=S.path.surrogate;
 ['hypothesis','interpretation','nextTest'].forEach(k=>$(k).value=S.notes[k]||'');$('csvText').value=S.data?dataCSV(S.data):'';S.dataDraftDirty=false;renderMetadata();renderDataStatus();renderRobustControls();editor?.refresh();
 document.querySelectorAll('[data-param],[data-initial],[data-slider]').forEach(input=>input.addEventListener('input',()=>{if(input.dataset.param){document.querySelectorAll('[data-param]').forEach(other=>{if(other!==input&&other.dataset.param===input.dataset.param&&other.dataset.paramPart===input.dataset.paramPart)other.value=input.value;});if(input.dataset.paramPart==='0')document.querySelectorAll('[data-slider]').forEach(s=>{if(s.dataset.slider===input.dataset.param)s.value=input.value;});}else if(input.dataset.slider){document.querySelectorAll('[data-param]').forEach(other=>{if(other.dataset.param===input.dataset.slider&&other.dataset.paramPart==='0')other.value=input.value;});}editBasic();}));document.querySelectorAll('[data-fit-param],[data-ensemble-param]').forEach(x=>x.onchange=()=>invalidate('Analysis selection changed. Run again; earlier results remain in Evidence.'));
}
function renderMetadata(){const m=S.model;$('workspaceTitle').textContent=m.name;$('workspaceDomain').textContent=S.path?.domain||'Your model · connected experiment';$('workspaceQuestion').textContent=m.question||'Write the scientific question before interpreting a calculation.';$('pathContext').textContent=S.path?.context||m.description||'Record the system, observation process and scope of use.';$('pathLesson').href='learn.html?lesson='+(S.path?.lesson||'question');$('modelScope').innerHTML=`<p>${esc(S.path?.source||'User-authored model; provenance and empirical validity are not established by this application.')}</p><ul style="padding-left:20px;margin-top:14px;font-size:13px;color:var(--muted)">${m.assumptions.map(a=>`<li style="margin:7px 0">${esc(a)}</li>`).join('')||'<li>No assumptions recorded yet.</li>'}</ul>${S.path?`<p><b>Try this:</b> ${esc(S.path.exercise)}</p><p><b>Boundary:</b> ${esc(S.path.risk)}</p><p><a href="${esc(S.path.research)}">Source research and deeper methods →</a></p>`:''}`;$('equations').innerHTML=m.vars.map((v,i)=>`<div class="equation"><b>d${esc(v)}/dt</b> = ${esc(m.eqs[i])}</div>`).join('')+(m.observables?.length?'<h4 class="form-heading">Declared measurements</h4>'+m.observables.map(o=>`<div class="equation"><b>${esc(o.id)}</b> = ${esc(o.expression)} <small> [${esc(o.unit)}]</small></div>`).join(''):'');}
function readModel(){const m=clone(S.model);m.name=$('projectName').value;m.question=$('question').value;m.t0=$('t0').value;m.t1=$('t1').value;m.outputVar=$('output').value;m.outputMetric=$('metric').value;document.querySelectorAll('[data-initial]').forEach(x=>m.y0[Number(x.dataset.initial)]=x.value);document.querySelectorAll('[data-param]').forEach(x=>m.params[x.dataset.param][Number(x.dataset.paramPart)]=x.value);const normalized=P.normalizeModel(m);if(normalized.t1<=normalized.t0)throw new Error('End time must be greater than start time in the connected workflow.');if(S.path?.id==='plant'&&normalized.params.leafAllocation&&normalized.params.rootAllocation&&normalized.params.leafAllocation[0]+normalized.params.rootAllocation[0]>1)throw new Error('Leaf plus root allocation exceeds one. Review the carbon allocation.');return normalized;}
function editBasic(){clearTimeout(liveTimer);invalidate();try{const next=readModel();if(P.fingerprint(next)!==P.fingerprint(S.model))editor?.remember('input edit');S.model=next;S.invalid=null;document.querySelectorAll('[data-slider]').forEach(sl=>{const p=S.model.params[sl.dataset.slider];sl.min=p[1];sl.max=p[2];sl.step=(p[2]-p[1])/200||1;sl.value=p[0];sl.disabled=p[1]===p[2];});if(!S.draftDirty)$('modelJSON').value=JSON.stringify(S.model,null,2);renderMetadata();queueSave();if($('liveRun').checked)liveTimer=setTimeout(()=>run('simulation'),500);}catch(e){S.invalid=e;showError(e);}}
function renderDataStatus(){if($('dataEditing'))$('dataEditing').open=!S.data;
 if(S.data?.schema===D.SCHEMA){const d=S.data,extra=[...new Set(d.rows.flatMap(r=>Object.keys(r.metadata||{})))];
  $('dataStatus').textContent=`${d.rows.length} observations · ${Object.keys(d.conditions).length} conditions · ${new Set(d.rows.map(r=>r.observable)).size} observables${/synthetic/i.test(d.source)?' · synthetic verification data':''}`;
  makeTable('dataTable','Observation record · no aggregation',['Time', 'Observable','Condition','Replicate','Value','Sigma','Unit',...extra],d.rows.map(r=>[r.time,r.observable,r.condition,r.replicate,r.value,r.sigma,r.unit,...extra.map(k=>r.metadata?.[k]??'')]),'observations.csv');
 }else{$('dataStatus').textContent=S.data?`${S.data.source==='synthetic'?'SYNTHETIC · ':''}${S.data.T.length} observations of ${S.data.output} · ${S.data.source}. ${S.data.output!==S.model.outputVar?'Select this observed state to fit these data.':''}`:'No observations attached. Preview a CSV or open a worked measurement case.';
  if(S.data)makeTable('dataTable','Loaded observations · '+S.data.source,['time ['+S.model.timeUnit+']',S.data.output+' ['+S.data.units+']'],S.data.T.map((t,i)=>[t,S.data.Y[i]]),'observations.csv');else $('dataTable').innerHTML='';
 }
 editor?.updateSplits();
}
function selected(selector,attribute){return Array.from(document.querySelectorAll(selector+':checked')).map(x=>x.getAttribute(attribute));}
function settings(kind){const s={output:S.model.outputVar,metric:S.model.outputMetric};if(kind==='synthetic')Object.assign(s,{count:28,noise:Number($('noise').value),seed:Number($('dataSeed').value)});if(kind==='fit')Object.assign(s,{parameters:selected('[data-fit-param]','data-fit-param'),trainFraction:Number($('trainFraction').value),degree:Number($('fitDegree').value),splitKind:$('splitKind').value,holdoutGroups:editor?.selectedHoldouts()||[]});if(kind==='sensitivity')s.fraction=Number($('perturbation').value);if(kind==='ensemble')Object.assign(s,{parameters:selected('[data-ensemble-param]','data-ensemble-param'),count:Number($('ensembleCount').value),seed:Number($('ensembleSeed').value)});if(kind==='surrogate')Object.assign(s,{parameter:$('surrogateParameter').value,degree:Number($('surrogateDegree').value),count:Number($('surrogateCount').value),seed:Number($('surrogateSeed').value)});return s;}
function settingsValid(kind){const ids={synthetic:['noise','dataSeed'],fit:['trainFraction'],sensitivity:['perturbation'],ensemble:['ensembleCount','ensembleSeed'],surrogate:['surrogateCount','surrogateSeed']}[kind]||[];for(const id of ids)if($(id).value.trim()==='')throw new Error($(id).closest('label').childNodes[0].textContent.trim()+' cannot be blank.');}
async function run(kind,override=null){try{if(kind==='fit'&&S.dataDraftDirty)throw new Error('Validate & use the observation draft before fitting.');if(S.draftDirty)throw new Error('Model JSON has unapplied edits. Review and apply them, or discard the draft before running.');S.model=readModel();S.invalid=null;settingsValid(kind);const request=override||{kind,model:clone(S.model),data:clone(S.data),settings:settings(kind)};if(kind==='fit'&&!S.data)throw new Error('Import or generate observations before fitting.');abortActive();const token=S.sequence,revision=S.revision;const snapshot={model:clone(request.model),data:clone(request.data||null),settings:clone(request.settings),kind};setStatus('running','Computing from an immutable input snapshot…');$('cancelRun').hidden=false;$('runProgress').hidden=false;$('runProgress').value=0;document.querySelectorAll('[data-run],#runRobust,#runCurrent').forEach(b=>b.disabled=true);const job=root.FokoResearchExecutor.start(request,(fraction,message)=>{if(token!==S.sequence||revision!==S.revision)return;$('runProgress').value=fraction;$('runStatus').textContent=message;});S.job=job;
 try{const result=await job.promise;if(token!==S.sequence||revision!==S.revision)return;const record={id:'run-'+Date.now().toString(36)+'-'+S.records.length,createdAt:new Date().toISOString(),source:'computed here',revision,kind,snapshot,result};S.records.push(record);S.current[kind]=record;$('onboarding').hidden=true;if(kind==='synthetic'){S.data=result.data;S.dataDraftDirty=false;S.current.fit=null;$('csvText').value=dataCSV(S.data);renderDataStatus();}setStatus('completed',`${labels[kind]} completed for current inputs.${result.execution==='bounded main-thread fallback'?' Limited browser mode: calculation used the bounded fallback.':''} ${kind==='synthetic'?'Data are synthetic, not measurements.':''}`);if(kind==='simulation')switchTab('model',false);else if(kind==='synthetic'||kind==='fit')switchTab('fit',false);else if(kind==='surrogate')switchTab('ml',false);else switchTab('robust',false);renderCurrent();save();}
 catch(e){if(token===S.sequence&&e.name!=='AbortError')showError(e);}
 finally{if(S.job===job){S.job=null;$('cancelRun').hidden=true;$('runProgress').hidden=true;document.querySelectorAll('[data-run],#runRobust,#runCurrent').forEach(b=>b.disabled=false);editor?.syncTab();}}
 }catch(e){showError(e);}}
const labels={simulation:'Simulation',synthetic:'Synthetic observations',fit:'Fit and held-out comparison',sensitivity:'Local sensitivity',ensemble:'Parameter ensemble',surrogate:'Conditional surrogate'};
function switchTab(tab,changeHash=true){S.tab=tab;document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;$('panel-'+b.dataset.tab).hidden=!active;});if(changeHash)(()=>{try{history.replaceState(null,'','#'+tab);}catch(_){/* Sandboxed previews may forbid history updates. */}})();editor?.syncTab();requestAnimationFrame(renderCurrent);}
function renderRobustControls(){const ensemble=$('robustKind').value==='ensemble';$('ensembleSettings').hidden=!ensemble;$('localSettings').hidden=ensemble;$('robustTitle').textContent=ensemble?'Parameter-propagation envelope':'Output sensitivity';$('robustExplain').textContent=ensemble?'Independent uniform samples inside selected bounds. The 5–95% band is a pointwise simulation summary, not a confidence or credible interval.':'Finite differences around the nominal input. The signed effect is scaled by the declared range, not integrated over a probability distribution.';}
function warnings(list){return list?.length?'<div class="notice warning" style="margin-top:15px">'+list.map(x=>'<p>'+esc(x)+'</p>').join('')+'</div>':'';}
function makeTable(hostId,title,headers,rows,filename){const host=$(hostId);if(!host)return;host.innerHTML='';if(!rows?.length)return;let page=0;const per=12,wrap=document.createElement('div');wrap.className='panel';const head=document.createElement('div');head.className='panel-head';head.innerHTML=`<h3>${esc(title)}</h3><button class="button">CSV</button>`;head.querySelector('button').onclick=()=>download(filename,toCSV(headers,rows),'text/csv');wrap.append(head);const inside=document.createElement('div');inside.className='panel-body';if(rows.length>12){const disclosure=document.createElement('details');disclosure.className='data-disclosure';const summary=document.createElement('summary');summary.textContent='Inspect data table · '+rows.length+' rows';disclosure.append(summary,inside);wrap.append(disclosure);}else wrap.append(inside);function draw(){const subset=rows.slice(page*per,(page+1)*per);inside.innerHTML=`<div class="table-wrap" tabindex="0" aria-label="${esc(title)} data; scroll horizontally when needed"><table><caption>${esc(title)} · ${rows.length} rows · displayed values rounded, CSV retains precision</caption><thead><tr>${headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')}</tr></thead><tbody>${subset.map(row=>'<tr>'+row.map(v=>'<td class="'+(typeof v==='number'?'num':'')+'">'+esc(typeof v==='number'?fmt(v):v===null?'not defined':v)+'</td>').join('')+'</tr>').join('')}</tbody></table></div><div class="table-pagination"><span>${page*per+1}–${Math.min(rows.length,(page+1)*per)} of ${rows.length}</span><div class="actions"><button class="button" data-page="prev" ${page===0?'disabled':''}>Previous</button><button class="button" data-page="next" ${(page+1)*per>=rows.length?'disabled':''}>Next</button></div></div>`;inside.querySelector('[data-page=prev]').onclick=()=>{page--;draw();};inside.querySelector('[data-page=next]').onclick=()=>{page++;draw();};}draw();host.append(wrap);}
function csvCell(v){let s=String(v??'');if(typeof v==='string'&&/^[=+@\-]/.test(s))s="'"+s;return /[,"\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function toCSV(headers,rows){return [headers,...rows].map(r=>r.map(csvCell).join(',')).join('\n');}
function dataCSV(d){if(d.schema===D.SCHEMA)return D.toCSV(d);return toCSV(['time',d.output],d.T.map((t,i)=>[t,d.Y[i]]));}
function renderSimulation(){const r=S.current.simulation?.result,m=S.model;if(!r){Charts.empty($('simulationPlot'));$('simulationStats').innerHTML='';$('simulationSummary').textContent=S.pin?'A historical baseline is pinned. Run the current model before comparing.':'Run a simulation before interpreting a curve.';$('simulationTable').innerHTML='';$('baselineChanges').hidden=true;return;}const t=r.trajectory,idx=m.vars.indexOf(m.outputVar),view=$('trajectoryView').value;let series=[],opts={xlabel:'Time ['+m.timeUnit+']',ylabel:m.outputVar+' ['+(m.units[m.outputVar]||'unspecified')+']',title:m.name+' · '+view};
 if(view==='phase'){if(m.vars.length<2){Charts.empty($('simulationPlot'),'A phase portrait needs at least two states.','Select the state trajectory or add another state in Model JSON.');return;}series=[{name:m.vars[0]+' vs '+m.vars[1],x:t.Y[0],y:t.Y[1]}];opts={...opts,xlabel:m.vars[0]+' ['+m.units[m.vars[0]]+']',ylabel:m.vars[1]+' ['+m.units[m.vars[1]]+']'};}else if(view==='all'||view==='normalized'){series=m.vars.map((v,i)=>{let y=t.Y[i];if(view==='normalized'){const lo=Math.min(...y),span=Math.max(...y)-lo;y=y.map(x=>span?(x-lo)/span:0);}return {name:v+' ['+(view==='normalized'?'0–1':m.units[v]||'?')+']',x:t.T,y,dash:i%2?'7 3':null};});opts.ylabel=view==='normalized'?'Within-run normalized value':'State value (see series units)';}else{series=[{name:m.outputVar+' · current',x:t.T,y:t.Y[idx]}];if(S.pin){const b=S.pin.snapshot.model,j=b.vars.indexOf(m.outputVar);if(j>=0&&b.timeUnit===m.timeUnit&&b.units[m.outputVar]===m.units[m.outputVar])series.push({name:'Pinned earlier run · '+new Date(S.pin.createdAt).toLocaleTimeString(),x:S.pin.result.trajectory.T,y:S.pin.result.trajectory.Y[j],dash:'6 5'});}}
 Charts.line($('simulationPlot'),series,opts);$('simulationDescription').textContent='Computed from the current input snapshot. '+(view==='all'?'Different state units may make magnitude comparisons misleading.':'');$('simulationSummary').innerHTML=`${esc(r.output)} · ${esc(S.model.outputMetric)} = <b>${esc(fmt(r.metric))}</b>. ${['max','min','range'].includes(m.outputMetric)?'Extrema refer to stored output samples, not a continuous-time optimum.':m.outputMetric==='integral'?'Trapezoidal integral of stored samples; check output-grid refinement.':m.outputMetric==='mean'?'Arithmetic mean of stored samples; not a continuous-time average.':''} ${warnings(r.warnings)}`;$('simulationStats').innerHTML=`<details class="solver-details"><summary>Numerical diagnostics · ${esc(r.trajectory.diagnostics.method)}</summary><div class="solver-stats"><div class="stat"><strong>${r.trajectory.diagnostics.accepted}</strong><span>accepted steps</span></div><div class="stat"><strong>${r.trajectory.diagnostics.rejected}</strong><span>rejected attempts</span></div><div class="stat"><strong>${fmt(m.rtol)}</strong><span>relative tolerance</span></div></div><p>${esc(r.execution||'Execution mode recorded in the run')}</p></details>`;
 $('baselineChanges').hidden=!S.pin;if(S.pin){const diff=H.differences(S.pin.snapshot.model,m);$('baselineChanges').textContent=`Baseline: ${S.pin.scenarioName||S.pin.snapshot.model.name}. ${diff.length?diff.slice(0,5).map(d=>d.field+': '+JSON.stringify(d.before)+' → '+JSON.stringify(d.after)).join('; '):'Same model inputs.'}`;}
makeTable('simulationTable','Computed trajectory',['time ['+m.timeUnit+']',...m.vars.map(v=>v+' ['+m.units[v]+']')],t.T.map((x,i)=>[x,...t.Y.map(y=>y[i])]),'trajectory.csv');}
function renderFit(){if(S.data?.schema===D.SCHEMA){renderStructuredFit();return;}$('fitSeries').closest('label').hidden=true;$('residualPlot').closest('details').hidden=true;const r=S.current.fit?.result;if(!r){if(S.data)Charts.line($('fitPlot'),[{name:S.data.source+' observations',x:S.data.T,y:S.data.Y,mode:'points'}],{xlabel:'Time ['+S.model.timeUnit+']',ylabel:S.data.output+' ['+S.data.units+']',title:'Loaded observations'});else Charts.empty($('fitPlot'),'Bring data to the model.','Import your observations, or explicitly generate labeled synthetic data for a recovery experiment.');$('fitSummary').textContent='The final time segment will be held out from fitting.';$('fitScores').innerHTML='';$('fitEstimates').innerHTML='';return;}
 const n=r.split.nTrain,ser=[{name:'Training observations',x:r.T.slice(0,n),y:r.Y.slice(0,n),mode:'points',color:Charts.colors()[4]},{name:'Held-out observations',x:r.T.slice(n),y:r.Y.slice(n),mode:'points',hollow:true,color:Charts.colors()[4]},...['mechanistic','data-only','hybrid'].map((name,i)=>({name,x:r.T,y:r.predictions[name],color:Charts.colors()[i],dash:i?'7 4':null}))];Charts.line($('fitPlot'),ser,{xlabel:'Time ['+S.model.timeUnit+']',ylabel:r.output+' ['+(S.model.units[r.output]||'?')+']',title:'Model comparison on common held-out observations',cutoff:r.split.cutoff});$('fitSummary').innerHTML=`${r.split.nTrain} training observations; ${r.split.nTest} held out. Fitted values are <b>not</b> applied to your nominal model automatically.${warnings(r.warnings)}`;makeTable('fitScores','Same split · four comparison models',['Model','Train RMSE','Held-out RMSE','Held-out MAE'],r.scores.map(x=>[x.name,x.train.rmse,x.test.rmse,x.test.mae]),'fit-scores.csv');makeTable('fitEstimates','Fitted parameter values',['Parameter','Estimate','Original nominal','Minimum','Maximum'],Object.entries(r.fitted).map(([k,v])=>[k,v,S.model.params[k][0],S.model.params[k][1],S.model.params[k][2]]),'fitted-parameters.csv');const b=document.createElement('button');b.className='button';b.textContent='Apply these fitted values to the model';b.style.marginTop='12px';b.onclick=()=>{const m=clone(S.model);Object.entries(r.fitted).forEach(([k,v])=>m.params[k][0]=v);editor?.remember('apply fitted values');S.model=P.normalizeModel(m);invalidate('Fitted values applied. Run the updated nominal model; earlier calculations remain historical.');renderInputs();switchTab('model');};$('fitEstimates').append(b);renderDataStatus();}
function renderRobust(){const kind=$('robustKind').value,r=S.current[kind]?.result;if(!r){Charts.empty($('robustPlot'),'Test what your conclusion depends on.','Declare parameter ranges and the output quantity before running.');$('robustSummary').textContent='';$('robustTable').innerHTML='';return;}if(kind==='sensitivity'){Charts.bars($('robustPlot'),r.rows.map(x=>({name:x.parameter,value:x.rangeScaled})),{title:'Signed range-scaled local sensitivity'});$('robustSummary').innerHTML=`Baseline ${esc(r.output)} · ${esc(r.metric)} = ${fmt(r.baseline)}. ${r.rows.length>12?'The graph shows 12 parameters; the table includes all.':''}${warnings(r.warnings)}`;makeTable('robustTable','Finite-difference results',['Parameter','Raw derivative','Range-scaled effect','Elasticity','Lower input','Upper input'],r.rows.map(x=>[x.parameter,x.derivative,x.rangeScaled,x.relative,x.lo,x.hi]),'local-sensitivity.csv');}else{Charts.line($('robustPlot'),[{name:'Ensemble median',x:r.T,y:r.median}],{xlabel:'Time ['+S.model.timeUnit+']',ylabel:r.output+' ['+S.model.units[r.output]+']',title:'Pointwise ensemble quantiles',band:{x:r.T,lower:r.lower,upper:r.upper}});$('robustSummary').innerHTML=`${r.samples.length} independent-uniform parameter samples. Metric interval: ${fmt(r.interval[0])} to ${fmt(r.interval[1])}.${warnings(r.warnings)}`;makeTable('robustTable','Pointwise simulation quantiles',['Time','5th percentile','Median','95th percentile'],r.T.map((t,i)=>[t,r.lower[i],r.median[i],r.upper[i]]),'ensemble-quantiles.csv');}}
function renderSurrogate(){const r=S.current.surrogate?.result;if(!r){Charts.empty($('surrogatePlot'),'Test a learned approximation of your model.','A polynomial surrogate, a baseline and untouched reference simulations will be compared.');['surrogateScores','surrogateOutside','surrogateCoefficients'].forEach(id=>$(id).innerHTML='');$('surrogateSummary').textContent='';return;}Charts.line($('surrogatePlot'),[{name:'Learned conditional response',x:r.grid.x,y:r.grid.y},{name:'Training simulations',x:r.trainX,y:r.trainY,mode:'points',color:Charts.colors()[0]},{name:'Held-out simulator references',x:r.testX,y:r.testY,mode:'points',hollow:true,color:Charts.colors()[1]}],{xlabel:r.parameter+' (declared model units)',ylabel:r.output+' · '+r.metric,title:'Conditional simulator surrogate with disjoint held-out settings'});$('surrogateDescription').textContent=`${r.parameter} varies; all other inputs remain nominal.`;$('surrogateSummary').innerHTML=`Training range: ${fmt(r.regression.trainingRange[0])} to ${fmt(r.regression.trainingRange[1])}. The regression’s center and scale come from training data only.${warnings(r.warnings)}`;makeTable('surrogateScores','Held-out simulator agreement',['Estimator','Held-out RMSE','Held-out MAE','Test points'],r.scores.map(x=>[x.name,x.rmse,x.mae,x.n]),'surrogate-scores.csv');makeTable('surrogateOutside','Outside-range stress test · not safe deployment',['Input','Simulator reference','Surrogate','Status'],r.outside.map(x=>[x.x,x.reference??null,x.prediction,x.status+(x.reason?': '+x.reason:'')]),'surrogate-outside-range.csv');makeTable('surrogateCoefficients','Learned coefficients in normalized z',['Term','Coefficient'],r.regression.coefficients.map((v,i)=>['z^'+i,v]),'surrogate-coefficients.csv');}
function renderEvidence(){const c=E.validationChecklist(S.model);$('readiness').innerHTML=[['Scientific question recorded',c.question],['State and time units recorded (not dimension-checked)',c.units],['Model assumptions recorded',c.assumptions],['Observations attached',Boolean(S.data)],['Locally executed records in this project',S.records.some(r=>r.source==='computed here')],['An interpretation and a falsifying next test recorded',Boolean(S.notes.interpretation&&S.notes.nextTest)]].map(([label,ok])=>`<div class="readiness" data-ready="${ok}"><span class="dot" aria-hidden="true"></span><span>${ok?'Recorded: ':'Missing: '}${esc(label)}</span></div>`).join('')+'<p class="right-note">These are documentation checks, not scores of scientific validity. Imported results remain unverified.</p>';$('historyCount').textContent=S.records.length+' calculations';$('runHistory').innerHTML=S.records.length?S.records.slice().reverse().map(r=>{const current=Object.values(S.current).some(x=>x?.id===r.id);return `<article class="run-record"><h4>${esc(labels[r.kind]||r.kind)}</h4><p>${esc(new Date(r.createdAt).toLocaleString())} · ${current?'current inputs':'historical snapshot'}</p><p>${esc(r.source)} · ${esc(r.result?.execution||'execution mode not recorded')}</p><code>${esc(r.result?.modelFingerprint||'fingerprint not recorded')}</code><div class="actions"><button class="button" data-restore="${esc(r.id)}">Restore inputs</button><button class="button" data-export-run="${esc(r.id)}">JSON</button>${r.kind==='simulation'?`<button class="button" data-pin="${esc(r.id)}">${S.pin?.id===r.id?'Unpin':'Pin baseline'}</button>`:''}</div></article>`;}).join(''):'<p class="muted">No calculations recorded yet. Run the model or generate an explicit synthetic experiment.</p>';
 document.querySelectorAll('[data-restore]').forEach(b=>b.onclick=()=>{const r=S.records.find(x=>x.id===b.dataset.restore);if(!r?.snapshot?.model){showError(new Error('This record has no replayable model snapshot.'));return;}try{editor?.remember('restore historical inputs');S.model=P.normalizeModel(r.snapshot.model);S.data=validateData(r.snapshot.data,S.model);S.invalid=null;S.draftDirty=false;invalidate('Historical inputs restored. Recompute; the old result is not marked current.');renderInputs();applySettings(r.kind,r.snapshot.settings||{});switchTab(r.kind==='fit'||r.kind==='synthetic'?'fit':r.kind==='surrogate'?'ml':r.kind==='simulation'?'model':'robust');}catch(e){showError(e);}});document.querySelectorAll('[data-export-run]').forEach(b=>b.onclick=()=>download('FokoLab-'+b.dataset.exportRun+'.json',JSON.stringify(S.records.find(x=>x.id===b.dataset.exportRun),null,2)));document.querySelectorAll('[data-pin]').forEach(b=>b.onclick=()=>{S.pin=S.pin?.id===b.dataset.pin?null:S.records.find(x=>x.id===b.dataset.pin);toast(S.pin?'Baseline pinned. Compatible state and time units are required for an overlay.':'Baseline unpinned.');renderEvidence();});editor?.renderAttachments();}
function applySettings(kind,s){if(s.output&&S.model.vars.includes(s.output))$('output').value=s.output;if(s.metric)$('metric').value=s.metric;if(kind==='fit'){$('splitKind').value=s.splitKind||'time';editor?.updateSplits();$('holdoutGroups').querySelectorAll('input').forEach(x=>x.checked=(s.holdoutGroups||[]).includes(x.value));$('trainFraction').value=s.trainFraction??.7;$('fitDegree').value=s.degree??2;document.querySelectorAll('[data-fit-param]').forEach(x=>x.checked=s.parameters?.includes(x.dataset.fitParam));}if(kind==='ensemble'||kind==='sensitivity'){$('robustKind').value=kind;renderRobustControls();if(kind==='ensemble'){$('ensembleCount').value=s.count;$('ensembleSeed').value=s.seed;document.querySelectorAll('[data-ensemble-param]').forEach(x=>x.checked=s.parameters?.includes(x.dataset.ensembleParam));}else $('perturbation').value=s.fraction;}if(kind==='surrogate'){$('surrogateParameter').value=s.parameter;$('surrogateDegree').value=s.degree;$('surrogateCount').value=s.count;$('surrogateSeed').value=s.seed;}if(kind==='synthetic'){$('noise').value=s.noise;$('dataSeed').value=s.seed;}}
function renderCurrent(){if(!S.model)return;document.querySelectorAll('[data-reveal]').forEach(a=>{const k=a.dataset.reveal;a.hidden=!(k==='robust'?(S.current.sensitivity||S.current.ensemble):S.current[k]);});try{if(S.tab==='model')renderSimulation();if(S.tab==='fit')renderFit();if(S.tab==='robust')renderRobust();if(S.tab==='ml')renderSurrogate();renderEvidence();}catch(e){showError(e);}}
function exportBundle(){if(S.invalid||S.draftDirty)throw new Error('Resolve invalid or unapplied model edits before exporting the experiment.');S.model=readModel();download('FokoLab-'+S.id+'.json',JSON.stringify(bundle(),null,2));}
function researchNote(){const m=S.model;return `# ${m.name}\n\nFokoLab ${E.VERSION} · ${new Date().toISOString()}\n\n## Question\n${m.question||'Not supplied'}\n\n## Assumptions\n${m.assumptions.map(x=>'- '+x).join('\n')||'Not supplied'}\n\n## Prediction before running\n${S.notes.hypothesis||'Not recorded'}\n\n## Interpretation and alternatives\n${S.notes.interpretation||'Not recorded'}\n\n## Next falsifying test\n${S.notes.nextTest||'Not recorded'}\n\n## Observations\n${S.data?S.data.source+'; '+S.data.T.length+' points of '+S.data.output:'None'}\n\n## Calculations\n${S.records.map(r=>`### ${labels[r.kind]||r.kind}\n${r.createdAt} · ${r.source}\nModel: ${r.result.modelFingerprint}\nSettings: ${JSON.stringify(r.snapshot.settings)}\n${r.result.metric!==undefined&&typeof r.result.metric==='number'?'Output metric: '+r.result.metric+'\n':''}${r.result.fitted?'Fitted parameters: '+JSON.stringify(r.result.fitted)+'\n':''}${r.result.scores?'Scores: '+JSON.stringify(r.result.scores)+'\n':''}${r.result.warnings?.map(w=>'- '+w).join('\n')||''}`).join('\n\n')||'None'}\n\n## Reproduction\nUse the companion foko.research/1 JSON bundle. Historical results retain their own inputs and require independent reproduction. Numerical agreement does not establish empirical validity.\n`;}
function renderStructuredFit(){
 const d=S.data,r=S.current.fit?.result,rows=r?.rows||d.rows,selector=$('fitSeries'),previous=selector.value;
 selector.closest('label').hidden=false;
 const channels=[...new Set(rows.map(x=>JSON.stringify([x.condition,x.observable])))];
 selector.innerHTML=channels.map(c=>{const [condition,observable]=JSON.parse(c);return `<option value="${esc(c)}">${esc(condition)} · ${esc(observable)}</option>`;}).join('');
 selector.value=channels.includes(previous)?previous:channels[0];
 const [condition,observable]=JSON.parse(selector.value),indices=rows.map((x,i)=>i).filter(i=>rows[i].condition===condition&&rows[i].observable===observable).sort((i,j)=>rows[i].time-rows[j].time),unit=rows[indices[0]].unit;
 const baseOptions={xlabel:'Time ['+S.model.timeUnit+']',ylabel:observable+' ['+unit+']',title:condition+' · '+observable,description:`${observable} in ${condition}. Filled markers are training data; open markers are held-out data. Where supplied, error bars show one known observation standard deviation, not parameter uncertainty. Row values and predictions are available in the accompanying tables.`};
 if(!r){Charts.line($('fitPlot'),[{name:'Observed '+observable,x:indices.map(i=>rows[i].time),y:indices.map(i=>rows[i].value),error:indices.map(i=>rows[i].sigma),mode:'points',color:Charts.colors()[4]}],baseOptions);$('fitSummary').textContent='Observations are preserved individually. Define the condition inputs and holdout before fitting.';['fitScores','fitEstimates','residualTable'].forEach(id=>$(id).innerHTML='');$('residualPlot').closest('details').hidden=true;return;}
 const training=new Set(r.split.trainIndices),train=indices.filter(i=>training.has(i)),test=indices.filter(i=>!training.has(i));
 const points=(ii,name,hollow)=>({name,x:ii.map(i=>rows[i].time),y:ii.map(i=>rows[i].value),error:ii.map(i=>rows[i].sigma),mode:'points',hollow,color:Charts.colors()[4]});
 const ser=[points(train,'Training measurements',false),points(test,'Held-out measurements',true),...['mechanistic','data-only','hybrid'].map((name,i)=>({name,x:indices.map(j=>rows[j].time),y:indices.map(j=>r.predictions[name][j]),color:Charts.colors()[i],dash:['','7 4','2 4'][i]}))];
 Charts.line($('fitPlot'),ser,{...baseOptions,cutoff:r.split.cutoff});
 const detected=r.warnings.filter(w=>/near a bound|candidate evaluations failed/.test(w)),limits=r.warnings.filter(w=>!detected.includes(w));
 $('fitSummary').innerHTML=`<strong>${r.split.nTrain} training · ${r.split.nTest} held out</strong>. ${esc(r.split.policy)} ${r.objective.weighting.startsWith('fixed')?'Joint objective uses the declared standard deviations.':'Unweighted objective in common observation units.'} Fitted values are not applied automatically.${warnings(detected)}<details><summary>Comparison assumptions &amp; limits</summary>${limits.map(w=>'<p>'+esc(w)+'</p>').join('')}</details>`;
 const standardized=r.objective.type.includes('standardized');
 makeTable('fitScores',standardized?'Same holdout · standardized errors':'Same holdout · prediction errors',['Estimator',standardized?'Train RMSE / sigma':'Train RMSE',standardized?'Held-out RMSE / sigma':'Held-out RMSE'],r.scores.map(x=>[x.name,standardized?x.train.standardizedRMSE:x.train.rmse,standardized?x.test.standardizedRMSE:x.test.rmse]),'model-comparison.csv');
 makeTable('fitEstimates','Shared fitted parameters',['Parameter','Estimate','Original nominal','Lower bound','Upper bound'],Object.entries(r.fitted).map(([k,v])=>[k,v,S.model.params[k][0],S.model.params[k][1],S.model.params[k][2]]),'fitted-parameters.csv');
 const button=document.createElement('button');button.className='button';button.textContent='Apply fitted values to the model';button.onclick=()=>{editor?.remember('apply fitted values');const m=clone(S.model);Object.entries(r.fitted).forEach(([k,v])=>m.params[k][0]=v);S.model=P.normalizeModel(m);invalidate('Fitted values applied; recompute the current model.');renderInputs();switchTab('model');};$('fitEstimates').append(button);
 const multi=document.createElement('details');multi.className='fit-starts';multi.innerHTML='<summary>Optimization evidence · all three starts</summary><div id="fitStarts"></div>';$('fitEstimates').append(multi);
 makeTable('fitStarts','Multistart search',['Start','Objective','Stop reason',...Object.keys(r.fitted)],r.starts.map(x=>[x.start,x.objective,x.stopReason,...Object.keys(r.fitted).map(k=>x.parameters[k])]),'multistart.csv');
 $('residualPlot').closest('details').hidden=false;
 const residual=indices.map(i=>(rows[i].value-r.predictions.mechanistic[i])/(rows[i].sigma||1));
 Charts.line($('residualPlot'),[{name:'Observed − mechanistic prediction'+(standardized?' / sigma':''),x:indices.map(i=>rows[i].time),y:residual,mode:'points'},{name:'Zero residual',x:[rows[indices[0]].time,rows[indices.at(-1)].time],y:[0,0],dash:'5 4'}],{xlabel:'Time ['+S.model.timeUnit+']',ylabel:standardized?'Standardized residual':'Residual ['+unit+']',title:'Residual check · '+condition+' · '+observable});
 makeTable('residualTable','Row-level predictions · original row order',['Row','Condition','Replicate','Observable','Time','Observed','Sigma','Split','Mechanistic','Data-only','Hybrid'],rows.map((x,i)=>[x.rowId,x.condition,x.replicate,x.observable,x.time,x.value,x.sigma,training.has(i)?'train':'holdout',r.predictions.mechanistic[i],r.predictions['data-only'][i],r.predictions.hybrid[i]]),'predictions.csv');
 renderDataStatus();
}
async function runBaseline(scenario){
 try{
  if(S.invalid||S.draftDirty)throw new Error('Resolve current model edits before running a baseline.');
  const model=P.normalizeModel(scenario.model);D.compileObservables(model,root.FokoStudioCompute,root.math);
  abortActive();const token=S.sequence,revision=S.revision,settings={output:model.outputVar,metric:model.outputMetric};
  const request={kind:'simulation',model,data:null,settings};
  setStatus('running','Computing the saved scenario, not the current model…');$('cancelRun').hidden=false;$('runProgress').hidden=false;
  const job=root.FokoResearchExecutor.start(request,(fraction,message)=>{if(token!==S.sequence)return;$('runProgress').value=fraction;$('runStatus').textContent=message;});S.job=job;
  try{
   const result=await job.promise;if(token!==S.sequence||revision!==S.revision)return;
   const record={id:'run-'+Date.now().toString(36)+'-'+S.records.length,createdAt:new Date().toISOString(),source:'computed here',revision,kind:'simulation',scenarioName:scenario.name,snapshot:{model:clone(model),data:clone(scenario.data),settings,kind:'simulation'},result};
   S.records.push(record);S.pin=record;
   setStatus(S.current.simulation?'completed':'ready','Saved baseline computed and pinned. '+(S.current.simulation?'Compare it with the current trajectory.':'Run the current model to see the comparison.'));
   switchTab('model');renderCurrent();save();
  }catch(e){if(token===S.sequence&&e.name!=='AbortError')showError(e);}
  finally{if(S.job===job){S.job=null;$('cancelRun').hidden=true;$('runProgress').hidden=true;editor?.syncTab();}}
 }catch(e){showError(e);}
}
function safeAction(fn){return(...args)=>{try{fn(...args);}catch(e){showError(e);}};}
['projectName','question','t0','t1','output','metric'].forEach(id=>$(id).addEventListener(id==='output'||id==='metric'?'change':'input',()=>{editBasic();if(id==='output')renderDataStatus();}));
$('modelJSON').addEventListener('input',()=>{S.draftDirty=true;abortActive();setStatus('outdated','Model JSON is a draft. Review and apply, or discard it before running.');});const discard=document.createElement('button');discard.className='button';discard.textContent='Discard JSON draft';discard.style.marginTop='8px';discard.onclick=()=>{$('modelJSON').value=JSON.stringify(S.model,null,2);S.draftDirty=false;setStatus('ready','JSON draft discarded; the applied model is unchanged.');};$('reviewModel').after(discard);
$('reviewModel').onclick=safeAction(()=>{const proposed=P.normalizeModel(JSON.parse($('modelJSON').value));root.FokoStudioCompute.compile(proposed,root.math);D.compileObservables(proposed,root.FokoStudioCompute,root.math);if(proposed.t1<=proposed.t0)throw new Error('The connected workflow needs an increasing time span.');S.pendingModel=proposed;$('modelDiff').innerHTML=`<p><b>${esc(proposed.name)}</b></p><p>${proposed.vars.length} states · ${Object.keys(proposed.params).length} parameters · ${proposed.t0} to ${proposed.t1} ${esc(proposed.timeUnit)}</p>${proposed.vars.map((v,i)=>'<div class="equation"><b>d'+esc(v)+'/dt</b> = '+esc(proposed.eqs[i])+'</div>').join('')}<p>Previous model ID: ${P.fingerprint(S.model)}<br>Proposed model ID: ${P.fingerprint(proposed)}</p>`;$('reviewDialog').showModal();});$('applyModel').onclick=safeAction(()=>{const data=validateData(S.data,S.pendingModel);D.compileObservables(S.pendingModel,root.FokoStudioCompute,root.math);editor?.remember('reviewed JSON model');S.model=S.pendingModel;S.data=data;S.path=null;S.invalid=null;S.draftDirty=false;invalidate('Reviewed model applied. Previous results remain historical.');renderInputs();$('reviewDialog').close();$('reviewModel').focus();});
$('cancelRun').onclick=()=>{abortActive();setStatus('cancelled','Calculation cancelled. No partial result was published.');};document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>run(b.dataset.run));$('runRobust').onclick=()=>run($('robustKind').value);$('robustKind').onchange=()=>{renderRobustControls();renderRobust();editor?.syncTab();};$('trajectoryView').onchange=renderSimulation;
['noise','dataSeed','trainFraction','fitDegree','perturbation','ensembleCount','ensembleSeed','surrogateParameter','surrogateDegree','surrogateCount','surrogateSeed'].forEach(id=>$(id).addEventListener('change',()=>invalidate('Analysis settings changed. Run again for the new settings.')));
$('csvText').addEventListener('input',()=>{S.dataDraftDirty=true;abortActive();setStatus('outdated','Observation text is a draft. Validate & use it before fitting.');});
$('csvFile').onchange=async()=>{try{const file=$('csvFile').files[0];if(!file)return;if(file.size>2000000)throw new Error('CSV exceeds the 2 MB input limit.');$('csvText').value=await file.text();S.dataDraftDirty=true;abortActive();toast('File read. Validate & use observations before fitting.');}catch(e){showError(e);}};$('applyCSV').onclick=safeAction(()=>{const d=E.observations($('csvText').value,S.model,S.model.outputVar);S.data=d;S.dataDraftDirty=false;invalidate('Observations validated and attached. Fit using the explicit chronological split.');renderDataStatus();renderFit();save();});
$('importProject').onclick=()=>$('projectFile').click();$('projectFile').onchange=async()=>{try{const file=$('projectFile').files[0];if(!file)return;if(file.size>15000000)throw new Error('Import a JSON file smaller than 15 MB.');const text=await file.text(),raw=JSON.parse(text);const validated=P.normalizeModel(raw.model||raw);root.FokoStudioCompute.compile(validated,root.math);abortActive();load(raw,true);renderInputs();renderCurrent();save();setStatus('ready','Imported model validated syntactically. Any imported results remain unverified until recomputed.');switchTab('model');}catch(e){showError(e);}finally{$('projectFile').value='';}};
$('advancedStudio').onclick=safeAction(()=>{if(S.invalid||S.draftDirty)throw new Error('Apply a valid model before transfer.');const project=P.create({model:readModel(),name:S.model.name});try{localStorage.setItem('fokolab:v73:model-studio-project',JSON.stringify(project));location.href='studio.html?research=1';}catch(_){download('FokoLab-studio-transfer.json',JSON.stringify(project,null,2));toast('Storage unavailable. Import the downloaded Project JSON in advanced Studio.');}});
$('saveProject').onclick=safeAction(exportBundle);$('exportBundle').onclick=safeAction(exportBundle);$('exportNote').onclick=safeAction(()=>download('FokoLab-research-note.md',researchNote(),'text/markdown'));$('exportAI').onclick=safeAction(()=>download('FokoLab-AI-review.md',E.aiBrief({model:S.model,results:S.records.map(r=>r.result)}),'text/markdown'));$('exportPython').onclick=safeAction(()=>{if(S.invalid||S.draftDirty)throw new Error('Apply valid model edits before exporting.');const bytes=new TextEncoder().encode(JSON.stringify(readModel()));let raw='';bytes.forEach(b=>raw+=String.fromCharCode(b));const script=root.FokoResearchPythonTemplate.replace('{MODEL_BASE64}',btoa(raw));download('fokolab_simulation.py',script,'text/x-python');});
['hypothesis','interpretation','nextTest'].forEach(id=>$(id).oninput=()=>{S.notes[id]=$(id).value;queueSave();});$('dismissGuide').onclick=()=>{$('onboarding').hidden=true;Store.set('foko:research:guideDismissed',true);};document.querySelectorAll('[data-tab]').forEach(b=>{b.onclick=()=>switchTab(b.dataset.tab);b.onkeydown=e=>{const tabs=Array.from(document.querySelectorAll('[data-tab]')),i=tabs.indexOf(b);let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;else if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=tabs.length-1;else return;e.preventDefault();tabs[j].focus();switchTab(tabs[j].dataset.tab);};});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(renderCurrent,180);});document.addEventListener('foko:appearance',renderCurrent);window.addEventListener('beforeunload',e=>{if(S.invalid||S.draftDirty||S.job){e.preventDefault();e.returnValue='';}save();});
root.FokoResearchWorkspace=Object.freeze({getState:()=>clone({id:S.id,model:S.model,data:S.data,records:S.records,revision:S.revision,currentKinds:Object.keys(S.current).filter(k=>S.current[k]),invalid:S.invalid?.message,tab:S.tab,scenarios:S.scenarios,attachments:S.attachments,pinned:S.pin?.id||null}),run,bundle,exportNote:researchNote});init();
editor=root.FokoResearchEditing.mount({state:()=>S,run,readModel,error:showError,save,renderFit,renderEvidence,invalidate,
 restore(value){const m=P.normalizeModel(value.model),data=validateData(value.data,m);root.FokoStudioCompute.compile(m,root.math);D.compileObservables(m,root.FokoStudioCompute,root.math);S.model=m;S.data=data;S.invalid=null;S.draftDirty=false;S.dataDraftDirty=false;invalidate('Configuration restored. Recompute for current evidence.');renderInputs();renderCurrent();save();},
 commitModel(m){const data=validateData(S.data,m);S.model=m;S.data=data;S.path=null;S.invalid=null;S.draftDirty=false;invalidate('Reviewed model applied. Recompute for current inputs.');renderInputs();renderCurrent();save();},
 commitData(d){S.data=d;S.dataDraftDirty=false;$('csvText').value=d?dataCSV(d):'';invalidate(d?'Reviewed observations attached. Configure the holdout before fitting.':'Observations detached; earlier runs retain them.');renderDataStatus();renderFit();save();},runBaseline
});
})(window);
