/* Original worked learning material: definitions → derivation → experiment → criticism.
 * References are starting points, not claims that an external source validates this app.
 */
(function(root){'use strict';const L=[
{id:'measurement',title:'From the instrument to a defensible fit',track:'Infer',path:'dynamics',time:'35–50 min',goal:'Keep states, measurements, conditions, replicates and noise separate; trace a fitted rate to held-out evidence.',intro:'This worked case uses explicitly synthetic fluorescence. The latent concentration decays; the instrument measures a scaled signal with a background. A correct ODE is not enough when the observation equation is wrong.',body:`
<h2>1. Predict before running</h2><p>Open the <a href="workspace.html?case=fluorescence">fluorescence investigation</a>. There are two initial concentrations, two replicates per condition and 13 times per replicate. The 52 rows are generated examples, not laboratory measurements. Predict whether doubling the initial concentration doubles the measured signal when an additive background is present.</p>
<h2>2. Derive the measurement</h2><pre class="math-line">dx/dt = −k x             x(0) = x₀,condition
x(t) = x₀,condition exp(−kt)
signal(t) = gain × x(t) + background</pre>
<p>The instrument has fixed calibration gain = 3 and background = 0.2 arbitrary fluorescence units (AU). Thus doubling x₀ doubles <em>signal − background</em>, not the full signal. At t = 0, low and high conditions produce 3.2 and 6.2 AU: 6.2 is not twice 3.2.</p>
<p>The synthetic generator uses k = 0.35 h⁻¹. At t = 2 h, the low-condition expected signal is 3 exp(−0.7) + 0.2, approximately 1.690 AU. These analytic numbers verify the forward model; noisy observations need not equal them.</p>
<h2>3. Explain the objective before optimizing</h2><p>Each measurement has a supplied observation standard deviation σ = 0.06 AU. The browser minimizes the root mean squared standardized residual. Minimizing it gives the same parameter estimate as weighted squared residuals with these fixed σ values:</p><pre class="math-line">residualᵢ = [predictionᵢ(k) − measurementᵢ] / σᵢ
objective = sqrt(mean(residualᵢ²))   over training rows only</pre>
<p>With predictions [1.12, 1.12], measurements [1.00, 1.00] and standard deviations [0.06, 0.12], the standardized residuals are [2, 1]. Their squared contributions are [4, 1], not equal. This weighting is a noise-model assumption, not a stylistic normalization.</p>
<h2>4. Compute without erasing experimental structure</h2><p>Inspect the structured editor’s Measurements tab and the imported observation table. The low/high conditions differ in x₀; they share k. Replicates share the deterministic mean trajectory but retain individual noise realizations. They are not silently averaged. The sigma bars represent one observation standard deviation, not parameter confidence intervals.</p>
<p>Keep the chronological split at 70%. All measurements at times 0–4 h train the model (36 rows); 4.5–6 h are held out (16 rows). Click Fit &amp; compare. Three bounded coordinate-search starts estimate k; fixed calibration parameters are not selected for fitting. Inspect the starts and residuals, not just the selected estimate.</p>
<h2>5. Diagnose rather than declare a winner</h2><p>The comparison includes a constant, the mechanism, a pooled time-polynomial and an additive residual correction. The polynomial baseline deliberately has no condition information. It cannot represent two distinct initial concentrations at the same time; this is a known limitation of that baseline, not proof that every ML model is inferior.</p>
<p>Change the holdout to an entire condition or replicate. State what generalization question each split asks. Repeatedly tuning after inspecting this holdout makes it a development set; reserve independent data before making a final validation claim.</p>
<h2>6. Inject a meaningful failure</h2><p>Duplicate the scenario, then set the background to zero in the parameter editor. Expand its bound explicitly if necessary. Before fitting again, predict the late-time residual direction. With the same k, predictions will be too small by 0.2 AU; refitting k can partly compensate, so diagnose the remaining structured bias rather than expect exactly −0.2 after optimization.</p>
<p>Now consider estimating both gain and x₀ from one uncalibrated condition. Their product appears in the measurement equation; these data alone cannot identify them separately. This browser release fits shared parameters, not initial values or a hierarchical replicate model. Use the derived ambiguity as evidence, not an unsupported browser-fit claim.</p>
<h2>7. Transfer and retain</h2><p>Attach the executed fitting record to <strong>Infer</strong>. Write which observable and intervention support the rate estimate, how the holdout was chosen, and why this synthetic recovery does not validate the biology. The exported attachment contains the run’s actual model, data, settings and diagnostics. The book’s chapters 1 and 11 provide the measurement/inference framing; chapter 19 develops structured validation. Work through predict → derive → compute → diagnose → transfer.</p>
<p>For an actual lipid, T-cell or photosynthesis dataset, replace the generator with documented measurements, units and experimental conditions. Unknown columns remain metadata until explicitly modeled. The importer does not implement full PEtab, correlated errors, fitted noise, dosing events or automatic unit conversion.</p>`,
practices:[['Separate signal from state','At time zero, x₀=2, gain=3 and background=0.2. What does the instrument report before noise? What doubles when x₀ doubles?','Substitute into h(x); subtract the background before comparing ratios.','The expectation is 6.2 AU. Doubling x₀ doubles the background-corrected signal. Raw fluorescence is not the modeled concentration.'],['Choose the holdout','The future task is prediction under a new initial-concentration condition. Would holding out late times from both existing conditions directly test that task?','Compare which information remains in the training set under each split.','No. A chronological split tests later-time prediction in conditions already observed. Holding out a complete condition tests transfer to the declared new condition, assuming its inputs are known. Neither split validates an unrepresented biological regime.']],
check:{q:'What does a low training error establish?',options:['Every rate and calibration parameter is identified','The selected model matches the training objective; identifiability and external validity remain separate questions','The sigma bars are confidence intervals for k'],answer:1,why:'Objective agreement is conditional on the observation equation, data split, noise weights and numerical implementation. It cannot by itself identify parameters or validate biology.'},refs:[['Open the worked experiment','workspace.html?case=fluorescence'],['Programme · Infer','programme.html?gate=infer']]},

{id:'question',title:'From a biological question to an observable',track:'Formulate',path:'plant',time:'20–30 min',goal:'Define a state, a parameter and an observable; choose a productivity metric before comparing scenarios.',intro:'A simulator answers the question encoded in its equations. It does not decide whether that is the scientific question you intended. Start with what changes, what you control and what you can actually observe.',body:`
<h2>1. Separate the three roles</h2><p>A <strong>state</strong> has a value that changes during the model run. A <strong>parameter</strong> controls a process and is held fixed in a particular run. An <strong>observable</strong> is what an experiment measures or what you choose to summarize. These roles are not interchangeable: leaf carbon can be a state, a photosynthetic capacity a parameter, and final plant dry mass an observable.</p>
<div class="concept-strip"><div><strong>State</strong><span>L(t): carbon in leaves, g C</span></div><div><strong>Parameter</strong><span>aL: allocated fraction, unitless</span></div><div><strong>Observable</strong><span>L(T) + R(T) + F(T)</span></div></div>
<h2>2. Derive the quantity you mean</h2><p>Let A(t) be gross carbon assimilation in g C per day. Let C(t) accumulate this carbon, and let L, R and F represent leaf, root and storage carbon. With allocation fractions aL, aR and 1−aL−aR and a shared respiratory rate m:</p>
<pre class="math-line">dC/dt = A(t)
dL/dt = aL A(t) − m L
dR/dt = aR A(t) − m R
dF/dt = (1 − aL − aR) A(t) − m F</pre>
<p>Add the last three equations. For B=L+R+F, dB/dt=A−mB. Thus cumulative gross assimilation C(T)−C(0) is <em>not</em> retained biomass B(T)−B(0). Respiration explains the difference; a prettier growth animation would not remove it.</p>
<h2>3. A worked accounting check</h2><p>Suppose a plant assimilates 0.8 g C in a day, allocates 50% to leaves, 30% to roots and the remainder to storage, and loses 0.1 g C in total respiration. Gross gains are 0.4, 0.24 and 0.16 g C. Total biomass gain is 0.7 g C, not 0.8. The model needs consistent carbon units before those sums mean anything.</p>
<h2>4. Perform a discriminating experiment</h2><p>Open the plant pathway. Run the nominal setting, then reduce irrigation to 0.02 and run again. Pin the first run before comparing C and W. State the horizon: a final-carbon comparison at day 10 can differ from one at day 35. Record which variables were changed, rather than calling the comparison simply “dry versus wet.”</p>
<h2>5. The boundary</h2><p>This reduction does not contain measured site weather, root-dependent uptake, an energy balance or a C4 carbon-concentrating mechanism. A constant temperature input is a controlled scenario, not a climate projection. Use the original plant research page to see what a richer model must retain.</p>`,
practices:[['Choose the output','Two scenarios have the same cumulative assimilation but different final biomass. Is that a contradiction?','Use the summed biomass equation.','No. Different respiratory losses or allocation-dependent losses can produce different retained biomass for the same gross carbon gain. Compare cumulative assimilation and biomass separately.'],['Check an impossible allocation','A proposed model uses aL=0.7 and aR=0.5. What fails?','Compute the remaining fraction.','The storage fraction becomes −0.2. That is not a meaningful positive allocation. Reject the configuration or change the allocation model; do not clamp a negative fraction silently.']],
check:{q:'Which result alone supports a claim about retained carbon?',options:['The cumulative gross assimilation C(T)','The biomass difference B(T)−B(0), with its units and losses accounted for','A larger leaf animation'],answer:1,why:'Gross assimilation excludes losses, while an animation may encode a different quantity. The observable must match the claim.'},refs:[['Original plant-work scope','research/photosynthesis.html']]},
{id:'balance',title:'Flux balances, dimensions and invariants',track:'Formulate',path:'lipid',time:'25–35 min',goal:'Translate a flow diagram into equations and identify what is, and is not, conserved.',intro:'Every source and sink is a claim about the system boundary. Write those claims explicitly before asking a solver to integrate the model.',body:`
<h2>1. Start with one compartment</h2><p>A balance equation states that the rate of change of an amount equals inflow minus outflow. For an amount x in micromoles and time in minutes, dx/dt must be in micromoles per minute. In a first-order loss kx, k therefore has units of inverse minutes. A Michaelis–Menten flux Vmax x/(Km+x) has the units of Vmax; Km must have the same units as x.</p>
<pre class="math-line">dx/dt = u − k x
[x] = μmol; [u] = μmol/min; [k] = 1/min</pre>
<h2>2. Derive an invariant, rather than guessing one</h2><p>For substrate S converting into product P in a closed, one-to-one reaction, dS/dt=−v and dP/dt=v. Add the equations: d(S+P)/dt=0. If S(0)=10 and P(0)=0, their sum must remain 10. That is a useful numerical regression test.</p><p>Now add product clearance cP. The sum obeys d(S+P)/dt=−cP, so conservation no longer holds. An observed decreasing sum is expected, not automatically a solver failure.</p>
<h2>3. Inspect the lipid reduction</h2><p>In the four-pool lipid pathway, each internal conversion appears with a positive and a negative sign. Algebraically adding its four equations cancels these conversion terms:</p>
<pre class="math-line">d(S1+S2+S3+S4)/dt = k1+k2+k3 − αS1 − βS3 − γS4</pre>
<p>This is an open-pool balance. It is not an atom-balanced carbon conservation law: the pools are relative quantities and the reduction does not supply molecular stoichiometric weights. Calling the sum “total carbon” would add information that the model does not contain.</p>
<h2>4. Test a boundary case</h2><p>Take dx/dt=2−0.5x. The equilibrium is x*=2/0.5=4. Starting below 4 should increase x; starting above 4 should decrease it. At x=0 the derivative is positive, so the continuous model cannot cross from nonnegative x to a negative value at that boundary. A computed negative excursion can indicate an unsuitable integration step, but arbitrary clipping changes the numerical method.</p>
<h2>5. What remains to be checked</h2><p>Units recorded in an editor are metadata, not automatic dimensional analysis. Check each term by hand or with a validated unit-aware symbolic tool. Similarly, one trajectory that looks bounded does not prove positivity for all permitted parameters or demonstrate global stability.</p>`,
practices:[['Derive the exact prediction','For dx/dt=2−0.5x and x(0)=0, calculate x(2).','Use x(t)=x*+(x0−x*)exp(−kt).','x(2)=4−4exp(−1)≈2.52848. This gives a concrete reference value, not merely an expected curve shape.'],['Translate a weighted balance','One molecule of S makes two molecules of P. Is S+P conserved?','Write dP/dt=2v.','No. d(S+P)/dt=v. The invariant is 2S+P (or S+P/2), assuming no other sources or sinks. Stoichiometry determines the weights.']],
check:{q:'A relative-pool model lacks molecular weights. What is justified?',options:['Treat the unweighted sum as total carbon','Check the algebraic pool balance while withholding an atom-balance claim','Normalize every curve and call it conserved'],answer:1,why:'Algebraic cancellation is useful, but physical conservation additionally requires consistent quantities and stoichiometric weights.'},refs:[['Lipid research and scope','research/fatty-acid-metabolism.html']]},
{id:'solver',title:'When should you trust a numerical trajectory?',track:'Compute',path:'dynamics',time:'25–40 min',goal:'Separate equation validity, numerical error and observation error; perform a concrete convergence check.',intro:'A successful return code means that a computation completed under an algorithm’s rules. It does not mean that the biological mechanism is correct.',body:`
<h2>1. Three errors, three different questions</h2><p><strong>Numerical error</strong> is disagreement between an approximate calculation and the mathematical solution. <strong>Observation error</strong> concerns the measurements. <strong>Model discrepancy</strong> is a mismatch between the assumed mechanism and the system. Tightening a solver tolerance addresses the first, not the other two.</p>
<h2>2. Build an exact reference</h2><p>For dx/dt=−kx, x(0)=x0, separate variables and integrate: log(x/x0)=−kt. Hence x(t)=x0 exp(−kt). With x0=2, k=0.4 and T=5, x(T)=2 exp(−2)≈0.2706705665.</p>
<pre class="math-line">absolute error = |x_numeric(T) − x_exact(T)|
relative error = absolute error / |x_exact(T)|</pre>
<p>For the logistic pathway the exact solution is x(t)=K/[1+(K/x0−1)exp(−rt)]. Compare the solver to this formula at several times, not only the endpoint. A correct endpoint can hide an incorrect intermediate trajectory.</p>
<h2>3. Tolerances are not truth certificates</h2><p>An adaptive method estimates a local error against an absolute-plus-relative scale. Small populations and large populations therefore need sensible scaling. A local estimate below a tolerance does not guarantee that the final global error has that exact magnitude. It also says nothing about whether logistic growth is appropriate for the organism.</p>
<h2>4. Run a convergence comparison</h2><p>Keep the model, initial state and output times identical. Run at rtol=10⁻⁶, then 10⁻⁸. Compare the output quantity you plan to use, such as final population, integral or peak. For the benchmark, compare each run with the exact result. Record the change together with computational cost. More printed decimal places are not more accuracy.</p>
<h2>5. Detect the wrong strategy</h2><p>Many rejected steps or a rapidly increasing cost can signal stiffness or a singular model region. The browser’s explicit integrator is not a substitute for checking a stiff system with an independent implicit solver. Chaotic systems add another issue: pointwise long-time agreement can disappear while statistical or geometric properties remain comparable.</p>`,
practices:[['Change the time unit','Let τ=t/60 convert seconds to minutes. What happens to dx/dt=−k x?','Apply dx/dτ=(dx/dt)(dt/dτ).','dx/dτ=−60k x. Keeping the same numeric k after changing the time label changes the model by a factor of 60.'],['Test the wrong explanation','The curve disagrees with data by 20%, but changing rtol barely affects it. Should you keep tightening tolerance?','Compare the numerical change with the data mismatch.','Not as the main strategy. Investigate parameter values, the observation model and missing mechanisms. A converged numerical answer can still be a poor scientific model.']],
check:{q:'What does a convergence check establish?',options:['The mechanism is biologically correct','The chosen quantity is becoming insensitive to a numerical setting under the tested conditions','The fit is statistically identifiable'],answer:1,why:'Numerical convergence is an important but separate layer of evidence.'},refs:[['SciPy solve_ivp documentation','https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html']]},
{id:'inverse',title:'Parameter fitting is not parameter identification',track:'Infer',path:'tcell',time:'30–45 min',goal:'Explain non-identifiability using equations and design an observation that breaks a confounding combination.',intro:'An optimizer returns parameters that reduce an objective. It cannot manufacture information absent from the observations.',body:`
<h2>1. Define the forward and inverse problems</h2><p>The forward problem maps parameters θ into a trajectory x(t;θ). The inverse problem uses observations yᵢ at times tᵢ to estimate θ. With additive errors and a squared-error criterion, one objective is the mean of [h(x(tᵢ;θ))−yᵢ]². The observation map h is part of the model: a total count and a generation-resolved count are different measurements.</p>
<h2>2. A proof of confounding</h2><p>For an unlimited birth–death expectation N′=(p−d)N, the trajectory depends on r=p−d. Rates p=0.4,d=0.1 and p=0.8,d=0.5 both give r=0.3. No noiseless, perfectly sampled total-count trajectory separates those pairs under this model. This is structural non-identifiability, not a failure of the fitting algorithm.</p>
<h2>3. Change the observable</h2><p>In the finite-generation teaching model, undivided cells satisfy G0′=−(p+d)G0. Therefore G0 alone determines the sum, not each rate. With G1 initially zero, G1(t)=2pG0(0)t exp[−(p+d)t]. Where G0 is observed, G1/G0=2pt. Generation-resolved observations can contain information that a single aggregate hides.</p>
<pre class="math-line">G0(t) = G0(0) exp[−(p+d)t]
G1(t)/G0(t) = 2pt
p = G1(t)/(2t G0(t)), for t > 0</pre>
<p>This derivation assumes the stated homogeneous constant-rate model, exact observations and compatible generation definitions. It is not a direct formula for noisy cytometry data.</p>
<h2>4. Fitting in the connected workspace</h2><p>The implementation fits one to three declared parameters with a bounded, three-start coordinate search. Only the early training segment enters its objective. The remaining times are evaluated afterwards. It does not compute posterior distributions or prove a global optimum. Near-bound solutions deserve inspection rather than automatic acceptance.</p>
<h2>5. Make the criticism operational</h2><p>Repeat the experiment with another initial guess and a different observable. Ask whether parameter values move while residuals stay nearly unchanged. Use profile likelihood, sensitivity-matrix structure or posterior analysis in a richer inference workflow before claiming a uniquely identified biological rate.</p>`,
practices:[['Recover two idealized rates','At t=2 days, G1/G0=2.4, while G0/G0(0)=exp(−1.6). Find p and d.','First derive p from the ratio, then p+d from G0.','p=2.4/(2×2)=0.6 day⁻¹. The decay rate is 1.6/2=0.8 day⁻¹, hence d=0.2 day⁻¹. This uses both observables.'],['Diagnose a low error','Two fits have the same tiny RMSE but very different rates. Which one is correct?','Distinguish goodness of fit from information about parameters.','The residuals alone do not choose. Examine identifiability, admissible ranges, independent observations and the observation model. Reporting both plausible explanations is more honest than selecting the prettier parameter set.']],
check:{q:'What can G0 alone identify in this reduction?',options:['p and d separately','p+d','p−d'],answer:1,why:'Both rates enter G0 only through the sum in its exponential decay.'},refs:[['T-cell research and model-family distinctions','research/tcell-proliferation.html']]},
{id:'sensitivity',title:'Sensitivity: specify the question before ranking parameters',track:'Challenge',path:'lipid',time:'25–35 min',goal:'Interpret derivatives and parameter-range effects without confusing local and global sensitivity.',intro:'There is no universal ranking of a model’s “important parameters.” A rank belongs to an output, time horizon, operating point and range assumption.',body:`
<h2>1. Reduce the trajectory deliberately</h2><p>A sensitivity calculation needs an output Q(θ). Examples include x(T), the largest sampled value, or an integral over a time interval. A parameter may strongly affect peak timing while barely changing the final state. Select a quantity tied to your scientific question rather than the easiest plot.</p>
<h2>2. Compute a finite difference</h2><p>Near a nominal parameter p, approximate dQ/dp by [Q(p+h)−Q(p−h)]/(2h). In this workspace the perturbation is a stated fraction of the declared parameter range. At a range boundary, the calculation uses the actual asymmetric interval and reports its endpoints. Repeat with a smaller perturbation to check stability.</p>
<pre class="math-line">raw derivative:      dQ/dp
range-scaled effect: (p_max − p_min) dQ/dp
elasticity:          (p/Q) dQ/dp, when Q ≠ 0</pre>
<h2>3. Work through a simple example</h2><p>If Q=exp(−pT), then dQ/dp=−T exp(−pT), and the elasticity is −pT. With p=0.4 and T=5, it is −2. A small 1% increase in p causes approximately a 2% decrease in Q at this operating point. This is a local approximation; it does not predict a 100% change accurately.</p>
<h2>4. Why changing a range changes a rank</h2><p>A range-scaled derivative multiplies by the range width. A parameter with a smaller raw slope can rank higher if it is allowed to vary much more. That is not a contradiction. It makes explicit a decision about plausible variation. Comparing derivatives with different units without scaling can be equally misleading.</p>
<h2>5. What this analysis misses</h2><p>The connected workflow computes local finite differences, not Sobol indices. Interactions, discontinuous branch changes and large excursions need other analyses. Use the global sensitivity lab when a probability distribution over the full parameter domain is justified. A deterministic response sweep is not automatically a variance decomposition.</p>`,
practices:[['Compute a slope','Q is 1.20 at p=0.9 and 1.10 at p=1.1. What derivative is estimated?','Divide the output change by the parameter change.','(1.10−1.20)/(1.1−0.9)=−0.5 output units per parameter unit. The estimate belongs to that finite interval.'],['Stress-test a ranking','Parameter a ranks above b for final x, but below it for peak x. Which rank is wrong?','Name the output functions explicitly.','Neither need be wrong. Final and peak values are different functions of the trajectory. Choose the output relevant to the scientific claim and report the horizon.']],
check:{q:'The plotted range-scaled derivative is best interpreted as:',options:['A universal causal importance score','A local output response scaled by a user-declared range','A total-order Sobol index'],answer:1,why:'It is conditional on the model, nominal point, metric and range, and does not integrate over the parameter distribution.'},refs:[['Global sensitivity workspace','sensitivity.html']]},
{id:'uncertainty',title:'What an uncertainty band actually means',track:'Challenge',path:'plant',time:'25–35 min',goal:'State the distribution behind a band and distinguish simulation quantiles from inference intervals.',intro:'A shaded region is an assertion about variation. Without a sampling rule and a target quantity, it has no unambiguous statistical meaning.',body:`
<h2>1. Declare what varies</h2><p>Here an ensemble samples selected parameters independently and uniformly within their declared bounds, then solves the same ODE. Initial conditions and all unselected parameters remain fixed. A random seed reproduces the sampling sequence. It does not turn the chosen bounds into empirically justified distributions.</p>
<h2>2. Build the band point by point</h2><p>At each time, collect the ensemble’s values for the selected state. Sort them and estimate the 5th, 50th and 95th percentiles. The shaded area is a pointwise central 90% simulation interval. Its median need not equal the trajectory computed at the median parameters because the model is nonlinear.</p>
<h2>3. Do not rename it</h2><p>A <strong>confidence interval</strong> concerns a frequentist procedure for an unknown quantity. A <strong>credible interval</strong> comes from a posterior distribution. A <strong>predictive interval</strong> describes future observations under an explicit predictive model. This ensemble implements none of those inference procedures. It propagates your chosen parameter ranges without observation noise or structural discrepancy.</p>
<h2>4. Pointwise is not simultaneous</h2><p>A central interval that covers 90% of simulated values at each time does not guarantee that 90% of entire trajectories lie inside the band at every time. A claim about full-trajectory coverage requires a different construction. Similarly, a 40-member ensemble has coarse tail estimates; a precise-looking smooth fill cannot fix limited sampling.</p>
<h2>5. Design a useful comparison</h2><p>Run the plant model varying only Amax, then varying Amax and irrigation. Compare not just band width but its source. Repeat with more samples and a new seed. Record whether a scientific conclusion, such as which scenario retains more carbon, changes under those assumptions.</p>`,
practices:[['Identify the missing uncertainty','A model’s parameter ensemble is narrow but field measurements vary widely. What may be absent?','List variation not included in parameter sampling.','Observation error, environmental forcing, individual heterogeneity, initial-condition variation and missing mechanisms may be absent. A narrow conditional ensemble is not evidence that the real system is predictable.'],['Check a nonlinear mean','If Q=p² and p is uniform on [0,2], is E[Q]=Q(E[p])?','Compute the integral of p² and the mean of p separately.','E[p]=1, so Q(E[p])=1. But E[p²]=(1/2)∫₀²p²dp=4/3. Averaging parameters and averaging outputs are different operations.']],
check:{q:'The workspace ensemble band is:',options:['A posterior credible interval','A pointwise simulation quantile band under declared independent uniform ranges','A guarantee that the true biology is inside it'],answer:1,why:'Its interpretation follows exactly from its sampling procedure, not from the visual convention of a shaded band.'},refs:[['Bayesian and advanced methods','advanced-methods.html']]},
{id:'validation',title:'Validation without leaking the answer',track:'Scientific ML',path:'dynamics',time:'30–40 min',goal:'Choose a holdout that matches the intended use and compare models on identical untouched observations.',intro:'The question is not whether a flexible model can fit the data it has seen. It is what happens when the information available at prediction time changes.',body:`
<h2>1. Define the prediction task</h2><p>Forecasting later times in one experiment, predicting a new subject and extrapolating to a new environment are different tasks. Their test sets must reflect those differences. Randomly mixing nearby times across training and test can make a forecasting task appear easier than it is.</p>
<h2>2. Follow the implemented split</h2><p>FokoLab orders observations strictly by time. The first 70% by row count train the models; the final 30% are held out by default. The kinetic fit uses only training residuals. Data-only and hybrid regressions also learn their centering and scaling from training inputs, not the full series. All methods then face the identical test times.</p>
<h2>3. Read all the baselines</h2><p>The comparison includes a constant predictor equal to the training mean, the fitted mechanistic model, a polynomial of time alone and an additive residual hybrid. A complex method should earn its complexity relative to a relevant baseline. Low training error without an improved test score is not evidence of improved generalization.</p>
<pre class="math-line">RMSE = sqrt[ Σ(prediction_i − observation_i)² / n ]
MAE  = Σ|prediction_i − observation_i| / n</pre>
<h2>4. Understand preprocessing leakage</h2><p>Suppose the future test segment has a much larger mean. Centering all inputs before the split allows the training procedure to use information about that future segment. Learn transformation parameters on training data and apply the same transform to held-out data. Feature selection and hyperparameter choice must follow the same separation.</p>
<h2>5. A holdout can be used up</h2><p>Repeatedly choosing polynomial degree, parameter bounds and preprocessing by watching this same test error turns the test set into a development set. For a publishable evaluation, freeze decisions and reserve another independent test set or use an appropriate nested/grouped validation design. The current chronological test does not establish new-subject or new-environment performance.</p>`,
practices:[['Calculate the score','Predictions are [3,5], observations [2,3]. Calculate RMSE and MAE.','Residuals are 1 and 2.','RMSE=√((1²+2²)/2)=√2.5≈1.5811. MAE=(1+2)/2=1.5. Both retain the output’s units; neither explains the error’s cause.'],['Choose a split','You will deploy a model on a new patient. Is holding out every fifth timestamp from each patient sufficient?','Ask whether the test still includes individuals seen during fitting.','No. A subject-level holdout is needed to evaluate new-subject transfer. Within-subject timestamps answer a different question and can leak individual-specific information.']],
check:{q:'When should normalization statistics be estimated?',options:['Before splitting, using every observation','Using only the training portion','Using only the test portion'],answer:1,why:'The test must not influence learned preprocessing. The fitted transformation is then applied unchanged to test inputs.'},refs:[['scikit-learn: common pitfalls and leakage','https://scikit-learn.org/stable/common_pitfalls.html']]},
{id:'surrogate',title:'A surrogate must beat a baseline and survive a challenge',track:'Scientific ML',path:'dynamics',time:'30–45 min',goal:'Train and test an interpretable simulator surrogate without confusing simulator agreement with scientific validation.',intro:'A surrogate approximates a map produced by another model. It is useful when it reproduces the required quantity cheaply enough within an explicitly tested domain.',body:`
<h2>1. Identify the map being learned</h2><p>Choose a parameter p and a scalar trajectory summary Q(p), such as final population. The connected workflow varies that one parameter while holding all others fixed. It samples disjoint training and held-out values from the same declared interval. Each target is generated by the mechanistic simulator, not by an experimental measurement.</p>
<h2>2. Fit a transparent model</h2><p>The model is a polynomial in a normalized coordinate z=(p−c)/s. Center c and scale s are derived from training inputs only. With degree two, Q̂(p)=b0+b1z+b2z². Ridge regularization penalizes the nonconstant coefficients; it does not penalize the intercept. Degree and ridge assumptions are part of the recorded estimator.</p>
<pre class="math-line">min_b Σ[Q_i − (b0+b1 z_i+b2 z_i²)]²
      + λ(b1²+b2²)</pre>
<h2>3. Keep an honest comparison</h2><p>Report held-out RMSE and MAE alongside a constant training-mean baseline and a linear baseline. Choosing a higher degree can improve interpolation but destabilize extrapolation. Read the coefficient table and residuals; do not treat the word “AI” as an extra validation step.</p>
<h2>4. Challenge the domain</h2><p>The workspace evaluates two additional points 10% beyond the declared interval. These are outside-range diagnostics, not a claim of safe use there. A negative rate or impossible temperature may make the extended model physically inadmissible. If the reference solve fails, the failure is reported rather than replaced with a fabricated target.</p>
<h2>5. What would make this research-grade?</h2><p>A multi-parameter emulator needs space-filling experimental design, interaction terms or a suitable nonlinear learner, an independent test set and error checks around relevant boundaries. A trustworthy deployment must detect when a query leaves its validated domain. The present conditional one-parameter model is a runnable starting point, not a substitute for that program.</p>`,
practices:[['Interpret a successful score','The surrogate agrees with the simulator to 0.1%. Does it predict real plant yield to 0.1%?','Separate emulation error from model discrepancy.','No. The score measures approximation of the simulator under the sampled conditions. Field accuracy additionally depends on the simulator’s structure, parameters, forcing and observation mapping.'],['Recognize a broken transfer','A light-response surrogate is trained with fixed irrigation. You change irrigation and reuse it. What assumption broke?','Which variables were fixed during training?','The learned map was conditional on the original irrigation. The target function changed. Recompute and evaluate new simulations, or train a model that explicitly includes irrigation as an input.']],
check:{q:'What does the one-parameter surrogate leave fixed?',options:['No conditions; it learns the entire system','Every parameter except the selected input, plus initial conditions and the time horizon','Only the seed'],answer:1,why:'Its training targets are a conditional slice of the simulator, not a complete replacement for the model.'},refs:[['AI modeling specialist lab','ai-modeling.html'],['scikit-learn: regression and preprocessing practice','https://scikit-learn.org/stable/common_pitfalls.html']]},
{id:'hybrid',title:'What should a learned correction be allowed to change?',track:'Scientific ML',path:'lipid',time:'25–40 min',goal:'Distinguish a residual correction from a learned dynamical mechanism and inspect constraints before accepting improvement.',intro:'Combining a mechanistic prediction and a learned term can be useful. The scientific meaning depends on where that term enters and which constraints it respects.',body:`
<h2>1. Start with the implemented hybrid</h2><p>After fitting a mechanistic model, calculate training residuals eᵢ=yᵢ−y_mech(tᵢ). Fit a polynomial g(t) to those residuals and predict y_hybrid(t)=y_mech(t)+g(t). This is the hybrid shown in the connected workspace. It corrects the observable directly; it does not change the differential equations or discover a hidden biochemical reaction.</p>
<h2>2. Work through a residual</h2><p>Suppose mechanistic predictions at t=[0,1,2] are [1,2,3], while observations are [1.2,2.2,3.2]. A constant residual correction of 0.2 fits the discrepancy. That discrepancy might reflect an observation offset, a missing baseline population or a flawed initial value. The regression itself does not choose the cause.</p>
<h2>3. Compare with a universal differential equation</h2><p>A different hybrid places a trainable term inside the dynamics, x′=f_known(x,θ)+g_learned(x,φ). Then training involves the trajectory generated by the modified equation. Positivity, conservation, parameter interpretation and generalization require additional care. FokoLab’s additive time-residual baseline is not that implementation.</p>
<pre class="math-line">Observable correction: ŷ(t) = h(x_mechanistic(t)) + g(t)
Dynamic correction:    dx/dt = f_known(x, θ) + g(x, φ)</pre>
<h2>4. Ask a harder question than training RMSE</h2><p>Does the corrected prediction remain nonnegative? Does a corrected pair of states still satisfy a known balance? What happens beyond the training horizon? A polynomial residual can grow quickly outside its training interval. An improved training fit can therefore make the scientific model less credible.</p>
<h2>5. A controlled next project</h2><p>Start with a system whose omitted mechanism is known. Remove that term deliberately, generate a separate dataset, then compare a residual correction and a constrained dynamic correction on new initial conditions. Retain a simple mechanistic baseline and test whether the learned part captures a transferable relationship rather than a time-specific patch.</p>`,
practices:[['Interpret the learner','A correction lowers training error but predicts negative concentrations later. What follows?','Separate objective improvement and admissibility.','Reject unrestricted use of the correction. Diagnose the observation model or use a constrained representation, then retest on untouched data. Do not clip the displayed result and conceal the failure.'],['Find the missing claim','The hybrid improves test RMSE. Has it identified the missing reaction?','What variables does g use?','No. A time-only residual can compensate for many errors without representing a reaction. Mechanistic identification requires additional structural constraints and discriminating data.']],
check:{q:'The current residual hybrid is:',options:['A neural differential equation','A correction to the observable based on training residuals','Proof of a new mechanism'],answer:1,why:'It is intentionally a transparent baseline. Dynamic hybrid models are a separate, more demanding project.'},refs:[['SciML: differentiation and hybrid scientific models','https://docs.sciml.ai/SciMLSensitivity/']]},
{id:'discovery',title:'Equation discovery: the library is a hypothesis',track:'Scientific ML',path:'dynamics',time:'30–45 min',goal:'Derive a sparse model for logistic growth and explain why noisy derivative estimates can create false terms.',intro:'Sparse equation discovery selects terms from a library you supply. It does not search every possible mechanism or remove the need for experimental judgment.',body:`
<h2>1. Put the equation in a linear-in-coefficients form</h2><p>Logistic growth x′=rx(1−x/K) can be rewritten as x′=rx−(r/K)x². With library columns [1,x,x²,x³], a true logistic generator has coefficients [0,r,−r/K,0]. For r=0.6 and K=100, the nonzero coefficients are 0.6 and −0.006.</p>
<pre class="math-line">Xdot ≈ Θ(X) Ξ
Θ(X) = [1, x, x², x³]
Ξ = [0, 0.6, −0.006, 0]ᵀ  (ideal logistic case)</pre>
<h2>2. Understand what sparsity asks for</h2><p>A sparse fit favors a small number of active terms while keeping prediction error acceptable. A threshold that is too high can delete a real but small quadratic coefficient. One that is too low can preserve noise-driven terms. Variable scaling changes coefficient magnitudes and therefore affects threshold interpretation.</p>
<h2>3. Differentiation amplifies observation noise</h2><p>For an adjacent-point difference (yᵢ₊₁−yᵢ)/Δt with independent noise of standard deviation σ, the noise in the derivative estimate has standard deviation √2σ/Δt. Sampling more closely without reducing measurement noise can increase this derivative-noise scale. A smooth-looking trajectory is not automatically a trustworthy derivative dataset.</p>
<h2>4. A working experiment</h2><p>Use the growth pathway to generate a clean trajectory and export its CSV. Open the specialist Scientific ML lab, load a compatible state/time table and enable constant, linear and quadratic terms. Inspect the learned equation. Repeat with observation noise and compare not just coefficients but rollout on a held-out initial condition. The transfer is an explicit file step; this page does not claim automatic cross-lab execution.</p>
<h2>5. The negative result is informative</h2><p>If the library omits a necessary saturation term, the learner may approximate it with several polynomial terms. If the data cover only near-equilibrium behavior, distinct nonlinear mechanisms can look locally alike. Before increasing complexity, ask whether the experiments explore the states needed to distinguish the proposed terms.</p>`,
practices:[['Recover K','A model learns x′=0.5x−0.01x². What logistic parameters follow?','Match the linear coefficient to r and the quadratic coefficient to −r/K.','r=0.5 and K=0.5/0.01=50 in the state’s units. This interpretation assumes the logistic form is appropriate and the identified coefficients are reliable.'],['Compute derivative noise','σ=0.1 and Δt=0.01. What is the adjacent-difference noise scale?','Evaluate √2σ/Δt.','About 14.14 output units per time unit. An apparent derivative signal of magnitude 1 is overwhelmed by this noise scale; differentiation and regularization need careful treatment.']],
check:{q:'What limits a sparse equation-discovery result?',options:['Only the number of samples','The candidate library, measurement quality, state coverage and validation design','Nothing once the equation is short'],answer:1,why:'A compact equation is interpretable, but sparsity by itself does not establish the correct mechanism.'},refs:[['PySINDy practical tips','https://pysindy.readthedocs.io/en/stable/tips.html'],['Scientific ML workspace','sciml.html']]},
{id:'design',title:'Choose the next experiment, not just the next optimizer',track:'Research practice',path:'lipid',time:'25–40 min',goal:'Use model structure and competing explanations to decide what new observation would be useful.',intro:'When current data do not distinguish parameters or mechanisms, collecting the same kind of data more precisely may not solve the problem.',body:`
<h2>1. Inspect a limiting regime</h2><p>For v=Vmax S/(Km+S), consider S much smaller than Km. Then v≈(Vmax/Km)S. Data confined to this regime mainly inform the ratio Vmax/Km. Conversely, when S is much larger than Km, v≈Vmax and has little sensitivity to Km.</p>
<h2>2. Design for contrast</h2><p>Measurements spanning below, near and above Km expose different curvature. Before collecting them, compare predictions from plausible parameter sets that already fit the existing data. Choose conditions where they disagree in a measurable quantity, while remaining feasible and scientifically meaningful.</p>
<pre class="math-line">Low substrate:  v ≈ (Vmax/Km) S
High substrate: v ≈ Vmax
Near Km:        saturation curvature is informative</pre>
<h2>3. Do not optimize an unexamined utility</h2><p>A design objective might maximize sensitivity, reduce posterior uncertainty or separate candidate models. These are not equivalent. An experiment with large absolute sensitivity may be uninformative if measurement noise is also large or parameters remain confounded. Cost, feasibility and safety belong in the design criteria rather than being added after numerical optimization.</p>
<h2>4. Use the connected workspace as a first pass</h2><p>Compare local sensitivity for early and late output horizons. In a separate saved scenario, change the initial substrate or environmental input. Record which candidate explanation the new scenario could falsify. More advanced optimal-design calculations need an explicit observation-noise model and identifiability analysis beyond this first-pass tool.</p>
<h2>5. Make the conclusion conditional</h2><p>A useful research statement is “These two parameter sets predict different generation-1 counts near day 2; measuring that quantity could discriminate between them under this model.” It is not “The algorithm found the best experiment” without a declared objective, assumptions and feasibility constraints.</p>`,
practices:[['Predict a non-identifying experiment','Two enzyme models share Vmax/Km. You collect only extremely low-substrate data. What is likely?','Use the low-substrate approximation.','Their predictions remain similar. The additional data can refine the ratio without separating Vmax and Km. Broaden the informative substrate range where feasible.'],['Account for noise','Design A changes a signal by 1 unit with noise SD 0.1; B changes it by 4 with noise SD 5. Which is more informative by a simple signal/noise criterion?','Compare 1/0.1 and 4/5, not only raw change.','A has ratio 10, B has 0.8. Under that simple criterion A is stronger, but a full design must also consider parameter confounding, costs and the noise model.']],
check:{q:'What is the first missing ingredient in a claim of an “optimal experiment”?',options:['A larger neural network','A declared utility and observation model','A more attractive figure'],answer:1,why:'Optimality is relative to an objective, assumptions and constraints. It is not an intrinsic property of a proposed experiment.'},refs:[['Optimization specialist lab','optimization.html']]},
{id:'reproducibility',title:'Build an evidence trail that another person can challenge',track:'Research practice',path:'dynamics',time:'30–40 min',goal:'Export an executable scientific record, use AI as a review aid, and distinguish demonstrated skills from plans.',intro:'A portfolio becomes convincing when an unfamiliar person can reproduce a claim, inspect its assumptions and find a meaningful test that could make it fail.',body:`
<h2>1. Preserve the scientific object</h2><p>Keep equations, initial conditions, parameter values and bounds, solver settings, observation data, data provenance, split rules, random seeds and software version with every result. A screenshot omits most of this information. A JSON bundle is useful only when its schema and numerical meaning are documented.</p>
<h2>2. Keep results attached to a revision</h2><p>Editing a model changes the problem. The workspace marks existing results historical and prevents an in-flight calculation from becoming current after an edit. Its run record stores the input model and settings, not just a plot. Imported results are labeled unverified and require recomputation before being treated as locally computed evidence.</p>
<h2>3. Delegate bounded work to AI</h2><p>The review-brief export asks an external assistant to challenge assumptions, units, observation choices and tests. It explicitly asks for deductions to be separated from hypotheses and forbids invented measurements or claims of execution. This is a text export, not a live assistant, and raw observations are excluded by default. Inspect the brief before sharing private model information.</p><p>Review proposed equations as untrusted input. The scalar expression parser accepts a restricted mathematical language rather than executing arbitrary source code. Passing syntax validation is still not dimensional, biological or statistical validation.</p>
<h2>4. Build four concrete portfolio artifacts</h2><p>The lipid study should include competing flux explanations and an identifiability limitation. The cell-generation study should connect the observable to hidden rates. The plant study should distinguish gross assimilation from retained biomass and identify missing physiology. The growth study should compare an analytic reference, mechanistic fitting, a residual baseline and a held-out surrogate.</p><p>Each artifact needs a question, a reproducible experiment, a negative test and a boundary of use. These outputs demonstrate actual modeling and software work; they do not certify that every advanced method mentioned in the learning material has been implemented.</p>
<h2>5. What remains useful as automation improves?</h2><p>The design choice here is to concentrate on problem formulation, experimental discrimination, uncertainty, numerical verification and readable research software. These skills let you evaluate generated code and model suggestions rather than depend on their fluency. This is a training strategy, not a prediction or guarantee about future hiring.</p>`,
practices:[['Audit a generated claim','An assistant says “the model is validated” after inspecting its equations. What evidence is missing?','Separate syntax, numerical verification and empirical validation.','Ask what was actually executed, against which references and data, under what settings, with what failures. Equation inspection alone cannot establish numerical execution or empirical accuracy.'],['Make a result portable','You have a figure and fitted parameters. What minimum additions enable a serious reproduction attempt?','Think forward model, observations and computation.','Provide equations, initial conditions, units, parameter bounds, observations with provenance, objective and split, solver/optimizer settings, seed when relevant, version, instructions and expected checks. Exact portability still needs independent execution.']],
check:{q:'What makes an AI-assisted result defensible?',options:['A confident explanation','Traceable assumptions, executed checks and reproducible evidence with explicit limits','The number of prompts used'],answer:1,why:'The record should allow someone else to challenge the result independently of how it was generated.'},refs:[['Scientific-use boundaries','trust.html'],['GitHub Pages deployment documentation','https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages']]}
];root.FokoResearchLessons=Object.freeze(L);if(typeof module==='object'&&module.exports)module.exports=L;})(typeof self!=='undefined'?self:globalThis);
