/* Explicit browser adapter of uploaded postdoc equations. See provenance.html text.
 * Temperature input is Celsius; internal temperatures Kelvin. Carbon rates remain
 * in the source biochemical units, µmol m^-2 s^-1 (no extra factor of 1e6).
 */
(function(root){'use strict';
const Updated=typeof module!=='undefined'&&module.exports?require('./leaf-updated.js'):root.UpdatedLeaf;
const R=8.3145,T25=298.15;
const eligibleC4=(c,f=c.fractions)=>c.p.loopC4Only===1&&f[0]>0&&f[1]<=1e-12&&f[2]>0;
const physicsFor=(c,gs)=>c.formulation==='updated'?Updated.physical({...c.p,loopC4Only:eligibleC4(c)?1:0},gs):physical(c.p,gs);
const chemistryFor=(c,ph,gs,f)=>c.formulation==='updated'?Updated.chemistry(c.p,ph,gs,f):chemistry(c.p,ph,gs,f);
function temp(v,t,ea,hd,s=0){return v*Math.exp(ea*(t-T25)/(T25*R*t))*(hd===undefined?1:(1+Math.exp((T25*s-hd)/(T25*R)))/(1+Math.exp((t*s-hd)/(t*R))));}
function physical(p,gs){const air=p.airC+273.15,reflection=p.rho_soil*((1-p.f_canopy)+p.f_canopy*p.tau_mes*p.tau_bs)*p.solar_irradiance,im=p.f_canopy*p.alpha_mes*p.solar_irradiance+p.gamma_mes*reflection,ib=p.f_canopy*p.tau_mes*p.alpha_bs*p.solar_irradiance+p.gamma_bs*reflection,sigma=p.leaf_emissivity*5.67e-8;let tm=air,tb=air;
 function eq(m,b){const vapor=611*Math.exp(17.27*(m-273.15)/(m-36)),E=gs*vapor*(1-p.rel_humidity/100)/101325,conv=p.c_p*p.g_h*(m-air),latent=p.lambda_heat*E,cond=p.u_a*(m-b),rm=sigma*(m**4-air**4),rb=sigma*(b**4-air**4);return{E,im,ib,conv,latent,cond,rm,rb,residual:[im-conv-latent-cond-rm,ib+cond-rb]};}
 for(let k=0;k<50;k++){const f=eq(tm,tb),[a,b]=f.residual;if(Math.max(Math.abs(a),Math.abs(b))<1e-8)break;const e=.001,fm=eq(tm+e,tb).residual,fb=eq(tm,tb+e).residual,J00=(fm[0]-a)/e,J10=(fm[1]-b)/e,J01=(fb[0]-a)/e,J11=(fb[1]-b)/e,det=J00*J11-J01*J10;let dm=(J11*a-J01*b)/det,db=(-J10*a+J00*b)/det;const scale=Math.min(1,20/Math.max(Math.abs(dm),Math.abs(db)));tm-=dm*scale;tb-=db*scale;}
 const f=eq(tm,tb),supply=p.k_l*(p.psi_sat*p.rel_soil_wetness**(-p.b)-p.leaf_water_potential);return{...f,tm,tb,supply,valid:Math.max(...f.residual.map(Math.abs))<1e-5&&tm>180&&tm<400&&tb>180&&tb<400&&f.E<=supply+1e-10&&f.E>=0};}
function chemistry(p,physics,gs,fractions){const [fp,fm,fb]=fractions,{tm,tb}=physics,budget=p.v_cmax_tot,kcm=temp(p.k_c,tm,p.k_c_ea),kcb=temp(p.k_c,tb,p.k_c_ea),kom=temp(p.k_o,tm,p.k_o_ea),kob=temp(p.k_o,tb,p.k_o_ea),kp=temp(p.k_p,tm,p.k_p_ea),vp=temp(fp*budget,tm,p.v_pmax_ea,p.v_pmax_hd,p.v_pmax_delta_s),vm=temp(fm*budget,tm,p.v_cmax_ea,p.v_cmax_hd,p.v_cmax_delta_s),vb=temp(fb*budget,tb,p.v_cmax_ea,p.v_cmax_hd,p.v_cmax_delta_s),rm=temp(p.r_mes,tm,p.r_ea),rb=temp(p.r_bs,tb,p.r_ea),gamM=temp(p.gamma_star,tm,p.gamma_star_ea),gamB=temp(p.gamma_star,tb,p.gamma_star_ea),ao=temp(p.a_o,tb,p.a_o_ea),gm=temp(p.g_m*1e-5*R*T25,tm,p.g_m_ea),gb=p.g_bs*1e-5*R*T25,gsSpeed=gs*R*T25/101400,ca=p.co2_atm*.1/(R*T25)*1e6,o=p.o2_atm*.1/(R*T25)*1e6,g=gsSpeed*gm/(gsSpeed+gm);
 function at(ci){const pep=vp*ci/(kp+ci),a=1-p.alpha/ao*kob/kcb,b=-(pep-rm+gb*ci+vb-rb+gb*kcb*(1+o/kcb)+(p.alpha/ao)*(gamB*vb+rb*kcb/kob)),c=(vb-rb)*(pep-rm+gb*ci)-(vb*gb*gamB*o+rb*gb*kcb*(1+o/kob)),disc=b*b-4*a*c,bs=Math.max((-b-Math.sqrt(Math.max(0,disc)))/(2*a),1e-9),mes=vm*(ci-gamM*o)/(ci+kcm*(1+o/kom))-rm,uptake=g*(ca-ci);return{ci,mes,bs,pep,uptake,assimilation:mes+bs,residual:uptake-mes-bs,discriminantClipped:disc<0,bsFloor:bs<=1e-9};}
 let lo=0,hi=ca;while(at(hi).residual>0&&hi<ca*1e6)hi*=2;for(let i=0;i<70;i++){const mid=(lo+hi)/2;if(at(mid).residual>0)lo=mid;else hi=mid;}return{...at((lo+hi)/2),vp,vm,vb,rm,rb};}
function validate(c){const p=c.p;if(c.formulation==='updated')Updated.validate(p);for(const k of ['airC','solar_irradiance','rel_humidity','rel_soil_wetness','co2_atm','v_cmax_tot'])if(!Number.isFinite(p[k]))throw Error('Nonfinite environmental input');if(p.airC<5||p.airC>45||p.solar_irradiance<0||p.solar_irradiance>1200||p.rel_humidity<1||p.rel_humidity>99||p.rel_soil_wetness<.02||p.rel_soil_wetness>1||p.co2_atm<100||p.co2_atm>2000||p.v_cmax_tot<1||p.v_cmax_tot>500)throw Error('Conditions exceed the supported input ranges.');if(!Number.isFinite(c.gs)||c.gs<.0001||c.gs>3||c.fractions.length!==3||c.fractions.some(v=>!Number.isFinite(v)||v<0)||c.fractions.reduce((a,b)=>a+b,0)>1.00000001)throw Error('Conductance must be in [0.0001, 3]; nonnegative enzyme fractions must sum to at most 1.');}
function evaluate(c){validate(c);const ph=physicsFor(c,c.gs);if(!ph.valid)return{valid:false,reason:ph.E>ph.supply?'Transpiration exceeds hydraulic supply.':'Heat/hydraulic solution outside the supported domain.',physics:ph};const ch=chemistryFor(c,ph,c.gs,c.fractions),valid=Object.values(ch).filter(v=>typeof v==='number').every(Number.isFinite)&&Math.abs(ch.residual)<1e-5;return{valid,reason:valid?'':'Carbon balance did not converge.',physics:ph,carbon:ch,gs:c.gs,fractions:c.fractions,waterUseEfficiency:ph.E>0?ch.assimilation/(ph.E*1000):null};}
function optimize(c){validate(c);let best=null,evaluations=0;const cache=new Map();function trial(gs,f){if(f.some(v=>v<0)||f.reduce((a,b)=>a+b,0)>1+1e-10||gs<.0001||gs>3)return;const key=gs+':'+eligibleC4(c,f);let ph=cache.get(key);if(!ph){ph=physicsFor({...c,fractions:f},gs);cache.set(key,ph);}if(!ph.valid)return;evaluations++;const ch=chemistryFor(c,ph,gs,f);if(Number.isFinite(ch.assimilation)&&Math.abs(ch.residual)<1e-5&&(!best||ch.assimilation>best.carbon.assimilation))best={valid:true,physics:ph,carbon:ch,gs,fractions:f.slice(),waterUseEfficiency:ch.assimilation/(ph.E*1000)};}
 for(let s=0;s<=12;s++){const gs=Math.exp(Math.log(.0001)+s/12*Math.log(3/.0001));for(let i=0;i<=6;i++)for(let j=0;j<=6-i;j++)for(let k=0;k<=6-i-j;k++)trial(gs,[i/6,j/6,k/6]);}if(!best)return{valid:false,reason:'No feasible point found within the conductance bounds.',evaluations};for(const step of [.1,.03,.01,.003])for(let it=0;it<15;it++){const prior=best.carbon.assimilation,gs=best.gs,f=best.fractions.slice();for(const sign of [-1,1]){trial(gs*Math.exp(sign*step*4),f);for(let i=0;i<3;i++){const z=f.slice();z[i]+=sign*step;trial(gs,z);for(let j=0;j<3;j++)if(j!==i){const z=f.slice();z[i]+=sign*step;z[j]-=sign*step;trial(gs,z);}}}if(best.carbon.assimilation<=prior+1e-8)break;}return{...best,evaluations,method:'Bounded grid search plus local coordinate refinement; no global optimality guarantee.'};}
function run(c){const point=c.optimize?optimize(c):evaluate(c);if(!point.valid)return{config:c,point,response:[]};const used={...c,gs:point.gs,fractions:point.fractions},response=Array.from({length:13},(_,i)=>{const airC=5+i*40/12,r=evaluate({...used,p:{...c.p,airC}});return{airC,...r};});const circulation=c.formulation==='updated'?[0,1].map(loopEnabled=>evaluate({...used,optimize:false,p:{...used.p,loopEnabled}})):null;return{config:c,point,response,circulation,provenance:c.formulation==='updated'?'Resource-constrained C3–C4 extension: soil cm H2O converted to Pa, air-temperature vapour pressure, serial boundary-layer resistance, pressure-consistent FvCB chemistry and explicit shared ATP/NADPH limits. Source optical coefficients and capacity budget retained; coupled soil temperatures, reciprocal longwave and transpiration-linked sensible heat added. No species calibration.':'Browser adapter of uploaded photosynthesis-climate-adaptation-model-main.zip. Explicit temperature/output-unit corrections and unclipped mesophyll assimilation; source equations otherwise retained. Bounded search replaces CasADi optimization.'};}
const api={temp,physical,chemistry,evaluate,optimize,run};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ResearchLeaf=api;
})(globalThis);
