/* Paired intervention: identical saved weather/configuration, one changed mechanism. */
(function(){let paired=null,job=null,lastHour=-1,cameras={};const el=id=>document.getElementById(id),f=x=>Number(x).toFixed(3);
el('compareCirculation').onclick=()=>{if(!result){el('circulationStatus').textContent='Complete a plant run first.';return;}if(result.config.thermalMode!=='coupled'){el('circulationStatus').textContent='Select coupled soil–leaf heat and run before comparing.';return;}job?.terminate();job=new Worker('worker.js');el('compareCirculation').disabled=true;el('cancelCirculation').hidden=false;el('circulationStatus').textContent='Calculating paired on/off trajectories using completed-run settings and weather repetition 1…';job.onmessage=({data})=>{if(data.progress!==undefined){el('circuitPairStatus').textContent='Calculating matched OFF / ON: '+Math.round(data.progress*100)+'%';el('circulationStatus').textContent='Paired comparison '+Math.round(data.progress*100)+'%';return;}el('compareCirculation').disabled=false;el('cancelCirculation').hidden=true;job.terminate();job=null;if(data.error){el('circulationStatus').textContent=data.error;el('circuitPairStatus').textContent='Comparison failed: '+data.error;return;}paired=data.paired;lastHour=-1;cameras=Object.fromEntries(['C3','C4','CAM'].map(t=>[t,PlantRenderer.camera(paired.series[t][0].concat(paired.series[t][1]),paired.config,t)]));el('circulationStatus').textContent='Same saved weather and starting state. Maximum C4 circulation flow '+paired.config.loopFlow+' mol m⁻² s⁻¹; effectiveness '+paired.config.loopEffectiveness+'. All other parameters fixed. Linked to the main playback time.';render();schedule();};job.onerror=e=>{el('circulationStatus').textContent=e.message;el('circuitPairStatus').textContent='Comparison failed: '+e.message;job?.terminate();job=null;el('compareCirculation').disabled=false;el('cancelCirculation').hidden=true;};job.postMessage({kind:'circulation',config:result.config,weather:result.weather});};
el('cancelCirculation').onclick=()=>{job?.terminate();job=null;el('compareCirculation').disabled=false;el('cancelCirculation').hidden=true;el('circulationStatus').textContent='Comparison cancelled. Previous comparison remains.';el('circuitPairStatus').textContent=paired?'Comparison cancelled. Showing the previous paired result.':'Comparison cancelled. Use Compare OFF / ON to retry.';};
el('exportCirculation').onclick=()=>{if(paired)download('plant-circulation-comparison.json','application/json',JSON.stringify(paired,null,2));};
function download(name,type,body){const u=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(){if(!paired)return;const hour=Math.min(Math.floor(clock),paired.weather.length);if(hour===lastHour)return;const changed=true;lastHour=hour;el('circulationTime').textContent='Comparison at day '+(hour/24).toFixed(1)+' of '+paired.config.days+' · '+paired.config.startDate;let html='<table><thead><tr><th>Pathway / result</th><th>Circulation OFF</th><th>Circulation ON</th><th>ON − OFF</th></tr></thead><tbody>';
for(const t of ['C3','C4','CAM']){const a=paired.series[t][0][hour],b=paired.series[t][1][hour];for(const[k,n]of [['leafWithoutLoop','Predicted leaf °C without circulation'],['loopActualFlow','Actual circulating mol/m²/s'],['loopUnmet','Unmet target °C'],['leafT','Leaf °C'],['soilRootT','Root-zone °C'],['latentHeat','Transpiration cooling W/m² leaf'],['loopHeat','Circulation cooling W/m² leaf'],['carbonInput','Acquired carbon g C'],['trans','Transpired water L'],['biomass','Standing dry biomass g'],['fruit','Reproductive dry tissue g']])html+='<tr><th>'+t+' · '+n+'</th><td>'+f(a[k])+'</td><td>'+f(b[k])+'</td><td>'+f(b[k]-a[k])+'</td></tr>';}
if(changed)el('circulationTable').innerHTML=html+'</tbody></table>';for(const t of ['C3','C4','CAM']){const both=paired.series[t],cam=cameras[t];for(let j=0;j<2;j++){const c=el('loopPlant'+t+j),r=c.getBoundingClientRect(),w=Math.max(240,r.width),h=330,d=Math.min(devicePixelRatio||1,2);c.width=w*d;c.height=h*d;const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);WaterCircuit.draw(ctx,w,h,both[j][hour],{...paired.config,loopEnabled:j},t,clock,{growth:true,maxStem:Math.max(...both.flat().map(x=>x.stem)),maxLeaves:Math.max(...both.flat().map(x=>x.leafUnits.length)),transport:true});}}}
globalThis.CirculationComparison={render,start(){paired=null;el('circuitPairStatus').textContent=result?.config.thermalMode==='coupled'?'Calculating matched C4 OFF / ON trajectories…':'Choose coupled soil–leaf heat, or run the overheating comparison.';el('compareCirculation').onclick();},frame(time){if(!paired)return null;const rows=paired.series.C4.map(list=>{const i=Math.min(list.length-1,Math.floor(time)),a=list[i],b=list[Math.min(i+1,list.length-1)],f=time-i;return Object.fromEntries(Object.keys(a).map(k=>[k,typeof a[k]==='number'?a[k]+(b[k]-a[k])*f:a[k]]));});return{config:paired.config,rows};},clear(){job?.terminate();job=null;el('compareCirculation').disabled=false;el('cancelCirculation').hidden=true;paired=null;lastHour=-1;for(const suffix of ['','Off']){el('circuitState'+suffix).textContent='Waiting for paired calculation';for(const name of ['Leaf','Return','Water','Carbon','Heat','Soil'])el('circuit'+name+suffix).textContent='—';}el('circuitDelta').textContent='Awaiting paired results.';el('circulationTable').textContent='';el('circulationTime').textContent='';el('circulationStatus').textContent='Run the paired comparison for this new experiment.';}};
})();
