/* Paired climate stress tests and a bounded grid search; no global-optimum claim. */
(function(root){'use strict';
const M=typeof module!=='undefined'&&module.exports?require('./plant-engine.js'):root.PlantModel;
const axes={vcmax:{label:'Vcmax',lo:5,hi:150,unit:'µmol m⁻² s⁻¹'},jmax25:{label:'Jmax',lo:0,hi:400,unit:'µmol e⁻ m⁻² s⁻¹'},cef:{label:'Pathway CEF / LEF',lo:0,hi:3,unit:'ratio'},c4Vpmax:{label:'C4 PEPC capacity',lo:0,hi:250,unit:'µmol m⁻² s⁻¹',type:'C4'},c4Gbs:{label:'C4 sheath CO₂ conductance',lo:.0001,hi:.1,unit:'mol m⁻² s⁻¹ bar⁻¹',type:'C4'},c4Gm:{label:'C4 mesophyll conductance',lo:.01,hi:10,unit:'mol m⁻² s⁻¹ bar⁻¹',type:'C4'},c4ATPshare:{label:'C4 ATP share to pump',lo:.05,hi:.95,unit:'fraction',type:'C4'},camCapacity:{label:'CAM storage capacity',lo:50,hi:800,unit:'mmol C m⁻²',type:'CAM'},camNightCapacity:{label:'CAM night uptake capacity',lo:0,hi:60,unit:'µmol m⁻² s⁻¹',type:'CAM'},nUptakeRate:{label:'Root nitrogen uptake capacity',lo:1,hi:240,unit:'mg N g⁻¹ root d⁻¹'}};
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),svp=t=>.6108*Math.exp(17.27*t/(t+237.3));
function validate(c,s){if(!M.TYPES.includes(s.type))throw Error('Choose a plant pathway.');for(const k of ['startDay','endDay','heat','recoveryIrrigation','minControl','minWorst','maxWater','minControlHarvest','minStressHarvest','minRecovery'])if(!Number.isFinite(s[k]))throw Error('Enter finite stress-test limits.');if(!Number.isInteger(s.startDay)||!Number.isInteger(s.endDay)||s.startDay<0||s.endDay<=s.startDay||s.endDay>c.days-3)throw Error('The drought window needs whole days and at least 3 days of recovery.');if(s.heat<0||s.heat>12||s.recoveryIrrigation<0||s.recoveryIrrigation>100||s.minControl<=0||s.minWorst<0||s.maxWater<=0)throw Error('Use heat 0–12 °C, recovery irrigation 0–100 mm, positive control carbon and water limits, and nonnegative minimum stress carbon.');if(!['fruit','leaf','stem','root'].includes(s.harvestOrgan)||s.minControlHarvest<=0||s.minStressHarvest<=0||s.minRecovery<0||s.minRecovery>2)throw Error('Choose a harvest organ, positive production floors and recovery threshold between 0 and 2.');if(!['robustYield','robustCarbon','resilience','fruit','waterEfficiency','lowWater'].includes(s.target))throw Error('Choose a supported objective.');}
function forcing(weather,s,kind){return weather.map((w,h)=>{const x={...w};if(kind!=='control'&&h>=s.startDay*24&&h<s.endDay*24){x.rain=0;x.irrigationOff=true;if(kind==='droughtHeat'){x.temperature=w.temperature+s.heat;x.rh=clamp(w.rh*svp(w.temperature)/svp(x.temperature),.01,1);}}if(kind!=='control'&&h===s.endDay*24)x.extraIrrigation=s.recoveryIrrigation;return x;});}
function score(config,weather,s){const rows={},summary={};for(const kind of ['control','drought','droughtHeat']){const out=M.trajectory(config,forcing(weather,s,kind),s.type);if(out.maxCarbonError>1e-7||out.maxWaterError>1e-7||out.maxNitrogenError>1e-7)throw Error('A candidate failed resource conservation.');rows[kind]=out.rows;const end=out.rows.at(-1);summary[kind]={harvest:end[s.harvestOrgan],netCarbon:end.netCarbon,carbonInput:end.carbonInput,biomass:end.biomass,fruit:end.fruit,trans:end.trans,irrigationLitres:end.irrigation*.25,structuralLoss:out.rows.slice(1).reduce((v,r,i)=>v+Math.max(0,out.rows[i].biomass-r.biomass),0)};}
const base=summary.control,ends=Object.values(summary),worstCarbon=Math.min(...ends.map(x=>x.netCarbon)),worstWater=Math.max(...ends.map(x=>x.trans));let score=null;let eligible=base.netCarbon>=s.minControl&&worstCarbon>=s.minWorst&&worstWater<=s.maxWater&&base.harvest>=s.minControlHarvest&&ends.every(x=>x.harvest>=s.minStressHarvest);
for(const kind of Object.keys(summary)){const endHour=(s.endDay+3)*24,startHour=endHour-24,uptake=rows[kind][endHour].carbonInput-rows[kind][startHour].carbonInput,reference=rows.control[endHour].carbonInput-rows.control[startHour].carbonInput;summary[kind].biomassRetention=base.biomass>0?summary[kind].biomass/base.biomass:null;summary[kind].carbonRetention=base.netCarbon>1e-9?summary[kind].netCarbon/base.netCarbon:null;summary[kind].recoveryRatio=reference>1e-9?uptake/reference:null;}
eligible=eligible&&['drought','droughtHeat'].every(k=>s.minRecovery===0||summary[k].recoveryRatio!==null&&summary[k].recoveryRatio>=s.minRecovery);
if(eligible){if(s.target==='robustYield')score=Math.min(...ends.map(x=>x.harvest));if(s.target==='robustCarbon')score=worstCarbon;if(s.target==='resilience')score=Math.min(summary.drought.netCarbon,summary.droughtHeat.netCarbon)/base.netCarbon;if(s.target==='fruit')score=Math.min(...ends.map(x=>x.fruit));if(s.target==='lowWater')score=-worstWater;if(s.target==='waterEfficiency'&&ends.every(x=>x.trans>1e-6))score=Math.min(...ends.map(x=>x.netCarbon/x.trans));}
return{summary,worstCarbon,worstWater,eligible:eligible&&score!==null,score};}
function search(input,weather,s,onProgress=()=>{}){const c=M.validate({...input});validate(c,s);if(weather.length!==c.days*24)throw Error('Complete a plant run before testing scenarios.');if(!Number.isInteger(s.points)||s.points<2||s.points>5)throw Error('Use 2–5 values per trait.');const active=s.compareOnly?[]:s.axes.filter(a=>a.key!=='none');if(!s.compareOnly&&!active.length)throw Error('Choose at least one trait.');if(new Set(active.map(a=>a.key)).size!==active.length)throw Error('Choose distinct traits.');for(const a of active){const d=axes[a.key];if(!d||d.type&&d.type!==s.type||!Number.isFinite(a.lo)||!Number.isFinite(a.hi)||a.lo>=a.hi||a.lo<d.lo||a.hi>d.hi)throw Error('Check the selected trait, pathway and increasing bounds.');}
let candidates=[{}];for(const a of active)candidates=candidates.flatMap(p=>Array.from({length:s.points},(_,i)=>({...p,[a.key==='cef'?'cef'+s.type:a.key]:a.lo+(a.hi-a.lo)*i/(s.points-1)})));if(candidates.length*c.days*3>3600)throw Error('Reduce days or grid values: at most 3,600 pathway-days per search.');
const baseline=score(c,weather,s),tested=[];for(let i=0;i<candidates.length;i++){const changes=candidates[i],cfg={...c,...changes};M.validate(cfg);tested.push({changes,...(s.compareOnly?baseline:score(cfg,weather,s))});onProgress((i+1)/candidates.length);}const feasible=tested.filter(x=>x.eligible).sort((a,b)=>b.score-a.score);return{modelVersion:'plant-lab-20',config:c,stress:s,baseline,tested,best:feasible[0]||null,method:'Finite grid; best tested feasible candidate only. One shared weather history, not a climate forecast or genetic engineering prediction.'};}
const api={axes,validate,forcing,score,search};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.PlantScenarios=api;
})(globalThis);
