import fs from 'node:fs';import assert from 'node:assert/strict';import {analyse,demo,nativeInput,hypervolume,dominates} from '../site/src/revision83/decision-core.mjs';
fs.mkdirSync('evidence/finish803',{recursive:true});const checks=[];function test(name,fn){try{const detail=fn();checks.push({name,status:'passed',detail});console.log('PASS',name);}catch(e){checks.push({name,status:'failed',error:e.message});console.log('FAIL',name,e.message);}}
const copy=x=>structuredClone(x),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-9,`${a} != ${b}`);
test('Analytic finite front and invalid sample preserved',()=>{const d=demo(),before=JSON.stringify(d),r=analyse(d,[2,2]);assert.equal(r.front.length,41);assert.equal(r.excluded.length,1);assert.equal(r.excluded[0].values.loss,null);assert.equal(JSON.stringify(d),before);assert.ok(r.hypervolume>3.8&&r.hypervolume<4);for(let i=1;i<r.hypervolumeHistory.length;i++)assert.ok(r.hypervolumeHistory[i].value>=r.hypervolumeHistory[i-1].value-1e-12);return{front:41,supplied:d.candidates.length,hypervolume:r.hypervolume};});
const objective=(key,direction='min')=>({key,label:key,direction,unit:'dimensionless'}),cand=(id,values,feasible=true)=>({id,values,feasible}),record=(objectives,candidates)=>({schema:'foko.decision/1',clock:'function evaluations',objectives,candidates});
test('Dominance uses all objectives, not a two-axis projection',()=>{const o=[objective('a'),objective('b'),objective('c')],p=[cand('x',{a:0,b:0,c:5}),cand('y',{a:1,b:1,c:0})];assert.equal(analyse(record(o,p)).front.length,2);assert.equal(analyse(record(o.slice(0,2),p)).front.length,1);});
test('Mixed maximize/minimize directions',()=>{const r=analyse(record([objective('gain','max'),objective('cost')],[cand('best',{gain:4,cost:1}),cand('worst',{gain:1,cost:4}),cand('tradeoff',{gain:5,cost:2})]));assert.deepEqual(r.front.map(p=>p.id),['best','tradeoff']);assert.equal(r.ranks.worst,1);});
test('Equal candidates do not dominate each other',()=>{const r=analyse(record([objective('a'),objective('b')],[cand('x',{a:1,b:1}),cand('y',{a:1,b:1})]));assert.equal(r.front.length,2);assert.equal(r.correlation[0][0],null);});
test('Null objective is excluded, never a zero optimum',()=>{const r=analyse(record([objective('a'),objective('b')],[cand('bad',{a:null,b:0}),cand('good',{a:1,b:1})]));assert.equal(r.front[0].id,'good');assert.equal(r.excluded.length,1);});
test('Infeasible candidates do not dominate feasible candidates',()=>{const r=analyse(record([objective('a'),objective('b')],[cand('bad',{a:-100,b:-100},false),cand('good',{a:1,b:1})]));assert.equal(r.front[0].id,'good');});
test('Exact rectangle-union reference case',()=>near(hypervolume([cand('a',{x:1,y:2}),cand('b',{x:2,y:1})],[objective('x'),objective('y')],[3,3]),3));
test('Exact hypervolume with maximize direction',()=>near(hypervolume([cand('a',{x:-1,y:2}),cand('b',{x:-2,y:1})],[objective('x','max'),objective('y')],[-3,3]),3));
test('Invalid reference is refused rather than moved silently',()=>assert.throws(()=>analyse(demo(),[0,0]),/Reference/));
test('3D hypervolume is not substituted by projected area',()=>assert.throws(()=>analyse(record([objective('x'),objective('y'),objective('z')],[cand('a',{x:1,y:1,z:1})]),[2,2,2]),/two objectives/));
test('Unknown feasibility is rejected',()=>assert.throws(()=>analyse(record([objective('a'),objective('b')],[{id:'a',values:{a:1,b:1}}])),/feasibility/));
test('Duplicate candidate IDs are rejected',()=>assert.throws(()=>analyse(record([objective('a'),objective('b')],[cand('a',{a:1,b:1}),cand('a',{a:2,b:2})])),/unique/));
test('Boolean and nonfinite objective values are not numeric observations',()=>assert.throws(()=>analyse(record([objective('a'),objective('b')],[cand('a',{a:true,b:1}),cand('b',{a:Infinity,b:0})])),/No feasible/));
test('Prototype-like IDs retain their actual ranks',()=>{const r=analyse(record([objective('a'),objective('b')],[cand('__proto__',{a:0,b:0}),cand('constructor',{a:1,b:1})]));assert.equal(r.ranks['__proto__'],0);assert.equal(r.ranks.constructor,1);});
test('Unknown event-candidate identity is refused',()=>{const r=demo();r.events=[{candidate:'does-not-exist',time:1}];assert.throws(()=>analyse(r),/recorded candidate/);});
test('Native evolutionary events preserve clocks, follow-up and source record',()=>{const source={lab:'evolution',result:{schema:'dynamics.kimura/1',config:{kimura:{horizon:50}},nodes:[{nodeId:0,carbon:1,water:2,heat:3,feasible:true,fractions:[.1,.8,.1],gs:.1},{nodeId:1,carbon:2,water:3,heat:2,feasible:true,fractions:[.2,.6,.2],gs:.2}],replicates:[{seed:42,termination:'event_cap',observedUntil:7,events:[{index:0,time:0,node:0,s:null,pfix:null,waiting:0},{index:1,time:7,node:1,s:.1,pfix:.02,waiting:7}]}]}};const input=nativeInput(source);assert.equal(input.clock,'biological generations');assert.equal(input.events[1].time,7);assert.equal(input.events[1].termination,'event_cap');assert.equal(input.events[1].observedUntil,7);assert.equal(input.events[1].pfix,.02);assert.deepEqual(input.provenance.original,source);return{events:input.events.length,termination:input.events[1].termination};});
// Independent exact reference: inclusion/exclusion over all nonempty rectangle subsets.
for(let trial=0;trial<30;trial++)test('Hypervolume inclusion-exclusion reference '+trial,()=>{const pts=Array.from({length:5},(_,i)=>({x:((trial+3)*(i+7)%19)/7,y:((trial+7)*(i+3)%23)/8}));let expected=0;for(let mask=1;mask<32;mask++){const subset=pts.filter((_,i)=>mask&(1<<i)),sign=subset.length%2?1:-1;expected+=sign*(4-Math.max(...subset.map(p=>p.x)))*(4-Math.max(...subset.map(p=>p.y)));}near(hypervolume(pts.map((p,i)=>cand(i,p)),[objective('x'),objective('y')],[4,4]),expected);});
const report={release:'80.3.0',checks,scope:'Finite deterministic candidate and record contracts; no empirical biological validation.',passed:checks.filter(x=>x.status==='passed').length,failed:checks.filter(x=>x.status==='failed').length};fs.writeFileSync('evidence/finish803/science.json',JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
