'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const site=path.resolve('site'),out=path.resolve('evidence/recovery');fs.mkdirSync(out,{recursive:true});
const checks=[],clone=x=>JSON.parse(JSON.stringify(x)),equal=(a,b)=>assert.deepEqual(a,b),close=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}; absolute tolerance ${t}`);
function test(name,fn){const start=performance.now();try{const detail=fn();checks.push({name,status:'passed',milliseconds:performance.now()-start,detail});console.log('PASS',name);}catch(e){checks.push({name,status:'failed',detail:e.message});console.log('FAIL',name,e.message);}}
const browser=JSON.parse(fs.readFileSync(out+'/browser.json','utf8'));
function config(name){const c=browser.checks.find(x=>x.name.startsWith(name));assert.ok(c&&c.status==='passed'&&c.detail?.config,'Missing successful browser configuration: '+name);return clone(c.detail.config);}
const Plants=require(site+'/plants/plant-engine.js'),Lipids=require(site+'/lipids/lipid-engine.js'),Motion=require(site+'/shared/model-motion.js'),Cells=require(site+'/tcells/tcell-engine.js'),Age=require(site+'/tcells/age-engine.js'),Leaf=require(site+'/leaf/leaf-engine.js'),Evolution=require(site+'/continuum/advanced-engine.js'),Random=require(site+'/engine.js');
const pc={...config('Original plant default computation'),days:3,reps:1};
for(const model of ['activation','birthdeath','age','cyton','kimmel'])test('Original '+model+': exact cell-history/event accounting',()=>{const c={...config('Cell family '+model),repetitions:8},engine=['age','cyton','kimmel'].includes(model)?Age:Cells,r=engine.experiment(c),again=engine.experiment(c);equal(r.events,again.events);equal(r.cells,again.cells);assert.ok(r.events.every((e,i)=>!i||e.time>=r.events[i-1].time));for(const e of r.events)equal(c.initial+e.divisions-e.dead,e.total);for(const cell of r.cells){if(cell.children.length){equal(cell.children.length,2);for(const id of cell.children){const daughter=r.cells.find(x=>x.id===id);equal(daughter.parent,cell.id);close(daughter.born,cell.end);equal(daughter.generation,cell.generation+1);}}if(cell.end!==null)assert.ok(cell.end<=c.hours,'Export exposes an unobserved assigned future fate');}const before=JSON.stringify(r);for(const f of [0,.17,.5,.9,1]){const frame=Motion.cellFrame(r,f*c.hours,5);equal(frame.alive.length,frame.generations.reduce((s,x)=>s+x,0));assert.ok(frame.shown.length<=5);}equal(JSON.stringify(r),before);return{events:r.events.length,cells:r.cells.length,distinct_realizations:JSON.stringify(r.first)!==JSON.stringify(r.second)};});
for(const model of ['synthesis','metabolism'])test('Original lipid '+model+': source solver and mass audit',()=>{const r=Lipids.run({model,p:clone(Lipids.defaults[model]),compare:true});equal(r.species.length,model==='synthesis'?18:4);assert.ok(r.rows.every(row=>row.length===r.species.length&&row.every(Number.isFinite)));assert.ok(r.rows.every(row=>row.every(x=>x>=-1e-9)));if(model==='synthesis'){const inv=r.rows.map(row=>Lipids.invariants(row)),initial=inv[0];for(const x of inv)for(const k of Object.keys(initial))if(typeof initial[k]==='number')close(x[k],initial[k],Math.max(1,Math.abs(initial[k]))*1e-6);const before=JSON.stringify(r),tr=Motion.tracer(r);equal(tr,Motion.tracer(r));for(let i=1;i<tr.events.length;i++){const a=tr.events[i-1],b=tr.events[i];assert.ok(b.time>=a.time);assert.ok([0,-1,2,4,6,8,10,12,14,16,18].includes(b.chain));assert.ok([0,14,16,18].includes(b.product));if(b.product)equal(b.chain,0);if(b.chain>0)assert.ok(b.chain===a.chain||b.chain===a.chain+2);equal(Motion.traceAt(tr,b.time),b);}equal(JSON.stringify(r),before);assert.ok(tr.events.some(e=>e.product>0),'Expected a seeded product release');return{states:18,rows:r.rows.length,tracer_events:tr.events.length,audit:r.audit,solver:r.solver};}return{states:4,audit:r.audit};});
test('Original plant: pathway resource ledgers and seeded forcing',()=>{const r=Plants.simulate(pc);equal(r.weather,Plants.simulate(pc).weather);for(const [type,rows]of Object.entries(r.series)){equal(rows.length,pc.days*24+1);assert.ok(rows.every(x=>Object.values(x).filter(v=>typeof v==='number').every(Number.isFinite)),type+' non-finite state');}return{pathways:Object.keys(r.series),accounting:r.accounting,days:pc.days};});
test('Original plant: no hidden water inflow without rain or irrigation',()=>{const c={...pc,rainProbability:0,rainDepth:0,irrigationMode:'none',stochastic:false,days:7},r=Plants.simulate(c);for(const [type,rows]of Object.entries(r.series)){const keys=Object.keys(rows[0]),stock=keys.find(k=>k==='soil')||keys.find(k=>k==='water');assert.ok(stock,'Missing original water stock field');for(let i=1;i<rows.length;i++)assert.ok(rows[i][stock]<=rows[i-1][stock]+1e-8,type+' water stock increased without input');}return{days:7};});
test('Original coupled leaf: finite source response, immutable inputs',()=>{const c=config('Source coupled leaf physiology'),before=JSON.stringify(c),r=Leaf.run(c);assert.ok(r.point.valid);equal(JSON.stringify(c),before);return{point:r.point};});
test('Original Kimura neutral fixation probability',()=>{for(const n of [10,100,1000])close(Evolution.fixation(0,n),1/(2*n),1e-12);return{convention:'Diploid source formula 1/(2 Ne), not haploid Moran 1/N'};});
test('Original accepted substitutions: times, transitions and seed replay',()=>{const c=config('Original Kimura allocation model runs'),r=Evolution.run(c),again=Evolution.run(c);equal(r.replicates,again.replicates);for(const rep of r.replicates){assert.ok(rep.events.length>1);for(let i=1;i<rep.events.length;i++){const a=rep.events[i-1],b=rep.events[i];assert.ok(b.time>a.time);close(b.time-a.time,b.waiting,1e-6);equal(b.from,a.node);const p=r.nodes[b.node];close(p.fractions.reduce((s,v)=>s+v,0),1,1e-12);assert.ok(p.feasible);}}return{accepted:r.replicates[0].events.length-1,convention:r.convention};});
test('Source Morris: independent analytic linear response',()=>{const r=Evolution.morris(x=>2*x[0]+3*x[1]+4*x[2],[[0,1],[0,1],[0,1]],16,71);r.rows.forEach((x,i)=>close(x.muStar,i+2,1e-10));return{muStar:r.rows.map(x=>x.muStar)};});
test('Source Sobol: independent analytic variance fractions',()=>{const r=Evolution.sobol(x=>x[0]+2*x[1]+3*x[2],[[0,1],[0,1],[0,1]],4096,73);r.rows.forEach((x,i)=>{close(x.S1,(i+1)**2/14,.065);close(x.ST,(i+1)**2/14,.035);});return{indices:r.rows.map(x=>({S1:x.S1,ST:x.ST})),expected:[1/14,4/14,9/14],absolute_tolerances:{first_order:.065,total_order:.035}};});
test('Source PCA: normalized variance and orthonormal components',()=>{const X=Array.from({length:120},(_,i)=>[Math.sin(i),Math.cos(i*.37),Math.sin(i)*.3+Math.cos(i*.2)]),r=Evolution.pca(X);close(r.explained.reduce((s,v)=>s+v,0),1,1e-10);for(const v of r.loadings)close(v.reduce((s,x)=>s+x*x,0),1,1e-10);return{explained:r.explained};});
const rc={n:40,m:8,weights:[1,1,1,1,1,1],values:[1,2,3,4,5,6],memory:.2,seed:42,geometry:'long',shape:'triangle',energy:200,obstacles:true,resources:true,initial:4,dt:.1,drift:0,sigma:1,incrementLaw:'normal',offspringLaw:'poisson',lambda:.8,offspringP:.5,trials:2,birthRate:.3,deathRate:.25,immigration:0,horizon:10,lower:-1,upper:1};
for(const mode of ['tree','chaos','colony','walk','brownian','branching','birthdeath'])test('Original random '+mode+': seeded event/frame replay',()=>{const r=Random.simulate({...rc,mode}),again=Random.simulate({...rc,mode});equal(r,again);assert.ok(r.frames.length>0);return{frames:r.frames.length,edges:r.edges.length,limited:r.truncated};});
test('Preservation manifest: all original scientific source hashes match',()=>{const m=JSON.parse(fs.readFileSync(site+'/recovery-manifest.json'));for(const x of m.scientific_source_checks)equal(crypto.createHash('sha256').update(fs.readFileSync(site+'/'+x.path)).digest('hex'),x.source_sha256);return{exact_assets:m.scientific_source_checks.length};});
const report={release:'80.1.0',scope:'Original source engines and recorded-event invariants. Test seeds and numerical tolerances are explicit. This is not biological calibration.',checks,summary:{passed:checks.filter(x=>x.status==='passed').length,failed:checks.filter(x=>x.status==='failed').length}};fs.writeFileSync(out+'/source-numerical.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary));if(report.summary.failed)process.exitCode=1;
