const assert = require('assert');
const data = require('../src/platform-data-engine.js');
const table = data.parseTable('time,response,group\n0,1.2,A\n1,2.4,A\n2,3.1,B');
assert.strictEqual(table.rowCount, 3);
assert.strictEqual(table.columnCount, 3);
assert.deepStrictEqual(table.names, ['time','response','group']);
const schema = data.inferSchema(table);
assert.strictEqual(schema[0].type, 'number');
assert.strictEqual(schema[1].type, 'number');
assert.strictEqual(schema[2].type, 'category');
assert.throws(() => data.parseTable(''), /non-empty/);
assert.throws(() => data.inferSchema(null), /parsed table/);
console.log('v70.19 data engine: ok');
