from pathlib import Path
from bs4 import BeautifulSoup
ROOT=Path(__file__).resolve().parents[1]

def read(rel):
    return (ROOT/rel).read_text(encoding='utf-8')

def soup(rel):
    return BeautifulSoup(read(rel),'html.parser')

def test_symbolic_lab_page_exists_and_has_expected_scope():
    html=read('symbolic.html')
    for term in ['Symbolic Lab','LaTeX preview','Jacobian matrix','Equilibria and linearization','Exported SymPy script']:
        assert term in html
    assert 'not a full in-browser CAS' in html or 'not a full in-browser' in html
    assert (ROOT/'src'/'symbolic-lab.js').exists()
    assert 'Generated by Foko Lab Symbolic Lab' in read('src/symbolic-lab.js')

def test_symbolic_examples_connect_to_modeling_labs_and_research():
    js=read('src/symbolic-lab.js')
    for key in ['Logistic growth','Lotka–Volterra','Michaelis–Menten','Genetic toggle switch','Simplified fatty-acid coarse model']:
        assert key in js
    for token in ['math.derivative','jacobian','sympyScript','nondim']:
        assert token in js


def test_mathematical_beauty_is_separate_from_symbolic_lab():
    html=read('beauty.html')
    for term in ['Mathematical Beauty','Fractals and nature','Curves and symmetry','Number theory','Gödel and limits']:
        assert term in html
    assert 'Explore fractals, patterns, curves, number theory, topology and formal limits.' in html
    js=read('src/math-beauty.js')
    for key in ['mandelbrot','julia','fern','sierpinski','koch','butterfly','ulam','collatz','godel']:
        assert key in js.lower()


def test_home_links_to_symbolic_and_beauty_without_research_pollution():
    html=read('index.html')
    assert 'href="symbolic.html"' in html
    assert 'href="beauty.html"' in html
    assert 'Symbolic Lab' in html
    assert 'Mathematical Beauty' in html
    assert 'Foko Models' not in html
