"""
test_v66_sindy_engine.py
========================

Protocol step 1: the test precedes the engine. This pins a STANDALONE,
TESTABLE SINDy engine (src/sindy.js, window.FokoSINDy) extracted from the
untested inline math currently buried in src/sciml-lab.js.

Why this matters
----------------
The shipped SciML lab recovers "governing equations" from data, but its numerics
have zero correctness coverage: every existing test checks string presence (does
a dropdown contain an option, does an atlas link exist), never whether the engine
recovers a single correct coefficient. 424 green tests certify nothing about the
science. This suite fixes that: it EXECUTES the engine against known systems and
asserts it recovers both the coefficients and the sparsity pattern.

The engine must be a behavior-preserving extraction
---------------------------------------------------
The lab builds its candidate library from CHECKBOX TOGGLES, not a single
polynomial degree:
    constant     -> 1
    linear       -> x, y, ...
    quadratic    -> x^2, y^2, ...              (per-variable squares only)
    interactions -> x*y, x*z, y*z, ...         (i<j pairs)
    cubic        -> x^3, y^3, ...              (per-variable cubes only)
    trig         -> sin(x), cos(x), ...        (per variable)
Column ORDER is load-bearing: the coefficient table and the library-correlation
heatmap index into Theta by position. The engine must emit columns in exactly
this order:  [constant] then [linear] then [quadratic] then [interactions] then
[cubic] then [trig].  This test pins that order.

How the engine is exercised
---------------------------
window.FokoSINDy is a browser IIFE. We run it in Node via vm (window===ctx), so
we test the exact shipping code. Recovery data is generated by RK4 integrating a
known RHS inside the harness; the derivatives fed to SINDy are the EXACT analytic
derivatives from that same RHS, isolating the sparse-regression correctness from
finite-difference error (which is tested separately, with a looser bound).

Run:
    python -m pytest tests/test_v66_sindy_engine.py -v
"""

from __future__ import annotations

import json
import subprocess
import textwrap
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SINDY_SRC = "src/sindy.js"

COEFF_TOL = 1e-3        # recovery error with exact derivatives
FD_COEFF_TOL = 0.15     # recovery error with finite-difference derivatives
LAMBDA = 0.02           # STLSQ threshold across recovery tests


# ─────────────────────────────────────────────────────────────────────────────
# Node harness
# ─────────────────────────────────────────────────────────────────────────────

def _run(body_js: str) -> dict:
    """
    Execute body_js with the shipping sindy.js loaded and window===ctx, so
    window.FokoSINDy is available exactly as in the browser. body_js must
    process.stdout.write(JSON.stringify(<result>)).

    Pre-conditions:
      * src/sindy.js exists (else the engine was not extracted);
      * Node runs cleanly and emits valid JSON.

    A harness-only RK4 + simulate() is injected so recovery tests can generate
    clean data from a known RHS with exact analytic derivatives.
    """
    src = ROOT / SINDY_SRC
    assert src.exists(), (
        f"[engine-missing] {SINDY_SRC} not found. Extract the SINDy math into a "
        "browser IIFE attaching window.FokoSINDy."
    )
    harness = textwrap.dedent(f"""
        const vm = require('vm'), fs = require('fs');
        const ctx = {{}}; ctx.window = ctx; ctx.console = console;
        vm.createContext(ctx);
        vm.runInContext(fs.readFileSync({json.dumps(str(src))}, 'utf8'), ctx);
        const S = ctx.FokoSINDy;
        if (!S) {{ console.error('FOKOSINDY_NOT_EXPORTED'); process.exit(4); }}

        function rk4Step(f,t,y,dt){{
          const add=(a,b,s)=>a.map((v,i)=>v+s*b[i]);
          const k1=f(t,y),k2=f(t+dt/2,add(y,k1,dt/2)),
                k3=f(t+dt/2,add(y,k2,dt/2)),k4=f(t+dt,add(y,k3,dt));
          return y.map((v,i)=>v+dt*(k1[i]+2*k2[i]+2*k3[i]+k4[i])/6);
        }}
        function simulate(f,y0,dt,nSteps){{
          const t=[],X=[],Xdot=[]; let y=y0.slice();
          for(let i=0;i<=nSteps;i++){{ t.push(i*dt); X.push(y.slice()); Xdot.push(f(i*dt,y)); y=rk4Step(f,i*dt,y,dt); }}
          return {{t,X,Xdot}};
        }}
        ctx.__h = {{ simulate }};
        {body_js}
    """)
    proc = subprocess.run(["node", "-e", harness], capture_output=True, text=True, cwd=str(ROOT))
    assert proc.returncode == 0, (
        f"Node harness failed (code {proc.returncode}).\nstderr:\n{proc.stderr}\nstdout:\n{proc.stdout}"
    )
    return json.loads(proc.stdout)


def _abs_err(a, b):
    assert len(a) == len(b), f"[test-env] length mismatch {len(a)} vs {len(b)}"
    return max(abs(x - y) for x, y in zip(a, b))


# Full checkbox library for a 2-variable system.
FULL_LIB = ("{constant:true, linear:true, quadratic:true, "
            "interactions:true, cubic:true, trig:false}")


# ═════════════════════════════════════════════════════════════════════════════
# 1. Library ordering + values match the checkbox basis exactly
# ═════════════════════════════════════════════════════════════════════════════

def test_library_order_matches_checkbox_basis() -> None:
    """
    For vars [x,y] with constant+linear+quadratic+interactions+cubic, the column
    order MUST be:
      1, x, y, x^2, y^2, x*y, x^3, y^3
    (constant, linear, per-var squares, pairwise interactions, per-var cubes).
    This ordering is what the coefficient table and library heatmap index into.
    """
    out = _run(f"""
        const {{Theta,names}} = S.buildLibrary([[2,3]], {{varNames:['x','y'],
            constant:true, linear:true, quadratic:true, interactions:true, cubic:true, trig:false}});
        process.stdout.write(JSON.stringify({{names, row:Theta[0]}}));
    """)
    assert out["names"] == ["1", "x", "y", "x^2", "y^2", "x*y", "x^3", "y^3"], out["names"]
    # values at (x=2,y=3): 1, 2, 3, 4, 9, 6, 8, 27
    assert out["row"] == [1, 2, 3, 4, 9, 6, 8, 27], out["row"]


def test_library_trig_columns_last() -> None:
    """With trig enabled, sin/cos columns come last, in (sin,cos) per-var order."""
    out = _run("""
        const {names} = S.buildLibrary([[0,0]], {varNames:['x','y'],
            constant:true, linear:true, quadratic:false, interactions:false, cubic:false, trig:true});
        process.stdout.write(JSON.stringify({names}));
    """)
    assert out["names"] == ["1", "x", "y", "sin(x)", "cos(x)", "sin(y)", "cos(y)"], out["names"]


def test_empty_library_throws() -> None:
    """All toggles off -> the candidate library is empty -> engine must throw."""
    out = _run("""
        let msg='NO_THROW';
        try { S.buildLibrary([[1,2]], {varNames:['x','y'], constant:false, linear:false,
            quadratic:false, interactions:false, cubic:false, trig:false}); }
        catch(e){ msg=String(e.message||e); }
        process.stdout.write(JSON.stringify({msg}));
    """)
    assert out["msg"] != "NO_THROW"
    assert "librar" in out["msg"].lower() or "empty" in out["msg"].lower(), out["msg"]


# ═════════════════════════════════════════════════════════════════════════════
# 2. Finite-difference derivatives
# ═════════════════════════════════════════════════════════════════════════════

def test_finite_difference_matches_central_scheme() -> None:
    """
    The engine's estimateDerivatives must reproduce the lab's central-difference
    scheme:  xdot[i] = (X[i+1]-X[i-1])/(t[i+1]-t[i-1]) on the interior. For
    x(t)=t^2 the interior estimate equals 2t to O(dt^2).
    """
    out = _run("""
        const dt=0.01,n=200,t=[],X=[];
        for(let i=0;i<=n;i++){const tt=i*dt;t.push(tt);X.push([tt*tt]);}
        const Xd=S.estimateDerivatives(X,t);
        let maxErr=0; for(let i=1;i<n;i++) maxErr=Math.max(maxErr, Math.abs(Xd[i][0]-2*(i*dt)));
        process.stdout.write(JSON.stringify({maxErr}));
    """)
    assert out["maxErr"] < 1e-3, out["maxErr"]


# ═════════════════════════════════════════════════════════════════════════════
# 3. STLSQ recovers a constructed sparse system exactly
# ═════════════════════════════════════════════════════════════════════════════

def test_stlsq_exact_recovery_and_support() -> None:
    """
    Construct Theta and a sparse Xi_true, form Xdot = Theta @ Xi_true, recover.
    Coefficients must match and the support (which entries are zero) must be exact.
    """
    out = _run("""
        const Theta=[
          [1,0.2,0.5,0.10,0.9],[1,0.9,0.1,0.80,0.2],[1,0.4,0.7,0.30,0.5],
          [1,0.6,0.3,0.05,0.8],[1,0.1,0.9,0.70,0.1],[1,0.8,0.2,0.20,0.6],
          [1,0.3,0.6,0.90,0.3],[1,0.5,0.4,0.40,0.7]];
        const XiTrue=[[0,0],[2.0,0],[0,-1.5],[0,0],[0.7,0.3]];
        const Xdot=Theta.map(r=>[0,1].map(j=>r.reduce((s,v,k)=>s+v*XiTrue[k][j],0)));
        const Xi=S.stlsq(Theta,Xdot,{lambda:0.05,iterations:20,ridge:1e-10});
        process.stdout.write(JSON.stringify({Xi,XiTrue}));
    """)
    Xi, XiTrue = out["Xi"], out["XiTrue"]
    for j in range(2):
        col = [Xi[i][j] for i in range(5)]
        col_true = [XiTrue[i][j] for i in range(5)]
        assert _abs_err(col, col_true) < COEFF_TOL, f"col{j}: {col} vs {col_true}"
    for i in range(5):
        for j in range(2):
            assert (abs(Xi[i][j]) < 1e-9) == (XiTrue[i][j] == 0.0), (i, j, Xi[i][j])


# ═════════════════════════════════════════════════════════════════════════════
# 4. End-to-end recovery of known systems (exact derivatives)
# ═════════════════════════════════════════════════════════════════════════════

def test_discover_linear_decay() -> None:
    """x' = -0.5 x : coeff(x) ~ -0.5, all else zero."""
    out = _run(f"""
        const f=(t,y)=>[-0.5*y[0]];
        const {{t,X,Xdot}}=ctx.__h.simulate(f,[3.0],0.02,400);
        const res=S.discover({{X,t,Xdot,varNames:['x'],
            library:{{constant:true,linear:true,quadratic:true,interactions:false,cubic:true,trig:false}},
            lambda:{LAMBDA}, ridge:1e-10}});
        process.stdout.write(JSON.stringify(res));
    """)
    names = out["featureNames"]
    coeff_x = out["Xi"][names.index("x")][0]
    assert abs(coeff_x - (-0.5)) < COEFF_TOL, coeff_x
    for i, nm in enumerate(names):
        if nm != "x":
            assert abs(out["Xi"][i][0]) < 1e-6, f"spurious {nm}={out['Xi'][i][0]}"


def test_discover_lotka_volterra() -> None:
    """
    N' = a N - b N P ,  P' = c N P - d P   (a=1,b=0.1,c=0.075,d=1.5).
    Must recover coeff(N)=a, coeff(N*P)=-b for eq0; coeff(P)=-d, coeff(N*P)=c for
    eq1; and the support must be exactly those four terms. This is the make-or-break
    test: pass it and the engine recovers real mechanisms.
    """
    a, b, c, d = 1.0, 0.1, 0.075, 1.5
    out = _run(f"""
        const a={a},b={b},c={c},d={d};
        const f=(t,y)=>[a*y[0]-b*y[0]*y[1], c*y[0]*y[1]-d*y[1]];
        const {{t,X,Xdot}}=ctx.__h.simulate(f,[10,5],0.01,2000);
        const res=S.discover({{X,t,Xdot,varNames:['N','P'],
            library:{FULL_LIB}, lambda:{LAMBDA}, ridge:1e-10}});
        process.stdout.write(JSON.stringify(res));
    """)
    names, Xi = out["featureNames"], out["Xi"]

    def coeff(feat, col):
        return Xi[names.index(feat)][col]

    assert abs(coeff("N", 0) - a) < COEFF_TOL, coeff("N", 0)
    assert abs(coeff("N*P", 0) - (-b)) < COEFF_TOL, coeff("N*P", 0)
    assert abs(coeff("P", 1) - (-d)) < COEFF_TOL, coeff("P", 1)
    assert abs(coeff("N*P", 1) - c) < COEFF_TOL, coeff("N*P", 1)

    support = {("N", 0), ("N*P", 0), ("P", 1), ("N*P", 1)}
    for i, nm in enumerate(names):
        for j in range(2):
            nonzero = abs(Xi[i][j]) > 1e-6
            assert nonzero == ((nm, j) in support), f"support: {nm} col{j}={Xi[i][j]}"
    assert out["rmse"] < 1e-6, out["rmse"]


def test_discover_equations_are_readable() -> None:
    """discover() must return human-readable equation strings, one per variable."""
    out = _run(f"""
        const f=(t,y)=>[-0.5*y[0]];
        const {{t,X,Xdot}}=ctx.__h.simulate(f,[3.0],0.02,300);
        const res=S.discover({{X,t,Xdot,varNames:['x'],
            library:{{constant:true,linear:true,quadratic:true,interactions:false,cubic:false,trig:false}},
            lambda:{LAMBDA}, ridge:1e-10}});
        process.stdout.write(JSON.stringify(res));
    """)
    assert len(out["equations"]) == 1
    assert "x" in out["equations"][0] and "=" in out["equations"][0]


# ═════════════════════════════════════════════════════════════════════════════
# 5. Finite-difference path (no exact derivatives)
# ═════════════════════════════════════════════════════════════════════════════

def test_discover_fd_path() -> None:
    """No Xdot supplied -> internal finite differences -> still recovers -0.5 x."""
    out = _run(f"""
        const f=(t,y)=>[-0.5*y[0]];
        const {{t,X}}=ctx.__h.simulate(f,[3.0],0.01,800);
        const res=S.discover({{X,t,varNames:['x'],
            library:{{constant:true,linear:true,quadratic:true,interactions:false,cubic:false,trig:false}},
            lambda:{LAMBDA}}});
        process.stdout.write(JSON.stringify(res));
    """)
    names = out["featureNames"]
    assert abs(out["Xi"][names.index("x")][0] - (-0.5)) < FD_COEFF_TOL
    assert out["usedFiniteDifferences"] is True


# ═════════════════════════════════════════════════════════════════════════════
# 6. Determinism
# ═════════════════════════════════════════════════════════════════════════════

def test_discover_deterministic() -> None:
    """Identical input -> identical Xi. SINDy has no stochastic component."""
    out = _run(f"""
        const a=1.0,b=0.1,c=0.075,d=1.5;
        const f=(t,y)=>[a*y[0]-b*y[0]*y[1], c*y[0]*y[1]-d*y[1]];
        const {{t,X,Xdot}}=ctx.__h.simulate(f,[10,5],0.01,1000);
        const cfg={{X,t,Xdot,varNames:['N','P'],library:{FULL_LIB},lambda:{LAMBDA},ridge:1e-10}};
        const r1=S.discover(cfg), r2=S.discover(cfg);
        process.stdout.write(JSON.stringify({{Xi1:r1.Xi,Xi2:r2.Xi}}));
    """)
    assert out["Xi1"] == out["Xi2"]


# ═════════════════════════════════════════════════════════════════════════════
# 7. Pre-conditions
# ═════════════════════════════════════════════════════════════════════════════

@pytest.mark.parametrize("bad_js, needle", [
    ("S.discover({X:[], t:[], varNames:['x'], library:{constant:true,linear:true}, lambda:0.02})", "empty"),
    ("S.discover({X:[[1,2],[3]], t:[0,1], varNames:['x','y'], library:{linear:true}, lambda:0.02})", "rectangular"),
    ("S.discover({X:[[1],[2],[3]], t:[0,1], varNames:['x'], library:{linear:true}, lambda:0.02})", "length"),
    ("S.discover({X:[[1],[2],[3]], t:[0,1,2], varNames:['x'], library:{linear:true}, lambda:-1})", "lambda"),
    ("S.discover({X:[[1,2],[3,4],[5,6]], t:[0,1,2], varNames:['x'], library:{linear:true}, lambda:0.02})", "varNames"),
])
def test_preconditions(bad_js: str, needle: str) -> None:
    """Each malformed call throws an Error whose message names the problem."""
    out = _run(f"""
        let msg='NO_THROW';
        try {{ {bad_js}; }} catch(e){{ msg=String(e.message||e); }}
        process.stdout.write(JSON.stringify({{msg}}));
    """)
    assert out["msg"] != "NO_THROW", f"expected throw for: {bad_js}"
    assert needle.lower() in out["msg"].lower(), f"{out['msg']!r} should mention {needle!r}"


# ═════════════════════════════════════════════════════════════════════════════
# 8. Wiring: sciml-lab.js uses the shared engine, not its own inline math
# ═════════════════════════════════════════════════════════════════════════════

def test_sciml_lab_uses_shared_engine() -> None:
    """
    After the cutover, sciml-lab.js must call window.FokoSINDy and the page must
    load src/sindy.js. Guards against the inline untested math silently surviving.
    """
    lab = (ROOT / "src/sciml-lab.js").read_text(encoding="utf-8")
    assert "FokoSINDy" in lab, "sciml-lab.js must call window.FokoSINDy after cutover."

    page = (ROOT / "sciml.html").read_text(encoding="utf-8")
    assert "src/sindy.js" in page, "sciml.html must load src/sindy.js before sciml-lab.js."
