from pathlib import Path
from bs4 import BeautifulSoup

ROOT = Path(__file__).resolve().parents[1]

def read(path):
    return (ROOT / path).read_text(encoding='utf-8')

def soup(path):
    return BeautifulSoup(read(path), 'html.parser')


def visible_text(path):
    return soup(path).get_text(' ', strip=True)


def test_model_atlas_filter_all_stays_inside_filter_card():
    html = soup('examples.html')
    filters = html.select_one('.atlas-filters')
    assert filters is not None
    first_control = next((child for child in filters.children if getattr(child, 'name', None)), None)
    assert first_control.name == 'button'
    assert first_control.get('data-filter') == 'all'
    css = read('styles/style.css')
    assert '.atlas-filters::before' in css
    assert 'content:none!important' in css
    assert '.atlas-filters.card{padding:14px 16px!important' in css


def test_gradient_bars_removed_from_generic_cards():
    css = read('styles/style.css')
    assert '.card::before' in css
    assert 'display:none!important' in css
    assert 'height:0!important' in css
    assert 'background:none!important' in css


def test_symbolic_prioritizes_computed_latex_over_plot_first_layout():
    html = read('symbolic.html')
    text = visible_text('symbolic.html')
    assert 'Computed LaTeX' in text
    assert 'Computation result' in text
    assert 'symComputed' in html
    assert text.index('Computation result') < text.index('Symbolic plot preview')
    assert 'decorative equation viewer' not in text
    assert 'Boundary' not in text


def test_symbolic_js_renders_computation_results_as_latex():
    js = read('src/symbolic-lab.js')
    for token in ['function computedLatex', 'function rowsToLatex', "renderMath($('symComputed')", "renderMath($('symNumericEquilibriaLatex')"]:
        assert token in js
    assert 'Generated by Foko Lab Symbolic Lab v49' in js


def test_symbolic_session_import_does_not_overwrite_imported_model():
    js = read('src/symbolic-lab.js')
    assert "const sel=$('symExample')" in js
    assert 'populate();  // populate example selector' not in js
