from pathlib import Path
from bs4 import BeautifulSoup
ROOT=Path(__file__).resolve().parents[1]

def read(rel): return (ROOT/rel).read_text(encoding='utf-8')
def soup(rel): return BeautifulSoup(read(rel), 'html.parser')

def test_agent_lab_exists_and_has_controls():
    html=read('agent.html')
    for token in ['agentExample','agentCanvas','agentMetrics','agentRun','agentStep','agentExport','T-cell proliferation','SIR agents','Game of Life']:
        assert token in html
    assert (ROOT/'src'/'agent-lab.js').exists()
    assert (ROOT/'styles'/'agent-lab.css').exists()

def test_agent_js_has_model_families_and_export():
    js=read('src/agent-lab.js')
    for token in ['tcell','sir','predprey','life','forest','plant','evolution','langton','exportConfig','Plotly.react']:
        assert token in js

def test_symbolic_plot_controls_are_visible_and_richer():
    html=read('symbolic.html')
    for token in ['Plot now','symParamControls','symPlotResolution','symPlotPalette','symAutoPlot','nullclines','Symbolic plot preview']:
        assert token in html
    assert html.index('Symbolic plot preview') < html.index('Algebraic operation')

def test_symbolic_js_avoids_raw_latex_eigen_failure_and_has_nullcline_plotting():
    js=read('src/symbolic-lab.js')
    for token in ['function eigenHtml','function vectorPack','nullclines','updateParamControls','sp.dsolve','Generated by Foko Lab Symbolic Lab v18']:
        assert token in js
    assert "renderLines($('symEigen')" not in js

def test_docs_tutorial_include_new_modules_without_old_noise():
    docs=soup('docs.html').get_text(' ', strip=True)
    tutorial=soup('tutorial.html').get_text(' ', strip=True)
    for term in ['Agent Lab','Symbolic Lab','Custom models','Scientific limits']:
        assert term in docs
    for term in ['Agent route','Symbolic route','Workbench route','Failure checks']:
        assert term in tutorial
