from pathlib import Path
from bs4 import BeautifulSoup
ROOT=Path(__file__).resolve().parents[1]

def read(rel): return (ROOT/rel).read_text(encoding='utf-8')
def text(rel): return BeautifulSoup(read(rel),'html.parser').get_text(' ', strip=True)

def test_agent_lab_exposes_approach_method_time_topology_and_custom_model():
    html=read('agent.html')
    for token in ['agentApproach','Rule-Based Decision Making','State-Driven Agents / Statecharts','Adaptive & Learning Agents','Graph / Network-Based Approach','agentTimeMode','continuous_rate','agentTopology','random_graph','agentCustomModelJson','agentApplyCustomModel','Approach comparison']:
        assert token in html

def test_agent_js_supports_model_authoring_approaches_and_richer_custom_contract():
    js=read('src/agent-lab.js')
    for token in ['APPROACHES','statechart','adaptive','graph','continuous_rate','rateProb','buildGraph','neighborhoodIds','customSkeleton','applyCustomModel','normalizeCustomResult','trait','memory','dt','mode===\'transition\'','mode===\'network\'']:
        assert token in js
    assert 'new Function' in js and 'cell' in js and 'neighbors' in js and 'counts' in js and 'params' in js

def test_symbolic_lab_has_custom_json_and_approach_selection():
    html=read('symbolic.html')
    for token in ['symApproach','Expression / algebraic analysis','ODE system analysis','Steady-state and linearization','Parameter scan / bifurcation sketch','Reduction / QSSA helper','symModelJson','symLoadJson','symApplyJson','Symbolic modeling approaches']:
        assert token in html
    js=read('src/symbolic-lab.js')
    for token in ['symbolicConfig','loadJsonSkeleton','applyJsonModel','APPROACH_INFO','Generated by Foko Lab Symbolic Lab v20']:
        assert token in js

def test_all_specialist_labs_expose_custom_model_and_method_standard():
    expectations={
      'ode.html':['Custom ODE model and method choice','Own model','Methods','RK45'],
      'optimization.html':['Custom optimization model and method choice','Problem class','Algorithm','Own model'],
      'steady.html':['Custom steady-state model and method choice','equations f(x,p)=0','continuation'],
      'stochastic.html':['Custom stochastic model and method choice','full JSON schema','Gillespie']
    }
    for rel,tokens in expectations.items():
        page=text(rel)
        for token in tokens:
            assert token in page

def test_docs_tutorial_cover_all_labs_authoring_and_agent_approach_comparison():
    docs=text('docs.html'); tutorial=text('tutorial.html')
    for token in ['Core workflow','ODE Lab','Optimization Lab','Steady-State Lab','Stochastic Lab','Symbolic Lab','Agent Lab']:
        assert token in docs
    for token in ['Equation model','Symbolic route','Agent route','Workbench route','Failure checks']:
        assert token in tutorial
