"""
test_v60_build_version_consistency.py
=====================================

Protocol step 1: the test comes before the fix. Each assertion below fails on
the shipped v60 tree and passes once the build-version inconsistency is
repaired. The test is written to be read: every block states the defect it
guards, why it matters to a scientist who exports models for reproducibility,
and what the passing contract is.

The defect, stated precisely
----------------------------
There is no single source of truth for the build version. Each lab module
hard-codes its own `version:` literal inside the JSON it exports:

    src/agent-lab.js      configObject()  -> version:'v54'
    src/agent-lab.js      customSkeleton()-> version:'v54'
    src/symbolic-lab.js   symbolicConfig()-> version:'v60'

and the Agent JSON download is named `foko-agent-model-v54.json`. So two labs
in the same build stamp different versions onto their exports, and the Agent
stamp (v54) misrepresents the v60 build the user is actually running. For a
platform whose selling point is reproducible exports, a wrong provenance stamp
is a correctness defect, not a cosmetic one.

The contract this test pins
---------------------------
1. A single build constant exists and is the declared source of truth.
2. Every *live* export version marker equals that constant.
3. The two labs agree with each other.
4. The Agent download filename tracks the build.
5. Intentional backward-compatibility audit-token *comments* are NOT touched
   (older test files assert their presence; removing them would break them).
   This test explicitly protects them so the fix cannot over-reach.

Design notes
------------
* We read source text and assert on it directly (static analysis). No browser
  is needed; these are provenance strings in emitted JSON, fully determined by
  the source.
* Pre-conditions are asserted at the top of each helper (protocol step 6):
  a missing file or a missing declaration is surfaced as a distinct
  test-environment error, not conflated with a contract failure.
* `EXPECTED_BUILD` is defined once here; if the build is bumped again the fix
  is: update the constant in the source AND this expectation, and every
  assertion re-aligns.

Run:
    python -m pytest tests/test_v60_build_version_consistency.py -v
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]

# The build this tree represents. The whole point of the fix is that this
# single value is reflected everywhere a live export is stamped.
EXPECTED_BUILD = "v60"


# ─────────────────────────────────────────────────────────────────────────────
# Helpers (with pre-condition assertions)
# ─────────────────────────────────────────────────────────────────────────────

def read(rel: str) -> str:
    """Read a repo-relative source file. Pre-condition: it exists and is nonempty."""
    p = ROOT / rel
    assert p.exists(), f"[test-env] source file missing: {rel}"
    text = p.read_text(encoding="utf-8")
    assert text.strip(), f"[test-env] source file empty: {rel}"
    return text


def declared_build(js: str) -> str | None:
    """Return the FOKO_BUILD value declared in this source, or None if absent."""
    m = re.search(r"(?:const|var|let)\s+FOKO_BUILD\s*=\s*'(v\d+)'", js)
    return m.group(1) if m else None


def live_version_markers(js: str) -> list[str]:
    """
    Return every LIVE export version marker in a JS source, RESOLVED to a
    concrete version string.

    Two valid representations are recognised:
      * a string literal            version:'vNN'
      * a reference to the constant version:FOKO_BUILD   (the fixed form)

    The reference form is resolved by reading the file's own FOKO_BUILD
    declaration. This makes the test representation-agnostic: it asserts the
    *resolved* build stamped onto exports, whether written inline or via the
    constant.

    We deliberately do NOT match the audit-token *comment* strings like
    "Generated by Foko Lab Symbolic Lab v50", which are prose, not properties.

    Pre-condition: the file emits at least one versioned config marker in one of
    the two forms; zero is a real failure worth surfacing.
    """
    literals = re.findall(r"version:\s*'(v\d+)'", js)
    ref_count = len(re.findall(r"version:\s*FOKO_BUILD\b", js))

    markers = list(literals)
    if ref_count:
        build = declared_build(js)
        assert build, (
            "[test-env] source uses `version:FOKO_BUILD` but declares no "
            "FOKO_BUILD constant to resolve it against."
        )
        markers.extend([build] * ref_count)

    assert markers, (
        "[test-env] no live version marker found (neither version:'vNN' nor "
        "version:FOKO_BUILD); the helper was called on a file that does not "
        "emit a versioned config."
    )
    return markers


# ─────────────────────────────────────────────────────────────────────────────
# 1. A single build constant must exist as the source of truth
# ─────────────────────────────────────────────────────────────────────────────

def test_single_build_constant_declared_somewhere() -> None:
    """
    P1 — the fix must introduce one declared build constant (e.g.
    `const FOKO_BUILD='v60'`) that the live exports read from, instead of each
    module hard-coding its own literal.

    FAILS on v60: no such constant exists; versions are scattered literals.
    """
    # Look across the shared/entry modules for a single build declaration.
    candidates = ["src/app.js", "src/navigation.js", "src/agent-lab.js",
                  "src/symbolic-lab.js"]
    found = []
    for rel in candidates:
        js = read(rel)
        m = re.search(r"(?:const|var|let)\s+FOKO_BUILD\s*=\s*'(v\d+)'", js)
        if m:
            found.append((rel, m.group(1)))
    assert found, (
        "No FOKO_BUILD constant found in any shared module. Introduce a single "
        "source of truth, e.g. `const FOKO_BUILD='v60';`, and have every live "
        "export read from it instead of hard-coding version:'vNN'."
    )
    # If declared in more than one place, they must all agree.
    values = {v for _, v in found}
    assert values == {EXPECTED_BUILD}, (
        f"FOKO_BUILD is declared as {found}; every declaration must equal "
        f"'{EXPECTED_BUILD}'."
    )


# ─────────────────────────────────────────────────────────────────────────────
# 2. Every live export marker equals the expected build
# ─────────────────────────────────────────────────────────────────────────────

def test_agent_live_markers_match_build() -> None:
    """
    P1 — Agent Lab's emitted configs (configObject, customSkeleton) must stamp
    the current build.

    FAILS on v60: agent-lab.js stamps 'v54'.
    """
    js = read("src/agent-lab.js")
    markers = live_version_markers(js)
    bad = [m for m in markers if m != EXPECTED_BUILD]
    assert not bad, (
        f"agent-lab.js emits version marker(s) {sorted(set(bad))} in its "
        f"exported config, but the build is '{EXPECTED_BUILD}'. A user who "
        "exports an Agent model gets a wrong provenance stamp. Read the version "
        "from the shared FOKO_BUILD constant."
    )


def test_symbolic_live_markers_match_build() -> None:
    """
    P1 — Symbolic Lab's emitted config must stamp the current build.

    PASSES on v60 for the property (symbolic already says v60) — this is the
    reference lab the Agent lab must be brought into line with. Kept so a future
    regression that drifts symbolic is caught too.
    """
    js = read("src/symbolic-lab.js")
    markers = live_version_markers(js)
    bad = [m for m in markers if m != EXPECTED_BUILD]
    assert not bad, (
        f"symbolic-lab.js emits version marker(s) {sorted(set(bad))} in its "
        f"exported config; expected '{EXPECTED_BUILD}'."
    )


# ─────────────────────────────────────────────────────────────────────────────
# 3. The two labs must agree with each other
# ─────────────────────────────────────────────────────────────────────────────

def test_labs_agree_on_export_version() -> None:
    """
    P1 — the union of live markers across Agent and Symbolic must be a single
    value. Two labs in one build stamping different versions is the core defect.

    FAILS on v60: {'v54','v60'}.
    """
    agent = set(live_version_markers(read("src/agent-lab.js")))
    symbolic = set(live_version_markers(read("src/symbolic-lab.js")))
    union = agent | symbolic
    assert union == {EXPECTED_BUILD}, (
        f"Agent live markers={sorted(agent)}, Symbolic live markers="
        f"{sorted(symbolic)}. The union {sorted(union)} must be a single value "
        f"'{EXPECTED_BUILD}'. Both labs must read the same build constant."
    )


# ─────────────────────────────────────────────────────────────────────────────
# 4. The Agent download filename must track the build
# ─────────────────────────────────────────────────────────────────────────────

def test_agent_download_filename_tracks_build() -> None:
    """
    P2 — the exported Agent JSON filename encodes a version; it must match the
    build so a downloaded file is self-describing.

    FAILS on v60: filename is 'foko-agent-model-v54.json'.
    """
    js = read("src/agent-lab.js")
    # Two valid forms:
    #   literal:  a.download='foko-agent-model-v60.json'
    #   built:    a.download='foko-agent-model-'+FOKO_BUILD+'.json'  (fixed form)
    literal_names = re.findall(r"foko-agent-model-(v\d+)\.json", js)
    built = re.search(r"'foko-agent-model-'\s*\+\s*FOKO_BUILD\s*\+\s*'\.json'", js)

    resolved: list[str] = list(literal_names)
    if built:
        build = declared_build(js)
        assert build, (
            "[test-env] download name is built from FOKO_BUILD but no "
            "FOKO_BUILD constant is declared to resolve it."
        )
        resolved.append(build)

    assert resolved, (
        "[test-env] no Agent download name found (neither a literal "
        "'foko-agent-model-vNN.json' nor a FOKO_BUILD-built name)."
    )
    bad = [n for n in resolved if n != EXPECTED_BUILD]
    assert not bad, (
        f"Agent download filename version(s) {sorted(set(bad))} do not match "
        f"the build '{EXPECTED_BUILD}'. Build the name from FOKO_BUILD so it "
        "tracks the build automatically."
    )


# ─────────────────────────────────────────────────────────────────────────────
# 5. Intentional backward-compat audit-token COMMENTS must be preserved
# ─────────────────────────────────────────────────────────────────────────────

def test_backward_compat_audit_tokens_preserved() -> None:
    """
    GUARD — the fix must not over-reach. symbolic-lab.js deliberately keeps
    prose audit tokens like "Generated by Foko Lab Symbolic Lab v50" so that
    older test files asserting their presence keep passing. These are comments,
    not live version markers, and the fix must leave them intact.

    This test PASSES on v60 and must KEEP passing after the fix. If a naive
    fix does a blanket version bump and rewrites these strings, this catches it.
    """
    js = read("src/symbolic-lab.js")
    # The audit tokens the surrounding comment says are retained intentionally.
    required_tokens = [
        "Foko Lab Symbolic Lab v18",
        "Foko Lab Symbolic Lab v20",
        "Foko Lab Symbolic Lab v50",
    ]
    missing = [t for t in required_tokens if t not in js]
    assert not missing, (
        f"Backward-compatibility audit token(s) removed: {missing}. These are "
        "intentional and older tests depend on them. The build-version fix must "
        "touch only live `version:'vNN'` properties and the download filename, "
        "not these comment strings."
    )


# ─────────────────────────────────────────────────────────────────────────────
# 6. Script cache tokens for the two edited labs should be coherent
# ─────────────────────────────────────────────────────────────────────────────

def test_lab_script_cache_tokens_are_build_coherent() -> None:
    """
    P2 — a page that loads a lab script it changed this build must bump that
    script's cache token so returning visitors do not run stale JS. We do not
    force a specific value, but agent-lab.js and symbolic-lab.js tokens should
    not still read the *old* build number after their source changed.

    Concretely on v60: agent.html loads `agent-lab.js?v=v54`. Since agent-lab.js
    is edited by this fix, that token must move off 'v54'.
    """
    agent_html = read("agent.html")
    m = re.search(r"agent-lab\.js\?v=(v?\d+)", agent_html)
    assert m, "[test-env] agent-lab.js script token not found in agent.html"
    token = m.group(1)
    # After the fix, agent-lab.js changes, so its cache token must not stay at
    # the pre-fix 'v54' value.
    assert token not in ("v54", "54"), (
        f"agent.html still loads agent-lab.js?v={token}. Since agent-lab.js is "
        "modified by the build-version fix, bump this cache token so returning "
        "visitors fetch the new file (e.g. ?v=v60)."
    )
