/* Curated, deterministic datasets for the v72.5 Curve Fitting reference lab. */
(function (root) {
  'use strict';

  root.FokoFittingPresets = {
    enzyme_low_substrate: {
      title: 'Michaelis–Menten identifiability trap',
      family: 'Nonlinear biochemical fit',
      model: 'michaelis',
      weighting: 'ordinary',
      x: 'substrate',
      y: 'rate',
      sigma: 'sigma',
      data: [
        'substrate,rate,sigma',
        '0.05,0.020,0.010',
        '0.10,0.039,0.010',
        '0.18,0.068,0.012',
        '0.28,0.101,0.013',
        '0.40,0.139,0.014',
        '0.55,0.181,0.016',
        '0.72,0.224,0.018',
        '0.90,0.266,0.020',
      ].join('\n'),
      initial: '1.0, 2.0',
      narrative: 'A deliberately low-substrate dataset can fit beautifully while constraining mainly the ratio Vmax/Km rather than the two parameters separately.',
      scientificNote: 'Use the correlation matrix and profile-SSE verdict. A high R² does not rescue a flat parameter profile; add saturation-region measurements before interpreting Vmax or Km individually.',
    },
    enzyme: {
      title: 'Michaelis–Menten kinetics',
      family: 'Nonlinear biochemical fit',
      model: 'michaelis',
      weighting: 'ordinary',
      x: 'substrate',
      y: 'rate',
      sigma: 'sigma',
      data: [
        'substrate,rate,sigma',
        '0.10,0.118,0.030',
        '0.20,0.210,0.032',
        '0.35,0.325,0.035',
        '0.55,0.430,0.038',
        '0.85,0.535,0.042',
        '1.20,0.626,0.045',
        '1.80,0.708,0.050',
        '2.70,0.794,0.054',
        '4.00,0.851,0.060',
        '6.00,0.897,0.066',
        '9.00,0.938,0.075',
      ].join('\n'),
      initial: '1.0, 0.8',
      narrative: 'Estimate Vmax and Km from a small saturation dataset, then inspect parameter uncertainty and profile shape.',
      scientificNote: 'The model is mechanistic only under the usual quasi-steady-state assumptions. A good numerical fit does not establish that those assumptions hold.',
    },
    calibration: {
      title: 'Weighted calibration curve',
      family: 'Known-sigma weighted regression',
      model: 'linear',
      weighting: 'known-sigma',
      x: 'concentration',
      y: 'signal',
      sigma: 'sigma',
      data: [
        'concentration,signal,sigma',
        '0,0.04,0.05',
        '1,1.92,0.08',
        '2,4.10,0.10',
        '3,6.01,0.13',
        '4,7.96,0.17',
        '5,10.25,0.22',
        '6,11.88,0.28',
        '7,14.21,0.35',
        '8,16.10,0.44',
      ].join('\n'),
      initial: '',
      narrative: 'Fit a linear calibration while treating the supplied observation standard deviations as known.',
      scientificNote: 'Inverse-variance weighting is justified only when sigma values are credible observation-level standard deviations. It does not repair model misspecification.',
    },
    logistic: {
      title: 'Logistic population growth',
      family: 'Three-parameter nonlinear fit',
      model: 'logistic',
      weighting: 'ordinary',
      x: 'time',
      y: 'population',
      sigma: 'sigma',
      data: [
        'time,population,sigma',
        '0,0.75,0.30',
        '1,1.10,0.30',
        '2,1.75,0.35',
        '3,2.85,0.40',
        '4,4.45,0.45',
        '5,6.25,0.50',
        '6,7.95,0.55',
        '7,9.05,0.60',
        '8,9.58,0.60',
        '9,9.88,0.65',
        '10,10.04,0.65',
      ].join('\n'),
      initial: '10, 0.8, 4.5',
      narrative: 'Estimate carrying capacity, growth rate and midpoint from a sigmoidal time series.',
      scientificNote: 'Residual independence is doubtful in longitudinal data. This browser fit treats observations as independent and should be validated with a time-series or hierarchical model when appropriate.',
    },
    exponential: {
      title: 'Exponential growth',
      family: 'Two-parameter nonlinear fit',
      model: 'exponential',
      weighting: 'ordinary',
      x: 'time',
      y: 'response',
      sigma: 'sigma',
      data: [
        'time,response,sigma',
        '0,1.95,0.15',
        '0.5,2.42,0.17',
        '1.0,3.05,0.20',
        '1.5,3.74,0.24',
        '2.0,4.72,0.28',
        '2.5,5.86,0.34',
        '3.0,7.31,0.42',
        '3.5,9.25,0.52',
        '4.0,11.42,0.64',
      ].join('\n'),
      initial: '2, 0.45',
      narrative: 'Fit y = a exp(bx) directly on the response scale and inspect heteroscedastic residual structure.',
      scientificNote: 'Direct least squares on y differs from log-scale regression. The error model must match the measurement process; neither transformation is automatically correct.',
    },
    quadratic: {
      title: 'Quadratic response surface',
      family: 'Polynomial least squares',
      model: 'quadratic',
      weighting: 'ordinary',
      x: 'dose',
      y: 'response',
      sigma: 'sigma',
      data: [
        'dose,response,sigma',
        '-3,8.9,0.45',
        '-2.5,6.1,0.40',
        '-2,3.9,0.36',
        '-1.5,2.3,0.34',
        '-1,1.2,0.32',
        '-0.5,0.7,0.30',
        '0,0.9,0.30',
        '0.5,1.5,0.31',
        '1,2.8,0.34',
        '1.5,4.8,0.38',
        '2,7.5,0.44',
        '2.5,10.8,0.52',
      ].join('\n'),
      initial: '',
      narrative: 'Fit a second-order polynomial and examine leverage near the range boundaries.',
      scientificNote: 'Polynomial coefficients are descriptive within the observed range. Extrapolation can diverge rapidly and has no mechanistic interpretation by default.',
    },
    outlier: {
      title: 'Influential observation stress test',
      family: 'Diagnostics and sensitivity',
      model: 'linear',
      weighting: 'ordinary',
      x: 'x',
      y: 'y',
      sigma: 'sigma',
      data: [
        'x,y,sigma',
        '0,1.1,0.20',
        '1,2.9,0.20',
        '2,5.2,0.20',
        '3,7.0,0.20',
        '4,9.1,0.20',
        '5,11.0,0.20',
        '6,13.2,0.20',
        '7,15.0,0.20',
        '12,31.0,0.20',
      ].join('\n'),
      initial: '',
      narrative: 'Use leverage and Cook-style diagnostics to see how a distant observation can dominate a fitted slope.',
      scientificNote: 'Influence diagnostics flag sensitivity under the fitted model; they do not prove that an observation is erroneous or should be removed.',
    },
  };
}(typeof window !== 'undefined' ? window : globalThis));
