/* Browser-scale, explicitly time-homogeneous CTMC presets for the v72.2 Stochastic reference lab. */
(function (root, factory) {
  const presets = factory();
  if (typeof module !== 'undefined' && module.exports) module.exports = presets;
  root.FokoStochasticPresets = presets;
}(typeof window !== 'undefined' ? window : globalThis, function () {
  'use strict';

  return Object.freeze({
    'Birth–death process': {
      family: 'Population process',
      title: 'Linear birth–death process',
      narrative: 'Each individual independently gives birth at rate λ and dies at rate μ. The direct SSA exposes extinction and path-to-path variability hidden by the expected-value ODE.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['X'],
      initial: [40],
      params: { lambda: 0.18, mu: 0.14 },
      reactions: [
        { name: 'birth', propensity: 'lambda*X', change: { X: 1 } },
        { name: 'death', propensity: 'mu*X', change: { X: -1 } },
      ],
      meanField: ['(lambda-mu)*X'],
      settings: { t0: 0, t1: 40, points: 240, runs: 250, seed: 1729, maxEvents: 200000, variable: 'X' },
      scientificNote: 'The deterministic comparison is the first-moment equation dE[X]/dt=(λ−μ)E[X], which closes exactly for this linear model.',
    },
    'Stochastic SIR epidemic': {
      family: 'Epidemiology',
      title: 'Finite-population SIR CTMC',
      narrative: 'Infections and recoveries occur as discrete random events. Early fade-out can occur even when the deterministic basic reproduction number exceeds one.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['S', 'I', 'R'],
      initial: [990, 10, 0],
      params: { beta: 0.34, gamma: 0.12, N: 1000 },
      reactions: [
        { name: 'infection', propensity: 'beta*S*I/N', change: { S: -1, I: 1 } },
        { name: 'recovery', propensity: 'gamma*I', change: { I: -1, R: 1 } },
      ],
      meanField: ['-beta*S*I/N', 'beta*S*I/N-gamma*I', 'gamma*I'],
      settings: { t0: 0, t1: 120, points: 360, runs: 220, seed: 2718, maxEvents: 10000, variable: 'I' },
      scientificNote: 'The mean-field ODE is a large-population approximation. Its trajectory is not the empirical mean of a finite ensemble in general.',
    },
    'Stochastic Michaelis–Menten': {
      family: 'Biochemical kinetics',
      title: 'Enzyme binding and catalysis CTMC',
      narrative: 'Binding, unbinding, and catalysis are simulated as molecule-count events. This is the reaction-network model; it does not assume the quasi-steady-state Michaelis–Menten rate law.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['E', 'S', 'ES', 'P'],
      initial: [30, 120, 0, 0],
      params: { k1: 0.002, km1: 0.25, kcat: 0.18 },
      reactions: [
        { name: 'binding', propensity: 'k1*E*S', change: { E: -1, S: -1, ES: 1 } },
        { name: 'unbinding', propensity: 'km1*ES', change: { E: 1, S: 1, ES: -1 } },
        { name: 'catalysis', propensity: 'kcat*ES', change: { E: 1, ES: -1, P: 1 } },
      ],
      meanField: [
        '-k1*E*S+km1*ES+kcat*ES',
        '-k1*E*S+km1*ES',
        'k1*E*S-km1*ES-kcat*ES',
        'kcat*ES',
      ],
      settings: { t0: 0, t1: 80, points: 280, runs: 180, seed: 31415, maxEvents: 50000, variable: 'P' },
      scientificNote: 'The ODE overlay uses mass-action mean-field equations, not the reduced Michaelis–Menten formula.',
    },
    'Two-stage gene expression': {
      family: 'Gene regulation',
      title: 'Transcription–translation CTMC',
      narrative: 'mRNA and protein are created and degraded through four elementary reactions. Bursty protein trajectories emerge without adding an artificial noise term.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['mRNA', 'Protein'],
      initial: [0, 0],
      params: { k_m: 2.0, gamma_m: 0.45, k_p: 5.5, gamma_p: 0.08 },
      reactions: [
        { name: 'transcription', propensity: 'k_m', change: { mRNA: 1 } },
        { name: 'mRNA degradation', propensity: 'gamma_m*mRNA', change: { mRNA: -1 } },
        { name: 'translation', propensity: 'k_p*mRNA', change: { Protein: 1 } },
        { name: 'protein degradation', propensity: 'gamma_p*Protein', change: { Protein: -1 } },
      ],
      meanField: ['k_m-gamma_m*mRNA', 'k_p*mRNA-gamma_p*Protein'],
      settings: { t0: 0, t1: 100, points: 320, runs: 250, seed: 16180, maxEvents: 200000, variable: 'Protein' },
      scientificNote: 'The mean equations close for this linear network, but the overlay still represents expected values rather than a typical realization.',
    },
    'Schlögl bistability': {
      family: 'Nonlinear chemical kinetics',
      title: 'Schlögl stochastic bistability',
      narrative: 'A one-species autocatalytic reaction network can produce switching and a bimodal finite-time distribution. Bimodality depends on parameters and horizon; it is not assumed from the model name.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['X'],
      initial: [40],
      params: { k1: 0.00003, k2: 0.0000005, k3: 0.08, k4: 0.6, A: 100, B: 80 },
      reactions: [
        { name: 'autocatalytic birth', propensity: 'k1*A*X*(X-1)/2', change: { X: 1 } },
        { name: 'autocatalytic reverse', propensity: 'k2*X*(X-1)*(X-2)/6', change: { X: -1 } },
        { name: 'reservoir birth', propensity: 'k3*B', change: { X: 1 } },
        { name: 'linear loss', propensity: 'k4*X', change: { X: -1 } },
      ],
      meanField: ['k1*A*X^2/2-k2*X^3/6+k3*B-k4*X'],
      settings: { t0: 0, t1: 80, points: 260, runs: 260, seed: 4242, maxEvents: 250000, variable: 'X' },
      scientificNote: 'The final histogram is a transient ensemble at the selected horizon. It is not an automatically certified stationary distribution.',
    },
    'Gene toggle switch': {
      family: 'Synthetic gene regulation',
      title: 'Stochastic mutual-repression toggle',
      narrative: 'Two proteins repress each other through nonlinear birth propensities and degrade one molecule at a time. Switching is finite-population stochastic evidence, not a deterministic bifurcation proof.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['A', 'B'],
      initial: [35, 4],
      params: { alphaA: 28, alphaB: 28, K: 18, n: 3, deltaA: 0.7, deltaB: 0.7 },
      reactions: [
        { name: 'A production', propensity: 'alphaA/(1+(B/K)^n)', change: { A: 1 } },
        { name: 'A degradation', propensity: 'deltaA*A', change: { A: -1 } },
        { name: 'B production', propensity: 'alphaB/(1+(A/K)^n)', change: { B: 1 } },
        { name: 'B degradation', propensity: 'deltaB*B', change: { B: -1 } },
      ],
      meanField: ['alphaA/(1+(B/K)^n)-deltaA*A', 'alphaB/(1+(A/K)^n)-deltaB*B'],
      settings: { t0: 0, t1: 80, points: 260, runs: 220, seed: 8675309, maxEvents: 180000, variable: 'A' },
      scientificNote: 'Hill propensities are phenomenological coarse-graining, not elementary mass-action reactions.',
    },
    'Ion-channel gating noise': {
      family: 'Neuroscience',
      title: 'Two-state ion-channel gating',
      narrative: 'A finite population of channels switches between closed and open states. The open fraction fluctuates even when the deterministic occupancy equation is smooth.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['Closed', 'Open'],
      initial: [80, 20],
      params: { alpha: 0.35, beta: 0.18 },
      reactions: [
        { name: 'opening', propensity: 'alpha*Closed', change: { Closed: -1, Open: 1 } },
        { name: 'closing', propensity: 'beta*Open', change: { Closed: 1, Open: -1 } },
      ],
      meanField: ['-alpha*Closed+beta*Open', 'alpha*Closed-beta*Open'],
      settings: { t0: 0, t1: 35, points: 220, runs: 260, seed: 60013, maxEvents: 120000, variable: 'Open' },
      scientificNote: 'The rates are fixed in time and do not include voltage dependence. This is gating noise, not a full membrane model.',
    },
    'Random telegraph gene bursting': {
      family: 'Gene expression',
      title: 'Promoter switching and transcription bursts',
      narrative: 'A promoter switches between inactive and active states. mRNA production during active periods creates bursts without a decorative noise term.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['Off', 'On', 'mRNA'],
      initial: [1, 0, 0],
      params: { kon: 0.12, koff: 0.35, ktx: 5.5, gamma: 0.42 },
      reactions: [
        { name: 'promoter activation', propensity: 'kon*Off', change: { Off: -1, On: 1 } },
        { name: 'promoter deactivation', propensity: 'koff*On', change: { Off: 1, On: -1 } },
        { name: 'transcription', propensity: 'ktx*On', change: { mRNA: 1 } },
        { name: 'mRNA degradation', propensity: 'gamma*mRNA', change: { mRNA: -1 } },
      ],
      meanField: ['-kon*Off+koff*On', 'kon*Off-koff*On', 'ktx*On-gamma*mRNA'],
      settings: { t0: 0, t1: 100, points: 320, runs: 260, seed: 91011, maxEvents: 160000, variable: 'mRNA' },
      scientificNote: 'The promoter is a single binary copy; ensemble means do not describe a typical burst trajectory.',
    },
    'Moran fixation process': {
      family: 'Evolutionary genetics',
      title: 'Two-type Moran process',
      narrative: 'A fixed-size population changes composition through coupled birth–death replacement events. Finite-horizon fixation probabilities are estimated from seeded ensembles.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['A', 'B'],
      initial: [20, 80],
      params: { fitnessA: 1.08, fitnessB: 1.0, N: 100 },
      reactions: [
        { name: 'A replaces B', propensity: 'fitnessA*A*B/N', change: { A: 1, B: -1 } },
        { name: 'B replaces A', propensity: 'fitnessB*B*A/N', change: { A: -1, B: 1 } },
      ],
      meanField: ['(fitnessA-fitnessB)*A*B/N', '(fitnessB-fitnessA)*A*B/N'],
      settings: { t0: 0, t1: 180, points: 300, runs: 300, seed: 1776, maxEvents: 180000, variable: 'A' },
      scientificNote: 'The displayed zero-state risk for A is an empirical finite-horizon extinction probability, not an analytic fixation theorem.',
    },
    'Stochastic predator–prey': {
      family: 'Ecology',
      title: 'Predator–prey reaction network',
      narrative: 'Prey reproduce, predators consume prey and reproduce, and predators die. Quasi-cycles and extinction emerge from discrete events.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['Prey', 'Predator'],
      initial: [90, 30],
      params: { birth: 0.65, predation: 0.012, death: 0.55 },
      reactions: [
        { name: 'prey birth', propensity: 'birth*Prey', change: { Prey: 1 } },
        { name: 'predation', propensity: 'predation*Prey*Predator', change: { Prey: -1, Predator: 1 } },
        { name: 'predator death', propensity: 'death*Predator', change: { Predator: -1 } },
      ],
      meanField: ['birth*Prey-predation*Prey*Predator', 'predation*Prey*Predator-death*Predator'],
      settings: { t0: 0, t1: 60, points: 280, runs: 220, seed: 2027, maxEvents: 250000, variable: 'Predator' },
      scientificNote: 'Extinction is absorbing in the CTMC. The deterministic overlay cannot reproduce absorbing-state probability.',
    },
    'Density-dependent extinction': {
      family: 'Population process',
      title: 'Logistic birth–competition extinction',
      narrative: 'Individuals reproduce linearly and die through pairwise competition plus baseline mortality. The ensemble exposes collapse risk near the persistence threshold.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['X'],
      initial: [55],
      params: { birth: 0.42, death: 0.30, competition: 0.0035 },
      reactions: [
        { name: 'birth', propensity: 'birth*X', change: { X: 1 } },
        { name: 'baseline death', propensity: 'death*X', change: { X: -1 } },
        { name: 'competition death', propensity: 'competition*X*(X-1)/2', change: { X: -1 } },
      ],
      meanField: ['(birth-death)*X-competition*X^2/2'],
      settings: { t0: 0, t1: 100, points: 300, runs: 320, seed: 10101, maxEvents: 220000, variable: 'X' },
      scientificNote: 'First-zero-passage estimates are right-censored at the chosen horizon.',
    },
    'Apoptosis activation cascade': {
      family: 'Cell signaling',
      title: 'Three-stage apoptosis cascade',
      narrative: 'An upstream trigger activates initiator and executioner species through discrete reactions with degradation. It is a teaching cascade, not a calibrated apoptosis network.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['Trigger', 'Initiator', 'Executioner'],
      initial: [18, 0, 0],
      params: { k1: 0.12, k2: 0.08, d1: 0.05, d2: 0.04, input: 0.3 },
      reactions: [
        { name: 'trigger input', propensity: 'input', change: { Trigger: 1 } },
        { name: 'initiator activation', propensity: 'k1*Trigger', change: { Initiator: 1 } },
        { name: 'executioner activation', propensity: 'k2*Initiator', change: { Executioner: 1 } },
        { name: 'initiator loss', propensity: 'd1*Initiator', change: { Initiator: -1 } },
        { name: 'executioner loss', propensity: 'd2*Executioner', change: { Executioner: -1 } },
      ],
      meanField: ['input', 'k1*Trigger-d1*Initiator', 'k2*Initiator-d2*Executioner'],
      settings: { t0: 0, t1: 80, points: 260, runs: 220, seed: 5150, maxEvents: 180000, variable: 'Executioner' },
      scientificNote: 'No thresholded cell-death event or biochemical calibration is inferred from this reduced cascade.',
    },
    'Immigration–death process': {
      family: 'Queueing / turnover',
      title: 'Immigration–death process',
      narrative: 'Individuals enter at a constant rate and leave independently. The stationary distribution is Poisson when the simulation is run long enough, but this page does not infer stationarity from one finite horizon.',
      interpretation: 'time-homogeneous CTMC',
      stateNames: ['X'],
      initial: [0],
      params: { immigration: 6.0, death: 0.25 },
      reactions: [
        { name: 'immigration', propensity: 'immigration', change: { X: 1 } },
        { name: 'death', propensity: 'death*X', change: { X: -1 } },
      ],
      meanField: ['immigration-death*X'],
      settings: { t0: 0, t1: 40, points: 220, runs: 300, seed: 14142, maxEvents: 100000, variable: 'X' },
      scientificNote: 'The known stationary Poisson law is not automatically claimed; the final-time histogram is a transient Monte Carlo sample unless horizon diagnostics justify otherwise.',
    },
  });
}));
