/* Adaptive implicit Euler with step doubling. Newton solves retain the original
 * ODE; no biological state is clamped. Rejected steps shrink on negativity. */
(function(root){'use strict';
function solve(A,b){const n=b.length,M=A.map((r,i)=>[...r,b[i]]);for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++)if(Math.abs(M[i][k])>Math.abs(M[p][k]))p=i;if(Math.abs(M[p][k])<1e-18)throw Error('Singular Newton matrix');[M[k],M[p]]=[M[p],M[k]];for(let i=k+1;i<n;i++){const f=M[i][k]/M[k][k];for(let j=k;j<=n;j++)M[i][j]-=f*M[k][j];}}const x=Array(n);for(let i=n-1;i>=0;i--){let v=M[i][n];for(let j=i+1;j<n;j++)v-=M[i][j]*x[j];x[i]=v/M[i][i];}return x;}
function integrate(f,y0,times,{rtol=2e-7,atol=1e-11,maxSteps=150000}={}){let y=y0.slice(),time=0,h=Math.min(.01,times.at(-1)/100),attempts=0,accepted=0;
 function step(v,h){let z=v.slice();for(let k=0;k<12;k++){const fz=f(z),r=z.map((a,i)=>a-v[i]-h*fz[i]);const norm=Math.max(...r.map((a,i)=>Math.abs(a)/(1e-11+1e-10*Math.max(Math.abs(z[i]),Math.abs(v[i])))));if(norm<1)return z;const J=Array.from({length:v.length},()=>Array(v.length));for(let j=0;j<v.length;j++){const eps=1e-7*Math.max(1,Math.abs(z[j])),w=z.slice();w[j]+=eps;const fw=f(w);for(let i=0;i<v.length;i++)J[i][j]=(i===j?1:0)-h*(fw[i]-fz[i])/eps;}const delta=solve(J,r);z=z.map((a,i)=>a-delta[i]);if(z.some(a=>!Number.isFinite(a)))throw Error('Newton overflow');}throw Error('Newton convergence');}
 const rows=times.map(target=>{while(time<target-1e-12*Math.max(1,target)){if(++attempts>maxSteps)throw Error('Solver limit reached. Reduce duration or extreme rates; no partial result is reported.');const dt=Math.min(h,target-time);try{const full=step(y,dt),half=step(y,dt/2),fine=step(half,dt/2);if(fine.some(a=>a<0)||full.some(a=>a<0))throw Error('Negative state');const error=Math.max(...fine.map((v,i)=>Math.abs(v-full[i])/(atol+rtol*Math.max(Math.abs(v),Math.abs(y[i])))));if(error>1){h=dt*Math.max(.1,.8/Math.sqrt(error));continue;}y=fine;time+=dt;accepted++;h=dt*Math.min(3,Math.max(.5,.9/Math.sqrt(Math.max(error,1e-12))));}catch(e){h=dt/2;if(h<1e-12)throw Error('Unable to resolve these parameters: '+e.message);}}return y.slice();});return{rows,accepted,attempts,rtol,atol};}
const api={solve,integrate};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ResearchODE=api;
})(globalThis);
