/* Native Plotly figures: explicit presentation settings and portable recorded-data exports. */
(function(root){'use strict';const d=root.document,seen=new WeakSet();
function save(name,body,type){const u=URL.createObjectURL(new Blob([body],{type})),a=d.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
function serial(value){return JSON.stringify(value,(k,v)=>ArrayBuffer.isView(v)?Array.from(v):v);}
function mount(){if(!root.Plotly)return;for(const plot of d.querySelectorAll('.js-plotly-plot')){if(seen.has(plot)||!plot.data)continue;seen.add(plot);const bar=d.createElement('div');bar.className='figure-export-bar';bar.setAttribute('aria-label','Figure presentation and exports');const caption=d.createElement('span');caption.textContent='FIGURE';bar.append(caption);const label=d.createElement('label');label.textContent='Style ';const style=d.createElement('select');style.setAttribute('aria-label','Figure style');for(const [v,t]of [['paper','Publication'],['contrast','High contrast'],['dark','Dark presentation']]){const o=d.createElement('option');o.value=v;o.textContent=t;style.append(o);}label.append(style);bar.append(label);let styling=false;
 async function apply(){if(styling||!plot.data)return;styling=true;const dark=style.value==='dark',contrast=style.value==='contrast',ink=dark?'#eef1fb':'#252938',grid=dark?'#3b455d':contrast?'#b7becb':'#e8ebf1';const layout={paper_bgcolor:dark?'#202735':'#ffffff',plot_bgcolor:dark?'#202735':'#ffffff','font.family':'Inter, Arial, sans-serif','font.size':12,'font.color':ink,'legend.font.size':11,'legend.font.color':ink,'legend.bgcolor':'rgba(0,0,0,0)',colorway:['#3d4df0','#16816d','#c55f35','#7955b6','#b58a28','#327a99']};for(const key of Object.keys(plot.layout||{}))if(/^[xy]axis\d*$/.test(key)){layout[key+'.gridcolor']=grid;layout[key+'.zerolinecolor']=contrast?'#747e90':grid;layout[key+'.linecolor']=dark?'#707b91':'#b9c0cc';layout[key+'.tickfont.size']=11;layout[key+'.tickfont.color']=ink;layout[key+'.title.font.color']=ink;layout[key+'.automargin']=true;}for(let i=0;i<(plot.layout?.annotations?.length||0);i++)layout['annotations['+i+'].font.color']=ink;try{await root.Plotly.relayout(plot,layout);}catch(e){caption.textContent='Style unavailable · '+e.message;}finally{styling=false;}}
 style.onchange=apply;if(typeof plot.on==='function')plot.on('plotly_afterplot',()=>{const background=style.value==='dark'?'#202735':'#ffffff';if(!styling&&(plot.layout?.paper_bgcolor!==background||plot.layout?.font?.family!=='Inter, Arial, sans-serif'))apply();});apply();
 const name=()=>((plot.id||'figure').replace(/[^\w-]/g,'-'));
 function add(text,fn){const b=d.createElement('button');b.type='button';b.textContent=text;b.onclick=async()=>{try{await fn();caption.textContent='FIGURE';}catch(e){caption.textContent='Export failed: '+e.message;}};bar.append(b);}
 add('PNG',()=>root.Plotly.downloadImage(plot,{format:'png',filename:name(),width:1600,height:1000,scale:2}));add('SVG',()=>root.Plotly.downloadImage(plot,{format:'svg',filename:name(),width:1200,height:750}));
 add('Python · figure',()=>{const json=serial({data:plot.data,layout:plot.layout});const code='# FokoLab — redraw the displayed recorded result. This does not rerun the model.\n# Install: pip install plotly\n# Optional static export: pip install kaleido (requires a supported Chrome installation)\nimport json\nfrom pathlib import Path\nimport plotly.graph_objects as go\n\nfigure = json.loads('+JSON.stringify(json)+')\nfig = go.Figure(data=figure["data"], layout=figure["layout"])\nfig.write_html("'+name()+'.html", include_plotlyjs=True)\n# fig.write_image("'+name()+'.svg")\n# fig.write_image("'+name()+'.png", width=1600, height=1000, scale=2)\nfig.show()\n';save(name()+'-figure.py',code,'text/x-python');});
 add('Figure JSON',()=>save(name()+'.json',serial({data:plot.data,layout:plot.layout}),'application/json'));plot.after(bar);
}}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;mount();});}if(d.readyState==='loading')d.addEventListener('DOMContentLoaded',()=>{new MutationObserver(schedule).observe(d.body,{childList:true,subtree:true});schedule();},{once:true});else{new MutationObserver(schedule).observe(d.body,{childList:true,subtree:true});schedule();}
})(globalThis);
