/* One shell across native FokoLab and Dynamics pages. No scientific DOM is remounted. */
(function(root){'use strict';
const doc=root.document;if(!doc)return;
const script=doc.currentScript.src,base=new URL('../../',script);const route=p=>new URL(p,base).href;
const I=root.FokoIntegration,el=(tag,cls,text)=>{const n=doc.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
const a=(text,path,cls)=>{const n=el('a',cls,text);n.href=route(path);return n;};
const button=(text,fn,cls)=>{const n=el('button',cls,text);n.type='button';n.onclick=fn;return n;};
const returnFocus=new WeakMap();
let dialogSerial=0;
function dialog(title){const d=el('dialog','foko-dialog'),h=el('div','foko-dialog-head'),t=el('h2','',title);t.id='foko-dialog-'+dialogSerial++;d.setAttribute('aria-labelledby',t.id);h.append(t,button('Close',()=>d.close()));d.append(h);doc.body.append(d);d.addEventListener('close',()=>{const opener=returnFocus.get(d);if(opener?.isConnected)opener.focus();});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});return d;}
function show(d){if(d.open)return;returnFocus.set(d,doc.activeElement);d.showModal();(d.querySelector('input')||d.querySelector('button'))?.focus();}
function portrait(cls){const img=el('img',cls);img.src=route('assets/profile-chilperic.webp');img.alt='Dr. Chilperic Armel Foko Kuate';img.width=48;img.height=48;return img;}
function boot(){
 if(doc.querySelector('.foko-header'))return;
 const relative=decodeURIComponent(location.pathname).slice(base.pathname.length),path=relative||'index.html';
 const current=I.tools.find(t=>t[1]===path)||I.resources.find(t=>t[1].split('?')[0]===path),group=current?.[3]||'';
 const isAbout=group==='About'||path.startsWith('research/')||['cv.html','contact.html','research.html','identity.html','integration-notes.html','trust.html'].includes(path);
 const area=path==='index.html'?'Home':isAbout?'About':['Inference','Scientific ML','Mathematics'].includes(group)||path==='analysis.html'?'Analyze':group==='Learning'||['book.html','learn.html','programme.html','lesson.html','workspace.html','docs.html'].includes(path)?'Learn':'Model';
 doc.body.dataset.fokoArea=area.toLowerCase();
 const header=el('header','foko-header'),brand=a('','index.html','foko-brand'),mark=el('img');mark.src=route('assets/brand/foko-symbol.png');mark.alt='';brand.setAttribute('aria-label','FokoLab home');brand.append(mark,el('span','','FokoLab'));
 const nav=el('nav','foko-primary-nav');nav.setAttribute('aria-label','Primary navigation');
 for(const g of [['Home','index.html'],...I.groups]){const n=a(g[0],g[1]);if(g[0]===area)n.setAttribute('aria-current','page');nav.append(n);}
 const actions=el('div','foko-header-actions'),searchBtn=button('Search',()=>openSearch(),'foko-search-trigger');searchBtn.append(el('kbd','','Ctrl K'));searchBtn.setAttribute('aria-haspopup','dialog');searchBtn.setAttribute('aria-label','Search FokoLab');
 const menu=button('Menu',()=>show(menuDialog),'foko-menu-trigger');menu.setAttribute('aria-haspopup','dialog');
 const creator=button('',()=>show(profileDialog),'foko-profile-trigger');creator.setAttribute('aria-label','About Dr. Foko: profile, CVs and contact');creator.setAttribute('aria-haspopup','dialog');creator.append(portrait(''),el('span','','Dr. Foko'),el('span','foko-chevron','⌄'));
 actions.append(a('Experiments','experiments.html','foko-experiments'),searchBtn,menu,creator);header.append(brand,nav,actions);doc.body.prepend(header);
 const context=el('nav','foko-context');context.setAttribute('aria-label','Related workspaces');let links,label;
 if(isAbout){label='About';links=[['Profile & CVs','cv.html'],['Research projects','research.html'],['Contact','contact.html'],['Methods & evidence','trust.html'],['Platform & source','integration-notes.html']];}
 else if(area==='Learn'){label='Learn';links=[['Worked lessons','learn.html'],['Scientific Mastery','book.html'],['Guided project','workspace.html?new=1'],['Programme','programme.html'],['Documentation','docs.html']];}
 else if(['plants/index.html','leaf/index.html','tcells/index.html','lipids/index.html','living.html','agent.html'].includes(path)){label='Living systems';links=[['Plants','plants/index.html'],['Leaf physiology','leaf/index.html'],['T cells','tcells/index.html'],['Fatty acids & lipids','lipids/index.html'],['Agents','agent.html']];}
 else if(path.startsWith('continuum/')||['evolution.html','population-genetics.html','evolution-hub.html'].includes(path)){label='Evolution';links=[['C3–C4 continuum','continuum/advanced.html'],['Fitness landscapes','evolution.html'],['Population genetics','population-genetics.html'],['Evolution & search','continuum/approaches.html']];}
 else if(['random.html','stochastic.html','ode.html','steady.html','bifurcation.html'].includes(path)){label='Dynamics';links=[['ODEs','ode.html'],['Randomness','random.html'],['Reaction networks','stochastic.html'],['Equilibria','steady.html'],['Bifurcations','bifurcation.html']];}
 else if(area==='Analyze'){label='Analyze';links=[['Overview','analysis.html'],['Statistics','statistics.html'],['Curve fitting','fitting.html'],['Sensitivity','sensitivity.html'],['Optimization','optimization.html']];}
 else{label='Explore';links=[['All workspaces','labs.html'],['Living systems','living.html'],['Evolution','evolution-hub.html'],['Model Atlas','examples.html'],['Saved experiments','experiments.html']];}
 const switcher=button('Switch lab',()=>show(switchDialog),'foko-switch-lab');switcher.setAttribute('aria-haspopup','dialog');context.append(switcher,el('span','foko-context-label',label));for(const [t,p]of links){const n=a(t,p);if(p.split('?')[0]===path)n.setAttribute('aria-current','page');context.append(n);}header.after(context);
 doc.querySelectorAll('.lab-route-strip').forEach(n=>n.remove());
 const themeDialog=dialog('Appearance'),themeOptions=el('div','foko-actions');themeDialog.append(el('p','','Choose the interface that is most comfortable for your work.'),themeOptions);
 function setTheme(mode){doc.documentElement.dataset.appearance=mode;try{localStorage.setItem('fokolab:appearance',mode);localStorage.setItem('foko:appearance',JSON.stringify(mode));}catch(_){}doc.dispatchEvent(new Event('foko:appearance'));root.dispatchEvent(new Event('resize'));for(const b of themeOptions.children)b.setAttribute('aria-pressed',String(b.dataset.mode===mode));}
 for(const [v,t]of [['light','Light'],['dark','Dark'],['contrast','High contrast']]){const b=button(t,()=>setTheme(v));b.dataset.mode=v;themeOptions.append(b);}try{setTheme(['light','dark','contrast'].includes(localStorage.getItem('fokolab:appearance'))?localStorage.getItem('fokolab:appearance'):'light');}catch(_){setTheme('light');}
 const profileDialog=dialog('The creator of FokoLab');profileDialog.classList.add('foko-profile-dialog');const identity=el('div','foko-menu-identity'),bio=el('div');bio.append(el('h3','','Dr. Chilperic Armel Foko Kuate'),el('p','','Applied mathematics · Computational biology'),el('small','','Düsseldorf, Germany'));identity.append(portrait(''),bio);profileDialog.append(identity);
 const personal=el('nav','foko-personal-links');personal.setAttribute('aria-label','Creator and personal pages');for(const [t,p,desc]of [['Profile & biography','cv.html','Experience, education and scientific computing'],['Research projects','research.html','Plants, metabolism and T-cell proliferation'],['Academic CV','assets/cv/academic_cv.pdf','PDF'],['Industry CV','assets/cv/industry_cv.pdf','PDF · English'],['Industry CV · Deutsch','assets/cv/industry_cv_german.pdf','PDF · German'],['Contact & links','contact.html','Email, GitHub, GitLab and personal website']]){const n=a('',p);n.append(el('b','',t),el('small','',desc));personal.append(n);}profileDialog.append(personal);
 const theme=button('Appearance',()=>{profileDialog.close();returnFocus.set(themeDialog,creator);themeDialog.showModal();},'foko-appearance');theme.id='fokoThemeButton';theme.setAttribute('aria-haspopup','dialog');profileDialog.append(theme);
 const switchDialog=dialog('Choose a workspace');switchDialog.classList.add('foko-switch-dialog');const toolsGrid=el('div','foko-switch-grid');for(const cat of [...new Set(I.tools.map(t=>t[3]))]){const section=el('section');section.append(el('h3','',cat));for(const t of I.tools.filter(t=>t[3]===cat)){const n=a(t[0],t[1]);if(t[1]===path)n.setAttribute('aria-current','page');section.append(n);}toolsGrid.append(section);}switchDialog.append(toolsGrid);
 const menuDialog=dialog('Explore FokoLab'),menuBody=el('div','foko-mobile-links');menuBody.append(a('Home','index.html'),a('Saved experiments','experiments.html'));for(const g of I.groups){const section=el('details','foko-mobile-section');section.append(el('summary','foko-mobile-group',g[0]));section.append(a('Explore '+g[0].toLowerCase(),g[1]));for(const t of [...I.tools,...I.resources].filter(t=>g.slice(2).includes(t[3])))section.append(a(t[0],t[1]));menuBody.append(section);}menuDialog.append(menuBody);
 // Store only known workspace routes; no query strings, input data or personal information.
 try{if(I.tools.some(t=>t[1]===path)){const old=JSON.parse(localStorage.getItem('fokolab:recent-tools')||'[]');localStorage.setItem('fokolab:recent-tools',JSON.stringify([path,...(Array.isArray(old)?old:[]).filter(p=>p!==path&&I.tools.some(t=>t[1]===p))].slice(0,4)));}const host=doc.getElementById('foko-recent');if(host){const rec=JSON.parse(localStorage.getItem('fokolab:recent-tools')||'[]');const rows=Array.isArray(rec)?rec.map(p=>I.tools.find(t=>t[1]===p)).filter(Boolean):[];if(rows.length){host.hidden=false;for(const t of rows)host.querySelector('nav').append(a(t[0],t[1]));}}}catch(_){}
 const searchDialog=dialog('Find a model, method or workspace'),labelNode=el('label','','Search FokoLab'),query=el('input'),status=el('p','foko-dialog-status'),results=el('div','foko-search-results'),more=button('Show more results',()=>{limit+=20;renderSearch();});query.type='search';query.id='foko-search-input';query.placeholder='Try C4, cyton, Gillespie, Sobol…';query.autocomplete='off';labelNode.htmlFor=query.id;status.setAttribute('role','status');searchDialog.append(labelNode,query,status,results,more);let catalog=[],loaded=false,limit=20;
 async function openSearch(){show(searchDialog);if(!loaded){try{if(!root.FokoScientificExampleCatalog){await load('src/models/scientific-example-catalog.js');}if(!root.FokoDynamicsCatalog)await load('src/integration/catalog.js');catalog=root.FokoScientificExampleCatalog||[];loaded=true;}catch(e){status.textContent='Some examples could not load. Workspaces remain searchable.';}}renderSearch();}
 function load(path){return new Promise((resolve,reject)=>{const s=el('script');s.src=route(path);s.onload=resolve;s.onerror=reject;doc.head.append(s);});}
 function renderSearch(){const q=query.value.trim().toLowerCase(),terms=q.split(/\s+/).filter(Boolean);const all=[...I.tools,...I.resources].map(t=>({title:t[0],href:t[1],summary:t[2],lab:t[3]})).concat(catalog);const unique=all.filter((x,i)=>all.findIndex(y=>y.href===x.href&&y.title===x.title)===i);const matches=unique.filter(x=>terms.every(w=>(x.title+' '+x.lab+' '+x.summary+' '+(x.family||'')).toLowerCase().includes(w)));results.replaceChildren();for(const x of matches.slice(0,limit)){const n=a('',x.href);n.append(el('b','',x.title),el('small','',x.lab+' · '+x.summary));results.append(n);}status.textContent=matches.length+' matches'+(matches.length>limit?' · showing '+limit:'');more.hidden=matches.length<=limit;}
 query.oninput=()=>{limit=20;renderSearch();};
 root.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();e.stopImmediatePropagation();openSearch();}},true);
 doc.querySelectorAll('[data-foko-search]').forEach(b=>b.addEventListener('click',openSearch));
 root.FokoShell={route,el,button,dialog,show,base:base.href,openSearch};root.dispatchEvent(new Event('foko:integrated-ready'));
}
if(doc.readyState==='loading')doc.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})(globalThis);
