/* Deterministic, finite toy models. No biological calibration is implied. */
(function(root){
'use strict';
const LIMIT=200000, TAU=Math.PI*2;
const directions=Array.from({length:6},(_,i)=>({x:Math.cos(-Math.PI/2+i*TAU/6),y:Math.sin(-Math.PI/2+i*TAU/6)}));
function rng(seed){let a=seed>>>0;return()=>{a=(a+0x6D2B79F5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296;};}
function validate(c){if(!['tree','colony','chaos','walk','brownian','branching','birthdeath'].includes(c.mode))throw Error('Choose a growth model.');if(!Number.isInteger(c.n)||c.n<1||c.n>10000||!Number.isInteger(c.m)||c.m<1||c.m>2000)throw Error('Use n = 1–10,000 and m = 1–2,000, as whole numbers.');if(c.n*c.m>LIMIT)throw Error('Use at most 200,000 initial tosses per panel: reduce n or m.');if(!Array.isArray(c.weights)||c.weights.length<1||c.weights.length>12||c.weights.some(w=>!Number.isFinite(w)||w<0)||!Number.isFinite(c.weights.reduce((a,b)=>a+b,0))||c.weights.reduce((a,b)=>a+b,0)<=0)throw Error('At least one dice weight must be greater than zero.');if(!Number.isFinite(c.memory)||c.memory<0||c.memory>1)throw Error('Memory must be between 0 and 100%.');if(!Number.isInteger(c.seed)||c.seed<0||c.seed>4294967295)throw Error('Seed must be an integer from 0 to 4,294,967,295.');if(!['long','compact'].includes(c.geometry)||!['triangle','hexagon'].includes(c.shape))throw Error('Choose a valid geometry.');if(c.mode==='colony'&&(!Number.isFinite(c.energy)||c.energy<10||c.energy>10000))throw Error('Colony energy must be between 10 and 10,000.');return c;}
function sampler(c,random){const total=c.weights.reduce((a,b)=>a+b,0);return previous=>{const memoryDraw=random(),faceDraw=random()*total;if(previous&&memoryDraw<c.memory)return previous;let sum=0;for(let i=0;i<c.weights.length;i++){sum+=c.weights[i];if(faceDraw<sum)return i+1;}return c.weights.length;};}
function segmentHitsBox(x,y,x2,y2,b){let lo=0,hi=1;for(const [start,delta,min,max] of [[x,x2-x,b.x,b.x+b.w],[y,y2-y,b.y,b.y+b.h]]){if(Math.abs(delta)<1e-12){if(start<min||start>max)return false;}else{let a=(min-start)/delta,z=(max-start)/delta;if(a>z)[a,z]=[z,a];lo=Math.max(lo,a);hi=Math.min(hi,z);if(lo>hi)return false;}}return true;}
function simulate(input){const c=validate({distShape:2,distScale:1,distBeta:5,distRate:1,distDf:5,...input,weights:[...input.weights]});if(['walk','brownian','branching','birthdeath'].includes(c.mode))return temporal(c);const random=rng(c.seed),sample=sampler(c,random);const model={config:c,edges:[],frames:Array.from({length:c.n},()=>[]),decisions:Array(c.n).fill(0),traces:Array.from({length:c.m},()=>[]),bounds:{minX:0,maxX:0,minY:0,maxY:0},faceCounts:Array(c.weights.length).fill(0),totalDecisions:0,blocked:0,energyUsed:0,truncated:false,status:'Complete',obstacles:[],resources:[],vertices:[]};
const {bounds}=model;function bound(x,y){bounds.minX=Math.min(bounds.minX,x);bounds.maxX=Math.max(bounds.maxX,x);bounds.minY=Math.min(bounds.minY,y);bounds.maxY=Math.max(bounds.maxY,y);}
function decision(step,run,previous){if(model.totalDecisions>=LIMIT){model.truncated=true;return null;}const face=sample(previous);model.totalDecisions++;model.decisions[step]++;model.faceCounts[face-1]++;model.traces[run].push({step,face});return face;}
function edge(x,y,x2,y2,face,step,run,keyMap,key){let id=keyMap?.get(key);if(id===undefined){id=model.edges.length;model.edges.push({id,x,y,x2,y2,face,first:step,count:0,run});if(keyMap)keyMap.set(key,id);bound(x2,y2);}model.edges[id].count++;model.frames[step].push({id,run,face});return id;}
if(c.mode==='tree'){
const shrink=c.geometry==='compact'?.32:(c.n===1?1:Math.pow(.05,1/(c.n-1))),trie={children:[]};model.shrink=shrink;
for(let run=0;run<c.m;run++){let parent=trie,x=0,y=0,len=1,last=0;for(let step=0;step<c.n;step++){const face=decision(step,run,last),angle=c.weights.length===2?(parent.angle??-Math.PI/2)+(face-1.5)*1.1:-Math.PI/2+(face-1)*TAU/c.weights.length,v={x:Math.cos(angle),y:Math.sin(angle)};let node=parent.children[face-1];if(!node){node={children:[],angle,id:edge(x,y,x+len*v.x,y+len*v.y,face,step,run)};parent.children[face-1]=node;}else{model.edges[node.id].count++;model.frames[step].push({id:node.id,run,face});}const e=model.edges[node.id];x=e.x2;y=e.y2;len*=shrink;last=face;parent=node;}}
}else if(c.mode==='chaos'){
const count=c.shape==='triangle'?3:6,ratio=c.shape==='triangle'?.5:1/3;model.contraction=ratio;model.vertices=Array.from({length:count},(_,i)=>({x:Math.cos(-Math.PI/2+i*TAU/count),y:Math.sin(-Math.PI/2+i*TAU/count)}));for(const v of model.vertices)bound(v.x,v.y);
for(let run=0;run<c.m;run++){let x=0,y=0,last=0;for(let step=0;step<c.n;step++){const face=decision(step,run,last),v=model.vertices[c.shape==='triangle'?Math.floor((face-1)/2):face-1],x2=ratio*x+(1-ratio)*v.x,y2=ratio*y+(1-ratio)*v.y;edge(x,y,x2,y2,face,step,run);x=x2;y=y2;last=face;}}
}else{
if(c.obstacles)model.obstacles=[{x:-65,y:-155,w:105,h:25},{x:70,y:-285,w:28,h:145},{x:-170,y:-310,w:70,h:25}];
if(c.resources)model.resources=[{x:-180,y:-220,r:70},{x:170,y:-380,r:85},{x:-30,y:-540,r:90}];
for(const b of model.obstacles){bound(b.x,b.y);bound(b.x+b.w,b.y+b.h);}for(const r of model.resources){bound(r.x-r.r,r.y-r.r);bound(r.x+r.r,r.y+r.r);}
const shared=new Map();let aliveAtEnd=0;
for(let run=0;run<c.m;run++){let tips=[{x:0,y:0,angle:-Math.PI/2,last:0}],energy=c.energy;const patches=model.resources.map(p=>({...p,left:25}));let step=0;
for(;step<c.n&&tips.length&&energy>=.2&&!model.truncated;step++){const next=[];for(const tip of tips){if(energy<.2||model.truncated)break;const face=decision(step,run,tip.last);if(face===null)break;const fee=Math.min(.2,energy);energy-=fee;model.energyUsed+=fee;if(face===6)continue;if(face===5){next.push({...tip,last:face});continue;}
const turns=face===4?[-.55,.55]:[face===2?-.55:face===3?.55:0];for(const turn of turns){if(energy<.8)break;let angle=tip.angle+turn;if(c.resources&&patches.length){let target=null,best=Infinity;for(const p of patches)if(p.left>0){const distance=Math.hypot(p.x-tip.x,p.y-tip.y);if(distance<best){target=p;best=distance;}}if(target){const goal=Math.atan2(target.y-tip.y,target.x-tip.x),difference=Math.atan2(Math.sin(goal-angle),Math.cos(goal-angle));angle+=Math.max(-.22,Math.min(.22,difference));}}
const x2=tip.x+14*Math.cos(angle),y2=tip.y+14*Math.sin(angle);energy-=.8;model.energyUsed+=.8;if(model.obstacles.some(b=>segmentHitsBox(tip.x,tip.y,x2,y2,b))){model.blocked++;continue;}
const key=[tip.x,tip.y,x2,y2].map(v=>v.toFixed(6)).join(',');edge(tip.x,tip.y,x2,y2,face,step,run,shared,key);for(const p of patches)if(p.left>0&&Math.hypot(x2-p.x,y2-p.y)<p.r){const gain=Math.min(2,p.left);energy+=gain;p.left-=gain;}next.push({x:x2,y:y2,angle,last:face});}}
tips=next;}
if(tips.length&&energy>=.2)aliveAtEnd+=tips.length;
if(model.truncated)break;}
model.status=model.truncated?'Stopped at the 200,000-decision limit':aliveAtEnd?'Step limit reached':'All tips stopped or exhausted their energy';
}
model.limitReached=model.truncated;model.steps=Math.max(1,model.decisions.reduce((last,v,i)=>v?i+1:last,0));return model;}

function temporal(c){
const random=rng(c.seed),uniform=()=>random()+.5/4294967296,normal=()=>Math.sqrt(-2*Math.log(uniform()))*Math.cos(TAU*uniform()),sample=sampler(c,random);
const number=(name,min,max)=>{if(!Number.isFinite(c[name])||c[name]<min||c[name]>max)throw Error(name+' must be between '+min+' and '+max+'.');};
if(c.mode==='walk'){if(!['discrete','normal','uniform','laplace','triangular','exponential','gamma','lognormal','beta','weibull','student'].includes(c.incrementLaw))throw Error('Choose an increment distribution.');if(c.incrementLaw==='discrete'&&(!Array.isArray(c.values)||c.values.length!==c.weights.length||c.values.some(x=>!Number.isFinite(x)||Math.abs(x)>1000000)))throw Error('Each outcome needs a finite numeric value.');if(['normal','laplace','triangular'].includes(c.incrementLaw)){number('drift',-100,100);number('sigma',0,100);}if(c.incrementLaw==='lognormal'){number('drift',-10,10);number('sigma',0,3);}if(c.incrementLaw==='student'){number('drift',-100,100);number('sigma',0,100);number('distDf',1,100);}if(c.incrementLaw==='exponential')number('distRate',.01,100);if(['gamma','beta','weibull'].includes(c.incrementLaw))number('distShape',.3,50);if(['gamma','weibull'].includes(c.incrementLaw))number('distScale',.01,20);if(c.incrementLaw==='beta')number('distBeta',.3,50);if(c.incrementLaw==='uniform'){number('lower',-100,100);number('upper',-100,100);if(c.upper<c.lower)throw Error('Uniform upper bound must be at least the lower bound.');}}
if(c.mode==='brownian'){number('drift',-100,100);number('sigma',0,100);number('dt',.0001,10);}
if(c.mode==='branching'){number('initial',0,10000);if(!Number.isInteger(c.initial))throw Error('Initial population must be a whole number.');if(!['poisson','binomial','geometric','custom'].includes(c.offspringLaw))throw Error('Choose an offspring distribution.');number('lambda',0,20);number('offspringP',.01,1);number('trials',1,100);if(!Number.isInteger(c.trials))throw Error('Binomial trials must be a whole number.');if(c.offspringLaw==='custom'&&(!c.values||c.values.length!==c.weights.length||c.values.some(x=>!Number.isInteger(x)||x<0||x>1000)))throw Error('Custom offspring counts must be integers from 0 to 1,000.');}
if(c.mode==='birthdeath'){number('initial',0,10000);if(!Number.isInteger(c.initial))throw Error('Initial population must be a whole number.');number('birthRate',0,100);number('deathRate',0,100);number('immigration',0,100);number('horizon',.001,10000);}
const model={config:c,edges:[],frames:Array.from({length:c.n},()=>[]),decisions:Array(c.n).fill(0),traces:Array.from({length:c.m},()=>[]),bounds:{minX:0,maxX:c.mode==='brownian'?c.n*c.dt:c.mode==='birthdeath'?c.horizon:c.n,minY:0,maxY:1},faceCounts:Array(c.mode==='birthdeath'?3:c.weights.length).fill(0),totalDecisions:0,blocked:0,energyUsed:0,truncated:false,status:'Complete',obstacles:[],resources:[],vertices:[],chart:true,axisX:c.mode==='birthdeath'||c.mode==='brownian'?'Time':'Step',axisY:c.mode==='branching'||c.mode==='birthdeath'?'Population':'Position',eventTimes:true};
function decision(step,run,value,category){if(model.totalDecisions>=LIMIT){model.truncated=true;return false;}model.totalDecisions++;model.decisions[step]++;if(category)model.faceCounts[category-1]++;model.traces[run].push({step,face:value});return true;}
function segment(x,y,x2,y2,step,run){const id=model.edges.length;model.edges.push({id,x,y,x2,y2,first:step,face:0,count:1,run});model.frames[step].push({id,run,face:0});model.bounds.minY=Math.min(model.bounds.minY,y,y2);model.bounds.maxY=Math.max(model.bounds.maxY,y,y2);}
const poisson=mean=>{if(mean===0)return 0;let product=1,k=0,limit=Math.exp(-mean);do{k++;product*=uniform();}while(product>limit);return k-1;};
// Marsaglia–Tsang rejection sampler; shape < 1 uses the gamma augmentation identity.
const gamma=k=>{if(k<1)return gamma(k+1)*Math.pow(uniform(),1/k);const d=k-1/3,a=1/Math.sqrt(9*d);for(;;){const z=normal(),v0=1+a*z;if(v0<=0)continue;const v=v0*v0*v0,u=uniform();if(u<1-.0331*z*z*z*z||Math.log(u)<.5*z*z+d*(1-v+Math.log(v)))return d*v;}};
const offspring=()=>{if(c.offspringLaw==='poisson')return poisson(c.lambda);if(c.offspringLaw==='binomial'){let n=0;for(let i=0;i<c.trials;i++)if(random()<c.offspringP)n++;return n;}if(c.offspringLaw==='geometric')return c.offspringP===1?0:Math.floor(Math.log(uniform())/Math.log(1-c.offspringP));return c.values[sample(0)-1];};
let cappedRuns=0,extinct=0,populationCap=false;
for(let run=0;run<c.m&&!model.truncated;run++){
if(c.mode==='walk'||c.mode==='brownian'){let y=0,last=0;for(let step=0;step<c.n;step++){let increment,category=0;if(c.mode==='brownian')increment=c.drift*c.dt+c.sigma*Math.sqrt(c.dt)*normal();else if(c.incrementLaw==='normal')increment=c.drift+c.sigma*normal();else if(c.incrementLaw==='laplace'){const u=uniform()-.5;increment=c.drift-c.sigma/Math.sqrt(2)*Math.sign(u)*Math.log1p(-2*Math.abs(u));}else if(c.incrementLaw==='triangular')increment=c.drift+c.sigma*Math.sqrt(6)*(uniform()-uniform());else if(c.incrementLaw==='exponential')increment=-Math.log(uniform())/c.distRate;else if(c.incrementLaw==='gamma')increment=c.distScale*gamma(c.distShape);else if(c.incrementLaw==='lognormal')increment=Math.exp(c.drift+c.sigma*normal());else if(c.incrementLaw==='beta'){const a=gamma(c.distShape),b=gamma(c.distBeta);increment=a/(a+b);}else if(c.incrementLaw==='weibull')increment=c.distScale*Math.pow(-Math.log(uniform()),1/c.distShape);else if(c.incrementLaw==='student')increment=c.drift+c.sigma*normal()/Math.sqrt(2*gamma(c.distDf/2)/c.distDf);else if(c.incrementLaw==='uniform')increment=c.lower+(c.upper-c.lower)*random();else{category=sample(last);last=category;increment=c.values[category-1];}if(!decision(step,run,Number(increment.toPrecision(4)),category))break;const dt=c.mode==='brownian'?c.dt:1;segment(step*dt,y,(step+1)*dt,y+increment,step,run);y+=increment;}}
else if(c.mode==='branching'){let population=c.initial;if(population===0)extinct++;for(let step=0;step<c.n;step++){let next=0;if(population===0){segment(step,0,c.n,0,step,run);break;}for(let individual=0;individual<population;individual++){const count=offspring();if(!decision(step,run,count,0))break;next+=count;if(next>1000000){populationCap=true;break;}}if(model.truncated||populationCap)break;segment(step,population,step+1,next,step,run);population=next;if(population===0){extinct++;if(step+1<c.n)segment(step+1,0,c.n,0,step,run);break;}}}
else {let t=0,population=c.initial,events=0;for(;events<c.n;events++){const birth=c.birthRate*population,death=c.deathRate*population,total=birth+death+c.immigration;if(total===0){segment(t,population,c.horizon,population,events,run);break;}const nextTime=t-Math.log(uniform())/total;if(nextTime>c.horizon){segment(t,population,c.horizon,population,events,run);break;}const choice=random()*total,category=choice<birth?1:choice<birth+death?2:3,next=population+(category===2?-1:1);if(next>1000000){populationCap=true;break;}if(!decision(events,run,['birth','death','immigration'][category-1],category))break;segment(t,population,nextTime,population,events,run);segment(nextTime,population,nextTime,next,events,run);t=nextTime;population=next;if(population===0&&c.immigration===0){segment(t,0,c.horizon,0,events,run);extinct++;break;}}if(events===c.n)cappedRuns++;}
if(populationCap)break;
}
model.steps=Math.max(1,model.frames.reduce((last,v,i)=>v.length||model.decisions[i]?i+1:last,0));
model.limitReached=model.truncated||populationCap||cappedRuns>0;model.status=model.truncated?'Stopped at the 200,000-sample limit':populationCap?'Stopped at the population safety limit (1,000,000)':c.mode==='birthdeath'?(cappedRuns?cappedRuns+' runs reached the event cap before the time horizon':'Time horizon or absorbing state reached'):c.mode==='branching'?extinct+' / '+c.m+' populations became extinct':'Complete';
return model;
}
const api={simulate,validate,rng,segmentHitsBox,LIMIT};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.FractalEngine=api;
})(typeof window==='undefined'?globalThis:window);
