/* Portable completed-experiment records. No model execution or storage side effects. */
(function(root){'use strict';
const schema='dynamics.experiment/1',release='36',routes={plants:'/plants/index.html',tcells:'/tcells/index.html',lipids:'/lipids/index.html',leaf:'/leaf/index.html',evolution:'/continuum/advanced.html',search:'/continuum/approaches.html',haploid:'/continuum/index.html',random:'/random.html'};
const names={plants:'Plant growth',tcells:'T cells',lipids:'Fatty acids & lipids',leaf:'Leaf physiology',evolution:'Kimura evolution',search:'Population evolution & search',haploid:'Haploid evolution',random:'Random processes'};
function stringify(value,space=0){return JSON.stringify(value,(_,v)=>typeof v==='number'&&!Number.isFinite(v)?{$nonfinite:String(v)}:v,space);}
function parse(text){return JSON.parse(text,(k,v)=>{if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe object key in experiment file.');if(v&&typeof v==='object'&&Object.keys(v).length===1&&'$nonfinite' in v){if(!['NaN','Infinity','-Infinity'].includes(v.$nonfinite))throw Error('Invalid numeric marker.');return Number(v.$nonfinite);}return v;});}
const clone=x=>parse(stringify(x));
function id(){return typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():'run-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);}
function series(result,lab){const out=[];const add=(key,label,unit,xLabel,xUnit,statistic,rows,x,y,interpolation='linear')=>{const points=rows.map((r,i)=>[Number(x(r,i)),Number.isFinite(y(r,i))?y(r,i):null]);if(points.length)out.push({key,label,unit,xLabel,xUnit,statistic,interpolation,points});};
if(lab==='plants'){for(const [type,rows]of Object.entries(result.series))for(const [key,label,unit]of [['biomass','Structural dry mass','g'],['fruit','Fruit / seed tissue','g dry mass'],['netCarbon','Net carbon','g C'],['trans','Cumulative transpiration','L'],['water','Soil water','mm'],['soilN','Soil nitrogen','mg N'],['leafT','Leaf temperature','degC']])add('plants.'+type+'.'+key,type+' · '+label,unit,'Elapsed time','h','first weather realization',rows,r=>r.hour,r=>r[key]);}
else if(lab==='tcells'){const xu=result.config.model==='kimmel'?'cycle':'h';add('tcells.living.mean','Living cells · ensemble mean','cells','Elapsed time',xu,'ensemble mean',result.summary,(_,i)=>result.times[i],r=>r.mean);add('tcells.living.reference','Living cells · reference expectation','cells','Elapsed time',xu,'reference expectation',result.theory,(_,i)=>result.times[i],r=>r.totalMean);add('tcells.living.variance','Population variance','cells^2','Elapsed time',xu,'ensemble sample variance',result.summary,(_,i)=>result.times[i],r=>r.variance);}
else if(lab==='lipids'){result.species.forEach((name,j)=>add('lipids.'+result.model+'.'+name,name,result.model==='synthesis'?'uM':'arbitrary pool','Elapsed time',result.model==='synthesis'?'s':'arbitrary time','deterministic trajectory',result.rows,(_,i)=>result.times[i],r=>r[j]));}
else if(lab==='leaf'){add('leaf.assimilation','Net assimilation','umol m^-2 s^-1','Air temperature','degC','fixed-trait response',result.response,r=>r.airC,r=>r.valid?r.carbon.assimilation:null);add('leaf.transpiration','Transpiration','mol m^-2 s^-1','Air temperature','degC','fixed-trait response',result.response,r=>r.airC,r=>r.valid?r.physics.E:null);}
else if(lab==='evolution'){result.replicates.forEach((rep,j)=>{for(const [key,label,unit]of [['carbon','Integrated carbon','mol m^-2 / forcing cycle'],['water','Integrated water','mol m^-2 / forcing cycle'],['heat','Heat exposure','K h / forcing cycle'],['logFitness','Log-performance','dimensionless']]){const rows=rep.events.map(e=>({...e,p:result.nodes[e.node]}));if(rep.observedUntil>rows.at(-1).time)rows.push({...rows.at(-1),time:rep.observedUntil});add('kimura.'+j+'.'+key,'Replicate '+(j+1)+' · '+label,unit,'Biological time','generation','resident state',rows,r=>r.time,r=>r.p[key],'step');}});}
else if(lab==='search'){if(result.config.method==='evolution')result.replicates.forEach((rep,j)=>{['PEPC','Mesophyll','Sheath'].forEach((name,k)=>add('population.'+j+'.'+k,'Replicate '+(j+1)+' · '+name,'fraction','Generation','generation','population mean',rep.history,r=>r.generation,r=>r.meanFractions[k]));});else for(const [k,unit]of [['carbon','mol m^-2 / forcing cycle'],['water','mol m^-2 / forcing cycle'],['heat','K h / forcing cycle']])add('search.'+k,'Evaluated '+k,unit,'Candidate index','index','evaluated candidate',result.samples,(_,i)=>i,r=>r.feasible?r[k]:null,'points');}
else if(lab==='haploid'){['PEPC','Mesophyll','Sheath'].forEach((name,k)=>add('haploid.'+k,name,'fraction','Generation','generation','population mean',result.history,r=>r.generation,r=>r.fractions[k]));}
else if(lab==='random'){result.models.forEach((m,j)=>{if(m.chart){const byRun=new Map();for(const e of m.edges){if(!byRun.has(e.run))byRun.set(e.run,[]);const rows=byRun.get(e.run);if(!rows.length)rows.push({x:e.x,y:e.y});rows.push({x:e.x2,y:e.y2});}for(const [run,rows]of byRun)add('random.'+m.config.mode+'.'+j+'.'+run,(j?'Control':'Experiment')+' · realization '+(run+1),m.axisY==='Population'?'individuals':'position unit',m.axisX,m.axisX==='Time'?'model time':'step','individual realization',rows,r=>r.x,r=>r.y,m.config.mode==='birthdeath'?'step':'linear');}else add('random.outcomes.'+j,(j?'Control':'Experiment')+' · outcome counts','draws','Outcome','category','outcome counts',m.faceCounts,(_,i)=>i+1,r=>r,'points');});}
for(const c of out)if(c.unit.includes('/ forcing cycle')){const forcing=result.config?.base?.forcing||result.config?.forcing;const hours=forcing?.reduce((n,r)=>n+r.hours,0);if(Number.isFinite(hours))c.unit=c.unit.replace('/ forcing cycle','/ '+hours+' h forcing cycle');}return out;}
function create(lab,result,title='',metadata={}){if(!routes[lab])throw Error('Unsupported laboratory.');const r=clone(result),configuration=clone(lab==='random'?r.models.map(m=>m.config):r.config),record={schema,id:id(),revision:0,createdAt:new Date().toISOString(),title:title.trim().slice(0,160)||names[lab]+' · '+new Date().toLocaleString(),lab,model:{id:lab==='random'?r.models[0].config.mode:r.config?.model||r.config?.method||lab,appRelease:release,engineHashes:clone(root.ResearchEngineHashes?.[lab]||{}),solver:r.solver||r.specification?.solver||'See laboratory model documentation'},source:{route:routes[lab],execution:'browser',evidence:'Numerical checks and limitations are documented separately; this record is not empirical validation.'},configuration,result:r,curves:series(r,lab),notes:'',...metadata};return validate(record);}
function validate(r){if(!r||r.schema!==schema||!routes[r.lab]||typeof r.id!=='string'||r.id.length>150||typeof r.title!=='string'||r.title.length>160||!r.configuration||!r.result||!r.model||!Array.isArray(r.curves)||r.curves.length>5000)throw Error('Invalid or unsupported experiment record.');if(r.lab==='random'&&(!Array.isArray(r.result.models)||r.result.models.length<1||r.result.models.length>2))throw Error('Random-process records support one experiment and one control.');if(!Number.isFinite(Date.parse(r.createdAt)))throw Error('Invalid experiment date.');if(typeof r.model.id!=='string'||!r.model.engineHashes||typeof r.model.engineHashes!=='object')throw Error('Missing model identity or engine fingerprints.');if(r.observations){for(const [key,data] of Object.entries(r.observations)){if(!data||typeof data.source!=='string'||!Array.isArray(data.rows)||data.rows.length>20000)throw Error('Invalid observation metadata.');const c=r.curves.find(c=>signature(c)===key);if(!c||data.units?.x!==c.xUnit||data.units?.y!==c.unit)throw Error('Observation units do not match the selected observable.');for(const o of data.rows)if(!Number.isFinite(o.x)||!Number.isFinite(o.y)||(o.sd!==null&&o.sd!==undefined&&(!Number.isFinite(o.sd)||o.sd<0)))throw Error('Invalid observation values.');}}for(const c of r.curves){if(!c||!['linear','step','points'].includes(c.interpolation)||['key','label','unit','xLabel','xUnit','statistic'].some(k=>typeof c[k]!=='string'||c[k].length>250)||!Array.isArray(c.points)||c.points.length>250000)throw Error('Invalid curve metadata.');let last=-Infinity;for(const p of c.points){if(!Array.isArray(p)||p.length!==2||!Number.isFinite(p[0])||(p[1]!==null&&!Number.isFinite(p[1]))||p[0]<last)throw Error('Curve coordinates must be finite, ordered pairs; missing y values use null.');last=p[0];}}return r;}
function signature(c){return[c.key,c.unit,c.xLabel,c.xUnit,c.statistic].join('|');}
function compatible(a,b){return signature(a)===signature(b);}
function differences(a,b,path=''){const out=[];if(Object.is(a,b))return out;if(a&&b&&typeof a==='object'&&typeof b==='object'){for(const k of new Set([...Object.keys(a),...Object.keys(b)]))out.push(...differences(a[k],b[k],path?path+'.'+k:k));}else out.push({path,before:a,after:b});return out;}
function sample(c,x){const p=c.points;if(!p.length||x<p[0][0]||x>p.at(-1)[0])return null;let lo=0,hi=p.length-1;while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(p[mid][0]<=x)lo=mid;else hi=mid-1;}const a=p[lo];if(a[1]===null)return null;if(a[0]===x||c.interpolation==='step'||lo===p.length-1)return a[1];if(c.interpolation==='points')return null;const b=p[lo+1];return b[1]===null?null:a[1]+(b[1]-a[1])*(x-a[0])/(b[0]-a[0]);}
function residuals(curve,observations){const rows=observations.map(o=>({x:o.x,observed:o.y,predicted:sample(curve,o.x),sd:o.sd??null}));const included=rows.filter(r=>r.predicted!==null);return{rows,matched:included.length,excluded:rows.length-included.length,rmse:included.length?Math.sqrt(included.reduce((s,r)=>s+(r.observed-r.predicted)**2,0)/included.length):null,interpretation:'Descriptive residuals only. No parameters were fitted; no unit conversion or extrapolation was performed.'};}
function csv(text){if(text.length>2000000)throw Error('Observation file exceeds 2 MB.');const lines=[],row=[];let cell='',quoted=false;for(let i=0;i<=text.length;i++){const ch=text[i]??'\n';if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&(ch===','||ch==='\n'||ch==='\r')){row.push(cell.trim());cell='';if(ch!==','){if(row.some(v=>v!==''))lines.push(row.splice(0));else row.length=0;if(ch==='\r'&&text[i+1]==='\n')i++;}}else cell+=ch;}if(quoted)throw Error('Unclosed CSV quotation.');const header=lines.shift()||[],ix=header.indexOf('x'),iy=header.indexOf('y'),isd=header.indexOf('sd');if(ix<0||iy<0)throw Error('CSV needs x,y columns; optional sd is measurement standard deviation.');if(!lines.length||lines.length>20000)throw Error('Provide 1–20,000 observations.');return lines.map((r,i)=>{const x=r[ix]===''?NaN:Number(r[ix]),y=r[iy]===''?NaN:Number(r[iy]),sd=isd<0||r[isd]===''?null:Number(r[isd]);if(!Number.isFinite(x)||!Number.isFinite(y)||(sd!==null&&(!Number.isFinite(sd)||sd<0)))throw Error('Invalid number in observation row '+(i+2));return{x,y,sd};});}
const api={schema,release,routes,names,stringify,parse,clone,id,series,create,validate,signature,compatible,differences,sample,residuals,csv};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ResearchRecords=api;
})(globalThis);
