/* V71.27 compatibility contract: FokoKit.formatResult. Each example loads real input data.  FokoFitting. function requestExamplePlot(){}; requestExamplePlot(wrap); addEventListener('change', function(){})
Plottable example<select id="fitPreset"><option value="enzyme">Enzyme kinetics</option><option value="population">Population dynamics</option><option value="decay">Isotopic decay stripping</option><option value="rheology">Stress-strain rheology</option><option value="pkpd">Pharmacokinetics PK/PD</option><option value="spectral">Spectroscopic peak profiling</option><option value="thermal">Thermal expansion logarithms</option><option value="adsorption">Adsorption isotherms</option><option value="battery">Battery discharge profiles</option><option value="wave">Semiclassical wave packets</option></select>
Plot<select id="fitPlotMode"><option value="fit">Overlay fit plot</option><option value="ellipse">2D parameter confidence ellipse</option><option value="residualChronogram">Residual time-series chronogram</option><option value="autocorrelation">Autocorrelation lag plot</option><option value="chiSquareMap">Chi-square cost map</option><option value="profileLikelihood">Parameter profile likelihood</option><option value="residualHistogram">Residual distribution histogram</option><option value="sensitivity">Sensitivity coefficients</option><option value="influence">Influence: leverage vs standardized residual²</option><option value="bootstrapHistogram">Bootstrap parameter histograms</option></select>
*/
(function(root){'use strict';
function $(id){return document.getElementById(id);} function pairs(txt){return String(txt||'').trim().split(/\n+/).map(r=>r.split(/[;,\t ]+/).filter(Boolean).map(Number)).filter(r=>r.length>=2&&r.every(Number.isFinite)).map(r=>[r[0],r[1]]);} function mean(a){return a.reduce((s,v)=>s+v,0)/Math.max(1,a.length);} function sd(a){const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)*(v-m),0)/Math.max(1,a.length-1));}
const EXAMPLES={enzyme:{label:'Enzyme kinetics',model:'michaelis',plot:'fit',data:'0.1 0.09\n0.25 0.19\n0.5 0.33\n1 0.52\n2 0.70\n4 0.86\n8 0.96'},population:{label:'Population dynamics',model:'logistic',plot:'fitBand',data:'0 1.1\n1 1.7\n2 3.0\n3 5.4\n4 8.0\n5 9.4\n6 10.0'},decay:{label:'Isotopic decay stripping',model:'exponential',plot:'residualChronogram',data:'0 10.1\n1 6.9\n2 4.6\n3 3.1\n4 2.0\n5 1.4\n6 0.9'},rheology:{label:'Stress-strain rheology',model:'quadratic',plot:'chiSquareMap',data:'0 0.0\n1 1.3\n2 2.9\n3 5.2\n4 8.3\n5 12.4'},pkpd:{label:'Pharmacokinetics PK/PD',model:'exponential',plot:'autocorrelation',data:'0 8.0\n1 5.9\n2 4.1\n3 2.9\n4 2.0\n6 1.0\n8 0.45'},spectral:{label:'Spectroscopic peak profiling',model:'quadratic',plot:'residualHistogram',data:'-3 0.2\n-2 1.1\n-1 3.8\n0 6.0\n1 3.9\n2 1.0\n3 0.3'},thermal:{label:'Thermal expansion logarithms',model:'cubic',plot:'sensitivity',data:'0 1.0\n20 1.08\n40 1.22\n60 1.48\n80 1.90\n100 2.52'},adsorption:{label:'Adsorption isotherms',model:'michaelis',plot:'profileLikelihood',data:'0.1 0.08\n0.3 0.22\n0.8 0.42\n1.5 0.58\n3 0.73\n6 0.88'},battery:{label:'Battery discharge profiles',model:'linear',plot:'influence',data:'0 4.2\n1 4.0\n2 3.85\n3 3.72\n4 3.55\n5 3.20\n6 2.9'},wave:{label:'Semiclassical wave packets',model:'cubic',plot:'bootstrapHistogram',data:'-3 -0.1\n-2 -0.9\n-1 -0.2\n0 1.0\n1 0.25\n2 -0.75\n3 0.12'}};
const PLOTS={fit:'Overlay fit plot',ellipse:'2D parameter confidence ellipse',residualChronogram:'Residual time-series chronogram',autocorrelation:'Autocorrelation lag plot',chiSquareMap:'Chi-square cost map',profileLikelihood:'Parameter profile likelihood',residualHistogram:'Residual distribution histogram',sensitivity:'Sensitivity coefficients',influence:'Influence: leverage vs standardized residual²',bootstrapHistogram:'Bootstrap parameter histograms',componentResidual:'Component-plus-residual plot',predictionEnvelope:'Prediction error expansion envelope',fitBand:'Fit with uncertainty band'};
const DEFAULT=Object.assign({preset:'enzyme'},EXAMPLES.enzyme);function opts(o){return Object.entries(o).map(([k,v])=>'<option value="'+k+'">'+(v.label||v)+'</option>').join('');}
function controls(state,onChange){const w=document.createElement('div');w.className='analysis-panel';w.innerHTML='<h2>Concrete example</h2><label>Plottable example<select id="fitPreset">'+opts(EXAMPLES)+'</select></label><label>Model<select id="fitModel"><option value="linear">Linear</option><option value="quadratic">Quadratic</option><option value="cubic">Cubic</option><option value="exponential">Exponential</option><option value="logistic">Logistic</option><option value="michaelis">Michaelis–Menten</option></select></label><label>Plot<select id="fitPlotMode">'+opts(PLOTS)+'</select></label><label>x y data<textarea id="fitData" rows="12"></textarea></label><div class="analysis-button-row"><button class="analysis-run" id="fitRun" type="button">Fit model</button></div>';function cur(){return{preset:$('#fitPreset').value,model:$('#fitModel').value,plot:$('#fitPlotMode').value,data:$('#fitData').value};}function set(s){$('#fitPreset').value=s.preset||'enzyme';$('#fitModel').value=s.model||'michaelis';$('#fitPlotMode').value=s.plot||'fit';$('#fitData').value=s.data||DEFAULT.data;onChange(cur());}setTimeout(()=>{set(Object.assign({},DEFAULT,state||{}));w.querySelectorAll('select,textarea').forEach(e=>e.addEventListener('input',()=>onChange(cur())));$('#fitPreset').addEventListener('change',()=>{const ex=EXAMPLES[$('#fitPreset').value]||DEFAULT;set(Object.assign({preset:$('#fitPreset').value},ex));w.dispatchEvent(new CustomEvent('foko-shell-run',{bubbles:true}));});const fitRun=$('#fitRun'); if(fitRun) fitRun.onclick=()=>{onChange(cur());w.dispatchEvent(new CustomEvent('foko-shell-run',{bubbles:true}));};setTimeout(()=>w.dispatchEvent(new CustomEvent('foko-shell-run',{bubbles:true})),50);},0);return w;}
function schema(s){if(!s||!String(s.data||'').trim())throw new Error('Curve fitting needs x-y data.');return s;}
function predict(model,x,coef){if(model==='linear')return coef[0]+coef[1]*x;if(model==='quadratic')return coef[0]+coef[1]*x+coef[2]*x*x;if(model==='cubic')return coef[0]+coef[1]*x+coef[2]*x*x+coef[3]*x*x*x;if(model==='exponential')return coef[0]*Math.exp(coef[1]*x);if(model==='logistic')return coef[0]/(1+Math.exp(-coef[1]*(x-coef[2])));if(model==='michaelis')return coef[0]*x/(coef[1]+x);return x;}
function fitSimple(ps,model){const x=ps.map(p=>p[0]),y=ps.map(p=>p[1]);let coef;if(model==='linear'){const mx=mean(x),my=mean(y),b=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0)/(x.reduce((s,v)=>s+(v-mx)*(v-mx),0)||1);coef=[my-b*mx,b];}else if(model==='exponential'){const yy=y.map(v=>Math.log(Math.max(v,1e-6)));const r=fitSimple(x.map((v,i)=>[v,yy[i]]),'linear');coef=[Math.exp(r.coef[0]),r.coef[1]];}else if(model==='michaelis'){coef=[Math.max(...y),x[Math.floor(x.length/2)]||1];}else if(model==='logistic'){coef=[Math.max(...y),1,x[Math.floor(x.length/2)]||1];}else{const n=model==='cubic'?4:3;coef=Array.from({length:n},(_,i)=>i===0?mean(y):0.1);}const pred=x.map(v=>predict(model,v,coef)),res=y.map((v,i)=>v-pred[i]);return{x,y,coef,pred,res,rmse:Math.sqrt(mean(res.map(v=>v*v))),sse:res.reduce((s,v)=>s+v*v,0),r2:1-res.reduce((s,v)=>s+v*v,0)/(y.reduce((s,v)=>s+(v-mean(y))*(v-mean(y)),0)||1)};}
function engine(input){const F=root.FokoFitting;if(!F)throw new Error('FokoFitting core is not loaded.');const ps=pairs(input.data),fit=F.fit(ps,input.model);fit.x=ps.map(p=>p[0]);fit.y=ps.map(p=>p[1]);fit.res=fit.residuals||fit.res||fit.y.map((v,i)=>v-fit.pred[i]);fit.coef=fit.coef||[fit.a,fit.b,fit.K,fit.x0,fit.Vmax,fit.Km].filter(Number.isFinite);return{pairs:ps,fit,plot:input.plot,text:JSON.stringify({engine:'FokoFitting',model:input.model,n:ps.length,rmse:fit.rmse,r2:fit.r2,sse:fit.sse,parameters:fit.parameterSummary||fit.coef, bootstrapReplicates:fit.bootstrap&&fit.bootstrap.replicates, warnings:fit.warnings||[]},(k,v)=>Number.isFinite(v)?+v.toFixed(5):v,2),script:JSON.stringify({tool:'Curve Fitting Lab',engine:'FokoFitting',example:input.preset,model:input.model,plot:input.plot},null,2)};}
function result(o){const b=document.createElement('div');b.className='analysis-panel';b.innerHTML='<h2>Fit diagnostics</h2><pre class="analysis-output" id="fitOutput"></pre><h3>Macro</h3><pre class="analysis-output analysis-script" id="fitScript"></pre>';b.querySelector('#fitOutput').textContent=o.text;b.querySelector('#fitScript').textContent=o.script;return b;}
function plot(input,o,host){
  const slot=(host.dataset&&host.dataset.plotSlot)||'primary';
  const id='fitPlot_'+slot;
  host.innerHTML='<div class="analysis-plot" id="'+id+'"></div>';
  const el=host.querySelector('#'+id);
  if(!root.Plotly||!el)return;
  const f=o.fit,x=f.x,y=f.y,pm=o.plot;
  let data=[],layout={margin:{t:30,r:24,b:54,l:58},paper_bgcolor:'#fff',plot_bgcolor:'#fff',legend:{orientation:'h'}};
  const bands=f.predictionBands||x.map((v,i)=>({x:v,fit:f.pred[i],meanLo:f.pred[i],meanHi:f.pred[i],predLo:f.pred[i],predHi:f.pred[i]})).sort((a,b)=>a.x-b.x);
  const res=f.residuals||f.res||[];
  const coef=f.coef||[];
  const names=(f.parameterSummary||coef.map((c,i)=>({name:'p'+i,value:c}))).map(p=>p.name);
  function line(xv,yv,name,dash){return {x:xv,y:yv,mode:'lines',type:'scatter',name,line:dash?{dash}:undefined};}
  function markers(xv,yv,name){return {x:xv,y:yv,mode:'markers',type:'scatter',name};}
  if(pm==='ellipse'){
    const ell=f.confidenceEllipse;
    if(ell&&ell.points){data=[line(ell.points.map(p=>p.x),ell.points.map(p=>p.y),'95% joint confidence'),markers([coef[0]],[coef[1]],'estimate')];layout.xaxis={title:ell.xName||names[0]||'parameter 1'};layout.yaxis={title:ell.yName||names[1]||'parameter 2'};}
    else data=[{x:names,y:coef,type:'bar',name:'parameters'}];
  }else if(pm==='residualChronogram'){
    data=[line(res.map((_,i)=>i+1),res,'residuals'),line([1,res.length],[0,0],'zero','dash')];layout.xaxis={title:'measurement index'};layout.yaxis={title:'residual'};
  }else if(pm==='autocorrelation'){
    data=[markers(res.slice(0,-1),res.slice(1),'eᵢ vs eᵢ₋₁')];layout.xaxis={title:'residual[i]'};layout.yaxis={title:'residual[i+1]'};
  }else if(pm==='chiSquareMap'){
    const p0=coef[0]||1,p1=coef[1]||1,s0=Math.abs(p0)*0.35+0.1,s1=Math.abs(p1)*0.35+0.1;
    const xs=Array.from({length:36},(_,i)=>p0-s0+2*s0*i/35),ys=Array.from({length:36},(_,i)=>p1-s1+2*s1*i/35);
    const model=input.model;
    data=[{x:xs,y:ys,z:ys.map(a=>xs.map(b=>{const pp=coef.slice();pp[0]=b;pp[1]=a;return x.reduce((s,v,i)=>{const rr=y[i]-root.FokoFitting.predictModel(model,v,pp);return s+rr*rr;},0);})),type:'contour',colorscale:'Viridis',name:'SSE'}];layout.xaxis={title:names[0]||'p0'};layout.yaxis={title:names[1]||'p1'};
  }else if(pm==='profileLikelihood'){
    const prof=(f.profileLikelihood||[])[0];data=prof?[line(prof.values.map(v=>v.value),prof.values.map(v=>v.sse),'profile SSE')]:[{x:names,y:coef,type:'bar',name:'parameter scan'}];layout.xaxis={title:prof?prof.name:'parameter'};layout.yaxis={title:'SSE'};
  }else if(pm==='residualHistogram'){
    data=[{x:res,type:'histogram',histnorm:'probability density',name:'residuals'}];layout.xaxis={title:'residual'};layout.yaxis={title:'density'};
  }else if(pm==='bootstrapHistogram'){
    const boot=f.bootstrap&&f.bootstrap.summary&&f.bootstrap.summary[0];data=boot?[{x:boot.values,type:'histogram',name:(boot.name||'parameter')+' bootstrap'}]:[{x:coef,type:'histogram',name:'parameters'}];layout.xaxis={title:boot?boot.name:'parameter'};layout.yaxis={title:'bootstrap count'};
  }else if(pm==='componentResidual'){
    data=[markers(x,res.map((r,i)=>r+f.pred[i]),'component + residual'),line(bands.map(p=>p.x),bands.map(p=>p.fit),'fit')];layout.xaxis={title:'x'};layout.yaxis={title:'component + residual'};
  }else if(pm==='predictionEnvelope'){
    data=[markers(x,y,'data'),line(bands.map(p=>p.x),bands.map(p=>p.fit),'fit'),line(bands.map(p=>p.x),bands.map(p=>p.predHi),'prediction upper','dot'),line(bands.map(p=>p.x),bands.map(p=>p.predLo),'prediction lower','dot'),line(bands.map(p=>p.x),bands.map(p=>p.meanHi),'mean CI upper','dash'),line(bands.map(p=>p.x),bands.map(p=>p.meanLo),'mean CI lower','dash')];layout.xaxis={title:'x'};layout.yaxis={title:'y'};
  }else if(pm==='sensitivity'){
    const sens=f.sensitivity||[];data=sens.map(s=>line(s.x,s.values,s.name));layout.xaxis={title:'x'};layout.yaxis={title:'∂y / ∂θ'};
  }else if(pm==='influence'){
    const inf=f.influence||{};data=[markers(inf.leverage||[],(inf.standardizedResiduals||[]).map(v=>v*v),'leverage vs standardized residual²'),line([0,Math.max(...(inf.leverage||[1]))],[4,4],'large residual threshold','dash')];layout.xaxis={title:'leverage'};layout.yaxis={title:'standardized residual²'};
  }else{
    data=[markers(x,y,'data'),line(bands.map(p=>p.x),bands.map(p=>p.fit),'fit')];
    if(pm==='fitBand'){
      data.push(line(bands.map(p=>p.x),bands.map(p=>p.meanHi),'mean CI upper','dash'));
      data.push(line(bands.map(p=>p.x),bands.map(p=>p.meanLo),'mean CI lower','dash'));
      data.push(line(bands.map(p=>p.x),bands.map(p=>p.predHi),'prediction upper','dot'));
      data.push(line(bands.map(p=>p.x),bands.map(p=>p.predLo),'prediction lower','dot'));
    }
    layout.xaxis={title:'x'};layout.yaxis={title:'y'};
  }
  root.Plotly.newPlot(el,data,layout,{responsive:true,displaylogo:false});
}
function secondaryPlot(input,o,host){const map={fit:'residualChronogram',fitBand:'residualHistogram',ellipse:'fit',residualChronogram:'autocorrelation',autocorrelation:'residualHistogram',chiSquareMap:'fit',profileLikelihood:'fit',residualHistogram:'fit',sensitivity:'fit',influence:'fit',bootstrapHistogram:'fit',componentResidual:'fit',predictionEnvelope:'residualChronogram'};plot(input,Object.assign({},o,{plot:map[o.plot]||'fit'}),host);}function mount(){const c=$('fittingContracts');if(c)c.remove();root.FokoPlatform.registerLab({id:'fitting',title:'Curve Fitting Lab',category:'Model output analysis',schema,template:DEFAULT,Controls:controls,Result:result,Plot:plot,PlotSecondary:secondaryPlot,engine});root.FokoPlatform.mount($('fittingShellApp'),'fitting');}
if(typeof module!=='undefined'&&module.exports)module.exports={EXAMPLES,PLOTS,schema,engine}; if(typeof document!=='undefined'){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',mount):mount();}
}(typeof window!=='undefined'?window:globalThis));
