(function(root){'use strict';
const FokoKit = root.FokoKit || (typeof require==='function' ? require('../fokokit.js') : null);
function requirePairs(pairs,name){if(!Array.isArray(pairs)||pairs.length===0||!pairs.every(p=>Array.isArray(p)&&p.length>=2&&Number.isFinite(p[0])&&Number.isFinite(p[1])))throw new Error(name+': expected a non-empty list of [x,y] pairs');}
function requireSameLength(x,y,name){return FokoKit?FokoKit.requireSameLength(x,y,name):[x,y];}
function parsePairs(text){return String(text||'').trim().split(/\n+/).map(r=>r.trim().split(/[\s,;]+/).map(Number)).filter(r=>r.length>=2&&Number.isFinite(r[0])&&Number.isFinite(r[1])).map(r=>[r[0],r[1]]);} 
function mean(a){return a.reduce((s,x)=>s+x,0)/(a.length||1);} 
function variance(a){const m=mean(a);return a.reduce((s,x)=>s+(x-m)*(x-m),0)/Math.max(1,a.length-1);} 
function sd(a){return Math.sqrt(variance(a));}
function quantile(a,p){const s=a.slice().sort((x,y)=>x-y);if(!s.length)return NaN;const i=(s.length-1)*p,lo=Math.floor(i),hi=Math.ceil(i),h=i-lo;return s[lo]*(1-h)+s[hi]*h;}
function normalInv(p){const a=[-39.69683028665376,220.9460984245205,-275.9285104469687,138.357751867269,-30.66479806614716,2.506628277459239],b=[-54.47609879822406,161.5858368580409,-155.6989798598866,66.80131188771972,-13.28068155288572],c=[-0.007784894002430293,-0.3223964580411365,-2.400758277161838,-2.549732539343734,4.374664141464968,2.938163982698783],d=[0.007784695709041462,0.3224671290700398,2.445134137142996,3.754408661907416];const pl=0.02425,ph=1-pl;let q,r;if(p<=0)return -Infinity;if(p>=1)return Infinity;if(p<pl){q=Math.sqrt(-2*Math.log(p));return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);}if(p<=ph){q=p-0.5;r=q*q;return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1);}q=Math.sqrt(-2*Math.log(1-p));return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);}
function solve(A,b){const n=A.length,M=A.map((r,i)=>r.slice().concat([b[i]]));for(let k=0;k<n;k++){let p=k;for(let i=k+1;i<n;i++) if(Math.abs(M[i][k])>Math.abs(M[p][k])) p=i; [M[k],M[p]]=[M[p],M[k]]; let piv=M[k][k]; if(Math.abs(piv)<1e-12)piv=piv<0?-1e-12:1e-12; for(let j=k;j<=n;j++) M[k][j]/=piv; for(let i=0;i<n;i++) if(i!==k){const f=M[i][k];for(let j=k;j<=n;j++) M[i][j]-=f*M[k][j];}} return M.map(r=>r[n]);}
function inverse(A){const n=A.length, I=Array.from({length:n},(_,i)=>Array.from({length:n},(_,j)=>i===j?1:0));const cols=I.map(e=>solve(A,e));return Array.from({length:n},(_,i)=>cols.map(c=>c[i]));}
function transpose(A){return A[0].map((_,j)=>A.map(r=>r[j]));}
function matmul(A,B){const Bt=transpose(B);return A.map(r=>Bt.map(c=>r.reduce((s,x,i)=>s+x*(c[i]||0),0)));}
function matvec(A,v){return A.map(r=>r.reduce((s,x,i)=>s+x*(v[i]||0),0));}
function dot(a,b){return a.reduce((s,x,i)=>s+x*(b[i]||0),0);}
function design(x,degree){return x.map(v=>Array.from({length:degree+1},(_,k)=>v**k));}
function modelInfo(model){if(model==='quadratic')return {names:['intercept','x','x^2'],predict:(x,p)=>p[0]+p[1]*x+p[2]*x*x};if(model==='cubic')return {names:['intercept','x','x^2','x^3'],predict:(x,p)=>p[0]+p[1]*x+p[2]*x*x+p[3]*x*x*x};if(model==='exponential')return {names:['a','b'],predict:(x,p)=>p[0]*Math.exp(p[1]*x)};if(model==='logistic')return {names:['K','r','x0'],predict:(x,p)=>p[0]/(1+Math.exp(-p[1]*(x-p[2])))};if(model==='michaelis'||model==='michaelis-menten')return {names:['Vmax','Km'],predict:(x,p)=>p[0]*x/(p[1]+x)};return {names:['intercept','slope'],predict:(x,p)=>p[0]+p[1]*x};}
function predictModel(model,x,p){return modelInfo(model).predict(x,p);}
function initialParams(model,x,y){if(model==='quadratic'||model==='cubic')return polyFitCore(x,y,model==='cubic'?3:2).coef;if(model==='exponential'){const clean=x.map((v,i)=>[v,y[i]]).filter(p=>p[1]>0);if(clean.length>=2){const lin=polyFitCore(clean.map(p=>p[0]),clean.map(p=>Math.log(p[1])),1).coef;return [Math.exp(lin[0]),lin[1]];}return [Math.max(1,mean(y)),0.1];}if(model==='logistic')return [Math.max(...y)*1.1,0.6,x[Math.floor(x.length/2)]||mean(x)];if(model==='michaelis')return [Math.max(...y)*1.25,Math.max(1,mean(x))];return polyFitCore(x,y,1).coef;}
function sseFor(model,x,y,p){return x.reduce((s,v,i)=>{const r=y[i]-predictModel(model,v,p);return s+r*r;},0);}
function numericJacobian(model,x,p){const info=modelInfo(model);return x.map(v=>p.map((pj,j)=>{const h=1e-6*(Math.abs(pj)+1);const pp=p.slice(),pm=p.slice();pp[j]+=h;pm[j]-=h;return (info.predict(v,pp)-info.predict(v,pm))/(2*h);}));}
function lmOptimize(model,x,y,start,opts){opts=opts||{};let p=start.slice(),lambda=opts.lambda||1e-3,mask=opts.mask||p.map(()=>true);let cur=sseFor(model,x,y,p);for(let it=0;it<(opts.steps||120);it++){const J=numericJacobian(model,x,p),r=x.map((v,i)=>y[i]-predictModel(model,v,p));const active=p.map((_,i)=>i).filter(i=>mask[i]);if(!active.length)break;const Ja=J.map(row=>active.map(i=>row[i]));const JT=transpose(Ja),JTJ=matmul(JT,Ja),JTr=JT.map(row=>dot(row,r));for(let i=0;i<JTJ.length;i++)JTJ[i][i]+=lambda*(JTJ[i][i]||1);let d;try{d=solve(JTJ,JTr);}catch(e){lambda*=10;continue;}const trial=p.slice();active.forEach((idx,k)=>{trial[idx]+=d[k];});if((model==='michaelis'||model==='logistic'||model==='exponential')&&trial[0]<=0)trial[0]=Math.abs(trial[0])+1e-6;if(model==='michaelis'&&trial[1]<=0)trial[1]=Math.abs(trial[1])+1e-6;const ss=sseFor(model,x,y,trial);if(Number.isFinite(ss)&&ss<cur){const prev=cur;p=trial;cur=ss;lambda=Math.max(lambda/4,1e-9);if(Math.abs(prev-ss)<1e-14)break;}else lambda=Math.min(lambda*4,1e9);}return p;}
function polyFitCore(x,y,deg){requireSameLength(x,y,'polyFit');if(x.length<=deg)throw new Error('polyFit: need more points than the polynomial degree');const X=design(x,deg),Xt=transpose(X),coef=solve(matmul(Xt,X),Xt.map(row=>dot(row,y)));return {coef,X,pred:x.map(v=>coef.reduce((s,c,k)=>s+c*v**k,0))};}
function score(x,y,pred,extra,k){const n=y.length,ybar=mean(y),residuals=y.map((v,i)=>v-pred[i]),sse=residuals.reduce((s,r)=>s+r*r,0),tss=y.reduce((s,v)=>s+(v-ybar)**2,0),df=Math.max(1,n-(k||1)),sigma2=sse/df,rmse=Math.sqrt(sse/Math.max(1,n)),aic=n*Math.log(Math.max(1e-12,sse/n))+2*(k||1),bic=n*Math.log(Math.max(1e-12,sse/n))+Math.log(Math.max(1,n))*(k||1);return Object.assign({n,df,sigma2,sse,rmse,r2:tss?1-sse/tss:1,aic,bic,pred,residuals},extra);}
function covarianceFromJacobian(J,sigma2){try{const Xt=transpose(J),XtX=matmul(Xt,J),inv=inverse(XtX);return inv.map(r=>r.map(v=>v*sigma2));}catch(e){return null;}}
function parameterSummary(names,coef,cov){return coef.map((c,i)=>{const se=cov&&cov[i]?Math.sqrt(Math.max(0,cov[i][i])):NaN;return {name:names[i]||('p'+i),value:c,se,t:Number.isFinite(se)&&se>0?c/se:NaN,ci95:Number.isFinite(se)?[c-1.96*se,c+1.96*se]:[NaN,NaN]};});}
function influenceDiagnostics(J,residuals,k,sigma2){let H=[],cooks=[],standardized=[];try{const inv=inverse(matmul(transpose(J),J));H=J.map(row=>dot(row,matvec(inv,row)));}catch(e){H=residuals.map(()=>NaN);}const mse=sigma2||variance(residuals)||1;for(let i=0;i<residuals.length;i++){const h=Math.max(0,Math.min(0.999999,H[i]||0));const sr=residuals[i]/Math.sqrt(Math.max(1e-12,mse*(1-h)));standardized.push(sr);cooks.push((sr*sr*h)/Math.max(1,k*(1-h)));}return {leverage:H,standardizedResiduals:standardized,cooksDistance:cooks};}
function enrich(model,x,y,coef,pred,extra){const info=modelInfo(model),J=numericJacobian(model,x,coef),base=score(x,y,pred,Object.assign({model,coef},extra||{}),coef.length),cov=covarianceFromJacobian(J,base.sigma2);base.covariance=cov;base.parameterSummary=parameterSummary(info.names,coef,cov);base.parameterSE=base.parameterSummary.map(p=>p.se);base.influence=influenceDiagnostics(J,base.residuals,coef.length,base.sigma2);base.predictionBands=predictionBands(model,x,coef,cov,base.sigma2);base.confidenceEllipse=confidenceEllipse(coef,cov,info.names);base.sensitivity=sensitivityCoefficients(model,x,coef);base.profileLikelihood=profileLikelihood(model,x,y,coef);base.bootstrap=bootstrapFit(x.map((v,i)=>[v,y[i]]),model,120);base.warnings=[];if(!cov)base.warnings.push('Covariance could not be estimated; check parameter identifiability or data volume.');if(base.n<=coef.length+1)base.warnings.push('Few observations relative to parameters; uncertainty diagnostics are unstable.');return base;}
function polyFit(x,y,deg){const pf=polyFitCore(x,y,deg),model=deg===1?'linear':deg===2?'quadratic':'cubic';return enrich(model,x,y,pf.coef,pf.pred,{degree:deg});}
function linearFit(pairs){requirePairs(pairs,'linearFit');return polyFit(pairs.map(p=>p[0]),pairs.map(p=>p[1]),1);} 
function expFit(pairs){requirePairs(pairs,'expFit');const x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]);const p=lmOptimize('exponential',x,y,initialParams('exponential',x,y),{steps:160});return enrich('exponential',x,y,p,x.map(v=>predictModel('exponential',v,p)),{});} 
function logisticFit(pairs){requirePairs(pairs,'logisticFit');const x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]);const p=lmOptimize('logistic',x,y,initialParams('logistic',x,y),{steps:220});return enrich('logistic',x,y,p,x.map(v=>predictModel('logistic',v,p)),{});} 
function michaelisFit(pairs){requirePairs(pairs,'michaelisFit');const x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]);const p=lmOptimize('michaelis',x,y,initialParams('michaelis',x,y),{steps:220});const res=enrich('michaelis',x,y,p,x.map(v=>predictModel('michaelis',v,p)),{});res.model='michaelis-menten';res.Vmax=p[0];res.Km=p[1];return res;}
function fit(pairs,model='linear'){requirePairs(pairs,'fit');const x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]); if(model==='exponential')return expFit(pairs); if(model==='logistic')return logisticFit(pairs); if(model==='michaelis')return michaelisFit(pairs); if(model==='quadratic')return polyFit(x,y,2); if(model==='cubic')return polyFit(x,y,3); return linearFit(pairs);}
function predictionBands(model,x,coef,cov,sigma2){const xs=x.slice().sort((a,b)=>a-b);const lo=xs[0],hi=xs[xs.length-1],grid=Array.from({length:80},(_,i)=>lo+(hi-lo)*i/79);return grid.map(v=>{const row=numericJacobian(model,[v],coef)[0],fit=predictModel(model,v,coef);let seMean=NaN;if(cov){const cv=matvec(cov,row);seMean=Math.sqrt(Math.max(0,dot(row,cv)));}const sePred=Number.isFinite(seMean)?Math.sqrt(seMean*seMean+(sigma2||0)):NaN;return {x:v,fit,meanLo:fit-1.96*seMean,meanHi:fit+1.96*seMean,predLo:fit-1.96*sePred,predHi:fit+1.96*sePred};});}
function confidenceEllipse(coef,cov,names){if(!cov||coef.length<2)return null;const a=cov[0][0],b=cov[0][1],d=cov[1][1],tr=a+d,det=a*d-b*b,disc=Math.sqrt(Math.max(0,tr*tr/4-det)),l1=Math.max(0,tr/2+disc),l2=Math.max(0,tr/2-disc),ang=0.5*Math.atan2(2*b,a-d),scale=Math.sqrt(5.991);const pts=Array.from({length:121},(_,i)=>{const t=2*Math.PI*i/120,c=Math.cos(t),s=Math.sin(t);const X=scale*Math.sqrt(l1)*c,Y=scale*Math.sqrt(l2)*s;return {x:coef[0]+X*Math.cos(ang)-Y*Math.sin(ang),y:coef[1]+X*Math.sin(ang)+Y*Math.cos(ang)};});return {xName:names&&names[0],yName:names&&names[1],points:pts};}
function sensitivityCoefficients(model,x,coef){const J=numericJacobian(model,x,coef),names=modelInfo(model).names;return names.map((name,j)=>({name,x:x.slice(),values:J.map(r=>r[j])}));}
function profileLikelihood(model,x,y,coef){const names=modelInfo(model).names;return names.map((name,j)=>{const se=Math.abs(coef[j])*0.25+1e-3;const values=Array.from({length:41},(_,i)=>coef[j]+(i-20)*se/5);const scan=values.map(v=>{const start=coef.slice();start[j]=v;const mask=coef.map((_,k)=>k!==j);const p=lmOptimize(model,x,y,start,{steps:50,mask});p[j]=v;return {value:v,sse:sseFor(model,x,y,p)};});return {name,values:scan};});}
function lcg(seed){let s=seed>>>0;return ()=>((s=(1664525*s+1013904223)>>>0)/4294967296);}
function bootstrapFit(pairs,model,B){const rand=lcg(9144+pairs.length),n=pairs.length,names=modelInfo(model).names,rows=[];for(let b=0;b<B;b++){const sample=Array.from({length:n},()=>pairs[Math.floor(rand()*n)]);try{const r=fitNoBootstrap(sample,model);if(r.coef&&r.coef.every(Number.isFinite))rows.push(r.coef);}catch(e){/* skip singular resample */}}const summary=names.map((name,j)=>{const vals=rows.map(r=>r[j]).filter(Number.isFinite);return {name,values:vals,mean:mean(vals),lo:quantile(vals,0.025),hi:quantile(vals,0.975)};});return {replicates:rows.length,summary};}
function fitNoBootstrap(pairs,model){const x=pairs.map(p=>p[0]),y=pairs.map(p=>p[1]);if(model==='linear')return polyFitCore(x,y,1);if(model==='quadratic')return polyFitCore(x,y,2);if(model==='cubic')return polyFitCore(x,y,3);const p=lmOptimize(model,x,y,initialParams(model,x,y),{steps:90});return {coef:p,pred:x.map(v=>predictModel(model,v,p))};}
function qqData(residuals){const sorted=residuals.slice().sort((a,b)=>a-b),m=mean(sorted),s=sd(sorted)||1,n=sorted.length;return {theory:sorted.map((_,i)=>m+s*normalInv((i+0.5)/n)),sample:sorted};}
function format(res){return Object.entries(res).filter(([k])=>!['pred','residuals','predictionBands','bootstrap','profileLikelihood','sensitivity','confidenceEllipse'].includes(k)).map(([k,v])=>k+' = '+(Array.isArray(v)?JSON.stringify(v.map(z=>Number.isFinite(z)?Number(z.toFixed(5)):z)):(typeof v==='object'?JSON.stringify(v,null,2):(Number.isFinite(v)?v.toFixed(5):v)))).join('\n');}
function plot(plotEl,x,y,res,mode){if(!root.Plotly||!plotEl)return;let data=[],layout={margin:{t:28,r:20,b:48,l:54},paper_bgcolor:'#fff',plot_bgcolor:'#fff'};if(mode==='residual'){data=[{x:res.pred,y:res.residuals,mode:'markers',type:'scatter',name:'residuals'}];layout.xaxis={title:'fitted'};layout.yaxis={title:'residual'};}else if(mode==='qq'){const q=qqData(res.residuals);data=[{x:q.theory,y:q.sample,mode:'markers',type:'scatter',name:'residual Q-Q'},{x:[Math.min(...q.theory),Math.max(...q.theory)],y:[Math.min(...q.theory),Math.max(...q.theory)],mode:'lines',name:'normal line'}];layout.xaxis={title:'normal quantile'};layout.yaxis={title:'residual quantile'};}else{const ord=res.predictionBands||x.map((v,i)=>({x:v,fit:res.pred[i]})).sort((a,b)=>a.x-b.x);data=[{x,y,mode:'markers',name:'data',type:'scatter'},{x:ord.map(p=>p.x),y:ord.map(p=>p.fit),mode:'lines',name:'fit'}];layout.xaxis={title:'x'};layout.yaxis={title:'y'};}root.Plotly.newPlot(plotEl,data,layout,{responsive:true,displaylogo:false});}
function boot(){const el=document.querySelector('[data-fitting-lab]'); if(!el) return; const $=id=>document.getElementById(id); const presets={growth:'0 1.1\n1 1.8\n2 3.2\n3 5.1\n4 8.4\n5 13.7',enzyme:'0.2 0.18\n0.5 0.34\n1 0.52\n2 0.71\n4 0.86\n8 0.94',logistic:'0 1.2\n1 1.7\n2 3.1\n3 5.8\n4 8.4\n5 9.6\n6 10.1',residual:'0 1.0\n1 2.1\n2 2.9\n3 5.2\n4 7.7\n5 11.8'}; const run=()=>{try{const pairs=parsePairs($('fitData').value), res=fit(pairs,$('fitModel').value), x=pairs.map(p=>p[0]), y=pairs.map(p=>p[1]);$('fitOutput').textContent=format(res);plot($('fitPlot'),x,y,res,$('fitPlotMode').value);}catch(e){$('fitOutput').textContent='Error: '+e.message;}}; if($('fitPreset'))$('fitPreset').addEventListener('change',()=>{const v=$('fitPreset').value;$('fitData').value=presets[v]||presets.growth;if(v==='enzyme')$('fitModel').value='michaelis';if(v==='logistic')$('fitModel').value='logistic';run();}); if($('fitRun'))$('fitRun').addEventListener('click',run); if($('fitPlotMode'))$('fitPlotMode').addEventListener('change',run); run();}
const api={parsePairs,solve,inverse,polyFit,linearFit,expFit,logisticFit,michaelisFit,fit,fitNoBootstrap,qqData,score,predictModel,numericJacobian,covarianceFromJacobian,confidenceEllipse,profileLikelihood,bootstrapFit,predictionBands,influenceDiagnostics,sensitivityCoefficients}; if(typeof module!=='undefined'&&module.exports) module.exports=api; root.FokoFitting=api; if(typeof document!=='undefined') (document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot());
}(typeof window!=='undefined'?window:globalThis));
