(function(root){'use strict';
const FokoKit = root.FokoKit || (typeof require==='function' ? require('../fokokit.js') : null);
// --- precondition guards (consistent across all Foko engines) ---
function requireEdges(edges,name){if(!Array.isArray(edges)||edges.length===0||!edges.every(e=>e&&e.source!=null&&e.target!=null))throw new Error(name+': expected a non-empty edge list of {source,target,weight}');}
function requireNodePresent(edges,node,name){if(node==null||String(node).length===0)throw new Error(name+': a node id is required');if(nodes(edges).indexOf(String(node))<0)throw new Error(name+': node "'+node+'" is not in the graph');}

function splitLine(line){return String(line||'').trim().split(/\s*,\s*|\s+|\s*;\s*/).filter(Boolean);} 
function parseEdges(text){const raw=String(text||'').trim().split(/\n+/).map(s=>s.trim()).filter(Boolean); if(!raw.length) return []; let start=0; if(raw.length && splitLine(raw[0]).some(v=>/source|target|weight/i.test(v))) start=1; return raw.slice(start).map(r=>splitLine(r)).filter(r=>r.length>=2).map(r=>({source:r[0],target:r[1],weight:Number(r[2])||1}));}
function nodes(edges){return Array.from(new Set(edges.reduce((a,e)=>a.concat([e.source,e.target]),[])));} 
function adjacency(edges,directed){const adj={}; nodes(edges).forEach(n=>adj[n]=[]); edges.forEach(e=>{adj[e.source].push({node:e.target,weight:e.weight}); if(!directed) adj[e.target].push({node:e.source,weight:e.weight});}); return adj;}
function degree(edges,directed){requireEdges(edges,'degree');const adj=adjacency(edges,directed); const out={}; Object.keys(adj).forEach(n=>out[n]=adj[n].length); return out;}
function dijkstra(edges,start,directed){requireEdges(edges,'dijkstra');requireNodePresent(edges,start,'dijkstra');const adj=adjacency(edges,directed), ns=Object.keys(adj), dist=Object.fromEntries(ns.map(n=>[n,Infinity])), prev={}; dist[start]=0; const seen=new Set(); while(seen.size<ns.length){ let u=null, best=Infinity; ns.forEach(n=>{ if(!seen.has(n) && dist[n]<best){best=dist[n];u=n;} }); if(u===null) break; seen.add(u); (adj[u]||[]).forEach(e=>{ const nd=dist[u]+e.weight; if(nd<dist[e.node]){dist[e.node]=nd; prev[e.node]=u;} }); } return {dist,prev};}
function shortestPath(edges,start,end,directed){requireEdges(edges,'shortestPath');requireNodePresent(edges,start,'shortestPath');requireNodePresent(edges,end,'shortestPath');const res=dijkstra(edges,start,directed), dist=res.dist, prev=res.prev; const path=[]; if(!(end in dist) || !Number.isFinite(dist[end])) return {distance:Infinity,path:[]}; for(let cur=end; cur; cur=prev[cur]){path.push(cur); if(cur===start) break;} path.reverse(); return {distance:dist[end], path};}
function bfs(adj,start){const dist={[start]:0}, q=[start]; for(let i=0;i<q.length;i++){const u=q[i]; (adj[u]||[]).forEach(v=>{if(dist[v.node]===undefined){dist[v.node]=dist[u]+1; q.push(v.node);}});} return dist;}
function components(edges){requireEdges(edges,'components');const adj=adjacency(edges,false), seen=new Set(), comps=[]; for(const n of Object.keys(adj)){if(seen.has(n)) continue; const d=bfs(adj,n), comp=Object.keys(d); comp.forEach(x=>seen.add(x)); comps.push(comp);} return comps;}
function pagerank(edges,d,it){requireEdges(edges,'pagerank');d=d===undefined?0.85:d;it=it||80;const ns=nodes(edges), N=ns.length, idx=Object.fromEntries(ns.map((n,i)=>[n,i])), adj=adjacency(edges,true); let r=Array(N).fill(1/Math.max(1,N)); for(let k=0;k<it;k++){const nr=Array(N).fill((1-d)/Math.max(1,N)); ns.forEach((n,i)=>{const outs=adj[n]||[]; if(!outs.length){for(let j=0;j<N;j++)nr[j]+=d*r[i]/Math.max(1,N);} else outs.forEach(e=>nr[idx[e.node]]+=d*r[i]/outs.length);}); r=nr;} return Object.fromEntries(ns.map((n,i)=>[n,r[i]]));}
function closeness(edges,directed){requireEdges(edges,'closeness');const adj=adjacency(edges,directed), out={}; Object.keys(adj).forEach(n=>{const d=directed?dijkstra(edges,n,directed).dist:bfs(adj,n); const vals=Object.values(d).filter(Number.isFinite); const sum=vals.reduce((a,b)=>a+b,0); out[n]=sum>0?(vals.length-1)/sum:0;}); return out;}
function adjacencyMatrix(edges,directed){requireEdges(edges,'adjacencyMatrix');const ns=nodes(edges), idx=Object.fromEntries(ns.map((n,i)=>[n,i])), M=Array.from({length:ns.length},()=>Array(ns.length).fill(0)); edges.forEach(e=>{M[idx[e.source]][idx[e.target]]+=e.weight; if(!directed) M[idx[e.target]][idx[e.source]]+=e.weight;}); return {nodes:ns, matrix:M};}

function betweenness(edges,directed){requireEdges(edges,'betweenness');const ns=nodes(edges), adj=adjacency(edges,directed), C=Object.fromEntries(ns.map(n=>[n,0])); for(const s of ns){const S=[],P=Object.fromEntries(ns.map(n=>[n,[]])),sigma=Object.fromEntries(ns.map(n=>[n,0])),d=Object.fromEntries(ns.map(n=>[n,-1])); sigma[s]=1; d[s]=0; const Q=[s]; for(let qi=0;qi<Q.length;qi++){const v=Q[qi]; S.push(v); (adj[v]||[]).forEach(e=>{const w=e.node; if(d[w]<0){Q.push(w); d[w]=d[v]+1;} if(d[w]===d[v]+1){sigma[w]+=sigma[v]; P[w].push(v);}});} const delta=Object.fromEntries(ns.map(n=>[n,0])); while(S.length){const w=S.pop(); P[w].forEach(v=>{delta[v]+=(sigma[v]/Math.max(1e-12,sigma[w]))*(1+delta[w]);}); if(w!==s) C[w]+=delta[w];}} if(!directed) ns.forEach(n=>C[n]/=2); return C;}
function eigenvectorCentrality(edges,directed,it=80){requireEdges(edges,'eigenvectorCentrality');const A=adjacencyMatrix(edges,directed), ns=A.nodes, M=A.matrix; let v=Array(ns.length).fill(1/Math.sqrt(Math.max(1,ns.length))); for(let k=0;k<it;k++){let w=M.map(r=>r.reduce((s,x,i)=>s+x*v[i],0)); const n=Math.sqrt(w.reduce((s,x)=>s+x*x,0))||1; v=w.map(x=>x/n);} return Object.fromEntries(ns.map((n,i)=>[n,v[i]]));}
function minimumSpanningTree(edges){requireEdges(edges,'minimumSpanningTree');const ns=nodes(edges), parent=Object.fromEntries(ns.map(n=>[n,n])); const find=x=>parent[x]===x?x:(parent[x]=find(parent[x])); const union=(a,b)=>{a=find(a);b=find(b); if(a===b)return false; parent[b]=a; return true;}; const chosen=[]; let weight=0; edges.slice().sort((a,b)=>a.weight-b.weight).forEach(e=>{if(union(e.source,e.target)){chosen.push(e); weight+=e.weight;}}); return {weight,edges:chosen,complete:chosen.length===Math.max(0,ns.length-1)};}
function communityLabelPropagation(edges,directed=false,steps=20){requireEdges(edges,'communityLabelPropagation');const ns=nodes(edges), adj=adjacency(edges,directed), labels=Object.fromEntries(ns.map(n=>[n,n])); for(let s=0;s<steps;s++){let changed=false; for(const n of ns){const counts={}; (adj[n]||[]).forEach(e=>{counts[labels[e.node]]=(counts[labels[e.node]]||0)+1;}); const best=Object.entries(counts).sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0])))[0]; if(best && labels[n]!==best[0]){labels[n]=best[0]; changed=true;}} if(!changed)break;} const communities={}; Object.entries(labels).forEach(([n,l])=>{(communities[l]=communities[l]||[]).push(n);}); return {labels,communities};}
function resilience(edges,directed=false){requireEdges(edges,'resilience');const deg=degree(edges,directed), order=Object.entries(deg).sort((a,b)=>b[1]-a[1]).map(([n])=>n), baseline=components(edges).length; const impact=order.slice(0,Math.min(8,order.length)).map(node=>{const kept=edges.filter(e=>e.source!==node&&e.target!==node);return {removed:node,components:components(kept).length,deltaComponents:components(kept).length-baseline,remainingEdges:kept.length};}); return {baselineComponents:baseline,removalOrder:order,impact};}

function summary(edges,directed){requireEdges(edges,'summary');return {nodes:nodes(edges).length,edges:edges.length,components:components(edges).length,degree:degree(edges,directed),closeness:closeness(edges,directed),betweenness:betweenness(edges,directed),eigenvector:eigenvectorCentrality(edges,directed),pagerank:pagerank(edges)};}
function plotGraph(plot, edges, directed, mode){ if(typeof window==='undefined' || !window.Plotly || !plot) return; const ns=nodes(edges); if(mode==='adjacency'){ const A=adjacencyMatrix(edges,directed); Plotly.newPlot(plot,[{z:A.matrix,x:A.nodes,y:A.nodes,type:'heatmap',colorscale:'Viridis'}],{margin:{t:28,r:20,b:48,l:56}},{responsive:true,displaylogo:false}); return; } if(mode==='sankey'){ const idx=Object.fromEntries(ns.map((n,i)=>[n,i])); Plotly.newPlot(plot,[{type:'sankey',node:{label:ns},link:{source:edges.map(e=>idx[e.source]),target:edges.map(e=>idx[e.target]),value:edges.map(e=>e.weight)}}],{margin:{t:20,l:10,r:10,b:10}},{responsive:true,displaylogo:false}); return; }
  const ang=ns.map((_,i)=>2*Math.PI*i/Math.max(1,ns.length)); const pos=Object.fromEntries(ns.map((n,i)=>[n,[Math.cos(ang[i]),Math.sin(ang[i])]])); const ex=[],ey=[]; edges.forEach(e=>{ex.push(pos[e.source][0],pos[e.target][0],null);ey.push(pos[e.source][1],pos[e.target][1],null);}); Plotly.newPlot(plot,[{x:ex,y:ey,mode:'lines',hoverinfo:'none',name:'edges',type:'scatter'},{x:ns.map(n=>pos[n][0]),y:ns.map(n=>pos[n][1]),mode:'markers+text',text:ns,textposition:'top center',type:'scatter',name:'nodes'}],{margin:{t:20},xaxis:{visible:false},yaxis:{visible:false,scaleanchor:'x'}},{responsive:true,displaylogo:false}); }
function format(obj){return JSON.stringify(obj,function(k,v){return Number.isFinite(v)?Number(v.toFixed(6)):v;},2);} 
function example(name){const map={social:'source,target,weight\nA,B,1\nA,C,1\nB,D,1\nC,D,1\nC,E,1\nD,F,1\nE,F,1\nF,G,1',transport:'source,target,weight\nA,B,4\nA,C,2\nB,D,5\nC,D,1\nC,E,7\nD,F,3\nE,F,1\nF,G,2',sankey:'source,target,weight\nInput,Filter,10\nInput,Bypass,3\nFilter,Reactor,8\nBypass,Reactor,3\nReactor,Product,9\nReactor,Waste,2'}; return map[name]||map.social; }
function boot(){const el=document.querySelector('[data-network-lab]'); if(!el) return; const $=id=>document.getElementById(id); const run=()=>{const edges=parseEdges($('netEdges').value), directed=$('netDirected').value==='true', mode=$('netMode').value, plotMode=$('netPlotMode').value==='auto'?(mode==='centrality'?'adjacency':(mode==='pagerank'?'graph':(($('netPreset').value==='sankey')?'sankey':'graph'))):$('netPlotMode').value; let res; if(mode==='shortest') res=shortestPath(edges,$('netStart').value.trim(),$('netEnd').value.trim(),directed); else if(mode==='pagerank') res={pagerank:pagerank(edges)}; else if(mode==='centrality') res={degree:degree(edges,directed), closeness:closeness(edges,directed), betweenness:betweenness(edges,directed), eigenvector:eigenvectorCentrality(edges,directed), pagerank:pagerank(edges)}; else if(mode==='betweenness') res={betweenness:betweenness(edges,directed)}; else if(mode==='mst') res={minimumSpanningTree:minimumSpanningTree(edges)}; else if(mode==='community') res=communityLabelPropagation(edges,directed); else if(mode==='resilience') res=resilience(edges,directed); else res=summary(edges,directed); $('netOutput').textContent=format(res); plotGraph($('netPlot'),edges,directed,plotMode); }; $('netRun').addEventListener('click',run); $('netPreset').addEventListener('change',()=>{ $('netEdges').value=example($('netPreset').value); if($('netPreset').value==='sankey'){ $('netDirected').value='true'; $('netPlotMode').value='sankey'; } run(); }); run(); }
const api={parseEdges,nodes,adjacency,degree,dijkstra,shortestPath,bfs,components,pagerank,closeness,betweenness,eigenvectorCentrality,minimumSpanningTree,communityLabelPropagation,resilience,adjacencyMatrix,summary}; if(typeof module!=='undefined'&&module.exports) module.exports=api; root.FokoNetworks=api; if(typeof document!=='undefined')(document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot());
}(typeof window!=='undefined'?window:globalThis));
