/* =====================================================================
 * Foko Lab — Statistics Lab engine (v70.14)
 * Generated by Foko Lab Statistics Lab.
 *
 * Rewrite goal: a statistics lab must DECIDE significance, not just print
 * point statistics. The previous engine returned t / F / z with no p-values
 * and no distributions. This version adds the full inferential core:
 *   - distributions: normal, Student-t, F, chi-square (erf, incomplete beta,
 *     incomplete gamma);
 *   - every parametric test now carries a p-value / CI;
 *   - non-parametric tests (Mann-Whitney U, Wilcoxon signed-rank,
 *     Kruskal-Wallis);
 *   - chi-square test of independence;
 *   - multiple linear regression with coefficient SE / t / p and model F.
 *
 * The numeric core is pure and Node-exported so it is unit-tested against
 * reference values in tests/js/statistics-core.test.js BEFORE the UI trusts
 * it. The browser UI (bottom) keeps the exact element IDs / analysis modes of
 * the previous lab, so the page and its contracts are unchanged.
 * ===================================================================== */
(function (root) {
'use strict';

// ---------- parsing / coercion ----------
function isNum(x){return Number.isFinite(Number(x));}
function splitLine(line){return String(line).trim().split(/\s*,\s*|\s+|\s*;\s*/).filter(s=>s.length);}
function parseTable(text, namesText='', missing='drop'){
  const raw=String(text||'').trim().split(/\n+/).map(r=>r.trim()).filter(Boolean);
  if(!raw.length) return {names:[], rows:[], cols:[]};
  let names=String(namesText||'').split(/[,;\s]+/).map(s=>s.trim()).filter(Boolean);
  let start=0; const first=splitLine(raw[0]);
  if(first.some(v=>!isNum(v))){ names=first; start=1; }
  const rows=[];
  for(let i=start;i<raw.length;i++){
    const vals=splitLine(raw[i]).map(v=>v===''||v==='NA'||v==='NaN'?NaN:Number(v));
    if(!vals.length) continue;
    rows.push(vals);
  }
  const width=Math.max(...rows.map(r=>r.length), names.length, 0);
  while(names.length<width) names.push('V'+(names.length+1));
  const means=Array(width).fill(0), counts=Array(width).fill(0);
  rows.forEach(r=>{for(let j=0;j<width;j++){const v=r[j]; if(Number.isFinite(v)){means[j]+=v;counts[j]++;}}});
  for(let j=0;j<width;j++) means[j]=counts[j]?means[j]/counts[j]:0;
  let clean=rows.map(r=>Array.from({length:width},(_,j)=>Number.isFinite(r[j])?r[j]:NaN));
  if(missing==='drop') clean=clean.filter(r=>r.every(Number.isFinite));
  if(missing==='zero') clean=clean.map(r=>r.map(v=>Number.isFinite(v)?v:0));
  if(missing==='mean') clean=clean.map(r=>r.map((v,j)=>Number.isFinite(v)?v:means[j]));
  const cols=Array.from({length:width},(_,j)=>clean.map(r=>r[j]).filter(Number.isFinite));
  return {names, rows:clean, cols};
}
function nums(input){ if(Array.isArray(input)) return input.map(Number).filter(Number.isFinite); return String(input||'').split(/[\s,;]+/).map(Number).filter(Number.isFinite); }

// ---------- descriptives ----------
function mean(a){a=nums(a);return a.reduce((s,x)=>s+x,0)/(a.length||1);}
function variance(a,sample=true){a=nums(a);if(a.length<2)return 0;const m=mean(a);return a.reduce((s,x)=>s+(x-m)**2,0)/(sample?a.length-1:a.length);}
function sd(a,sample=true){return Math.sqrt(variance(a,sample));}
function sem(a){a=nums(a);return sd(a)/Math.sqrt(a.length||1);}
function quantile(a,q){a=nums(a).sort((x,y)=>x-y);if(!a.length)return NaN;const p=(a.length-1)*q,lo=Math.floor(p),hi=Math.ceil(p);return lo===hi?a[lo]:a[lo]+(a[hi]-a[lo])*(p-lo);}
function median(a){return quantile(a,.5);}
function skewness(a){a=nums(a);const n=a.length,m=mean(a),s=sd(a);if(n<3||!s)return NaN;let acc=0;for(const x of a)acc+=((x-m)/s)**3;return n/((n-1)*(n-2))*acc;}
function kurtosisExcess(a){a=nums(a);const n=a.length,m=mean(a),s=sd(a);if(n<2||!s)return NaN;let acc=0;for(const x of a)acc+=((x-m)/s)**4;return acc/n-3;}
function describe(a){a=nums(a);return {n:a.length,mean:mean(a),sd:sd(a),sem:sem(a),variance:variance(a),min:Math.min(...a),q1:quantile(a,.25),median:median(a),q3:quantile(a,.75),max:Math.max(...a),iqr:quantile(a,.75)-quantile(a,.25),skewness:skewness(a),kurtosisExcess:kurtosisExcess(a)};}
function covariance(x,y){x=nums(x);y=nums(y);const n=Math.min(x.length,y.length);if(n<2)return 0;const mx=mean(x.slice(0,n)),my=mean(y.slice(0,n));let s=0;for(let i=0;i<n;i++)s+=(x[i]-mx)*(y[i]-my);return s/(n-1);}
function correlation(x,y){const sx=sd(x),sy=sd(y);return sx&&sy?covariance(x,y)/(sx*sy):0;}
function correlationMatrix(cols){cols=(cols||[]).map(nums).filter(c=>c.length);return cols.map(a=>cols.map(b=>correlation(a,b)));}

// ---------- distributions (the previously-missing inferential engine) ----------
function erf(x){const s=x<0?-1:1;x=Math.abs(x);const t=1/(1+0.3275911*x);const y=1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-0.284496736)*t+0.254829592)*t*Math.exp(-x*x);return s*y;}
function normalCdf(z){return 0.5*(1+erf(z/Math.SQRT2));}
function normalPdf(z){return Math.exp(-0.5*z*z)/Math.sqrt(2*Math.PI);}
function normalInv(p){ if(!(p>0&&p<1))throw new Error('normalInv needs p in (0,1)');
  const a=[-3.969683028665376e1,2.209460984245205e2,-2.759285104469687e2,1.383577518672690e2,-3.066479806614716e1,2.506628277459239e0];
  const b=[-5.447609879822406e1,1.615858368580409e2,-1.556989798598866e2,6.680131188771972e1,-1.328073155288572e1];
  const c=[-7.784894002430293e-3,-3.223964580411365e-1,-2.400758277161838e0,-2.549732539343734e0,4.374664141464968e0,2.938163982698783e0];
  const d=[7.784695709041462e-3,3.224671290700398e-1,2.445134137142996e0,3.754408661907416e0];
  const pl=0.02425,ph=1-pl;let q,r;
  if(p<pl){q=Math.sqrt(-2*Math.log(p));return (((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);}
  if(p<=ph){q=p-0.5;r=q*q;return (((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1);}
  q=Math.sqrt(-2*Math.log(1-p));return -(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1);
}
function logGamma(z){const g=[76.18009172947146,-86.50532032941677,24.01409824083091,-1.231739572450155,0.1208650973866179e-2,-0.5395239384953e-5];let x=z,y=z,tmp=x+5.5;tmp-=(x+0.5)*Math.log(tmp);let ser=1.000000000190015;for(let j=0;j<6;j++){y+=1;ser+=g[j]/y;}return -tmp+Math.log(2.5066282746310005*ser/x);}
function betacf(a,b,x){const MAXIT=300,EPS=3e-12,FPMIN=1e-300;let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<FPMIN)d=FPMIN;d=1/d;let h=d;for(let m=1;m<=MAXIT;m++){let m2=2*m,aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<FPMIN)d=FPMIN;c=1+aa/c;if(Math.abs(c)<FPMIN)c=FPMIN;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<FPMIN)d=FPMIN;c=1+aa/c;if(Math.abs(c)<FPMIN)c=FPMIN;d=1/d;let del=d*c;h*=del;if(Math.abs(del-1)<EPS)break;}return h;}
function regIncBeta(a,b,x){ if(x<=0)return 0; if(x>=1)return 1; const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log(1-x)); return x<(a+1)/(a+b+2)?bt*betacf(a,b,x)/a:1-bt*betacf(b,a,1-x)/b;}
function studentTCdf(t,df){ if(!(df>0))throw new Error('studentTCdf df>0'); const x=df/(df+t*t),ib=0.5*regIncBeta(df/2,0.5,x); return t>0?1-ib:ib;}
function tTwoTailP(t,df){return 2*(1-studentTCdf(Math.abs(t),df));}
function studentTinv(p,df){let lo=-1e3,hi=1e3;for(let i=0;i<200;i++){const m=(lo+hi)/2;if(studentTCdf(m,df)<p)lo=m;else hi=m;}return (lo+hi)/2;}
function fCdf(f,d1,d2){ if(f<=0)return 0; const x=d1*f/(d1*f+d2); return regIncBeta(d1/2,d2/2,x);}
function fUpperP(f,d1,d2){return 1-fCdf(f,d1,d2);}
// regularized lower incomplete gamma P(a,x) via series / continued fraction
function gammaP(a,x){ if(x<0||a<=0)throw new Error('gammaP domain'); if(x===0)return 0;
  if(x<a+1){ let ap=a,sum=1/a,del=sum; for(let n=0;n<300;n++){ap+=1;del*=x/ap;sum+=del;if(Math.abs(del)<Math.abs(sum)*3e-12)break;} return sum*Math.exp(-x+a*Math.log(x)-logGamma(a)); }
  const FPMIN=1e-300;let b=x+1-a,c=1/FPMIN,d=1/b,h=d;for(let i=1;i<=300;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<FPMIN)d=FPMIN;c=b+an/c;if(Math.abs(c)<FPMIN)c=FPMIN;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<3e-12)break;}return 1-Math.exp(-x+a*Math.log(x)-logGamma(a))*h;
}
function chiSqCdf(x,k){ if(x<=0)return 0; return gammaP(k/2,x/2);}
function chiUpperP(x,k){return 1-chiSqCdf(x,k);}

// ---------- ranks (for non-parametric tests, average ranks with ties) ----------
function rankData(a){const idx=a.map((v,i)=>[v,i]).sort((p,q)=>p[0]-q[0]);const ranks=Array(a.length);let i=0;while(i<idx.length){let j=i;while(j+1<idx.length&&idx[j+1][0]===idx[i][0])j++;const r=(i+j)/2+1;for(let k=i;k<=j;k++)ranks[idx[k][1]]=r;i=j+1;}return ranks;}
function tieCorrection(all){const counts={};all.forEach(v=>counts[v]=(counts[v]||0)+1);let s=0;Object.values(counts).forEach(t=>{if(t>1)s+=t*t*t-t;});return s;}

// ---------- parametric tests (now with p-values) ----------
function tTestOne(x,mu0){x=nums(x);if(x.length<2)throw new Error('one-sample t needs n>=2');const m=mean(x),se=sem(x),df=x.length-1,t=se?(m-mu0)/se:0;return {mean:m,mu0,t,df,se,p:tTwoTailP(t,df)};}
function welchT(x,y){x=nums(x);y=nums(y);if(x.length<2||y.length<2)throw new Error('Welch needs n>=2 each');const mx=mean(x),my=mean(y),vx=variance(x),vy=variance(y),se=Math.sqrt(vx/x.length+vy/y.length),t=se?(mx-my)/se:0;const num=(vx/x.length+vy/y.length)**2,den=(vx*vx)/(x.length*x.length*(x.length-1))+(vy*vy)/(y.length*y.length*(y.length-1)),df=den?num/den:1;return {meanA:mx,meanB:my,difference:mx-my,se,t,df,p:tTwoTailP(t,df)};}
function corTest(x,y){x=nums(x);y=nums(y);const n=Math.min(x.length,y.length);if(n<3)throw new Error('corTest needs n>=3');const r=correlation(x.slice(0,n),y.slice(0,n)),df=n-2,t=r===1||r===-1?Infinity:r*Math.sqrt(df/(1-r*r));return {r,n,df,t,p:isFinite(t)?tTwoTailP(t,df):0};}
function anovaOneWay(groups){groups=(groups||[]).map(nums).filter(g=>g.length>1);const k=groups.length,all=[].concat(...groups),grand=mean(all);const ssB=groups.reduce((s,g)=>s+g.length*(mean(g)-grand)**2,0),ssW=groups.reduce((s,g)=>{const mg=mean(g);return s+g.reduce((a,x)=>a+(x-mg)**2,0);},0);const dfB=Math.max(1,k-1),dfW=Math.max(1,all.length-k),msB=ssB/dfB,msW=ssW/dfW,F=msW?msB/msW:0;return {groups:k,n:all.length,grandMean:grand,ssBetween:ssB,ssWithin:ssW,dfBetween:dfB,dfWithin:dfW,msBetween:msB,msWithin:msW,F,p:isFinite(F)&&F>0?fUpperP(F,dfB,dfW):1};}
function ols(x,y){x=nums(x);y=nums(y);const n=Math.min(x.length,y.length);x=x.slice(0,n);y=y.slice(0,n);const mx=mean(x),my=mean(y);let sxx=0,sxy=0;for(let i=0;i<n;i++){sxx+=(x[i]-mx)**2;sxy+=(x[i]-mx)*(y[i]-my);}const slope=sxx?sxy/sxx:0,intercept=my-slope*mx,pred=x.map(v=>intercept+slope*v),resid=y.map((v,i)=>v-pred[i]),sse=resid.reduce((s,v)=>s+v*v,0),tss=y.reduce((s,v)=>s+(v-my)**2,0),df=Math.max(1,n-2),mse=sse/df,seSlope=sxx?Math.sqrt(mse/sxx):0,seIntercept=Math.sqrt(mse*(1/n+mx*mx/(sxx||1))),tSlope=seSlope?slope/seSlope:Infinity,tc=studentTinv(0.975,df);const r=correlation(x,y),r2=tss?1-sse/tss:1,F=(mse&&tss)?(tss-sse)/mse:0;return {n,intercept,slope,r,r2,sse,rmse:Math.sqrt(mse),df,seSlope,seIntercept,tSlope,pSlope:isFinite(tSlope)?tTwoTailP(tSlope,df):0,ciSlope:[slope-tc*seSlope,slope+tc*seSlope],F,pModel:F>0?fUpperP(F,1,df):1,pred,resid};}

// ---------- small linear algebra for multiple regression ----------
function matInverse(A){const n=A.length,M=A.map((r,i)=>r.concat(Array.from({length:n},(_,j)=>i===j?1:0)));for(let col=0;col<n;col++){let piv=col;for(let r=col+1;r<n;r++)if(Math.abs(M[r][col])>Math.abs(M[piv][col]))piv=r;if(Math.abs(M[piv][col])<1e-12)throw new Error('singular design matrix (collinear predictors?)');[M[col],M[piv]]=[M[piv],M[col]];const d=M[col][col];for(let j=0;j<2*n;j++)M[col][j]/=d;for(let r=0;r<n;r++){if(r===col)continue;const f=M[r][col];for(let j=0;j<2*n;j++)M[r][j]-=f*M[col][j];}}return M.map(r=>r.slice(n));}
function multipleRegression(X,y){ // X: rows of predictors (without intercept). Adds intercept.
  y=nums(y);const n=X.length;if(n<2||!Array.isArray(X[0]))throw new Error('multipleRegression needs matrix X and vector y');
  const p=X[0].length,D=X.map(row=>[1,...row.map(Number)]);const k=p+1; // design incl intercept
  const XtX=Array.from({length:k},()=>Array(k).fill(0)),XtY=Array(k).fill(0);
  for(let i=0;i<n;i++){for(let a=0;a<k;a++){XtY[a]+=D[i][a]*y[i];for(let b=0;b<k;b++)XtX[a][b]+=D[i][a]*D[i][b];}}
  const inv=matInverse(XtX),beta=inv.map(row=>row.reduce((s,v,j)=>s+v*XtY[j],0));
  const fitted=D.map(row=>row.reduce((s,v,j)=>s+v*beta[j],0)),resid=y.map((v,i)=>v-fitted[i]);
  const sse=resid.reduce((s,v)=>s+v*v,0),my=mean(y),tss=y.reduce((s,v)=>s+(v-my)**2,0);
  const dfRes=Math.max(1,n-k),mse=sse/dfRes,r2=tss?1-sse/tss:1,adjR2=1-(1-r2)*(n-1)/dfRes;
  const se=beta.map((_,j)=>Math.sqrt(Math.max(0,mse*inv[j][j]))),tvals=beta.map((b,j)=>se[j]?b/se[j]:Infinity),pvals=tvals.map(t=>isFinite(t)?tTwoTailP(t,dfRes):0);
  const F=(p&&mse)?((tss-sse)/p)/mse:0;
  return {coefficients:beta,se,t:tvals,p:pvals,r2,adjR2,rmse:Math.sqrt(mse),df:dfRes,F,pModel:F>0?fUpperP(F,p,dfRes):1,fitted,residuals:resid,n,k};
}

// ---------- non-parametric ----------
function mannWhitneyU(x,y){x=nums(x);y=nums(y);const n1=x.length,n2=y.length;if(n1<1||n2<1)throw new Error('Mann-Whitney needs data in both groups');const all=x.concat(y),ranks=rankData(all),R1=ranks.slice(0,n1).reduce((s,r)=>s+r,0);const U1=R1-n1*(n1+1)/2,U2=n1*n2-U1,U=Math.min(U1,U2);const mu=n1*n2/2,N=n1+n2,tc=tieCorrection(all),sigma=Math.sqrt((n1*n2/12)*((N+1)-tc/(N*(N-1))));const z=sigma?(U-mu)/sigma:0;return {U,U1,U2,n1,n2,z,p:sigma?2*(1-normalCdf(Math.abs(z))):1};}
function wilcoxonSignedRank(x,y){x=nums(x);y=nums(y);const n0=Math.min(x.length,y.length);let d=[];for(let i=0;i<n0;i++){const v=x[i]-y[i];if(v!==0)d.push(v);}const n=d.length;if(!n)return {W:0,z:0,p:1,n:0};const ranks=rankData(d.map(Math.abs));let Wp=0,Wm=0;for(let i=0;i<n;i++){if(d[i]>0)Wp+=ranks[i];else Wm+=ranks[i];}const W=Math.min(Wp,Wm),mu=n*(n+1)/4,sigma=Math.sqrt(n*(n+1)*(2*n+1)/24),z=sigma?(W-mu)/sigma:0;return {W,Wplus:Wp,Wminus:Wm,n,z,p:sigma?2*(1-normalCdf(Math.abs(z))):1};}
function kruskalWallis(groups){groups=(groups||[]).map(nums).filter(g=>g.length);const k=groups.length,all=[].concat(...groups),N=all.length,ranks=rankData(all);let idx=0,H=0;for(const g of groups){let R=0;for(let i=0;i<g.length;i++)R+=ranks[idx++];H+=R*R/g.length;}H=12/(N*(N+1))*H-3*(N+1);const tc=tieCorrection(all),corr=1-tc/(N*N*N-N);if(corr>0)H/=corr;const df=Math.max(1,k-1);return {H,df,groups:k,n:N,p:H>0?chiUpperP(H,df):1};}

// ---------- categorical / proportions ----------
function chiSquareTest(table){ // 2D array of observed counts
  if(!Array.isArray(table)||!Array.isArray(table[0]))throw new Error('chiSquareTest needs a 2D table');
  const r=table.length,c=table[0].length,rowSum=table.map(row=>row.reduce((s,v)=>s+v,0)),colSum=Array(c).fill(0);table.forEach(row=>row.forEach((v,j)=>colSum[j]+=v));const N=rowSum.reduce((s,v)=>s+v,0);const expected=table.map((row,i)=>row.map((_,j)=>rowSum[i]*colSum[j]/N));let chi2=0;for(let i=0;i<r;i++)for(let j=0;j<c;j++){const e=expected[i][j];if(e>0)chi2+=(table[i][j]-e)**2/e;}const df=(r-1)*(c-1);return {chi2,df,expected,p:df>0?chiUpperP(chi2,df):1};}
function abTest(successA,totalA,successB,totalB){const p1=successA/totalA,p2=successB/totalB,p=(successA+successB)/(totalA+totalB),se=Math.sqrt(p*(1-p)*(1/totalA+1/totalB)),z=se?(p1-p2)/se:0;return {pA:p1,pB:p2,difference:p1-p2,z,p:se?2*(1-normalCdf(Math.abs(z))):1};}

// ---------- simulation / diagnostics ----------
function lcg(seed){let s=(Number(seed)>>>0)||123456789;return function(){s=(1664525*s+1013904223)>>>0;return s/4294967296;};}
function bootstrapMeanCI(a,reps=2000,alpha=.05,seed=1234){a=nums(a);const rnd=lcg(seed),means=[];if(!a.length)return {n:0,mean:NaN,low:NaN,high:NaN,reps};for(let r=0;r<reps;r++){let s=0;for(let i=0;i<a.length;i++)s+=a[Math.floor(rnd()*a.length)];means.push(s/a.length);}return {n:a.length,mean:mean(a),low:quantile(means,alpha/2),high:quantile(means,1-alpha/2),reps};}
function outliersIQR(a){a=nums(a);const q1=quantile(a,.25),q3=quantile(a,.75),iqr=q3-q1,lo=q1-1.5*iqr,hi=q3+1.5*iqr;return {q1,q3,iqr,lowerFence:lo,upperFence:hi,outliers:a.filter(v=>v<lo||v>hi)};}
function randomNormal(n=100,mu=0,sigma=1,seed=123){const r=lcg(seed),a=[];for(let i=0;i<n;i++){const u1=Math.max(1e-12,r()),u2=r();a.push(mu+sigma*Math.sqrt(-2*Math.log(u1))*Math.cos(2*Math.PI*u2));}return a;}
function spc(a){a=nums(a);const m=mean(a),s=sd(a);return {center:m,ucl:m+3*s,lcl:m-3*s,violations:a.map((v,i)=>({i:i+1,value:v})).filter(o=>o.value>m+3*s||o.value<m-3*s)};}

function rocPrCurve(score,label){
  const pairs=score.map((v,i)=>[Number(v),Number(label[i])>0?1:0]).filter(p=>Number.isFinite(p[0])).sort((a,b)=>b[0]-a[0]);
  const P=pairs.filter(p=>p[1]).length, N=pairs.length-P; let tp=0,fp=0;
  const roc=[{fpr:0,tpr:0,threshold:Infinity}], pr=[];
  pairs.forEach(([threshold,lab])=>{ if(lab)tp++; else fp++; roc.push({fpr:N?fp/N:0,tpr:P?tp/P:0,threshold}); pr.push({recall:P?tp/P:0,precision:(tp+fp)?tp/(tp+fp):1,threshold}); });
  let auc=0; for(let i=1;i<roc.length;i++) auc+=(roc[i].fpr-roc[i-1].fpr)*(roc[i].tpr+roc[i-1].tpr)/2;
  let averagePrecision=0; for(let i=1;i<pr.length;i++) averagePrecision+=(pr[i].recall-pr[i-1].recall)*pr[i].precision;
  return {n:pairs.length,positive:P,negative:N,auc,averagePrecision,roc,pr};
}
function benjaminiHochberg(pvals){
  const arr=pvals.map((p,i)=>({p:Number(p),i})).filter(o=>Number.isFinite(o.p)).sort((a,b)=>a.p-b.p),m=arr.length; let prev=1;
  for(let k=m-1;k>=0;k--){const raw=arr[k].p*m/(k+1); arr[k].q=Math.min(prev,raw,1); prev=arr[k].q;}
  const q=Array(pvals.length).fill(NaN); arr.forEach(o=>q[o.i]=o.q); return q;
}
function olsInfluence(x,y){
  const reg=ols(x,y),n=reg.n,p=2,mx=mean(x),sxx=x.reduce((s,v)=>s+(v-mx)*(v-mx),0)||1,mse=reg.sse/Math.max(1,n-p);
  const leverage=x.map(v=>1/n+(v-mx)*(v-mx)/sxx);
  const standardizedResidual=reg.resid.map((e,i)=>e/Math.sqrt(Math.max(1e-12,mse*(1-leverage[i]))));
  const cooks=reg.resid.map((e,i)=>(e*e/(p*Math.max(1e-12,mse)))*(leverage[i]/Math.max(1e-12,(1-leverage[i])*(1-leverage[i]))));
  return Object.assign({},reg,{leverage,standardizedResidual,cooks});
}
function olsBands(x,y,alpha=.05){
  x=nums(x); y=nums(y); const reg=ols(x,y),n=reg.n,mx=mean(x),sxx=x.reduce((s,v)=>s+(v-mx)*(v-mx),0)||1,df=Math.max(1,n-2),tc=studentTinv(1-alpha/2,df),mse=reg.sse/df;
  return x.map((v,i)=>{const fit=reg.pred[i],seMean=Math.sqrt(mse*(1/n+(v-mx)*(v-mx)/sxx)),sePred=Math.sqrt(mse*(1+1/n+(v-mx)*(v-mx)/sxx));return {x:v,y:y[i],fit,ciLow:fit-tc*seMean,ciHigh:fit+tc*seMean,piLow:fit-tc*sePred,piHigh:fit+tc*sePred};}).sort((a,b)=>a.x-b.x);
}
function kaplanMeier(time,event){
  const arr=time.map((t,i)=>({time:Number(t),event:Number(event[i])>0?1:0})).filter(o=>Number.isFinite(o.time)).sort((a,b)=>a.time-b.time),uniq=[...new Set(arr.map(o=>o.time))].sort((a,b)=>a-b); let surv=1; const x=[0],y=[1],censored=[];
  uniq.forEach(t=>{const atRisk=arr.filter(o=>o.time>=t).length,events=arr.filter(o=>o.time===t&&o.event).length,cens=arr.filter(o=>o.time===t&&!o.event).length;if(events>0&&atRisk>0){x.push(t,t);y.push(y[y.length-1],surv*(1-events/atRisk));surv=y[y.length-1];}if(cens)censored.push({time:t,survival:surv,count:cens});});
  return {n:arr.length,events:arr.filter(o=>o.event).length,censored:arr.filter(o=>!o.event).length,x,y,censored};
}
function logRank2(time,event,group){
  const rows=time.map((t,i)=>({time:Number(t),event:Number(event[i])>0?1:0,group:String(group[i])})).filter(o=>Number.isFinite(o.time)); const keys=[...new Set(rows.map(o=>o.group))].slice(0,2); if(keys.length<2)return null; const A=rows.filter(o=>o.group===keys[0]),B=rows.filter(o=>o.group===keys[1]),eventTimes=[...new Set(rows.filter(o=>o.event).map(o=>o.time))].sort((a,b)=>a-b); let O1=0,E1=0,V=0;
  eventTimes.forEach(t=>{const n1=A.filter(o=>o.time>=t).length,n2=B.filter(o=>o.time>=t).length,n=n1+n2,d1=A.filter(o=>o.time===t&&o.event).length,d2=B.filter(o=>o.time===t&&o.event).length,d=d1+d2;if(n>1){O1+=d1;E1+=d*n1/n;V+=n1*n2*d*(n-d)/(n*n*(n-1));}});
  const chi2=V?((O1-E1)*(O1-E1)/V):0; return {groups:keys,observedA:O1,expectedA:E1,chi2,p:chiUpperP(chi2,1)};
}


const api={parseTable,nums,mean,variance,sd,sem,quantile,median,skewness,kurtosisExcess,describe,covariance,correlation,correlationMatrix,
  erf,normalCdf,normalPdf,normalInv,logGamma,regIncBeta,studentTCdf,studentTinv,tTwoTailP,fCdf,fUpperP,gammaP,chiSqCdf,chiUpperP,
  rankData,tTestOne,welchT,corTest,anovaOneWay,ols,matInverse,multipleRegression,mannWhitneyU,wilcoxonSignedRank,kruskalWallis,chiSquareTest,abTest,
  bootstrapMeanCI,outliersIQR,randomNormal,spc,rocPrCurve,benjaminiHochberg,olsInfluence,olsBands,kaplanMeier,logRank2};
if(typeof module!=='undefined'&&module.exports)module.exports=api;
root.FokoStatistics=api;

// =====================================================================
// BROWSER UI — unchanged element IDs / modes; now prints p-values.
// =====================================================================
if(typeof document==='undefined')return;
function fmt(x){return Number.isFinite(x)?(Math.abs(x)>1e4||Math.abs(x)<1e-3&&x!==0?x.toExponential(4):Number(x.toFixed(5))):String(x);}
function pStr(p){return !Number.isFinite(p)?'—':(p<1e-4?'< 0.0001':p.toFixed(4));}
function sig(p){return Number.isFinite(p)?(p<0.05?'  \u2192 significant at \u03b1=0.05':'  \u2192 not significant at \u03b1=0.05'):'';}
function formatObject(obj){return Object.entries(obj).map(([k,v])=>k+' = '+(Array.isArray(v)?JSON.stringify(v.map(x=>typeof x==='number'?Number(x.toFixed(4)):x)):fmt(v))).join('\n');}

function plotDiagnostic(plot, plotMode, table, x, y, res){ if(!window.Plotly||!plot)return; const names=table.names, cols=table.cols; const mode=plotMode==='auto'?null:plotMode; const data=[]; let layout={margin:{t:28,r:20,b:48,l:52},paper_bgcolor:'#fff',plot_bgcolor:'#fff'};
  const chosen=mode||((res&&res.pred)?'scatter':'histogram');
  const sorted=a=>a.slice().sort((p,q)=>p-q);
  if(chosen==='scatter'){data.push({x,y,mode:'markers',type:'scatter',name:'data'}); res&&res.pred&&data.push({x,y:res.pred,mode:'lines',name:'fit'});}
  else if(chosen==='line') data.push({x:x.length?x:y,y:y.length?y:x,mode:'lines+markers',type:'scatter'});
  else if(chosen==='bar') data.push({x:names.slice(0,cols.length),y:cols.map(c=>mean(c)),type:'bar'});
  else if(chosen==='box') cols.forEach((c,i)=>data.push({y:c,type:'box',name:names[i]}));
  else if(chosen==='violin') cols.forEach((c,i)=>data.push({y:c,type:'violin',box:{visible:true},meanline:{visible:true},name:names[i]}));
  else if(chosen==='heatmap') data.push({z:correlationMatrix(cols),x:names,y:names,type:'heatmap',colorscale:'Viridis',zmin:-1,zmax:1});
  else if(chosen==='bubble') data.push({x,y,mode:'markers',marker:{size:(cols[2]||y).map(v=>6+Math.abs(v)*2)},type:'scatter'});
  else if(chosen==='histogram'){const vals=cols[0]||[];data.push({x:vals,type:'histogram',histnorm:'probability density',name:'histogram'});if(vals.length>2){const m=mean(vals),s=sd(vals)||1,min=Math.min(...vals),max=Math.max(...vals),grid=Array.from({length:80},(_,i)=>min+(max-min)*i/79);const bw=1.06*s*Math.pow(vals.length,-0.2)||1;const dens=grid.map(g=>vals.reduce((acc,v)=>acc+normalPdf((g-v)/bw)/bw,0)/vals.length);data.push({x:grid,y:dens,mode:'lines',type:'scatter',name:'KDE'});}}
  else if(chosen==='splom'){data.push({type:'splom',dimensions:cols.map((c,i)=>({label:names[i]||('V'+(i+1)),values:c})),diagonal:{visible:true},showupperhalf:true});layout.height=520;}
  else if(chosen==='qq'){const s=sorted(x.length?x:cols[0]||[]),n=s.length,m=mean(s),sdv=sd(s)||1,theo=s.map((_,i)=>m+sdv*normalInv((i+0.5)/n));data.push({x:theo,y:s,mode:'markers',type:'scatter',name:'Q-Q'});data.push({x:[Math.min(...theo),Math.max(...theo)],y:[Math.min(...theo),Math.max(...theo)],mode:'lines',name:'y=x',line:{dash:'dash'}});layout.xaxis={title:'theoretical'};layout.yaxis={title:'sample'};}
  else if(chosen==='ecdf'){const s=sorted(x.length?x:cols[0]||[]),n=s.length;data.push({x:s,y:s.map((_,i)=>(i+1)/n),mode:'lines+markers',type:'scatter',name:'ECDF'});layout.yaxis={title:'F(x)',range:[0,1]};}
  else if(chosen==='pareto'){const vals=cols[0]||[];const counts={};vals.forEach(v=>counts[v]=(counts[v]||0)+1);const entries=Object.entries(counts).sort((a,b)=>b[1]-a[1]);let cum=0,total=vals.length;data.push({x:entries.map(e=>e[0]),y:entries.map(e=>e[1]),type:'bar',name:'count'});data.push({x:entries.map(e=>e[0]),y:entries.map(e=>(cum+=e[1])/total*100),type:'scatter',mode:'lines+markers',name:'cumulative %',yaxis:'y2'});layout.yaxis2={overlaying:'y',side:'right',range:[0,100]};}
  else if(chosen==='residual'&&res&&(res.resid||res.residuals)) data.push({x:res.pred||res.fitted,y:res.resid||res.residuals,mode:'markers',type:'scatter',name:'residuals'});
  else data.push({x:cols[0]||[],type:'histogram',name:names[0]||'values'});
  Plotly.newPlot(plot,data,layout,{responsive:true,displaylogo:false}); }

function boot(){const el=document.querySelector('[data-statistics-lab]');if(!el)return;const $=id=>document.getElementById(id);const input=$('statsData'),namesEl=$('statsNames'),missing=$('statsMissing'),mode=$('statsMode'),plotMode=$('statsPlotMode'),out=$('statsOutput'),plot=$('statsPlot'),script=$('statsScript');
  const run=()=>{const table=parseTable(input.value,namesEl.value,missing.value);const xi=Number($('statsX').value)-1,yi=Number($('statsY').value)-1,gi=Number($('statsGroup').value)-1;const x=table.cols[xi]||[],y=table.cols[yi]||[];let res,txt='';
    try{
      if(mode.value==='regression'&&y.length){res=ols(x,y);txt='Linear regression (Y ~ X)\n'+formatObject({intercept:res.intercept,slope:res.slope,seSlope:res.seSlope,tSlope:res.tSlope,pSlope:res.pSlope,r2:res.r2,rmse:res.rmse,n:res.n})+'\n95% CI(slope) = ['+fmt(res.ciSlope[0])+', '+fmt(res.ciSlope[1])+']'+sig(res.pSlope);}
      else if(mode.value==='mregression'){const yv=table.rows.map(r=>r[yi]);const Xrows=table.rows.map(r=>r.filter((_,j)=>j!==yi).slice(0,4));res=multipleRegression(Xrows,yv);txt='Multiple linear regression\ncoefficients (intercept first) = '+res.coefficients.map(fmt).join(', ')+'\nse = '+res.se.map(fmt).join(', ')+'\np  = '+res.p.map(pStr).join(', ')+'\nR2 = '+fmt(res.r2)+'  adjR2 = '+fmt(res.adjR2)+'  F = '+fmt(res.F)+'  pModel = '+pStr(res.pModel)+sig(res.pModel);res.pred=res.fitted;res.resid=res.residuals;}
      else if(mode.value==='ttest1'){res=tTestOne(x,Number($('statsGroup').value)||0);txt='One-sample t-test (\u03bc\u2080 = Group field)\n'+formatObject({mean:res.mean,mu0:res.mu0,t:res.t,df:res.df,p:res.p})+sig(res.p);}
      else if(mode.value==='welch'&&y.length){res=welchT(x,y);txt='Welch two-sample t-test\n'+formatObject({meanA:res.meanA,meanB:res.meanB,difference:res.difference,t:res.t,df:res.df,p:res.p})+sig(res.p);}
      else if(mode.value==='correlation'){const M=correlationMatrix(table.cols);let extra='';if(y.length){const ct=corTest(x,y);extra='\nX\u2013Y: r='+fmt(ct.r)+', t='+fmt(ct.t)+', df='+ct.df+', p='+pStr(ct.p)+sig(ct.p);}res=M;txt='Correlation matrix\n'+M.map(row=>row.map(fmt).join('\t')).join('\n')+extra;}
      else if(mode.value==='anova'){const groups={};table.rows.forEach(r=>{const g=r[gi]??0;(groups[g]=groups[g]||[]).push(r[yi]??r[0]);});res=anovaOneWay(Object.values(groups));txt='One-way ANOVA\n'+formatObject({groups:res.groups,F:res.F,dfBetween:res.dfBetween,dfWithin:res.dfWithin,p:res.p})+sig(res.p);}
      else if(mode.value==='kruskal'){const groups={};table.rows.forEach(r=>{const g=r[gi]??0;(groups[g]=groups[g]||[]).push(r[yi]??r[0]);});res=kruskalWallis(Object.values(groups));txt='Kruskal\u2013Wallis test\n'+formatObject({H:res.H,df:res.df,groups:res.groups,p:res.p})+sig(res.p);}
      else if(mode.value==='mannwhitney'){res=mannWhitneyU(x,y);txt='Mann\u2013Whitney U test\n'+formatObject({U:res.U,z:res.z,p:res.p})+sig(res.p);}
      else if(mode.value==='wilcoxon'){res=wilcoxonSignedRank(x,y);txt='Wilcoxon signed-rank test\n'+formatObject({W:res.W,n:res.n,z:res.z,p:res.p})+sig(res.p);}
      else if(mode.value==='chisq'){res=chiSquareTest(table.rows.map(r=>r.map(v=>Math.max(0,Math.round(v)))));txt='Chi-square test of independence (table = numeric rows)\n'+formatObject({chi2:res.chi2,df:res.df,p:res.p})+sig(res.p);}
      else if(mode.value==='bootstrap'){res=bootstrapMeanCI(x,Number($('statsReps').value)||2000,.05,Number($('statsSeed').value)||1234);txt='Bootstrap mean 95% CI\n'+formatObject(res);}
      else if(mode.value==='outliers'){res=outliersIQR(x);txt='IQR outlier detection\n'+formatObject(res);}
      else if(mode.value==='abtest'){res=abTest(x[0]||1,x[1]||10,y[0]||1,y[1]||10);txt='A/B test for proportions (X = successes,total for A; Y = successes,total for B)\n'+formatObject(res)+sig(res.p);}
      else if(mode.value==='simulate'){const sim=randomNormal(200,mean(x),sd(x)||1,Number($('statsSeed').value)||1234);res=describe(sim);txt='Random normal simulation from first-column mean/sd\n'+formatObject(res);table.cols=[sim];table.names=['simulation'];}
      else if(mode.value==='spc'){res=spc(x);txt='Quality-control (3\u03c3) chart\n'+formatObject(res);}
      else {res=describe(x);txt='Descriptive statistics for '+(table.names[xi]||'column '+(xi+1))+'\n'+formatObject(res);}
    }catch(err){txt='Error: '+(err&&err.message?err.message:err);res=null;}
    out.textContent=txt;
    script.textContent=JSON.stringify({tool:'Foko Statistics Lab',dataset:$('statsName').value,missingPolicy:missing.value,task:mode.value,plot:plotMode.value,variables:table.names,columns:{x:xi+1,y:yi+1,group:gi+1},seed:Number($('statsSeed').value)},null,2);
    plotDiagnostic(plot,plotMode.value,table,x,y,res);};
  $('statsRun').addEventListener('click',run);
  $('statsExport').addEventListener('click',()=>navigator.clipboard&&navigator.clipboard.writeText(script.textContent));
  run();}
(document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot());
}(typeof window!=='undefined'?window:globalThis));
