/* Foko Lab v72.16 model intermediate representation.
 * Project-owned, dependency-free schema inspired by the uploaded mxlweb-core
 * separation between model definition, lowering and numerical execution.
 */
(function (root, factory) {
  const api=factory(); if(typeof module!=='undefined'&&module.exports)module.exports=api; root.FokoModelIR=api;
}(typeof window!=='undefined'?window:globalThis,function(){
  'use strict';
  const IDENT=/^[A-Za-z_][A-Za-z0-9_]*$/;
  function clone(x){return JSON.parse(JSON.stringify(x));}
  function identifier(value,label){const x=String(value||'').trim();if(!IDENT.test(x))throw new Error((label||'identifier')+' must start with a letter or underscore and contain only letters, numbers and underscores.');return x;}
  function finite(value,label){const x=Number(value);if(!Number.isFinite(x))throw new Error((label||'value')+' must be finite.');return x;}
  function expression(value,label){const x=String(value==null?'':value).trim();if(!x)throw new Error((label||'expression')+' is required.');if(/[;{}\[\]`]/.test(x))throw new Error((label||'expression')+' contains unsupported control characters.');return x;}
  function normalizeParameter(value,name){if(typeof value==='number')return [finite(value,name),finite(value,name),finite(value,name)];if(Array.isArray(value)){const v=finite(value[0],name),lo=finite(value[1]==null?v:value[1],name+' minimum'),hi=finite(value[2]==null?v:value[2],name+' maximum');if(lo>hi)throw new Error(name+' minimum exceeds maximum.');return [v,lo,hi];}if(value&&typeof value==='object'){const v=finite(value.value,name),lo=finite(value.min==null?v:value.min,name+' minimum'),hi=finite(value.max==null?v:value.max,name+' maximum');if(lo>hi)throw new Error(name+' minimum exceeds maximum.');return [v,lo,hi];}throw new Error('Invalid parameter '+name+'.');}
  function normalizeStates(raw){const states=Array.isArray(raw)?raw:[];if(!states.length)throw new Error('Model IR requires at least one state.');const out=states.map(function(item,index){if(typeof item==='string')return {id:identifier(item,'state '+(index+1)),initial:0};return {id:identifier(item&&item.id,'state '+(index+1)),initial:finite(item&&item.initial==null?0:item.initial,'initial value for state '+(index+1))};});if(new Set(out.map(function(row){return row.id;})).size!==out.length)throw new Error('Model IR state identifiers must be unique.');return out;}
  function normalizeParameters(raw){const out={};Object.keys(raw||{}).sort().forEach(function(key){const id=identifier(key,'parameter');out[id]=normalizeParameter(raw[key],id);});return out;}
  function directOde(ir,states,params){const equations=ir.equations||ir.dxdt||{};const eqs=states.map(function(state){if(!(state.id in equations))throw new Error('Missing equation for state '+state.id+'.');return expression(equations[state.id],'equation for '+state.id);});return {module:'ode',model:{name:String(ir.name||'Imported Model IR'),vars:states.map(function(row){return row.id;}),eqs:eqs,y0:states.map(function(row){return row.initial;}),params:params,t0:finite(ir.time&&ir.time.start==null?0:ir.time.start,'start time'),t1:finite(ir.time&&ir.time.end==null?20:ir.time.end,'end time'),points:Math.max(20,Math.floor(finite(ir.time&&ir.time.points==null?800:ir.time.points,'points'))),method:String(ir.method||'rk45'),narrative:String(ir.description||'Imported direct-ODE Model IR.')}};}
  function reactionNetwork(ir,states,params){const stateSet=new Set(states.map(function(row){return row.id;}));const reactions=Array.isArray(ir.reactions)?ir.reactions:[];if(!reactions.length)throw new Error('Reaction-network Model IR requires at least one reaction.');const terms={};states.forEach(function(row){terms[row.id]=[];});reactions.forEach(function(reaction,index){const id=identifier(reaction&&reaction.id||('r'+(index+1)),'reaction '+(index+1));const rate=expression(reaction&&reaction.rate,'rate for '+id);const stoich=reaction&&reaction.stoichiometry;if(!stoich||typeof stoich!=='object'||Array.isArray(stoich))throw new Error('Reaction '+id+' requires a stoichiometry object.');Object.keys(stoich).forEach(function(name){if(!stateSet.has(name))throw new Error('Reaction '+id+' references unknown state '+name+'.');const coeff=finite(stoich[name],'stoichiometry '+id+'/'+name);if(coeff!==0)terms[name].push((coeff===1?'':coeff===-1?'-':'('+coeff+')*')+'('+rate+')');});});const eqs=states.map(function(row){const values=terms[row.id];return values.length?values.join(' + ').replace(/\+ -/g,'- '):'0';});return {module:'ode',model:{name:String(ir.name||'Imported reaction network'),vars:states.map(function(row){return row.id;}),eqs:eqs,y0:states.map(function(row){return row.initial;}),params:params,t0:finite(ir.time&&ir.time.start==null?0:ir.time.start,'start time'),t1:finite(ir.time&&ir.time.end==null?20:ir.time.end,'end time'),points:Math.max(20,Math.floor(finite(ir.time&&ir.time.points==null?800:ir.time.points,'points'))),method:String(ir.method||'rk45'),narrative:String(ir.description||'Reaction network lowered to dx/dt = N·v using Foko Model IR.'),modelIR:{schema:'foko.model-ir/1',kind:'reaction-network',reactionCount:reactions.length}}};}
  function isModelIR(raw){return !!(raw&&typeof raw==='object'&&(raw.schema==='foko.model-ir/1'||raw.kind==='reaction-network'||raw.kind==='direct-ode')&&Array.isArray(raw.states));}
  function lower(raw){const ir=clone(raw||{});if(!isModelIR(ir))throw new Error('Not a supported Foko Model IR document.');const states=normalizeStates(ir.states),params=normalizeParameters(ir.parameters||{}),kind=String(ir.kind||'direct-ode').toLowerCase();if(kind==='reaction-network')return reactionNetwork(ir,states,params);if(kind==='direct-ode'||kind==='ode')return directOde(ir,states,params);throw new Error('Unsupported Model IR kind: '+kind+'.');}
  return {isModelIR:isModelIR,lower:lower,version:'1'};
}));
