/* Bellman–Harris variant: fate is drawn at birth; lifetime is conditional on fate.
 * This is distinct from Cyton competing independent division/death clocks.
 */
(function(root){
'use strict';
const core=typeof module!=='undefined'&&module.exports?require('../shared/linear-network.js'):root.LinearNetwork;
const spec={id:'tcell-age-dependent-branching',version:1,title:'Age-dependent binary branching',source:'Age-dependent branching model family reviewed in Foko Kuate (2016), section 2.2. Explicit Bellman–Harris variant specified in the app; not a claimed reproduction of a fitted thesis model.',timeUnit:'h',parameterStatus:'Illustrative; not fitted',solver:'Individual event scheduling; discretized renewal moment equations'};
function validate(c){if(c.rest&&(c.rest.length!==c.generations+1||c.rest.some((q,i)=>!Number.isFinite(q)||q<0||q>1||q+c.probability[i]>1+1e-12)))throw Error('For each generation: division probability + quiescent probability must not exceed 1.');for(const [k,lo,hi]of [['initial',1,50],['generations',0,8],['repetitions',2,500],['hours',1,240],['seed',0,4294967295],['shape',1,20]])if(!Number.isInteger(c[k])||c[k]<lo||c[k]>hi)throw Error(`${k} must be an integer between ${lo} and ${hi}.`);for(const k of ['firstMean','divisionMean','deathMean'])if(!Number.isFinite(c[k])||c[k]<.5||c[k]>240)throw Error('Mean lifetimes must be between 0.5 and 240 hours.');if(c.deathDistribution&&!['same','erlang','lognormal','fixed','exponential'].includes(c.deathDistribution))throw Error('Unknown death lifetime distribution.');if(!['erlang','lognormal','fixed','exponential'].includes(c.distribution))throw Error('Unknown lifetime distribution.');if(!Number.isFinite(c.cv)||c.cv<.1||c.cv>2)throw Error('Lognormal CV must be between 0.1 and 2.');if(!Array.isArray(c.probability)||c.probability.length!==c.generations+1||c.probability.some(p=>!Number.isFinite(p)||p<0||p>1)||c.probability[c.generations]!==0)throw Error('Division probabilities must be in [0, 1], with p = 0 at generation h.');}
function normal(random){return Math.sqrt(-2*Math.log(1-random()))*Math.cos(2*Math.PI*random());}
function lifetime(c,mean,random){if(c.distribution==='fixed')return mean;if(c.distribution==='exponential')return-mean*Math.log(1-random());if(c.distribution==='erlang'){let v=0;for(let i=0;i<c.shape;i++)v-=Math.log(1-random());return v*mean/c.shape;}const s=Math.sqrt(Math.log1p(c.cv*c.cv));return Math.exp(Math.log(mean)-s*s/2+s*normal(random));}
function erf(x){const sign=x<0?-1:1;x=Math.abs(x);const t=1/(1+.3275911*x);return sign*(1-(((((1.061405429*t-1.453152027)*t)+1.421413741)*t-.284496736)*t+.254829592)*t*Math.exp(-x*x));}
function cdf(c,t,mean){if(t<=0)return 0;if(c.distribution==='fixed')return t+1e-12>=mean?1:0;if(c.distribution==='exponential')return-Math.expm1(-t/mean);if(c.distribution==='lognormal'){const s=Math.sqrt(Math.log1p(c.cv*c.cv));return .5*(1+erf((Math.log(t)-Math.log(mean)+s*s/2)/(s*Math.SQRT2)));}const x=t*c.shape/mean;let term=1,sum=1;for(let j=1;j<c.shape;j++){term*=x/j;sum+=term;}return Math.max(0,Math.min(1,1-Math.exp(-x)*sum));}
class Heap{constructor(){this.a=[];}push(e){let i=this.a.length;this.a.push(e);while(i>0){const p=(i-1)>>1;if(this.a[p].end<=e.end)break;this.a[i]=this.a[p];i=p;}this.a[i]=e;}pop(){const first=this.a[0],last=this.a.pop();if(this.a.length){let i=0;while(i*2+1<this.a.length){let j=i*2+1;if(j+1<this.a.length&&this.a[j+1].end<this.a[j].end)j++;if(this.a[j].end>=last.end)break;this.a[i]=this.a[j];i=j;}this.a[i]=last;}return first;}get length(){return this.a.length;}peek(){return this.a[0];}}
function deathConfig(c){return {...c,distribution:(!c.deathDistribution||c.deathDistribution==='same')?c.distribution:c.deathDistribution};}
function trajectory(c,times,random,record,budget){const g=c.generations+1,counts=Array(2*g).fill(0),heap=new Heap(),cells=[],events=[{time:0,total:c.initial,q:0,a:c.initial,dead:0,divisions:0}],samples=[];let nextId=0,dead=0,divisions=0,total=c.initial;
 function birth(generation,born,parent,founder){const id=nextId++;let fate,wait;const rest=c.model==='cyton'?0:(c.rest?.[generation]||0);const meanDiv=generation===0?c.firstMean:c.divisionMean;if(c.model==='cyton'){const competent=random()<c.probability[generation],td=competent?lifetime(c,meanDiv,random):Infinity,tx=lifetime(deathConfig(c),c.deathMean,random);fate=td<tx?'division':'death';wait=Math.min(td,tx);}else{const u=random();fate=u<c.probability[generation]?'division':u<c.probability[generation]+rest?'quiescent':'death';wait=fate==='quiescent'?Infinity:lifetime(fate==='death'?deathConfig(c):c,fate==='division'?meanDiv:c.deathMean,random);}const end=born+wait;const cell={id,parent,founder,generation,born,activated:fate==='quiescent'?null:born,end:fate==='quiescent'?null:end,fate,children:[]};if(fate!=='quiescent')heap.push(cell);counts[(fate==='quiescent'?0:g)+generation]++;if(record)cells.push(cell);return id;}
 for(let i=0;i<c.initial;i++)birth(0,0,null,i);events[0].q=counts.slice(0,g).reduce((a,b)=>a+b,0);events[0].a=c.initial-events[0].q;
 for(const time of times){while(heap.length&&heap.peek().end<=time){if(--budget.remaining<0)throw Error('Experiment exceeds 2,000,000 events. Reduce founders, generations, duration or repetitions. No partial ensemble is reported.');const cell=heap.pop();counts[g+cell.generation]--;if(cell.fate==='division'){divisions++;total++;for(let k=0;k<2;k++){const id=birth(cell.generation+1,cell.end,cell.id,cell.founder);if(record)cell.children.push(id);}}else{dead++;total--;}if(record)events.push({time:cell.end,total,q:counts.slice(0,g).reduce((a,b)=>a+b,0),a:counts.slice(g).reduce((a,b)=>a+b,0),dead,divisions});}samples.push(counts.slice());}
 // Do not expose assigned future fates as observed events in exports/animation.
 if(record)for(const cell of cells)if(cell.end>c.hours){cell.end=null;cell.fate=null;}
 return{samples,cells,events};
}
function renewal(c,steps){
 if(c.model==='kimmel')steps=c.hours;const g=c.generations+1,dt=c.hours/steps,L=steps+1;let child=null;
 for(let start=g-1;start>=0;start--){const p=c.probability[start],q=c.model==='cyton'?0:(c.rest?.[start]||0),mean=start===0?c.firstMean:c.divisionMean,S=new Float64Array(L),mass=new Float64Array(L);for(let t=0;t<L;t++){const fd=cdf(c,t*dt,mean),fx=cdf(deathConfig(c),t*dt,c.deathMean);S[t]=c.model==='cyton'?(1-fx)*(1-p*fd):Math.max(0,1-p*fd-(1-p-q)*fx);if(t){mass[t]=Math.max(0,fd-cdf(c,(t-1)*dt,mean));if(c.model==='cyton'){const age=c.distribution==='fixed'?mean:(t-.5)*dt;mass[t]*=1-cdf(deathConfig(c),age,c.deathMean);}}}
  const means=Array.from({length:g+1},()=>new Float64Array(L)),second=Array.from({length:g+1},()=>new Float64Array(L));
  for(let target=start;target<=g;target++){const own=target===start||target===g;for(let t=0;t<L;t++){let m=own?S[t]:0,s=m;if(child&&p>0){const cm=child.means[target],cs=child.second[target];for(let j=1;j<=t;j++){const w=p*mass[j],u=t-j;m+=2*w*cm[u];s+=2*w*(cs[u]+cm[u]*cm[u]);}}means[target][t]=m;second[target][t]=s;}}
  child={means,second};
 }
 return Array.from({length:121},(_,i)=>{const t=c.model==='kimmel'?Math.floor(i*steps/120+1e-10):i*steps/120,m=child.means[g][t],s=child.second[g][t];return{totalMean:c.initial*m,totalVar:c.initial*Math.max(0,s-m*m),generationMean:Array.from({length:g},(_,k)=>c.initial*child.means[k][t]),generationVar:Array.from({length:g},(_,k)=>c.initial*Math.max(0,child.second[k][t]-child.means[k][t]**2))};});
}
function experiment(c,progress=()=>{}){if(c.model==='kimmel')c={...c,distribution:'fixed',deathDistribution:'fixed',firstMean:1,divisionMean:1,deathMean:1};validate(c);const g=c.generations+1,times=Array.from({length:121},(_,i)=>c.hours*i/120);let steps=960,coarse=renewal(c,480),theory=renewal(c,steps),resolutionDifference;while(true){resolutionDifference=0;for(let i=0;i<121;i++)for(const k of ['totalMean','totalVar'])resolutionDifference=Math.max(resolutionDifference,Math.abs(coarse[i][k]-theory[i][k])/Math.max(1,Math.abs(theory[i][k])));if(resolutionDifference<=.01||steps>=3840)break;coarse=theory;steps*=2;theory=renewal(c,steps);}
 const summary=times.map(()=>({mean:0,M2:0,generationMean:Array(g).fill(0),generationM2:Array(g).fill(0)})),budget={remaining:2000000},finals=[];let first,cells,events,second,secondCells,secondEvents;
 for(let r=0;r<c.repetitions;r++){const tr=trajectory(c,times,core.rng((c.seed+Math.imul(r,2654435761))>>>0),r<2,budget);if(r===0){first=tr.samples;cells=tr.cells;events=tr.events;}if(r===1){second=tr.samples;secondCells=tr.cells;secondEvents=tr.events;}finals.push(tr.samples.at(-1).reduce((a,b)=>a+b,0));tr.samples.forEach((row,j)=>{const s=summary[j],v=row.reduce((a,b)=>a+b,0),d=v-s.mean;s.mean+=d/(r+1);s.M2+=d*(v-s.mean);for(let i=0;i<g;i++){const n=row[i]+row[g+i],delta=n-s.generationMean[i];s.generationMean[i]+=delta/(r+1);s.generationM2[i]+=delta*(n-s.generationMean[i]);}});if(r%5===0||r===c.repetitions-1)progress({done:r+1,total:c.repetitions});}
 return{specification:c.model==='cyton'?{...spec,id:'tcell-cyton',title:'Cyton competing-clock model',source:'Cyton model family reviewed in Foko Kuate (2016), section 2.2. Minimal independent division/death clocks and generation-specific proliferation fraction; no inherited division destiny.'}:c.model==='kimmel'?{...spec,id:'tcell-multitype-galton-watson',title:'Multitype Galton–Watson · Kimmel–Axelrod framework',timeUnit:'cycle',source:'Kimmel–Axelrod branching-process framework as reviewed in Foko Kuate (2016), pp. 14–15. Explicit independent three-fate discrete-cycle variant, not a claimed fitted original parameterization.',solver:'Individual synchronous events; exact discrete renewal moments'}:{...spec,title:'Bellman–Harris · three-fate age-dependent branching',source:'Three-fate age-dependent branching family reviewed in Foko Kuate (2016), pp. 14–15. Dying, permanently quiescent and dividing types; independent daughters.'},config:c,times,theory,reference:{exactDiscrete:c.model==='kimmel',method:'Renewal equations with interval masses assigned to right endpoints',steps,comparisonSteps:steps/2,stepHours:c.hours/steps,comparisonStepHours:c.hours/(steps/2),resolutionDifference,converged:resolutionDifference<=.01},summary:summary.map(s=>({mean:s.mean,variance:s.M2/(c.repetitions-1),generationMean:s.generationMean,generationVariance:s.generationM2.map(v=>v/(c.repetitions-1))})),first,cells,events,second,secondCells,secondEvents,finals,eventsSimulated:2000000-budget.remaining};}
const api={specification:spec,validate,lifetime,cdf,trajectory,renewal,experiment};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.AgeBranching=api;
})(globalThis);
