from pathlib import Path
import json,subprocess
R=Path(__file__).resolve().parents[1];S=R/'site'
reg=json.loads(subprocess.check_output(['node','-e',f"console.log(JSON.stringify(require({str(S/'src/upgrade/registry.js')!r})))"]))
for lab in reg['labs']:
 html='''<!doctype html><html lang="en" data-appearance="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>__TITLE__ · FokoLab</title><meta name="description" content="__DESCRIPTION__"><link rel="icon" href="assets/brand/foko-lab-micro.svg"><link rel="stylesheet" href="styles/v72-tokens.css"><link rel="stylesheet" href="styles/v72-lab-shell.css"><link rel="stylesheet" href="styles/v76-system.css"><link rel="stylesheet" href="styles/identity.css"><link rel="stylesheet" href="styles/upgrade.css"></head>
<body class="u-page" data-lab="__ID__" data-upgrade-lab="__ID__" data-page-key="__PAGE__" data-color-family="__FAMILY__"><a class="skip-link" href="#workbench">Skip to experiment</a><header class="topbar"></header>
<section class="u-heading"><div><p class="u-eyebrow">FokoLab · __AREA__</p><h1>__TITLE__</h1><p>__DESCRIPTION__</p></div><nav class="u-crosslinks" aria-label="Related workspaces"><a href="labs.html">All laboratories</a><a href="studio.html">Model Studio</a><a href="examples.html">Model Atlas</a><a href="workspace.html">Connected research</a></nav></section>
<form class="u-commandbar" id="experimentToolbar"><label>Example<select id="u-example"></select></label><label id="u-model-label" hidden>Model<select id="u-model"></select></label><label>Method<select id="u-method"></select></label><label><span id="u-duration-label">Duration</span><input id="u-duration" type="number" min="0.001" step="any" required></label><div class="u-runbuttons"><button type="submit" class="u-primary" id="u-run">Run</button><button type="button" id="u-cancel" disabled>Cancel</button><button type="button" id="u-pin" disabled title="Keep the current result and its inputs as an explicit comparison baseline">Pin comparison</button></div></form>
<main class="u-lab-layout" id="workbench"><aside class="u-parameters" aria-label="Experiment settings"><details class="u-mobile-parameters u-card" id="u-settings" open><summary>Experiment settings</summary><div id="u-climate" class="u-scenario" hidden><label class="u-small" for="u-location">Illustrative location preset</label><select id="u-location" style="width:100%;margin-top:5px"></select><p class="u-small u-muted">Sets forcing parameters only. It never resets water, nitrogen or biomass.</p></div><div id="u-fields"></div><details><summary>Numerical settings</summary><div class="u-field"><label for="u-t0">Start time</label><input id="u-t0" type="number" value="0" step="any"></div><div class="u-field"><label for="u-step">Maximum transfer / initial solver step</label><input id="u-step" type="number" min="0" step="any"></div><div class="u-field"><label for="u-samples">Stored samples</label><input id="u-samples" type="number" min="20" max="1500" value="241"></div><div class="u-field"><label for="u-seed">Random seed</label><input id="u-seed" type="number" min="0" max="4294967295" value="42"></div><div class="u-field"><label for="u-rtol">Relative tolerance (ODE)</label><input id="u-rtol" type="number" value="0.0000001" step="any"></div><div class="u-field"><label for="u-atol">Absolute tolerance (ODE)</label><input id="u-atol" type="number" value="0.000000001" step="any"></div><p class="u-small u-muted">Integration and output sampling are different. Discrete stochastic kernels use exact declared generation/event rules; ODE tolerances do not apply to them.</p></details><details id="u-weather-details" hidden><summary>Measured weather</summary><p class="u-small">Numeric CSV: day, temperature_C, rain_mm_day, light_umol_m2_s. Time must cover the entire experiment. Rain is a rate, not a cumulative amount.</p><input id="u-weather-file" type="file" accept=".csv"><button id="u-weather-clear" type="button">Use preset forcing</button><p id="u-weather-status" class="u-small"></p></details></details>
<div class="u-card"><h2>Keep the experiment</h2><div class="u-exportbar"><button id="u-save">Save inputs</button><button id="u-restore">Restore inputs</button></div><label class="u-small">Load experiment JSON<input id="u-import" type="file" accept=".json" style="width:100%;font-size:11px;margin-top:6px"></label><p id="u-save-status" class="u-small u-muted">Browser storage is local. Export JSON for a portable record.</p></div>
<details id="u-model-editor" class="u-card" hidden><summary>Equations, initial states & import</summary><p class="u-small">Original model schema, JSON, text, dictionary, YAML, CSV and strict SBML imports use the retained 79.1 parser. Unsupported constructs are rejected.</p><textarea id="u-model-json" rows="13" spellcheck="false"></textarea><div class="u-exportbar"><button id="u-apply-model">Apply model</button><button id="u-to-studio">Open in Model Studio</button></div><input id="u-model-file" type="file" accept=".txt,.json,.yaml,.yml,.csv,.xml,.sbml,.py,.js"><p id="u-model-status" class="u-small"></p></details></aside>
<section class="u-results" aria-label="Results"><div class="u-resulthead"><div id="u-status" class="u-state" data-state="ready" role="status" aria-live="polite">Ready · choose inputs, then Run</div><div class="u-tabs" role="tablist" aria-label="Result workspace"><button id="u-tab-results" data-tab="results" role="tab" aria-selected="true">Results</button><button id="u-tab-data" data-tab="data" role="tab" aria-selected="false">Data & export</button><button id="u-tab-methods" data-tab="methods" role="tab" aria-selected="false">Model & methods</button></div></div><div id="u-message" class="u-message" hidden role="status"></div>
<div id="u-panel-results" role="tabpanel" aria-labelledby="u-tab-results"><div class="u-plotcontrols"><div class="u-tabs" aria-label="Plot layout"><button id="u-two" aria-pressed="true">Two-up</button><button id="u-focus" aria-pressed="false">Focus</button></div><div class="u-play"><button id="u-play" disabled title="Reveal already computed points. This does not recalculate the model.">Play</button><label class="u-small" for="u-speed">Speed</label><select id="u-speed"><option value="1">1×</option><option value="2">2×</option><option value="4">4×</option></select><input type="range" min="0" max="1000" value="1000" id="u-scrub" aria-label="Playback position" disabled><span id="u-time" class="u-small"></span></div></div><div id="u-legend" class="u-pathway-legend" hidden><span style="--dot:#367fa0">C3 landmark</span><span style="--dot:#b98235">C3–C4 intermediate landmark</span><span style="--dot:#477647">C4 landmark</span></div><div id="u-compare" class="u-message" hidden></div><div class="u-twoplot" id="u-plots" data-layout="two">__PLOTS__</div><div class="u-metrics" id="u-metrics"></div><div id="u-animation" class="u-card u-anim" hidden><canvas id="u-canvas" width="700" height="420" aria-label="State-derived simulation view"></canvas><div><h3 id="u-animation-title">State-derived view</h3><p id="u-animation-text" class="u-small u-muted"></p><p class="u-small u-muted">Geometry is an illustration of the computed state, not a measured anatomical or spatial reconstruction.</p></div></div><div class="u-warnings" id="u-warnings"><p>__SCOPE__</p></div></div>
<div id="u-panel-data" role="tabpanel" aria-labelledby="u-tab-data" hidden><div class="u-card"><h2>Current result & provenance</h2><p id="u-provenance" class="u-small u-muted">No calculation has been performed.</p><div class="u-exportbar"><button id="u-json" disabled>Experiment JSON</button><button id="u-csv" disabled>Results CSV</button><button id="u-python" disabled>Python reference</button><button id="u-html" disabled>Figure HTML</button></div><div class="u-tablewrap"><table><thead id="u-table-head"></thead><tbody id="u-table-body"></tbody></table></div><div class="u-exportbar"><button id="u-prev">Previous rows</button><span id="u-table-page" class="u-small"></span><button id="u-next">Next rows</button></div><details><summary>Overlay observations</summary><p class="u-small">Upload a finite numeric CSV. The first column is the plotted x coordinate; subsequent columns are observations. Confirm matching units before interpreting agreement. This overlay is not a fit.</p><input id="u-observations" type="file" accept=".csv"><button id="u-observations-clear">Clear overlay</button><p id="u-observations-status" class="u-small"></p></details></div></div>
<div id="u-panel-methods" role="tabpanel" aria-labelledby="u-tab-methods" class="u-card u-methods" hidden><h2>Assumptions, equations & sources</h2><p>__SCOPE__</p><div id="u-equations"></div><dl id="u-references"></dl><div class="u-exportbar"><a class="u-button" href="book.html">V6.17 book</a><a class="u-button" href="programme.html">Research programme</a><a class="u-button" href="docs.html">Full platform documentation</a><a class="u-button" href="trust.html">Method boundaries</a></div></div>
</section></main><footer class="u-foot"><span>FokoLab · Dr. Chilperic Armel Foko Kuate</span><span>79.2.0 · browser calculations · no account required</span></footer>
<script src="src/platform/storage.js"></script><script src="assets/vendor/plotly/plotly-2.35.2.min.js"></script><script src="assets/vendor/mathjs/math-15.2.0.js"></script><script src="src/core/model-ir.js"></script><script src="src/core/model-import.js"></script><script src="src/core/project.js"></script><script src="src/core/ode.js"></script><script src="src/core/studio-compute.js"></script><script src="src/upgrade/registry.js"></script><script src="src/upgrade/preserved-models.js"></script><script src="src/v76/app-shell.js"></script><script src="src/upgrade/common.js"></script><script type="module" src="src/upgrade/lab-ui.mjs"></script></body></html>'''
 plots=''.join(f'<article class="u-plotcard" id="u-{side}-card"><div class="u-plot-title"><label class="u-small" for="u-{side}-select">{side.title()} view</label><select id="u-{side}-select" aria-label="{side.title()} plot"><option>Compute a result</option></select></div><div class="u-plot" id="u-{side}-plot"><div class="u-plot-empty">Run the experiment to inspect computed data.</div></div><div class="u-figureactions"><button data-image="{side}:svg">SVG</button><button data-image="{side}:png">PNG</button></div></article>' for side in ['left','right'])
 values={'TITLE':lab['title'],'DESCRIPTION':lab['description'],'ID':lab['id'],'PAGE':lab['route'][:-5],'FAMILY':lab['family'],'AREA':'Living systems' if lab['family']=='living' else 'Dynamics & mathematical structure','PLOTS':plots,'SCOPE':lab['scope']}
 for key,val in values.items():html=html.replace('__'+key+'__',val)
 (S/lab['route']).write_text(html)
