/* Curated optimization presets for the v72.3 reference lab.
 * Expressions are compiled in the UI; this file stores declarative models only.
 */
(function (root) {
  'use strict';

  const presets = {
    'Convex bowl': {
      title: 'Convex bowl',
      family: 'Smooth unconstrained reference',
      narrative: 'A two-dimensional quadratic with a unique minimizer at x = 2, y = -1. It is the basic sanity check for local and population methods.',
      scientificNote: 'The analytical solution is known. Numerical output should approach it, but the interface still reports a candidate rather than asserting an optimizer certificate.',
      sense: 'minimize',
      algorithm: 'coordinate',
      variables: [
        { name: 'x', start: 0, lower: -5, upper: 5 },
        { name: 'y', start: 0, lower: -5, upper: 5 },
      ],
      objective: '(x - 2)^2 + (y + 1)^2',
      objective2: '',
      inequalities: [],
      equalities: [],
    },
    'Constrained quadratic': {
      title: 'Constrained quadratic',
      family: 'Smooth inequality-constrained reference',
      narrative: 'Minimize a quadratic subject to x + y ≤ 4. The unconstrained optimum violates the inequality, so feasibility evidence matters.',
      scientificNote: 'The constrained solution lies on the active boundary near (2.5, 1.5). The penalty search is not a formal active-set or KKT solver.',
      sense: 'minimize',
      algorithm: 'projected_gradient',
      variables: [
        { name: 'x', start: 1, lower: 0, upper: 10 },
        { name: 'y', start: 1, lower: 0, upper: 10 },
      ],
      objective: '(x - 3)^2 + (y - 2)^2',
      objective2: '',
      inequalities: ['x + y - 4'],
      equalities: [],
    },
    'Rosenbrock on disk': {
      title: 'Rosenbrock on disk',
      family: 'Non-convex constrained benchmark',
      narrative: 'A curved Rosenbrock valley inside a circular feasible region. The example exposes start sensitivity and the difference between finding a good candidate and proving global optimality.',
      scientificNote: 'Use multi-start or differential evolution. A single local run is weak evidence on this landscape.',
      sense: 'minimize',
      algorithm: 'multi_start',
      variables: [
        { name: 'x', start: -1, lower: -2, upper: 2 },
        { name: 'y', start: 1, lower: -2, upper: 2 },
      ],
      objective: '(1 - x)^2 + 100*(y - x^2)^2',
      objective2: '',
      inequalities: ['x^2 + y^2 - 2'],
      equalities: [],
    },
    'Rugged Rastrigin': {
      title: 'Rugged Rastrigin',
      family: 'Multimodal benchmark',
      narrative: 'A highly multimodal surface with a known global minimum at the origin. It is useful for testing exploration, reproducibility, and sensitivity to the search budget.',
      scientificNote: 'Differential evolution is a heuristic. Repeated seeded runs can test robustness but are not a proof of global optimality.',
      sense: 'minimize',
      algorithm: 'differential_evolution',
      variables: [
        { name: 'x', start: 3, lower: -5.12, upper: 5.12 },
        { name: 'y', start: -3, lower: -5.12, upper: 5.12 },
      ],
      objective: '20 + x^2 - 10*cos(2*pi*x) + y^2 - 10*cos(2*pi*y)',
      objective2: '',
      inequalities: [],
      equalities: [],
    },

    'Ackley exploration benchmark': {
      title: 'Ackley exploration benchmark',
      family: 'Multimodal global-search benchmark',
      narrative: 'A broad nearly flat exterior with a narrow central basin. It tests whether a bounded population search explores rather than stalling far from the origin.',
      scientificNote: 'The global minimum at the origin is known analytically. A browser heuristic approaching it is a regression check, not a general global-optimality certificate.',
      sense: 'minimize', algorithm: 'differential_evolution',
      variables: [{ name: 'x', start: 3.5, lower: -5, upper: 5 }, { name: 'y', start: -3.5, lower: -5, upper: 5 }],
      objective: '-20*exp(-0.2*sqrt(0.5*(x^2+y^2))) - exp(0.5*(cos(2*pi*x)+cos(2*pi*y))) + e + 20',
      objective2: '', inequalities: [], equalities: [],
    },
    'Beale function': {
      title: 'Beale function',
      family: 'Smooth nonlinear benchmark',
      narrative: 'A two-variable polynomial benchmark with a narrow curved valley and known minimizer at x = 3, y = 0.5.',
      scientificNote: 'The known solution makes this a regression benchmark. A browser candidate near it checks the search implementation but does not certify generic global optimization performance.',
      sense: 'minimize', algorithm: 'multi_start',
      variables: [{ name: 'x', start: 1, lower: -4.5, upper: 4.5 }, { name: 'y', start: 1, lower: -4.5, upper: 4.5 }],
      objective: '(1.5-x+x*y)^2 + (2.25-x+x*y^2)^2 + (2.625-x+x*y^3)^2',
      objective2: '', inequalities: [], equalities: [],
    },
    'Booth function': {
      title: 'Booth function',
      family: 'Convex quadratic benchmark',
      narrative: 'A two-variable quadratic benchmark with a unique minimizer at x = 1, y = 3.',
      scientificNote: 'This is a transparent sanity check for bounded local search. Its success does not transfer to non-convex or constrained problems.',
      sense: 'minimize', algorithm: 'coordinate',
      variables: [{ name: 'x', start: 0, lower: -10, upper: 10 }, { name: 'y', start: 0, lower: -10, upper: 10 }],
      objective: '(x + 2*y - 7)^2 + (2*x + y - 5)^2',
      objective2: '', inequalities: [], equalities: [],
    },
    'Himmelblau four minima': {
      title: 'Himmelblau four minima',
      family: 'Multi-basin nonlinear benchmark',
      narrative: 'Four equal minima occupy different basins. Multi-start exposes basin dependence and demonstrates why one initial point is weak evidence.',
      scientificNote: 'The four known minima make this a characterization test. Finite starts can miss a basin and do not prove exhaustive global search.',
      sense: 'minimize', algorithm: 'multi_start',
      variables: [{ name: 'x', start: 0, lower: -6, upper: 6 }, { name: 'y', start: 0, lower: -6, upper: 6 }],
      objective: '(x^2+y-11)^2 + (x+y^2-7)^2',
      objective2: '', inequalities: [], equalities: [],
    },
    'Reactor yield window': {
      title: 'Reactor yield window',
      family: 'Chemical-process teaching surrogate',
      narrative: 'Maximize a nonlinear yield surrogate over temperature and residence time while respecting a heat-load limit.',
      scientificNote: 'This dimensionless response surface is a teaching model, not a calibrated reactor design. Feasibility and sensitivity to bounds matter more than the visual peak.',
      sense: 'maximize', algorithm: 'differential_evolution',
      variables: [{ name: 'T', start: 3, lower: 0, upper: 8 }, { name: 'tau', start: 3, lower: 0.2, upper: 8 }],
      objective: 'T*tau*exp(-0.22*T-0.18*tau) - 0.03*(T-4)^2',
      objective2: 'T^2*tau', inequalities: ['T^2*tau - 120'], equalities: [],
    },
    'Heat-sink geometry': {
      title: 'Heat-sink geometry',
      family: 'Thermal-design teaching surrogate',
      narrative: 'Balance thermal resistance against material use using fin height and spacing under a simple footprint constraint.',
      scientificNote: 'The formulas are deliberately reduced and dimensionless. They illustrate constrained trade-offs, not CFD or manufacturing validation.',
      sense: 'minimize', algorithm: 'differential_evolution',
      variables: [{ name: 'h', start: 2, lower: 0.4, upper: 6 }, { name: 's', start: 1, lower: 0.2, upper: 4 }],
      objective: '1/(h*(1+2/s)) + 0.035*h^2 + 0.02/s',
      objective2: 'h/s', inequalities: ['h/s - 12'], equalities: [],
    },
    'Sparse LASSO geometry': {
      title: 'Sparse LASSO geometry',
      family: 'Regularized regression geometry',
      narrative: 'A two-coefficient least-squares surface with an L1 penalty. Increasing lambda pulls the candidate toward sparse axes.',
      scientificNote: 'This is a geometric teaching reduction, not a full regression pipeline. Coefficient uncertainty and cross-validated lambda selection are not established here.',
      sense: 'minimize', algorithm: 'multi_start',
      variables: [{ name: 'b1', start: 0, lower: -4, upper: 4 }, { name: 'b2', start: 0, lower: -4, upper: 4 }],
      objective: '(b1+0.6*b2-2.4)^2 + (0.4*b1+b2-1.6)^2 + 0.65*(abs(b1)+abs(b2))',
      objective2: 'abs(b1)+abs(b2)', inequalities: [], equalities: [],
    },
    'PINN loss-weight profile': {
      title: 'PINN loss-weight profile',
      family: 'Scientific-ML loss-landscape teaching model',
      narrative: 'Explore a reduced two-weight composite loss with competing data and physics terms. The valley illustrates scale imbalance, not neural-network training.',
      scientificNote: 'This is an analytic loss surrogate. It does not train a PINN and must not be presented as PINN performance evidence.',
      sense: 'minimize', algorithm: 'differential_evolution',
      variables: [{ name: 'wd', start: 1, lower: 0.01, upper: 8 }, { name: 'wp', start: 1, lower: 0.01, upper: 8 }],
      objective: '(log(wd)-0.4)^2 + 0.7*(log(wp)+0.2)^2 + 0.18*(wd*wp-1.5)^2',
      objective2: 'abs(log(wd/wp))', inequalities: [], equalities: [],
    },
    'Cylinder material design': {
      title: 'Cylinder material design',
      family: 'Engineering teaching surrogate',
      narrative: 'Choose radius and height to minimize closed-cylinder surface area while satisfying a minimum volume.',
      scientificNote: 'This is a dimensionless teaching model. It is not an engineering design certificate and omits manufacturing, buckling, and safety constraints.',
      sense: 'minimize',
      algorithm: 'differential_evolution',
      variables: [
        { name: 'r', start: 1, lower: 0.1, upper: 5 },
        { name: 'h', start: 2, lower: 0.1, upper: 10 },
      ],
      objective: '2*pi*r*h + 2*pi*r^2',
      objective2: '-pi*r^2*h',
      inequalities: ['10 - pi*r^2*h'],
      equalities: [],
    },
    'Portfolio equality toy': {
      title: 'Portfolio equality toy',
      family: 'Equality-constrained educational model',
      narrative: 'A three-variable quadratic risk-return toy with non-negative weights and a full-investment equality.',
      scientificNote: 'Educational only; not financial advice. Equality feasibility is judged against the displayed tolerance and enforced through a quadratic penalty, not an exact equality-constrained solver.',
      sense: 'minimize',
      algorithm: 'multi_start',
      variables: [
        { name: 'x', start: 0.33, lower: 0, upper: 1 },
        { name: 'y', start: 0.33, lower: 0, upper: 1 },
        { name: 'z', start: 0.34, lower: 0, upper: 1 },
      ],
      objective: '0.2*x^2 + 0.12*y^2 + 0.18*z^2 - 0.08*x - 0.11*y - 0.07*z',
      objective2: '-(0.08*x + 0.11*y + 0.07*z)',
      inequalities: [],
      equalities: ['x + y + z - 1'],
    },
    'Bi-objective Rosenbrock–Rastrigin': {
      title: 'Bi-objective Rosenbrock–Rastrigin',
      family: 'Finite-sample multi-objective benchmark',
      narrative: 'The primary Rosenbrock valley competes with a shifted Rastrigin objective. The finite candidate sample exposes disconnected and uneven trade-off coverage.',
      scientificNote: 'This is not a ZDT/DTLZ-complete multi-objective solver. The nondominated set depends on bounds, seed, and sample budget.',
      sense: 'minimize', algorithm: 'differential_evolution',
      variables: [{ name: 'x', start: -1, lower: -3, upper: 3 }, { name: 'y', start: 1, lower: -3, upper: 3 }],
      objective: '(1-x)^2 + 50*(y-x^2)^2',
      objective2: '20 + (x-1)^2 - 10*cos(2*pi*(x-1)) + (y+1)^2 - 10*cos(2*pi*(y+1))',
      inequalities: [], equalities: [],
    },
    'Tracking vs control effort': {
      title: 'Tracking vs control effort',
      family: 'Reduced control trade-off surrogate',
      narrative: 'Choose two bounded control gains that trade tracking error against control effort in an analytic reduced model.',
      scientificNote: 'This is not nonlinear MPC. It has no dynamic transcription, horizon, state constraints, or receding-horizon execution.',
      sense: 'minimize', algorithm: 'differential_evolution',
      variables: [{ name: 'kp', start: 1, lower: 0, upper: 8 }, { name: 'kd', start: 0.5, lower: 0, upper: 5 }],
      objective: '1/(1+kp)^2 + 0.25/(1+kd)^2 + 0.03*(kp-kd)^2',
      objective2: '0.5*kp^2 + kd^2',
      inequalities: ['kp + 1.5*kd - 11'], equalities: [],
    },
    'Pareto design trade-off': {
      title: 'Pareto design trade-off',
      family: 'Finite-sample multi-objective demonstration',
      narrative: 'Two competing quadratic objectives define a trade-off. The browser samples feasible candidates and extracts a nondominated subset.',
      scientificNote: 'The displayed front is a seeded finite candidate sample. It is not an exact Pareto frontier and can change with seed and sample budget.',
      sense: 'minimize',
      algorithm: 'differential_evolution',
      variables: [
        { name: 'x', start: 1, lower: -4, upper: 6 },
        { name: 'y', start: 1, lower: -4, upper: 6 },
      ],
      objective: '(x - 2)^2 + (y - 1)^2',
      objective2: '(x + 1)^2 + (y - 4)^2',
      inequalities: ['x + y - 6'],
      equalities: [],
    },
  };

  root.FokoOptimizationPresets = presets;
  if (typeof module !== 'undefined' && module.exports) module.exports = presets;
})(typeof window !== 'undefined' ? window : globalThis);
