(function (root, factory) {
  'use strict';
  const presets = factory();
  if (typeof module === 'object' && module.exports) module.exports = presets;
  root.FokoSymbolicPresets = presets;
}(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  return Object.freeze({
    lorenz: {
      label: 'Lorenz-system Jacobian',
      family: 'Nonlinear dynamics',
      difficulty: 'intermediate',
      variables: ['x', 'y', 'z'],
      parameters: ['sigma', 'rho', 'beta'],
      expressions: ["x' = sigma*(y-x)", "y' = x*(rho-z)-y", "z' = x*y-beta*z"],
      scope: 'x=1\ny=1\nz=1\nsigma=10\nrho=28\nbeta=2.6666666667',
      range: [-25, 35],
      selectedExpression: 1,
      derivativeVariable: 'x',
      note: 'The browser computes exact supported derivatives and a numeric Jacobian at the declared scope. It does not establish chaotic dynamics or global invariant structure.'
    },
    rosenbrock: {
      label: 'Rosenbrock gradient and Hessian',
      family: 'Optimization algebra',
      difficulty: 'intermediate',
      variables: ['x', 'y'],
      parameters: ['a', 'b'],
      expressions: ["gx = -2*(a-x)-4*b*x*(y-x^2)", "gy = 2*b*(y-x^2)"],
      scope: 'x=-1.2\ny=1\na=1\nb=100',
      range: [-2.5, 2.5],
      selectedExpression: 0,
      derivativeVariable: 'x',
      note: 'The Jacobian of the declared gradient components is the Rosenbrock Hessian. Positive definiteness is local and does not prove global optimality.'
    },
    massaction: {
      label: 'Mass-action conservation residuals',
      family: 'Reaction-network algebra',
      difficulty: 'intermediate',
      variables: ['A', 'B', 'C'],
      parameters: ['k1', 'k2', 'M'],
      expressions: ["A' = -k1*A+k2*C", "B' = -k1*B+k2*C", "C' = k1*A-k2*C", "mass = A+B+2*C-M"],
      scope: 'A=1\nB=1\nC=0\nk1=2\nk2=0.5\nM=2',
      range: [0, 4],
      selectedExpression: 3,
      derivativeVariable: 'C',
      note: 'The explicit mass residual provides a symbolic dependency check. Conservation still depends on the correctness of the declared stoichiometry and initial conditions.'
    },
    circuit: {
      label: 'Two-loop circuit mesh residuals',
      family: 'Algebraic systems',
      difficulty: 'introductory',
      variables: ['I1', 'I2'],
      parameters: ['R1', 'R2', 'R3', 'V1', 'V2'],
      expressions: ["f1 = (R1+R3)*I1-R3*I2-V1", "f2 = -R3*I1+(R2+R3)*I2-V2"],
      scope: 'I1=1\nI2=0.5\nR1=2\nR2=3\nR3=1\nV1=5\nV2=1',
      range: [-3, 3],
      selectedExpression: 0,
      derivativeVariable: 'I1',
      note: 'The browser computes the exact linear Jacobian and numeric root candidates. Frequency-dependent complex impedance is outside this real-valued reference scope.'
    },
    logistic: {
      label: 'Logistic growth',
      family: 'One-dimensional dynamics',
      difficulty: 'introductory',
      variables: ['x'],
      parameters: ['r', 'K'],
      expressions: ["x' = r*x*(1-x/K)"],
      scope: 'x=1\nr=1\nK=10',
      range: [-1, 12],
      selectedExpression: 0,
      derivativeVariable: 'x',
      note: 'Exact differentiation and Jacobian are browser-computed. Equilibria are located numerically over the declared range; exact algebraic solving remains a SymPy export task.'
    },
    cubic: {
      label: 'Cubic multistability residual',
      family: 'Roots and local stability',
      difficulty: 'intermediate',
      variables: ['x'],
      parameters: ['a'],
      expressions: ["x' = x*(1-x)*(x-a)"],
      scope: 'x=0.2\na=0.35',
      range: [-0.25, 1.25],
      selectedExpression: 0,
      derivativeVariable: 'x',
      note: 'The finite range contains three simple roots for this parameter value. A grid scan can miss tangent or repeated roots, so the result is not an exhaustive exact solve.'
    },
    michaelis: {
      label: 'Michaelis–Menten balance',
      family: 'Algebraic residuals',
      difficulty: 'introductory',
      variables: ['S'],
      parameters: ['Vmax', 'Km', 'qin'],
      expressions: ["balance = qin - Vmax*S/(Km+S)"],
      scope: 'S=1\nVmax=4\nKm=2\nqin=1',
      range: [0, 12],
      selectedExpression: 0,
      derivativeVariable: 'S',
      note: 'The browser reports a numeric zero and local derivative. Positivity and unit consistency remain the modeler’s responsibility.'
    },
    oscillator: {
      label: 'Linear harmonic oscillator',
      family: 'Two-dimensional systems',
      difficulty: 'introductory',
      variables: ['x', 'v'],
      parameters: ['omega'],
      expressions: ["x' = v", "v' = -omega^2*x"],
      scope: 'x=1\nv=0\nomega=1',
      range: [-2, 2],
      selectedExpression: 1,
      derivativeVariable: 'x',
      note: 'The Jacobian is exact within the supported grammar. Local eigenvalue classification is numeric and limited to small systems.'
    },
    damped: {
      label: 'Damped oscillator',
      family: 'Two-dimensional systems',
      difficulty: 'intermediate',
      variables: ['x', 'v'],
      parameters: ['omega', 'zeta'],
      expressions: ["x' = v", "v' = -omega^2*x-2*zeta*omega*v"],
      scope: 'x=1\nv=0\nomega=2\nzeta=0.2',
      range: [-2, 2],
      selectedExpression: 1,
      derivativeVariable: 'v',
      note: 'Symbolic derivatives expose the local linear system. Damping interpretation still depends on parameter units and model assumptions.'
    },
    lotka: {
      label: 'Lotka–Volterra predator–prey',
      family: 'Nonlinear dynamics',
      difficulty: 'intermediate',
      variables: ['prey', 'pred'],
      parameters: ['alpha', 'beta', 'delta', 'gamma'],
      expressions: ["prey' = alpha*prey-beta*prey*pred", "pred' = delta*prey*pred-gamma*pred"],
      scope: 'prey=10\npred=5\nalpha=1\nbeta=0.1\ndelta=0.1\ngamma=1',
      range: [0, 20],
      selectedExpression: 0,
      derivativeVariable: 'prey',
      note: 'The browser computes the Jacobian and finite multi-start equilibria. It does not prove completeness, structural stability or ecological validity.'
    },
    toggle: {
      label: 'Mutual repression toggle',
      family: 'Nonlinear dynamics',
      difficulty: 'advanced',
      variables: ['u', 'v'],
      parameters: ['alpha', 'n'],
      expressions: ["u' = alpha/(1+v^n)-u", "v' = alpha/(1+u^n)-v"],
      scope: 'u=1\nv=1\nalpha=4\nn=2',
      range: [0, 5],
      selectedExpression: 0,
      derivativeVariable: 'v',
      note: 'Finite multi-start can reveal several numerical roots but is not a certified bifurcation or exhaustive branch calculation.'
    },
    fhn: {
      label: 'FitzHugh–Nagumo system',
      family: 'Nonlinear dynamics',
      difficulty: 'advanced',
      variables: ['v', 'w'],
      parameters: ['a', 'b', 'tau', 'I'],
      expressions: ["v' = v-v^3/3-w+I", "w' = (v+a-b*w)/tau"],
      scope: 'v=0\nw=0\na=0.7\nb=0.8\ntau=12.5\nI=0.5',
      range: [-3, 3],
      selectedExpression: 0,
      derivativeVariable: 'v',
      note: 'The local Jacobian and numerical equilibria do not establish excitability, oscillations or global phase-space structure.'
    },
    sir: {
      label: 'SIR epidemic vector field',
      family: 'Three-dimensional systems',
      difficulty: 'intermediate',
      variables: ['S', 'I', 'R'],
      parameters: ['beta', 'gamma', 'N'],
      expressions: ["S' = -beta*S*I/N", "I' = beta*S*I/N-gamma*I", "R' = gamma*I"],
      scope: 'S=990\nI=10\nR=0\nbeta=0.35\ngamma=0.1\nN=1000',
      range: [0, 1000],
      selectedExpression: 1,
      derivativeVariable: 'I',
      note: 'The exact Jacobian is browser-computed. Conservation, positivity and epidemiological identifiability require separate model analysis.'
    },
    pendulum: {
      label: 'Nonlinear pendulum',
      family: 'Elementary functions',
      difficulty: 'intermediate',
      variables: ['theta', 'omega'],
      parameters: ['g', 'L', 'c'],
      expressions: ["theta' = omega", "omega' = -(g/L)*sin(theta)-c*omega"],
      scope: 'theta=0.5\nomega=0\ng=9.81\nL=1\nc=0.1',
      range: [-3.14159, 3.14159],
      selectedExpression: 1,
      derivativeVariable: 'theta',
      note: 'sin, cos, tan, exp, log and sqrt are supported. General special functions and branch-sensitive complex algebra are not.'
    },
    enzyme2d: {
      label: 'Enzyme–complex balances',
      family: 'Algebraic residuals',
      difficulty: 'advanced',
      variables: ['S', 'C'],
      parameters: ['kin', 'k1', 'km1', 'kcat', 'E0'],
      expressions: ["f1 = kin-k1*(E0-C)*S+km1*C", "f2 = k1*(E0-C)*S-(km1+kcat)*C"],
      scope: 'S=1\nC=0.1\nkin=0.2\nk1=1\nkm1=0.5\nkcat=1\nE0=1',
      range: [0, 4],
      selectedExpression: 1,
      derivativeVariable: 'C',
      note: 'Numeric roots depend on starts and scaling. Exact elimination, positivity-constrained solving and dimensional reduction belong in an external CAS or numerical workflow.'
    },
    repressilator: {
      label: 'Repressilator equilibrium system',
      family: 'Gene regulatory networks',
      difficulty: 'advanced',
      variables: ['x', 'y', 'z'],
      parameters: ['alpha', 'n'],
      expressions: ["x' = alpha/(1+z^n)-x", "y' = alpha/(1+x^n)-y", "z' = alpha/(1+y^n)-z"],
      scope: 'x=1.4\ny=1.4\nz=1.4\nalpha=4\nn=2',
      range: [0, 5],
      selectedExpression: 0,
      derivativeVariable: 'z',
      note: 'The exact supported Jacobian and finite-start equilibrium candidates are computed. Oscillation and Hopf claims require time-domain and bifurcation analysis.'
    },
    goodwin: {
      label: 'Goodwin feedback system',
      family: 'Gene regulatory networks',
      difficulty: 'advanced',
      variables: ['m', 'p', 'q'],
      parameters: ['a', 'b', 'c', 'd', 'e', 'f', 'n'],
      expressions: ["m' = a/(1+q^n)-b*m", "p' = c*m-d*p", "q' = e*p-f*q"],
      scope: 'm=0.8\np=0.8\nq=0.8\na=2.5\nb=1\nc=1\nd=1\ne=1\nf=1\nn=4',
      range: [0, 3],
      selectedExpression: 0,
      derivativeVariable: 'q',
      note: 'The browser computes supported derivatives and a finite numerical operating point. Periodicity and global feedback behavior are not inferred from the equilibrium alone.'
    },
    mapk: {
      label: 'MAPK two-tier activation',
      family: 'Signal transduction',
      difficulty: 'intermediate',
      variables: ['M1', 'M2'],
      parameters: ['S', 'k1', 'K1', 'd1', 'k2', 'K2', 'd2'],
      expressions: ["M1' = k1*S*(1-M1)/(K1+1-M1)-d1*M1", "M2' = k2*M1*(1-M2)/(K2+1-M2)-d2*M2"],
      scope: 'M1=0.45\nM2=0.55\nS=1\nk1=1.4\nK1=0.25\nd1=0.7\nk2=1.2\nK2=0.2\nd2=0.55',
      range: [0, 1],
      selectedExpression: 1,
      derivativeVariable: 'M1',
      note: 'This reduced cascade exposes exact local derivatives and a numerical operating point. It is not a calibrated pathway or a proof of ultrasensitivity.'
    },
    cstr: {
      label: 'CSTR concentration–temperature residuals',
      family: 'Chemical engineering',
      difficulty: 'advanced',
      variables: ['C', 'T'],
      parameters: ['D', 'Cin', 'Tin', 'k0', 'E', 'heat', 'cool', 'Tc'],
      expressions: ["C' = D*(Cin-C)-k0*exp(-E/T)*C", "T' = D*(Tin-T)+heat*k0*exp(-E/T)*C-cool*(T-Tc)"],
      scope: 'C=0.25\nT=2.8\nD=1\nCin=1\nTin=1\nk0=18\nE=5\nheat=8\ncool=2.2\nTc=0.9',
      range: [0.1, 4],
      selectedExpression: 1,
      derivativeVariable: 'T',
      note: 'The browser provides exact supported derivatives, nullclines and finite-root evidence. Thermal-runaway claims require parameter continuation and physical validation.'
    },
    exponential: {
      label: 'Exponential response',
      family: 'Elementary functions',
      difficulty: 'introductory',
      variables: ['x'],
      parameters: ['A', 'k', 'c'],
      expressions: ["f = A*exp(-k*x)+c"],
      scope: 'x=1\nA=3\nk=0.7\nc=-0.5',
      range: [0, 8],
      selectedExpression: 0,
      derivativeVariable: 'x',
      note: 'The derivative is exact for the supported expression tree. Parameter estimation is not performed in this lab.'
    }
  });
}));
