(function(root){'use strict';
const FokoKit = {};
function isFiniteNumber(x){return Number.isFinite(Number(x));}
function assert(cond,msg){if(!cond) throw new Error(msg);}
FokoKit.requireMatrix=function(A,name='matrix'){assert(Array.isArray(A)&&A.length>0,name+': expected non-empty matrix');assert(A.every(r=>Array.isArray(r)&&r.length===A[0].length&&r.every(isFiniteNumber)),name+': expected rectangular numeric matrix');return A;};
FokoKit.requireSquare=function(A,name='matrix'){FokoKit.requireMatrix(A,name);assert(A.length===A[0].length,name+': expected square matrix');return A;};
FokoKit.requireVector=function(v,name='vector'){assert(Array.isArray(v)&&v.length>0&&v.every(isFiniteNumber),name+': expected non-empty numeric vector');return v;};
FokoKit.requireSameLength=function(a,b,name='arrays'){assert(Array.isArray(a)&&Array.isArray(b)&&a.length===b.length&&a.length>0,name+': expected arrays of same non-zero length');return [a,b];};
FokoKit.requirePositiveInt=function(n,name='n'){assert(Number.isInteger(Number(n))&&Number(n)>0,name+': expected positive integer');return Number(n);};
FokoKit.requireInRange=function(x,min,max,name='value'){x=Number(x);assert(Number.isFinite(x)&&x>=min&&x<=max,name+': expected value in ['+min+', '+max+']');return x;};
FokoKit.requireEdges=function(edges,name='edges'){assert(Array.isArray(edges)&&edges.length>0,name+': expected non-empty edge list');assert(edges.every(e=>e&&e.source!=null&&e.target!=null),name+': edges require source and target');return edges;};
FokoKit.requirePairs=function(pairs,name='pairs'){assert(Array.isArray(pairs)&&pairs.length>0,name+': expected [x,y] pairs');assert(pairs.every(p=>Array.isArray(p)&&p.length>=2&&isFiniteNumber(p[0])&&isFiniteNumber(p[1])),name+': pairs must be numeric [x,y]');return pairs;};
FokoKit.seededRandom=function(seed=123456789){let x=(Number(seed)||123456789)>>>0;return function(){x^=x<<13;x^=x>>>17;x^=x<<5;return ((x>>>0)/4294967296);};};
FokoKit.formatResult=function(value,opts={}){const digits=opts.digits??6;function fmt(x){return Number.isFinite(x)?Number(x.toFixed(digits)):x;}function walk(v,depth=0){if(depth>8)return '[depth-limit]';if(Number.isFinite(v))return fmt(v);if(Array.isArray(v))return v.map(x=>walk(x,depth+1));if(v&&typeof v==='object'){const out={};Object.keys(v).sort().forEach(k=>out[k]=walk(v[k],depth+1));return out;}return v;}const cleaned=walk(value);if(opts.json)return JSON.stringify(cleaned,null,2);if(cleaned&&typeof cleaned==='object'&&!Array.isArray(cleaned)){return Object.entries(cleaned).map(([k,v])=>`${k}: ${typeof v==='object'?JSON.stringify(v,null,2):v}`).join('\n');}return JSON.stringify(cleaned,null,2);};
FokoKit.toReproConfig=function(kind,payload={}){return {engine:'Foko Lab',version:'77.4.1',kind,createdAt:new Date().toISOString(),payload};};
FokoKit.encodeState=function(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');};
FokoKit.decodeState=function(s){if(!s)return null;try{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return JSON.parse(decodeURIComponent(escape(atob(s))));}catch(e){return null;}};
FokoKit.downloadJSON=function(filename,obj){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename||'foko-run.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
FokoKit.attachPlotExport=function(plot,label='figure'){if(!plot||plot.dataset.fokoExportAttached)return;plot.dataset.fokoExportAttached='true';const bar=document.createElement('div');bar.className='foko-plot-export-bar';bar.innerHTML='<button type="button" class="foko-export-svg">Download SVG</button><button type="button" class="foko-export-png">Download PNG</button>';plot.parentNode.insertBefore(bar,plot);bar.addEventListener('click',e=>{if(!root.Plotly)return;if(e.target.classList.contains('foko-export-svg'))root.Plotly.downloadImage(plot,{format:'svg',filename:label});if(e.target.classList.contains('foko-export-png'))root.Plotly.downloadImage(plot,{format:'png',filename:label,scale:3});});};
FokoKit.parseTable=function(text){const lines=String(text||'').trim().split(/\n+/).map(s=>s.trim()).filter(Boolean);if(!lines.length)return {names:[],rows:[]};const split=s=>s.split(/\s*,\s*|\s*;\s*|\t|\s+/).filter(Boolean);const first=split(lines[0]);let names=[],start=0;if(first.some(v=>!isFiniteNumber(v))){names=first;start=1;}const rows=lines.slice(start).map(split);if(!names.length)names=rows[0]?.map((_,i)=>'V'+(i+1))||[];return {names,rows};};
FokoKit.inferSchema=function(table){const rows=table.rows||[];return (table.names||[]).map((name,i)=>{const vals=rows.map(r=>r[i]).filter(v=>v!=null&&v!=='');const numeric=vals.every(isFiniteNumber);return {name,type:numeric?'number':'string',missing:rows.length-vals.length,unique:new Set(vals).size};});};
FokoKit.validateTemplate=function(kind,text){const table=FokoKit.parseTable(text);const schema=FokoKit.inferSchema(table);if(kind==='network'&&!(table.names.includes('source')&&table.names.includes('target')))throw new Error('Network template requires source and target columns');if(kind==='ml'&&table.names.length<2)throw new Error('ML template requires at least one feature and one target/label column');if(kind==='statistics'&&table.names.length<1)throw new Error('Statistics template requires at least one column');return {table,schema};};
FokoKit.attachAriaLive=function(el){if(el){el.setAttribute('aria-live','polite');el.setAttribute('aria-atomic','true');}};
FokoKit.installFocusRings=function(){if(document.getElementById('fokokit-focus-css'))return;const s=document.createElement('style');s.id='fokokit-focus-css';s.textContent=':focus-visible{outline:3px solid #2DD4BF!important;outline-offset:3px!important}.foko-plot-export-bar{display:flex;gap:8px;margin:8px 0}.foko-plot-export-bar button,.v71-shell-button{border:1px solid #c8d8e4;border-radius:12px;background:#eef8fb;color:#0f2f57;font-weight:800;padding:8px 11px;cursor:pointer}.foko-command-palette{position:fixed;inset:0;background:rgba(6,27,42,.48);z-index:9999;display:none;align-items:flex-start;justify-content:center;padding-top:10vh}.foko-command-palette.open{display:flex}.foko-command-dialog{width:min(720px,calc(100vw - 32px));background:#fff;border-radius:22px;border:1px solid #cbddeb;box-shadow:0 28px 80px rgba(0,0,0,.24);padding:16px}.foko-command-dialog input{width:100%;font:inherit;font-size:1.1rem;border:1px solid #cbddeb;border-radius:14px;padding:12px}.foko-command-list{max-height:360px;overflow:auto;margin-top:10px}.foko-command-list a{display:block;padding:10px 12px;border-radius:12px;color:#0f172a;text-decoration:none}.foko-command-list a:hover,.foko-command-list a:focus{background:#eafcff}';document.head.appendChild(s);};
FokoKit.createCommandPalette=function(items){if(document.getElementById('fokoCommandPalette'))return;const wrap=document.createElement('div');wrap.id='fokoCommandPalette';wrap.className='foko-command-palette';wrap.innerHTML='<div class="foko-command-dialog" role="dialog" aria-label="Command palette"><input aria-label="Search commands" placeholder="Search labs, examples, actions…"><div class="foko-command-list"></div></div>';document.body.appendChild(wrap);const input=wrap.querySelector('input'),list=wrap.querySelector('.foko-command-list');function render(q=''){const s=q.toLowerCase();list.innerHTML=items.filter(it=>(it.label+' '+(it.tags||'')).toLowerCase().includes(s)).slice(0,30).map(it=>`<a href="${it.href}"><b>${it.label}</b><br><small>${it.tags||''}</small></a>`).join('');}render();document.addEventListener('keydown',e=>{if(e.key==='/'&&!e.ctrlKey&&!e.metaKey&&document.activeElement.tagName!=='INPUT'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();wrap.classList.add('open');input.focus();render();}if(e.key==='Escape')wrap.classList.remove('open');});input.addEventListener('input',()=>render(input.value));wrap.addEventListener('click',e=>{if(e.target===wrap)wrap.classList.remove('open');});};
if(typeof module!=='undefined'&&module.exports)module.exports=FokoKit;
root.FokoKit=FokoKit;
if(typeof document!=='undefined'){document.addEventListener('DOMContentLoaded',()=>{FokoKit.installFocusRings();document.querySelectorAll('pre[id$="Output"],pre[id$="Result"],.analysis-output').forEach(FokoKit.attachAriaLive);document.querySelectorAll('[id$="Plot"],.js-plotly-plot').forEach((p,i)=>FokoKit.attachPlotExport(p,'foko-figure-'+(i+1)));});}
}(typeof window!=='undefined'?window:globalThis));
