const $ = id => document.getElementById(id);
const clone = x => JSON.parse(JSON.stringify(x));
const OPT_PRESETS = {
  'Constrained quadratic': {family:'Convex', optClass:'convex', algorithm:'random_coord', narrative:'Smooth convex quadratic with one inequality. Good first constrained problem.', sense:'minimize', variables:[['x',1,0,10],['y',1,0,10]], objective:'(x-3)^2 + (y-2)^2', objective2:'', ineq:['x + y - 4'], eq:[]},
  'Convex bowl': {family:'Convex', optClass:'convex', algorithm:'coordinate', narrative:'Unconstrained smooth bowl. This is the safest first test because every algorithm should move toward the same minimum.', sense:'minimize', variables:[['x',0,-5,5],['y',0,-5,5]], objective:'(x-2)^2 + (y+1)^2', objective2:'', ineq:[], eq:[]},
  'Rosenbrock on disk': {family:'Non-convex', optClass:'nonconvex', algorithm:'multi_start', narrative:'Narrow curved valley plus a circular constraint. Shows why local search needs good starts.', sense:'minimize', variables:[['x',-1,-2,2],['y',1,-2,2]], objective:'(1-x)^2 + 100*(y-x^2)^2', objective2:'', ineq:['x^2 + y^2 - 2'], eq:[]},
  'Pareto design trade-off': {family:'Multi-objective', optClass:'multiobjective', algorithm:'differential_evolution', narrative:'Two objectives create a trade-off frontier rather than one universal best design.', sense:'minimize', variables:[['x',1,-4,6],['y',1,-4,6]], objective:'(x-2)^2 + (y-1)^2', objective2:'(x+1)^2 + (y-4)^2', ineq:['x + y - 6'], eq:[]},
  'Rugged Rastrigin': {family:'Metaheuristic', optClass:'metaheuristic', algorithm:'particle_swarm', narrative:'Highly multimodal landscape where metaheuristics are useful for exploration.', sense:'minimize', variables:[['x',3,-5.12,5.12],['y',-3,-5.12,5.12]], objective:'20 + x^2 - 10*cos(2*pi*x) + y^2 - 10*cos(2*pi*y)', objective2:'', ineq:[], eq:[]},
  'Cylinder design': {family:'Engineering design', optClass:'convex', algorithm:'random_coord', narrative:'Minimize material area under a minimum volume requirement.', sense:'minimize', variables:[['r',1,.1,5],['h',2,.1,10]], objective:'2*pi*r*h + 2*pi*r^2', objective2:'-pi*r^2*h', ineq:['10 - pi*r^2*h'], eq:[]},
  'Portfolio toy model': {family:'Finance toy', optClass:'convex', algorithm:'random_coord', narrative:'Quadratic risk with full-investment equality. Educational only, not financial advice.', sense:'minimize', variables:[['x',.33,0,1],['y',.33,0,1],['z',.34,0,1]], objective:'0.2*x^2 + 0.12*y^2 + 0.18*z^2 - 0.08*x - 0.11*y - 0.07*z', objective2:'-(0.08*x + 0.11*y + 0.07*z)', ineq:[], eq:['x + y + z - 1']},
  'Threshold stopping': {family:'Optimal stopping', optClass:'optimal_stopping', algorithm:'coordinate', narrative:'Choose a threshold balancing search cost and reward quality.', sense:'minimize', variables:[['tau',0.6,0,1]], objective:'(tau - 0.72)^2 + 0.08*tau', objective2:'', ineq:[], eq:[]}
};
const CORE_OPT = ['Convex bowl','Constrained quadratic','Rosenbrock on disk','Pareto design trade-off','Rugged Rastrigin'];
let model, currentName='Constrained quadratic', worker=null, last=null;
function init(){ setTheme(localStorage.getItem('chilperic-theme')||'aurora'); $('themeBtn')?.addEventListener('change',e=>setTheme(e.target.value)); initTabs(); bindSideNav(); renderLibrary(); loadPreset(new URLSearchParams(location.search).get('example') || currentName,false); wire(); }
function setTheme(t){ document.documentElement.dataset.theme=t; if($('themeBtn')) $('themeBtn').value=t; localStorage.setItem('chilperic-theme',t); setTimeout(()=>['optPlotLeft','optPlotRight'].forEach(id=>{try{Plotly.Plots.resize(id)}catch{}}),60); }
function bindSideNav(){ document.querySelectorAll('[data-jump]').forEach(btn=>btn.addEventListener('click',()=>{ const el=$(btn.dataset.jump); if(el) el.scrollIntoView({behavior:'smooth',block:'start'}); document.querySelectorAll('.side-nav .nav-item').forEach(b=>b.classList.toggle('active', b===btn)); })); }
function initTabs(){ document.querySelectorAll('#resultTabs .tab').forEach(btn=>btn.addEventListener('click',()=>{ document.querySelectorAll('#resultTabs .tab').forEach(b=>b.classList.toggle('active',b===btn)); document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===btn.dataset.panel)); setTimeout(()=>['optPlotLeft','optPlotRight'].forEach(id=>{try{Plotly.Plots.resize(id)}catch{}}),40); })); }
function wire(){ $('runOpt').addEventListener('click',runOpt); $('cancelOpt')?.addEventListener('click',cancelOpt); $('resetOpt').addEventListener('click',()=>loadPreset(currentName,true)); $('addVar').addEventListener('click',()=>{ model.variables.push({name:'x'+(model.variables.length+1),initial:0,lower:-10,upper:10}); renderEditor(); }); ['optPlotA','optPlotB'].forEach(id=>$(id)?.addEventListener('change',plotAll)); ['exportOptWide','exportOptLong','exportOptJson','exportOptPlotJson','exportOptModel','exportOptPython','exportOptWide2','exportOptLong2','exportOptPython2'].forEach(id=>$(id)?.addEventListener('click',exportById)); $('optExportPng')?.addEventListener('click',()=>downloadPlot('optPlotLeft','png')); $('optExportSvg')?.addEventListener('click',()=>downloadPlot('optPlotLeft','svg')); document.addEventListener('keydown',e=>{ if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();runOpt();} }); }
function renderLibrary(){ const deck=$('optDeck'), add=$('optAdditional'), select=$('optSelect'); deck.innerHTML=''; add.innerHTML=''; if(select) select.innerHTML=''; Object.keys(OPT_PRESETS).forEach(n=>{ if(select){ const o=document.createElement('option'); o.value=n; o.textContent=n; select.append(o); } }); CORE_OPT.forEach(n=>deck.append(optButton(n,true))); Object.keys(OPT_PRESETS).filter(n=>!CORE_OPT.includes(n)).forEach(n=>add.append(optButton(n,false))); $('loadOpt')?.addEventListener('click',()=>loadPreset($('optSelect').value,true)); }
function optButton(name, core){ const p=OPT_PRESETS[name]; const b=document.createElement('button'); b.className=core?'model-card':'secondary stoch2-model-button'; b.type='button'; b.innerHTML=core?`<span>${p.family}</span><b>${name}</b><small>${p.algorithm.replaceAll('_',' ')}</small>`:`<b>${name}</b><span>${p.family}</span>`; b.onclick=()=>loadPreset(name,true); return b; }
function normalize(p){ return {family:p.family,narrative:p.narrative,optClass:p.optClass||'nonconvex',algorithm:p.algorithm||'random_coord',sense:p.sense||'minimize',variables:p.variables.map(v=>Array.isArray(v)?{name:v[0],initial:+v[1],lower:+v[2],upper:+v[3]}:v),objective:p.objective||'0',objective2:p.objective2||'',ineq:p.ineq||[],eq:p.eq||[]}; }
function loadPreset(name,updateUrl=true){ currentName=OPT_PRESETS[name]?name:CORE_OPT[0]; model=normalize(clone(OPT_PRESETS[currentName])); if(updateUrl) history.replaceState(null,'',`?example=${encodeURIComponent(currentName)}`); if($('optSelect')) $('optSelect').value=currentName; $('optTitle').textContent=currentName; $('optFamily').textContent=model.family; $('optNarrative').textContent=model.narrative; renderEditor(); clearPlots(); }
function renderEditor(){ $('optClass').value=model.optClass; $('optAlgorithm').value=model.algorithm; $('optSense').value=model.sense; $('objective').value=model.objective; $('objective2').value=model.objective2||''; $('ineq').value=model.ineq.join('\n'); $('eqcon').value=model.eq.join('\n'); renderVars(); ['optClass','optAlgorithm','optSense','objective','objective2','ineq','eqcon'].forEach(id=>$(id).oninput=()=>{ readEditor(); preview(); }); preview(); }
function renderVars(){ const root=$('variableRows'); root.innerHTML='<div class="table-head"><div>name</div><div>initial</div><div>lower</div><div>upper</div><div></div></div>'; model.variables.forEach((v,i)=>{ const row=document.createElement('div'); row.className='table-row five'; row.innerHTML=`<input value="${esc(v.name)}"><input type="number" step="any" value="${v.initial}"><input type="number" step="any" value="${v.lower}"><input type="number" step="any" value="${v.upper}"><button class="delete" type="button">×</button>`; const [n,ini,lo,hi,del]=row.querySelectorAll('input,button'); n.oninput=e=>{v.name=e.target.value.trim(); preview();}; ini.oninput=e=>v.initial=+e.target.value; lo.oninput=e=>v.lower=+e.target.value; hi.oninput=e=>v.upper=+e.target.value; del.onclick=()=>{model.variables.splice(i,1);renderVars();preview();}; root.append(row); }); }
function readEditor(){ model.optClass=$('optClass').value; model.algorithm=$('optAlgorithm').value; model.sense=$('optSense').value; model.objective=$('objective').value; model.objective2=$('objective2').value.trim(); model.ineq=$('ineq').value.split(/\n/).map(s=>s.trim()).filter(Boolean); model.eq=$('eqcon').value.split(/\n/).map(s=>s.trim()).filter(Boolean); }
function preview(){ readEditor(); const raw=`${model.sense}\\quad f_1 = ${texExpr(model.objective)}${model.objective2?`\\\\ f_2 = ${texExpr(model.objective2)}`:''}\\\\ \\text{algorithm: }${model.algorithm.replaceAll('_',' ')}\\quad \\text{class: }${model.optClass}`; try{ if(window.katex) katex.render(raw,$('optPreview'),{throwOnError:false,displayMode:true}); else $('optPreview').textContent=raw; }catch{ $('optPreview').innerHTML=`<b>${model.sense}</b> f₁ = ${esc(model.objective)}${model.objective2?`<br>f₂ = ${esc(model.objective2)}`:''}<br><span class="note">algorithm: ${esc(model.algorithm.replaceAll('_',' '))}; class: ${esc(model.optClass)}</span>`; } }
function runOpt(){ if($('runOpt').disabled) return; readEditor(); $('optDiagnostics').textContent='Optimizing...'; if($('optProgressBar')) $('optProgressBar').style.width='20%'; $('runOpt').disabled=true; $('runOpt').textContent='Optimizing…'; $('cancelOpt')?.classList.remove('hidden'); if($('optTopStatus')) $('optTopStatus').textContent='Running'; if(worker) worker.terminate(); worker=new Worker('src/worker.js'); worker.onmessage=ev=>{ const r=ev.data; if(r.progress!==undefined){ $('optDiagnostics').textContent=`${r.text||'Running'} ${(r.progress*100).toFixed(0)}%`; if($('optProgressBar')) $('optProgressBar').style.width=Math.max(5,Math.min(98,r.progress*100)).toFixed(0)+'%'; return;} $('runOpt').disabled=false; $('runOpt').textContent='▶ Optimize'; $('cancelOpt')?.classList.add('hidden'); if(!r.ok){ $('optDiagnostics').textContent=r.error||'Optimization failed.'; if($('optTopStatus')) $('optTopStatus').textContent=r.cancelled?'Cancelled':'Error'; return;} if($('optProgressBar')) $('optProgressBar').style.width='100%'; last=r; plotAll(); diagnostics(); }; worker.onerror=err=>{ $('runOpt').disabled=false; $('runOpt').textContent='▶ Optimize'; $('cancelOpt')?.classList.add('hidden'); if($('optProgressBar')) $('optProgressBar').style.width='0%'; $('optDiagnostics').textContent=err.message||'Worker error.'; if($('optTopStatus')) $('optTopStatus').textContent='Error'; }; worker.postMessage({type:'opt', payload:{...model, algorithm:model.algorithm||'random_coord', optClass:model.optClass||'nonconvex', samples:+$('optSamples').value, penalty:$('penalty').value, refineSteps:+$('refineSteps').value, population:+$('optPopulation').value, temperature:$('optTemperature').value, tolerance:$('optTolerance').value, seed:+($('optSeed')?.value || 12345)}}); }
function cancelOpt(){ if(worker){ worker.terminate(); worker=null; } $('runOpt').disabled=false; $('runOpt').textContent='▶ Optimize'; $('cancelOpt')?.classList.add('hidden'); if($('optProgressBar')) $('optProgressBar').style.width='0%'; $('optDiagnostics').textContent='Cancelled.'; if($('optTopStatus')) $('optTopStatus').textContent='Cancelled'; }
function plotAll(){ plotOne('optPlotLeft',$('optPlotA').value); plotOne('optPlotRight',$('optPlotB').value); }
function safePlot(id,traces,lay,config){ const el=$(id); if(!el) return; if(!window.Plotly){ el.innerHTML='<div class="diagnostics empty">Plotly is not loaded.</div>'; return; } if(!traces || !traces.length){ el.innerHTML='<div class="diagnostics empty">No data available for this plot.</div>'; return; } try{ if(el.querySelector('.diagnostics')) el.innerHTML=''; Plotly.purge(el); return Plotly.react(el,traces,lay,config||cfg()).then(()=>{ el.classList.add('plot-ready'); try{ Plotly.Plots.resize(el); }catch{} }).catch(err=>{ el.innerHTML='<div class="diagnostics empty">Plot error: '+esc(err.message||err)+'</div>'; }); }catch(err){ el.innerHTML='<div class="diagnostics empty">Plot error: '+esc(err.message||err)+'</div>'; } }
function plotOne(id,type){ if(!last){ $(id).innerHTML='<div class="diagnostics empty">Run to plot.</div>'; return;} const pts=last.samples||[], vars=last.variables||[]; if(type==='landscape'){ plotLandscape(id,pts,vars); return; } if(type==='convergence'){ let best=[],b=Infinity; pts.forEach(p=>{b=Math.min(b,p.obj + (p.violation||0)); best.push(b);}); safePlot(id,[{x:best.map((_,i)=>i+1),y:best,type:'scatter',mode:'lines',name:'best'}],layout('Convergence','sample','best objective'),cfg()); return;} if(type==='pareto'){ const good=pts.filter(p=>Number.isFinite(p.obj2)); if(!good.length){ const el=$(id); if(el) el.innerHTML='<div class="diagnostics empty">This template has no secondary objective. Select Pareto design trade-off or add f2.</div>'; return; } safePlot(id,[{x:good.map(p=>p.obj),y:good.map(p=>p.obj2),mode:'markers',type:'scatter',name:'samples'}],layout('Objective trade-off','f1','f2'),cfg()); return;} if(type==='feasibility'){ safePlot(id,[{x:pts.map(p=>p.obj),y:pts.map(p=>p.violation),mode:'markers',type:'scatter',name:'constraint residual'}],layout('Feasibility','objective','constraint residual'),cfg()); return;} if(type==='variables'){ const traces=vars.map((name,j)=>({x:pts.map((_,i)=>i), y:pts.map(p=>p.x[j]), mode:'lines', type:'scatter', name})); safePlot(id,traces,layout('Candidate variable traces','sample','value'),cfg()); return; } const x=pts.map(p=>p.x[0]), y=pts.map(p=>vars.length>1?p.x[1]:p.obj), c=pts.map(p=>p.violation); safePlot(id,[{x,y,mode:'markers',type:'scatter',marker:{size:5,color:c,colorscale:'Viridis',showscale:true},name:'samples'},{x:[last.best[0]],y:[vars.length>1?last.best[1]:last.objective],mode:'markers',marker:{size:14,symbol:'star'},name:'best'}],layout('Samples and best candidate',vars[0]||'x',vars[1]||'objective'),cfg()); }

function plotLandscape(id, pts, vars){
  const el=$(id);
  if(!vars || vars.length<2){ if(el) el.innerHTML='<div class="diagnostics empty">Landscape / contours require at least two decision variables.</div>'; return; }
  if(!window.math){ if(el) el.innerHTML='<div class="diagnostics empty">Math.js is not loaded, so the objective landscape cannot be evaluated.</div>'; return; }
  try{
    const xvar=vars[0], yvar=vars[1];
    const vx=model.variables[0], vy=model.variables[1];
    const x0=Number(vx.lower), x1=Number(vx.upper), y0=Number(vy.lower), y1=Number(vy.upper);
    const n=45;
    const xs=Array.from({length:n},(_,i)=>x0+(x1-x0)*i/(n-1));
    const ys=Array.from({length:n},(_,i)=>y0+(y1-y0)*i/(n-1));
    const compiled=math.compile(model.objective || '0');
    const z=ys.map(y=>xs.map(x=>{
      const scope={}; model.variables.forEach((v,j)=>scope[v.name]=j===0?x:j===1?y:Number(v.initial));
      const val=Number(compiled.evaluate(scope));
      return Number.isFinite(val)?val:null;
    }));
    const traces=[{x:xs,y:ys,z,type:'contour',colorscale:'Viridis',contours:{coloring:'heatmap'},colorbar:{title:'f'},name:'objective'}];
    if(pts && pts.length) traces.push({x:pts.map(p=>p.x[0]),y:pts.map(p=>p.x[1]),mode:'markers',type:'scatter',marker:{size:4,color:'rgba(255,255,255,.72)',line:{color:'#0f2b62',width:1}},name:'samples'});
    if(last && last.best) traces.push({x:[last.best[0]],y:[last.best[1]],mode:'markers',type:'scatter',marker:{size:15,symbol:'star',color:'#ef4444',line:{color:'#fff',width:1.5}},name:'best'});
    safePlot(id,traces,layout('Objective landscape / contours',xvar,yvar),cfg());
  }catch(err){ if(el) el.innerHTML='<div class="diagnostics empty">Landscape error: '+esc(err.message||err)+'</div>'; }
}

function diagnostics(){ const vars=last.variables.map((n,i)=>`${n}=${last.best[i].toPrecision(6)}`).join(', '); const html=`<b>${last.feasible?'Feasible candidate':'Constraint violation remains'}</b><br>Browser optimization is approximate; validate scientific results externally.<br>Algorithm: ${esc(last.diagnostics?.method||model.algorithm)}<br>Seed: ${esc(last.diagnostics?.seed ?? '—')}<br>Best objective: ${last.objective.toPrecision(6)}<br>${vars}<br>Violation: ${last.violation.toExponential(3)}`; if($('optDiagnostics')) $('optDiagnostics').textContent=last.feasible?'Done. Feasible solution found.':'Done. Constraint violation remains.'; if($('optDiagPanel')) $('optDiagPanel').innerHTML=html; if($('optTopStatus')) $('optTopStatus').textContent=last.feasible?'Feasible':'Infeasible'; if($('optAlgoStatus')) $('optAlgoStatus').textContent=(last.diagnostics?.method||model.algorithm).replaceAll('_',' '); if($('optSamplesStatus')) $('optSamplesStatus').textContent=(last.samples||[]).length; if($('optBestStatus')) $('optBestStatus').textContent=Number(last.objective).toPrecision(4); if($('metricAlgo')) $('metricAlgo').textContent=(last.diagnostics?.method||model.algorithm).replaceAll('_',' '); if($('metricSamples')) $('metricSamples').textContent=(last.samples||[]).length; if($('metricBest')) $('metricBest').textContent=Number(last.objective).toPrecision(4); if($('metricFeasible')) $('metricFeasible').textContent=last.feasible?'yes':'no'; }
function clearPlots(){ last=null; ['optPlotLeft','optPlotRight'].forEach(id=>{ const el=$(id); if(el){ try{ if(window.Plotly) Plotly.purge(el); }catch{} el.classList.remove('plot-ready'); el.innerHTML='<div class="diagnostics empty">Run to plot.</div>'; }}); if($('optDiagnostics')) $('optDiagnostics').textContent='Ready.'; if($('optDiagPanel')) $('optDiagPanel').textContent='Run the optimizer to see candidates, convergence, and feasibility.'; if($('optTopStatus')) $('optTopStatus').textContent='Ready'; if($('optAlgoStatus')) $('optAlgoStatus').textContent='—'; if($('optSamplesStatus')) $('optSamplesStatus').textContent='—'; if($('optBestStatus')) $('optBestStatus').textContent='—'; }
function layout(title,x,y){ return {title,xaxis:{title:x,zeroline:false},yaxis:{title:y,zeroline:false},margin:{l:60,r:20,t:55,b:55},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)'}; } function cfg(){ return {responsive:true,displaylogo:false}; }
function csvCell(v){ const s=String(v??''); return /[,\n"]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s; }
function wideCsv(){ if(!last) return 'sample,objective,violation,feasible\n'; return [['sample','objective','objective2','violation','feasible',...last.variables].join(','),...last.samples.map((p,i)=>[i,p.obj,p.obj2,p.violation,p.feasible,...p.x].map(csvCell).join(','))].join('\n'); }
function longCsv(){ const rows=[['dataset','sample','axis','variable','value','extra'].join(',')]; if(last){ last.samples.forEach((p,i)=>{ rows.push(['optimization',i,'','objective',p.obj,`violation=${p.violation}; feasible=${p.feasible}`].map(csvCell).join(',')); p.x.forEach((v,j)=>rows.push(['optimization',i,'decision',last.variables[j],v,''].map(csvCell).join(','))); }); } return rows.join('\n'); }
function dataExport(){ return {model,result:last,exportedAt:new Date().toISOString()}; } function plotlyExport(){ const pack={exportedAt:new Date().toISOString(),plots:{}}; ['optPlotLeft','optPlotRight'].forEach(id=>{ const el=$(id); if(el&&el.data) pack.plots[id]={data:el.data,layout:el.layout};}); return pack; }
function pythonExport(){ const names=model.variables.map(v=>v.name); const unpack=names.map((n,i)=>`    ${n} = x[${i}]`).join('\n'); const bounds=JSON.stringify(model.variables.map(v=>[Number(v.lower),Number(v.upper)])); const x0=JSON.stringify(model.variables.map(v=>Number(v.initial))); const ineq=model.ineq.map(g=>`{'type': 'ineq', 'fun': lambda x: -(${pyExpr(g)})}`).join(',\n    '); const eq=model.eq.map(h=>`{'type': 'eq', 'fun': lambda x: (${pyExpr(h)})}`).join(',\n    '); const constraints=[ineq,eq].filter(Boolean).join(',\n    '); const algo=model.algorithm||'random_coord'; return `import numpy as np\nfrom scipy.optimize import minimize, differential_evolution\n\n# Foko Lab optimization export\n# Model: ${currentName}\n# Algorithm selected in the browser: ${algo}\n# Browser result is approximate; validate important results with a production solver.\n\ndef objective(x):\n${unpack}\n    return ${pyExpr(model.objective)}\n\ndef objective2(x):\n${unpack}\n    return ${model.objective2 ? pyExpr(model.objective2) : 'np.nan'}\n\nbounds = ${bounds}\nx0 = np.array(${x0}, dtype=float)\nconstraints = [\n    ${constraints}\n]\n\nif '${algo}' == 'differential_evolution':\n    result = differential_evolution(objective, bounds=bounds, tol=1e-9, polish=True)\nelse:\n    result = minimize(objective, x0, method='SLSQP', bounds=bounds, constraints=constraints, options={'maxiter': 1000, 'ftol': 1e-9})\n\nprint(result)\nprint('x =', result.x)\nprint('f1 =', objective(result.x))\nprint('f2 =', objective2(result.x))\n`; }
function exportById(e){ const id=e.target.id; const map={exportOptWide:['foko_lab_optimization_wide.csv',wideCsv(),'text/csv'],exportOptLong:['foko_lab_optimization_long.csv',longCsv(),'text/csv'],exportOptJson:['foko_lab_optimization_data.json',JSON.stringify(dataExport(),null,2),'application/json'],exportOptPlotJson:['foko_lab_optimization_plotly.json',JSON.stringify(plotlyExport(),null,2),'application/json'],exportOptModel:['foko_lab_optimization_model.json',JSON.stringify(model,null,2),'application/json'],exportOptPython:['foko_lab_optimization_export.py',pythonExport(),'text/x-python'],exportOptPython2:['foko_lab_optimization_export.py',pythonExport(),'text/x-python'],exportOptWide2:['foko_lab_optimization_wide.csv',wideCsv(),'text/csv'],exportOptLong2:['foko_lab_optimization_long.csv',longCsv(),'text/csv']}; const spec=map[id]; if(!spec) return; const [n,t,ty]=spec; download(n,t,ty); }
function downloadPlot(id, fmt){ const node=$(id); if(node && node.data) Plotly.downloadImage(id,{format:fmt,filename:`foko-lab-optimization-${id}`}); }
function download(name,text,type='text/plain'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function esc(s){ return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
function texExpr(s){ return String(s||'').replaceAll('^','^').replace(/\bpi\b/g,'\\pi').replace(/\*/g,'\\,'); }
function pyExpr(s){ return String(s||'0').replace(/\^/g,'**').replace(/\bpi\b/g,'np.pi').replace(/\bcos\(/g,'np.cos(').replace(/\bsin\(/g,'np.sin(').replace(/\bexp\(/g,'np.exp(').replace(/\blog\(/g,'np.log(').replace(/\bsqrt\(/g,'np.sqrt('); }
window.addEventListener('load',init);
